# Released under the MIT License. See LICENSE for details.
#
# Auto-generated; do not edit by hand.
"""Asset-package wrapper for ``a-0.baclassiccharacterassets.260911``
(bascenev1).

Everything a classic character is made of: body textures and color masks, body
part meshes, and voice sounds -- exactly what the builtin appearance table
(bamaster spazcharacters.json) names, minus icons, which live in
BaClassicCatalogAssets. Bundled with the game; a newer version is fetched on
demand when a server-delivered character definition references it, and CAS
dedupe means that costs roughly the new character's own art.
"""

# ba_meta require api 9
# ba_meta require asset-package 316

# pylint: disable=useless-suppression
# pylint: disable=too-many-lines
# pylint: disable=too-few-public-methods, disallowed-name

from typing import TYPE_CHECKING

from bacommon.assetpackage import ApverNum

from bascenev1._assetref import AssetGroup

# a-0.baclassiccharacterassets.260911
_ASSET_PACKAGE = ApverNum(316)

if TYPE_CHECKING:
    from bascenev1._assetref import MeshHandle, SoundHandle, TextureHandle

    class AudioGroup:
        """
        ::

            Character voice and body sounds.

            See source for the full asset list.
        """

        action_hero1: SoundHandle
        action_hero2: SoundHandle
        action_hero3: SoundHandle
        action_hero4: SoundHandle
        action_hero_death: SoundHandle
        action_hero_fall: SoundHandle
        action_hero_hit1: SoundHandle
        action_hero_hit2: SoundHandle
        agent1: SoundHandle
        agent2: SoundHandle
        agent3: SoundHandle
        agent4: SoundHandle
        agent_death: SoundHandle
        agent_fall: SoundHandle
        agent_hit1: SoundHandle
        agent_hit2: SoundHandle
        ali1: SoundHandle
        ali2: SoundHandle
        ali3: SoundHandle
        ali4: SoundHandle
        ali_death: SoundHandle
        ali_fall: SoundHandle
        ali_hit1: SoundHandle
        ali_hit2: SoundHandle
        alien1: SoundHandle
        alien2: SoundHandle
        alien3: SoundHandle
        alien4: SoundHandle
        alien_death: SoundHandle
        alien_fall: SoundHandle
        alien_hit1: SoundHandle
        alien_hit2: SoundHandle
        assassin1: SoundHandle
        assassin2: SoundHandle
        assassin3: SoundHandle
        assassin4: SoundHandle
        assassin_death: SoundHandle
        assassin_fall: SoundHandle
        assassin_hit1: SoundHandle
        assassin_hit2: SoundHandle
        bear1: SoundHandle
        bear2: SoundHandle
        bear3: SoundHandle
        bear4: SoundHandle
        bear_death: SoundHandle
        bear_fall: SoundHandle
        bear_hit1: SoundHandle
        bear_hit2: SoundHandle
        bones1: SoundHandle
        bones2: SoundHandle
        bones3: SoundHandle
        bones_death: SoundHandle
        bones_fall: SoundHandle
        bunny1: SoundHandle
        bunny2: SoundHandle
        bunny3: SoundHandle
        bunny4: SoundHandle
        bunny_death: SoundHandle
        bunny_fall: SoundHandle
        bunny_hit1: SoundHandle
        bunny_hit2: SoundHandle
        bunny_jump: SoundHandle
        cowboy1: SoundHandle
        cowboy2: SoundHandle
        cowboy3: SoundHandle
        cowboy4: SoundHandle
        cowboy_death: SoundHandle
        cowboy_fall: SoundHandle
        cowboy_hit1: SoundHandle
        cowboy_hit2: SoundHandle
        cyborg1: SoundHandle
        cyborg2: SoundHandle
        cyborg3: SoundHandle
        cyborg4: SoundHandle
        cyborg_death: SoundHandle
        cyborg_fall: SoundHandle
        cyborg_hit1: SoundHandle
        cyborg_hit2: SoundHandle
        frosty01: SoundHandle
        frosty02: SoundHandle
        frosty03: SoundHandle
        frosty04: SoundHandle
        frosty05: SoundHandle
        frosty_death: SoundHandle
        frosty_fall: SoundHandle
        frosty_hit01: SoundHandle
        frosty_hit02: SoundHandle
        frosty_hit03: SoundHandle
        gladiator1: SoundHandle
        gladiator2: SoundHandle
        gladiator3: SoundHandle
        gladiator4: SoundHandle
        gladiator_death: SoundHandle
        gladiator_fall: SoundHandle
        gladiator_hit1: SoundHandle
        gladiator_hit2: SoundHandle
        jack01: SoundHandle
        jack02: SoundHandle
        jack03: SoundHandle
        jack04: SoundHandle
        jack05: SoundHandle
        jack06: SoundHandle
        jack_death01: SoundHandle
        jack_fall01: SoundHandle
        jack_hit01: SoundHandle
        jack_hit02: SoundHandle
        jack_hit03: SoundHandle
        jack_hit04: SoundHandle
        jack_hit05: SoundHandle
        jack_hit06: SoundHandle
        jack_hit07: SoundHandle
        jumpsuit1: SoundHandle
        jumpsuit2: SoundHandle
        jumpsuit3: SoundHandle
        jumpsuit4: SoundHandle
        jumpsuit_death: SoundHandle
        jumpsuit_fall: SoundHandle
        jumpsuit_hit1: SoundHandle
        jumpsuit_hit2: SoundHandle
        kronk1: SoundHandle
        kronk10: SoundHandle
        kronk2: SoundHandle
        kronk3: SoundHandle
        kronk4: SoundHandle
        kronk5: SoundHandle
        kronk6: SoundHandle
        kronk7: SoundHandle
        kronk8: SoundHandle
        kronk9: SoundHandle
        kronk_death: SoundHandle
        kronk_fall: SoundHandle
        mel01: SoundHandle
        mel02: SoundHandle
        mel03: SoundHandle
        mel04: SoundHandle
        mel05: SoundHandle
        mel06: SoundHandle
        mel07: SoundHandle
        mel08: SoundHandle
        mel09: SoundHandle
        mel10: SoundHandle
        mel_death01: SoundHandle
        mel_fall01: SoundHandle
        ninja_attack1: SoundHandle
        ninja_attack2: SoundHandle
        ninja_attack3: SoundHandle
        ninja_attack4: SoundHandle
        ninja_attack5: SoundHandle
        ninja_attack6: SoundHandle
        ninja_attack7: SoundHandle
        ninja_death1: SoundHandle
        ninja_fall1: SoundHandle
        ninja_hit1: SoundHandle
        ninja_hit2: SoundHandle
        ninja_hit3: SoundHandle
        ninja_hit4: SoundHandle
        ninja_hit5: SoundHandle
        ninja_hit6: SoundHandle
        ninja_hit7: SoundHandle
        ninja_hit8: SoundHandle
        old_lady1: SoundHandle
        old_lady2: SoundHandle
        old_lady3: SoundHandle
        old_lady4: SoundHandle
        old_lady_death: SoundHandle
        old_lady_fall: SoundHandle
        old_lady_hit1: SoundHandle
        old_lady_hit2: SoundHandle
        opera_singer1: SoundHandle
        opera_singer2: SoundHandle
        opera_singer3: SoundHandle
        opera_singer4: SoundHandle
        opera_singer_death: SoundHandle
        opera_singer_fall: SoundHandle
        opera_singer_hit1: SoundHandle
        opera_singer_hit2: SoundHandle
        penguin1: SoundHandle
        penguin2: SoundHandle
        penguin3: SoundHandle
        penguin4: SoundHandle
        penguin_death: SoundHandle
        penguin_fall: SoundHandle
        penguin_hit1: SoundHandle
        penguin_hit2: SoundHandle
        pixie1: SoundHandle
        pixie2: SoundHandle
        pixie3: SoundHandle
        pixie4: SoundHandle
        pixie_death: SoundHandle
        pixie_fall: SoundHandle
        pixie_hit1: SoundHandle
        pixie_hit2: SoundHandle
        robot1: SoundHandle
        robot2: SoundHandle
        robot3: SoundHandle
        robot4: SoundHandle
        robot_death: SoundHandle
        robot_fall: SoundHandle
        robot_hit1: SoundHandle
        robot_hit2: SoundHandle
        santa01: SoundHandle
        santa02: SoundHandle
        santa03: SoundHandle
        santa04: SoundHandle
        santa05: SoundHandle
        santa_death: SoundHandle
        santa_fall: SoundHandle
        santa_hit01: SoundHandle
        santa_hit02: SoundHandle
        santa_hit03: SoundHandle
        santa_hit04: SoundHandle
        spaz_attack01: SoundHandle
        spaz_attack02: SoundHandle
        spaz_attack03: SoundHandle
        spaz_attack04: SoundHandle
        spaz_death01: SoundHandle
        spaz_fall01: SoundHandle
        spaz_impact01: SoundHandle
        spaz_impact02: SoundHandle
        spaz_impact03: SoundHandle
        spaz_impact04: SoundHandle
        spaz_jump01: SoundHandle
        spaz_jump02: SoundHandle
        spaz_jump03: SoundHandle
        spaz_jump04: SoundHandle
        spaz_pickup01: SoundHandle
        superhero1: SoundHandle
        superhero2: SoundHandle
        superhero3: SoundHandle
        superhero4: SoundHandle
        superhero_death: SoundHandle
        superhero_fall: SoundHandle
        superhero_hit1: SoundHandle
        superhero_hit2: SoundHandle
        warrior1: SoundHandle
        warrior2: SoundHandle
        warrior3: SoundHandle
        warrior4: SoundHandle
        warrior_death: SoundHandle
        warrior_fall: SoundHandle
        warrior_hit1: SoundHandle
        warrior_hit2: SoundHandle
        witch1: SoundHandle
        witch2: SoundHandle
        witch3: SoundHandle
        witch4: SoundHandle
        witch_death: SoundHandle
        witch_fall: SoundHandle
        witch_hit1: SoundHandle
        witch_hit2: SoundHandle
        wizard1: SoundHandle
        wizard2: SoundHandle
        wizard3: SoundHandle
        wizard4: SoundHandle
        wizard_death: SoundHandle
        wizard_fall: SoundHandle
        wizard_hit1: SoundHandle
        wizard_hit2: SoundHandle
        wrestler1: SoundHandle
        wrestler2: SoundHandle
        wrestler3: SoundHandle
        wrestler4: SoundHandle
        wrestler_death: SoundHandle
        wrestler_fall: SoundHandle
        wrestler_hit1: SoundHandle
        wrestler_hit2: SoundHandle
        zoe_attack01: SoundHandle
        zoe_attack02: SoundHandle
        zoe_attack03: SoundHandle
        zoe_attack04: SoundHandle
        zoe_death01: SoundHandle
        zoe_fall01: SoundHandle
        zoe_impact01: SoundHandle
        zoe_impact02: SoundHandle
        zoe_impact03: SoundHandle
        zoe_impact04: SoundHandle
        zoe_jump01: SoundHandle
        zoe_jump02: SoundHandle
        zoe_jump03: SoundHandle
        zoe_pickup01: SoundHandle

    class MeshesGroup:
        """
        ::

            Character body part meshes.

            See source for the full asset list.
        """

        action_hero_fore_arm: MeshHandle
        action_hero_hand: MeshHandle
        action_hero_head: MeshHandle
        action_hero_lower_leg: MeshHandle
        action_hero_pelvis: MeshHandle
        action_hero_toes: MeshHandle
        action_hero_torso: MeshHandle
        action_hero_upper_arm: MeshHandle
        action_hero_upper_leg: MeshHandle
        agent_fore_arm: MeshHandle
        agent_hand: MeshHandle
        agent_head: MeshHandle
        agent_lower_leg: MeshHandle
        agent_pelvis: MeshHandle
        agent_toes: MeshHandle
        agent_torso: MeshHandle
        agent_upper_arm: MeshHandle
        agent_upper_leg: MeshHandle
        ali_fore_arm: MeshHandle
        ali_hand: MeshHandle
        ali_head: MeshHandle
        ali_lower_leg: MeshHandle
        ali_pelvis: MeshHandle
        ali_toes: MeshHandle
        ali_torso: MeshHandle
        ali_upper_arm: MeshHandle
        ali_upper_leg: MeshHandle
        alien_fore_arm: MeshHandle
        alien_hand: MeshHandle
        alien_head: MeshHandle
        alien_lower_leg: MeshHandle
        alien_pelvis: MeshHandle
        alien_toes: MeshHandle
        alien_torso: MeshHandle
        alien_upper_arm: MeshHandle
        alien_upper_leg: MeshHandle
        assassin_fore_arm: MeshHandle
        assassin_hand: MeshHandle
        assassin_head: MeshHandle
        assassin_lower_leg: MeshHandle
        assassin_pelvis: MeshHandle
        assassin_toes: MeshHandle
        assassin_torso: MeshHandle
        assassin_upper_arm: MeshHandle
        assassin_upper_leg: MeshHandle
        bear_fore_arm: MeshHandle
        bear_hand: MeshHandle
        bear_head: MeshHandle
        bear_lower_leg: MeshHandle
        bear_pelvis: MeshHandle
        bear_toes: MeshHandle
        bear_torso: MeshHandle
        bear_upper_arm: MeshHandle
        bear_upper_leg: MeshHandle
        bones_fore_arm: MeshHandle
        bones_hand: MeshHandle
        bones_head: MeshHandle
        bones_lower_leg: MeshHandle
        bones_pelvis: MeshHandle
        bones_toes: MeshHandle
        bones_torso: MeshHandle
        bones_upper_arm: MeshHandle
        bones_upper_leg: MeshHandle
        bunny_fore_arm: MeshHandle
        bunny_hand: MeshHandle
        bunny_head: MeshHandle
        bunny_lower_leg: MeshHandle
        bunny_pelvis: MeshHandle
        bunny_toes: MeshHandle
        bunny_torso: MeshHandle
        bunny_upper_arm: MeshHandle
        bunny_upper_leg: MeshHandle
        cowboy_fore_arm: MeshHandle
        cowboy_hand: MeshHandle
        cowboy_head: MeshHandle
        cowboy_lower_leg: MeshHandle
        cowboy_pelvis: MeshHandle
        cowboy_toes: MeshHandle
        cowboy_torso: MeshHandle
        cowboy_upper_arm: MeshHandle
        cowboy_upper_leg: MeshHandle
        cyborg_fore_arm: MeshHandle
        cyborg_hand: MeshHandle
        cyborg_head: MeshHandle
        cyborg_lower_leg: MeshHandle
        cyborg_pelvis: MeshHandle
        cyborg_toes: MeshHandle
        cyborg_torso: MeshHandle
        cyborg_upper_arm: MeshHandle
        cyborg_upper_leg: MeshHandle
        frosty_fore_arm: MeshHandle
        frosty_hand: MeshHandle
        frosty_head: MeshHandle
        frosty_lower_leg: MeshHandle
        frosty_pelvis: MeshHandle
        frosty_toes: MeshHandle
        frosty_torso: MeshHandle
        frosty_upper_arm: MeshHandle
        frosty_upper_leg: MeshHandle
        gladiator_fore_arm: MeshHandle
        gladiator_hand: MeshHandle
        gladiator_head: MeshHandle
        gladiator_lower_leg: MeshHandle
        gladiator_pelvis: MeshHandle
        gladiator_toes: MeshHandle
        gladiator_torso: MeshHandle
        gladiator_upper_arm: MeshHandle
        gladiator_upper_leg: MeshHandle
        jack_fore_arm: MeshHandle
        jack_hand: MeshHandle
        jack_head: MeshHandle
        jack_lower_leg: MeshHandle
        jack_toes: MeshHandle
        jack_torso: MeshHandle
        jack_upper_arm: MeshHandle
        jack_upper_leg: MeshHandle
        jumpsuit_fore_arm: MeshHandle
        jumpsuit_hand: MeshHandle
        jumpsuit_head: MeshHandle
        jumpsuit_lower_leg: MeshHandle
        jumpsuit_pelvis: MeshHandle
        jumpsuit_toes: MeshHandle
        jumpsuit_torso: MeshHandle
        jumpsuit_upper_arm: MeshHandle
        jumpsuit_upper_leg: MeshHandle
        kronk_fore_arm: MeshHandle
        kronk_hand: MeshHandle
        kronk_head: MeshHandle
        kronk_lower_leg: MeshHandle
        kronk_pelvis: MeshHandle
        kronk_toes: MeshHandle
        kronk_torso: MeshHandle
        kronk_upper_arm: MeshHandle
        kronk_upper_leg: MeshHandle
        mel_fore_arm: MeshHandle
        mel_hand: MeshHandle
        mel_head: MeshHandle
        mel_lower_leg: MeshHandle
        mel_toes: MeshHandle
        mel_torso: MeshHandle
        mel_upper_arm: MeshHandle
        mel_upper_leg: MeshHandle
        neo_spaz_fore_arm: MeshHandle
        neo_spaz_hand: MeshHandle
        neo_spaz_head: MeshHandle
        neo_spaz_lower_leg: MeshHandle
        neo_spaz_pelvis: MeshHandle
        neo_spaz_toes: MeshHandle
        neo_spaz_torso: MeshHandle
        neo_spaz_upper_arm: MeshHandle
        neo_spaz_upper_leg: MeshHandle
        ninja_fore_arm: MeshHandle
        ninja_hand: MeshHandle
        ninja_head: MeshHandle
        ninja_lower_leg: MeshHandle
        ninja_pelvis: MeshHandle
        ninja_toes: MeshHandle
        ninja_torso: MeshHandle
        ninja_upper_arm: MeshHandle
        ninja_upper_leg: MeshHandle
        old_lady_fore_arm: MeshHandle
        old_lady_hand: MeshHandle
        old_lady_head: MeshHandle
        old_lady_lower_leg: MeshHandle
        old_lady_pelvis: MeshHandle
        old_lady_toes: MeshHandle
        old_lady_torso: MeshHandle
        old_lady_upper_arm: MeshHandle
        old_lady_upper_leg: MeshHandle
        opera_singer_fore_arm: MeshHandle
        opera_singer_hand: MeshHandle
        opera_singer_head: MeshHandle
        opera_singer_lower_leg: MeshHandle
        opera_singer_pelvis: MeshHandle
        opera_singer_toes: MeshHandle
        opera_singer_torso: MeshHandle
        opera_singer_upper_arm: MeshHandle
        opera_singer_upper_leg: MeshHandle
        penguin_fore_arm: MeshHandle
        penguin_hand: MeshHandle
        penguin_head: MeshHandle
        penguin_lower_leg: MeshHandle
        penguin_pelvis: MeshHandle
        penguin_toes: MeshHandle
        penguin_torso: MeshHandle
        penguin_upper_arm: MeshHandle
        penguin_upper_leg: MeshHandle
        pixie_fore_arm: MeshHandle
        pixie_hand: MeshHandle
        pixie_head: MeshHandle
        pixie_lower_leg: MeshHandle
        pixie_pelvis: MeshHandle
        pixie_toes: MeshHandle
        pixie_torso: MeshHandle
        pixie_upper_arm: MeshHandle
        pixie_upper_leg: MeshHandle
        robot_fore_arm: MeshHandle
        robot_hand: MeshHandle
        robot_head: MeshHandle
        robot_lower_leg: MeshHandle
        robot_pelvis: MeshHandle
        robot_toes: MeshHandle
        robot_torso: MeshHandle
        robot_upper_arm: MeshHandle
        robot_upper_leg: MeshHandle
        santa_fore_arm: MeshHandle
        santa_hand: MeshHandle
        santa_head: MeshHandle
        santa_lower_leg: MeshHandle
        santa_toes: MeshHandle
        santa_torso: MeshHandle
        santa_upper_arm: MeshHandle
        santa_upper_leg: MeshHandle
        superhero_fore_arm: MeshHandle
        superhero_hand: MeshHandle
        superhero_head: MeshHandle
        superhero_lower_leg: MeshHandle
        superhero_pelvis: MeshHandle
        superhero_toes: MeshHandle
        superhero_torso: MeshHandle
        superhero_upper_arm: MeshHandle
        superhero_upper_leg: MeshHandle
        warrior_fore_arm: MeshHandle
        warrior_hand: MeshHandle
        warrior_head: MeshHandle
        warrior_lower_leg: MeshHandle
        warrior_pelvis: MeshHandle
        warrior_toes: MeshHandle
        warrior_torso: MeshHandle
        warrior_upper_arm: MeshHandle
        warrior_upper_leg: MeshHandle
        witch_fore_arm: MeshHandle
        witch_hand: MeshHandle
        witch_head: MeshHandle
        witch_lower_leg: MeshHandle
        witch_pelvis: MeshHandle
        witch_toes: MeshHandle
        witch_torso: MeshHandle
        witch_upper_arm: MeshHandle
        witch_upper_leg: MeshHandle
        wizard_fore_arm: MeshHandle
        wizard_hand: MeshHandle
        wizard_head: MeshHandle
        wizard_lower_leg: MeshHandle
        wizard_pelvis: MeshHandle
        wizard_toes: MeshHandle
        wizard_torso: MeshHandle
        wizard_upper_arm: MeshHandle
        wizard_upper_leg: MeshHandle
        wrestler_fore_arm: MeshHandle
        wrestler_hand: MeshHandle
        wrestler_head: MeshHandle
        wrestler_lower_leg: MeshHandle
        wrestler_pelvis: MeshHandle
        wrestler_toes: MeshHandle
        wrestler_torso: MeshHandle
        wrestler_upper_arm: MeshHandle
        wrestler_upper_leg: MeshHandle
        zoe_fore_arm: MeshHandle
        zoe_hand: MeshHandle
        zoe_head: MeshHandle
        zoe_lower_leg: MeshHandle
        zoe_pelvis: MeshHandle
        zoe_toes: MeshHandle
        zoe_torso: MeshHandle
        zoe_upper_arm: MeshHandle
        zoe_upper_leg: MeshHandle

    class TexturesGroup:
        """
        ::

            Character body textures and their color masks.

            See source for the full asset list.
        """

        action_hero_color: TextureHandle
        action_hero_color_mask: TextureHandle
        agent_color: TextureHandle
        agent_color_mask: TextureHandle
        ali_color: TextureHandle
        ali_color_mask: TextureHandle
        alien_color: TextureHandle
        alien_color_mask: TextureHandle
        assassin_color: TextureHandle
        assassin_color_mask: TextureHandle
        bear_color: TextureHandle
        bear_color_mask: TextureHandle
        bones_color: TextureHandle
        bones_color_mask: TextureHandle
        bunny_color: TextureHandle
        bunny_color_mask: TextureHandle
        cowboy_color: TextureHandle
        cowboy_color_mask: TextureHandle
        cyborg_color: TextureHandle
        cyborg_color_mask: TextureHandle
        frosty_color: TextureHandle
        frosty_color_mask: TextureHandle
        gladiator_color: TextureHandle
        gladiator_color_mask: TextureHandle
        jack_color: TextureHandle
        jack_color_mask: TextureHandle
        jumpsuit_color: TextureHandle
        jumpsuit_color_mask: TextureHandle
        kronk: TextureHandle
        kronk_color_mask: TextureHandle
        mel_color: TextureHandle
        mel_color_mask: TextureHandle
        neo_spaz_color: TextureHandle
        neo_spaz_color_mask: TextureHandle
        ninja_color: TextureHandle
        ninja_color_mask: TextureHandle
        old_lady_color: TextureHandle
        old_lady_color_mask: TextureHandle
        opera_singer_color: TextureHandle
        opera_singer_color_mask: TextureHandle
        penguin_color: TextureHandle
        penguin_color_mask: TextureHandle
        pixie_color: TextureHandle
        pixie_color_mask: TextureHandle
        robot_color: TextureHandle
        robot_color_mask: TextureHandle
        santa_color: TextureHandle
        santa_color_mask: TextureHandle
        superhero_color: TextureHandle
        superhero_color_mask: TextureHandle
        warrior_color: TextureHandle
        warrior_color_mask: TextureHandle
        witch_color: TextureHandle
        witch_color_mask: TextureHandle
        wizard_color: TextureHandle
        wizard_color_mask: TextureHandle
        wrestler_color: TextureHandle
        wrestler_color_mask: TextureHandle
        zoe_color: TextureHandle
        zoe_color_mask: TextureHandle

    #: The ``audio`` group - 280 assets (``action_hero1``, ``action_hero2``,
    #: ``action_hero3``, ``action_hero4``, ``action_hero_death``, and 275 more).
    #: Full list in source.
    audio: AudioGroup

    #: The ``meshes`` group - 267 assets (``action_hero_fore_arm``,
    #: ``action_hero_hand``, ``action_hero_head``, ``action_hero_lower_leg``,
    #: ``action_hero_pelvis``, and 262 more). Full list in source.
    meshes: MeshesGroup

    #: The ``textures`` group - 60 assets (``action_hero_color``,
    #: ``action_hero_color_mask``, ``agent_color``, ``agent_color_mask``,
    #: ``ali_color``, and 55 more). Full list in source.
    textures: TexturesGroup

_TREE = {
    'audio': {
        'action_hero1': 's',
        'action_hero2': 's',
        'action_hero3': 's',
        'action_hero4': 's',
        'action_hero_death': 's',
        'action_hero_fall': 's',
        'action_hero_hit1': 's',
        'action_hero_hit2': 's',
        'agent1': 's',
        'agent2': 's',
        'agent3': 's',
        'agent4': 's',
        'agent_death': 's',
        'agent_fall': 's',
        'agent_hit1': 's',
        'agent_hit2': 's',
        'ali1': 's',
        'ali2': 's',
        'ali3': 's',
        'ali4': 's',
        'ali_death': 's',
        'ali_fall': 's',
        'ali_hit1': 's',
        'ali_hit2': 's',
        'alien1': 's',
        'alien2': 's',
        'alien3': 's',
        'alien4': 's',
        'alien_death': 's',
        'alien_fall': 's',
        'alien_hit1': 's',
        'alien_hit2': 's',
        'assassin1': 's',
        'assassin2': 's',
        'assassin3': 's',
        'assassin4': 's',
        'assassin_death': 's',
        'assassin_fall': 's',
        'assassin_hit1': 's',
        'assassin_hit2': 's',
        'bear1': 's',
        'bear2': 's',
        'bear3': 's',
        'bear4': 's',
        'bear_death': 's',
        'bear_fall': 's',
        'bear_hit1': 's',
        'bear_hit2': 's',
        'bones1': 's',
        'bones2': 's',
        'bones3': 's',
        'bones_death': 's',
        'bones_fall': 's',
        'bunny1': 's',
        'bunny2': 's',
        'bunny3': 's',
        'bunny4': 's',
        'bunny_death': 's',
        'bunny_fall': 's',
        'bunny_hit1': 's',
        'bunny_hit2': 's',
        'bunny_jump': 's',
        'cowboy1': 's',
        'cowboy2': 's',
        'cowboy3': 's',
        'cowboy4': 's',
        'cowboy_death': 's',
        'cowboy_fall': 's',
        'cowboy_hit1': 's',
        'cowboy_hit2': 's',
        'cyborg1': 's',
        'cyborg2': 's',
        'cyborg3': 's',
        'cyborg4': 's',
        'cyborg_death': 's',
        'cyborg_fall': 's',
        'cyborg_hit1': 's',
        'cyborg_hit2': 's',
        'frosty01': 's',
        'frosty02': 's',
        'frosty03': 's',
        'frosty04': 's',
        'frosty05': 's',
        'frosty_death': 's',
        'frosty_fall': 's',
        'frosty_hit01': 's',
        'frosty_hit02': 's',
        'frosty_hit03': 's',
        'gladiator1': 's',
        'gladiator2': 's',
        'gladiator3': 's',
        'gladiator4': 's',
        'gladiator_death': 's',
        'gladiator_fall': 's',
        'gladiator_hit1': 's',
        'gladiator_hit2': 's',
        'jack01': 's',
        'jack02': 's',
        'jack03': 's',
        'jack04': 's',
        'jack05': 's',
        'jack06': 's',
        'jack_death01': 's',
        'jack_fall01': 's',
        'jack_hit01': 's',
        'jack_hit02': 's',
        'jack_hit03': 's',
        'jack_hit04': 's',
        'jack_hit05': 's',
        'jack_hit06': 's',
        'jack_hit07': 's',
        'jumpsuit1': 's',
        'jumpsuit2': 's',
        'jumpsuit3': 's',
        'jumpsuit4': 's',
        'jumpsuit_death': 's',
        'jumpsuit_fall': 's',
        'jumpsuit_hit1': 's',
        'jumpsuit_hit2': 's',
        'kronk1': 's',
        'kronk10': 's',
        'kronk2': 's',
        'kronk3': 's',
        'kronk4': 's',
        'kronk5': 's',
        'kronk6': 's',
        'kronk7': 's',
        'kronk8': 's',
        'kronk9': 's',
        'kronk_death': 's',
        'kronk_fall': 's',
        'mel01': 's',
        'mel02': 's',
        'mel03': 's',
        'mel04': 's',
        'mel05': 's',
        'mel06': 's',
        'mel07': 's',
        'mel08': 's',
        'mel09': 's',
        'mel10': 's',
        'mel_death01': 's',
        'mel_fall01': 's',
        'ninja_attack1': 's',
        'ninja_attack2': 's',
        'ninja_attack3': 's',
        'ninja_attack4': 's',
        'ninja_attack5': 's',
        'ninja_attack6': 's',
        'ninja_attack7': 's',
        'ninja_death1': 's',
        'ninja_fall1': 's',
        'ninja_hit1': 's',
        'ninja_hit2': 's',
        'ninja_hit3': 's',
        'ninja_hit4': 's',
        'ninja_hit5': 's',
        'ninja_hit6': 's',
        'ninja_hit7': 's',
        'ninja_hit8': 's',
        'old_lady1': 's',
        'old_lady2': 's',
        'old_lady3': 's',
        'old_lady4': 's',
        'old_lady_death': 's',
        'old_lady_fall': 's',
        'old_lady_hit1': 's',
        'old_lady_hit2': 's',
        'opera_singer1': 's',
        'opera_singer2': 's',
        'opera_singer3': 's',
        'opera_singer4': 's',
        'opera_singer_death': 's',
        'opera_singer_fall': 's',
        'opera_singer_hit1': 's',
        'opera_singer_hit2': 's',
        'penguin1': 's',
        'penguin2': 's',
        'penguin3': 's',
        'penguin4': 's',
        'penguin_death': 's',
        'penguin_fall': 's',
        'penguin_hit1': 's',
        'penguin_hit2': 's',
        'pixie1': 's',
        'pixie2': 's',
        'pixie3': 's',
        'pixie4': 's',
        'pixie_death': 's',
        'pixie_fall': 's',
        'pixie_hit1': 's',
        'pixie_hit2': 's',
        'robot1': 's',
        'robot2': 's',
        'robot3': 's',
        'robot4': 's',
        'robot_death': 's',
        'robot_fall': 's',
        'robot_hit1': 's',
        'robot_hit2': 's',
        'santa01': 's',
        'santa02': 's',
        'santa03': 's',
        'santa04': 's',
        'santa05': 's',
        'santa_death': 's',
        'santa_fall': 's',
        'santa_hit01': 's',
        'santa_hit02': 's',
        'santa_hit03': 's',
        'santa_hit04': 's',
        'spaz_attack01': 's',
        'spaz_attack02': 's',
        'spaz_attack03': 's',
        'spaz_attack04': 's',
        'spaz_death01': 's',
        'spaz_fall01': 's',
        'spaz_impact01': 's',
        'spaz_impact02': 's',
        'spaz_impact03': 's',
        'spaz_impact04': 's',
        'spaz_jump01': 's',
        'spaz_jump02': 's',
        'spaz_jump03': 's',
        'spaz_jump04': 's',
        'spaz_pickup01': 's',
        'superhero1': 's',
        'superhero2': 's',
        'superhero3': 's',
        'superhero4': 's',
        'superhero_death': 's',
        'superhero_fall': 's',
        'superhero_hit1': 's',
        'superhero_hit2': 's',
        'warrior1': 's',
        'warrior2': 's',
        'warrior3': 's',
        'warrior4': 's',
        'warrior_death': 's',
        'warrior_fall': 's',
        'warrior_hit1': 's',
        'warrior_hit2': 's',
        'witch1': 's',
        'witch2': 's',
        'witch3': 's',
        'witch4': 's',
        'witch_death': 's',
        'witch_fall': 's',
        'witch_hit1': 's',
        'witch_hit2': 's',
        'wizard1': 's',
        'wizard2': 's',
        'wizard3': 's',
        'wizard4': 's',
        'wizard_death': 's',
        'wizard_fall': 's',
        'wizard_hit1': 's',
        'wizard_hit2': 's',
        'wrestler1': 's',
        'wrestler2': 's',
        'wrestler3': 's',
        'wrestler4': 's',
        'wrestler_death': 's',
        'wrestler_fall': 's',
        'wrestler_hit1': 's',
        'wrestler_hit2': 's',
        'zoe_attack01': 's',
        'zoe_attack02': 's',
        'zoe_attack03': 's',
        'zoe_attack04': 's',
        'zoe_death01': 's',
        'zoe_fall01': 's',
        'zoe_impact01': 's',
        'zoe_impact02': 's',
        'zoe_impact03': 's',
        'zoe_impact04': 's',
        'zoe_jump01': 's',
        'zoe_jump02': 's',
        'zoe_jump03': 's',
        'zoe_pickup01': 's',
    },
    'meshes': {
        'action_hero_fore_arm': 'm',
        'action_hero_hand': 'm',
        'action_hero_head': 'm',
        'action_hero_lower_leg': 'm',
        'action_hero_pelvis': 'm',
        'action_hero_toes': 'm',
        'action_hero_torso': 'm',
        'action_hero_upper_arm': 'm',
        'action_hero_upper_leg': 'm',
        'agent_fore_arm': 'm',
        'agent_hand': 'm',
        'agent_head': 'm',
        'agent_lower_leg': 'm',
        'agent_pelvis': 'm',
        'agent_toes': 'm',
        'agent_torso': 'm',
        'agent_upper_arm': 'm',
        'agent_upper_leg': 'm',
        'ali_fore_arm': 'm',
        'ali_hand': 'm',
        'ali_head': 'm',
        'ali_lower_leg': 'm',
        'ali_pelvis': 'm',
        'ali_toes': 'm',
        'ali_torso': 'm',
        'ali_upper_arm': 'm',
        'ali_upper_leg': 'm',
        'alien_fore_arm': 'm',
        'alien_hand': 'm',
        'alien_head': 'm',
        'alien_lower_leg': 'm',
        'alien_pelvis': 'm',
        'alien_toes': 'm',
        'alien_torso': 'm',
        'alien_upper_arm': 'm',
        'alien_upper_leg': 'm',
        'assassin_fore_arm': 'm',
        'assassin_hand': 'm',
        'assassin_head': 'm',
        'assassin_lower_leg': 'm',
        'assassin_pelvis': 'm',
        'assassin_toes': 'm',
        'assassin_torso': 'm',
        'assassin_upper_arm': 'm',
        'assassin_upper_leg': 'm',
        'bear_fore_arm': 'm',
        'bear_hand': 'm',
        'bear_head': 'm',
        'bear_lower_leg': 'm',
        'bear_pelvis': 'm',
        'bear_toes': 'm',
        'bear_torso': 'm',
        'bear_upper_arm': 'm',
        'bear_upper_leg': 'm',
        'bones_fore_arm': 'm',
        'bones_hand': 'm',
        'bones_head': 'm',
        'bones_lower_leg': 'm',
        'bones_pelvis': 'm',
        'bones_toes': 'm',
        'bones_torso': 'm',
        'bones_upper_arm': 'm',
        'bones_upper_leg': 'm',
        'bunny_fore_arm': 'm',
        'bunny_hand': 'm',
        'bunny_head': 'm',
        'bunny_lower_leg': 'm',
        'bunny_pelvis': 'm',
        'bunny_toes': 'm',
        'bunny_torso': 'm',
        'bunny_upper_arm': 'm',
        'bunny_upper_leg': 'm',
        'cowboy_fore_arm': 'm',
        'cowboy_hand': 'm',
        'cowboy_head': 'm',
        'cowboy_lower_leg': 'm',
        'cowboy_pelvis': 'm',
        'cowboy_toes': 'm',
        'cowboy_torso': 'm',
        'cowboy_upper_arm': 'm',
        'cowboy_upper_leg': 'm',
        'cyborg_fore_arm': 'm',
        'cyborg_hand': 'm',
        'cyborg_head': 'm',
        'cyborg_lower_leg': 'm',
        'cyborg_pelvis': 'm',
        'cyborg_toes': 'm',
        'cyborg_torso': 'm',
        'cyborg_upper_arm': 'm',
        'cyborg_upper_leg': 'm',
        'frosty_fore_arm': 'm',
        'frosty_hand': 'm',
        'frosty_head': 'm',
        'frosty_lower_leg': 'm',
        'frosty_pelvis': 'm',
        'frosty_toes': 'm',
        'frosty_torso': 'm',
        'frosty_upper_arm': 'm',
        'frosty_upper_leg': 'm',
        'gladiator_fore_arm': 'm',
        'gladiator_hand': 'm',
        'gladiator_head': 'm',
        'gladiator_lower_leg': 'm',
        'gladiator_pelvis': 'm',
        'gladiator_toes': 'm',
        'gladiator_torso': 'm',
        'gladiator_upper_arm': 'm',
        'gladiator_upper_leg': 'm',
        'jack_fore_arm': 'm',
        'jack_hand': 'm',
        'jack_head': 'm',
        'jack_lower_leg': 'm',
        'jack_toes': 'm',
        'jack_torso': 'm',
        'jack_upper_arm': 'm',
        'jack_upper_leg': 'm',
        'jumpsuit_fore_arm': 'm',
        'jumpsuit_hand': 'm',
        'jumpsuit_head': 'm',
        'jumpsuit_lower_leg': 'm',
        'jumpsuit_pelvis': 'm',
        'jumpsuit_toes': 'm',
        'jumpsuit_torso': 'm',
        'jumpsuit_upper_arm': 'm',
        'jumpsuit_upper_leg': 'm',
        'kronk_fore_arm': 'm',
        'kronk_hand': 'm',
        'kronk_head': 'm',
        'kronk_lower_leg': 'm',
        'kronk_pelvis': 'm',
        'kronk_toes': 'm',
        'kronk_torso': 'm',
        'kronk_upper_arm': 'm',
        'kronk_upper_leg': 'm',
        'mel_fore_arm': 'm',
        'mel_hand': 'm',
        'mel_head': 'm',
        'mel_lower_leg': 'm',
        'mel_toes': 'm',
        'mel_torso': 'm',
        'mel_upper_arm': 'm',
        'mel_upper_leg': 'm',
        'neo_spaz_fore_arm': 'm',
        'neo_spaz_hand': 'm',
        'neo_spaz_head': 'm',
        'neo_spaz_lower_leg': 'm',
        'neo_spaz_pelvis': 'm',
        'neo_spaz_toes': 'm',
        'neo_spaz_torso': 'm',
        'neo_spaz_upper_arm': 'm',
        'neo_spaz_upper_leg': 'm',
        'ninja_fore_arm': 'm',
        'ninja_hand': 'm',
        'ninja_head': 'm',
        'ninja_lower_leg': 'm',
        'ninja_pelvis': 'm',
        'ninja_toes': 'm',
        'ninja_torso': 'm',
        'ninja_upper_arm': 'm',
        'ninja_upper_leg': 'm',
        'old_lady_fore_arm': 'm',
        'old_lady_hand': 'm',
        'old_lady_head': 'm',
        'old_lady_lower_leg': 'm',
        'old_lady_pelvis': 'm',
        'old_lady_toes': 'm',
        'old_lady_torso': 'm',
        'old_lady_upper_arm': 'm',
        'old_lady_upper_leg': 'm',
        'opera_singer_fore_arm': 'm',
        'opera_singer_hand': 'm',
        'opera_singer_head': 'm',
        'opera_singer_lower_leg': 'm',
        'opera_singer_pelvis': 'm',
        'opera_singer_toes': 'm',
        'opera_singer_torso': 'm',
        'opera_singer_upper_arm': 'm',
        'opera_singer_upper_leg': 'm',
        'penguin_fore_arm': 'm',
        'penguin_hand': 'm',
        'penguin_head': 'm',
        'penguin_lower_leg': 'm',
        'penguin_pelvis': 'm',
        'penguin_toes': 'm',
        'penguin_torso': 'm',
        'penguin_upper_arm': 'm',
        'penguin_upper_leg': 'm',
        'pixie_fore_arm': 'm',
        'pixie_hand': 'm',
        'pixie_head': 'm',
        'pixie_lower_leg': 'm',
        'pixie_pelvis': 'm',
        'pixie_toes': 'm',
        'pixie_torso': 'm',
        'pixie_upper_arm': 'm',
        'pixie_upper_leg': 'm',
        'robot_fore_arm': 'm',
        'robot_hand': 'm',
        'robot_head': 'm',
        'robot_lower_leg': 'm',
        'robot_pelvis': 'm',
        'robot_toes': 'm',
        'robot_torso': 'm',
        'robot_upper_arm': 'm',
        'robot_upper_leg': 'm',
        'santa_fore_arm': 'm',
        'santa_hand': 'm',
        'santa_head': 'm',
        'santa_lower_leg': 'm',
        'santa_toes': 'm',
        'santa_torso': 'm',
        'santa_upper_arm': 'm',
        'santa_upper_leg': 'm',
        'superhero_fore_arm': 'm',
        'superhero_hand': 'm',
        'superhero_head': 'm',
        'superhero_lower_leg': 'm',
        'superhero_pelvis': 'm',
        'superhero_toes': 'm',
        'superhero_torso': 'm',
        'superhero_upper_arm': 'm',
        'superhero_upper_leg': 'm',
        'warrior_fore_arm': 'm',
        'warrior_hand': 'm',
        'warrior_head': 'm',
        'warrior_lower_leg': 'm',
        'warrior_pelvis': 'm',
        'warrior_toes': 'm',
        'warrior_torso': 'm',
        'warrior_upper_arm': 'm',
        'warrior_upper_leg': 'm',
        'witch_fore_arm': 'm',
        'witch_hand': 'm',
        'witch_head': 'm',
        'witch_lower_leg': 'm',
        'witch_pelvis': 'm',
        'witch_toes': 'm',
        'witch_torso': 'm',
        'witch_upper_arm': 'm',
        'witch_upper_leg': 'm',
        'wizard_fore_arm': 'm',
        'wizard_hand': 'm',
        'wizard_head': 'm',
        'wizard_lower_leg': 'm',
        'wizard_pelvis': 'm',
        'wizard_toes': 'm',
        'wizard_torso': 'm',
        'wizard_upper_arm': 'm',
        'wizard_upper_leg': 'm',
        'wrestler_fore_arm': 'm',
        'wrestler_hand': 'm',
        'wrestler_head': 'm',
        'wrestler_lower_leg': 'm',
        'wrestler_pelvis': 'm',
        'wrestler_toes': 'm',
        'wrestler_torso': 'm',
        'wrestler_upper_arm': 'm',
        'wrestler_upper_leg': 'm',
        'zoe_fore_arm': 'm',
        'zoe_hand': 'm',
        'zoe_head': 'm',
        'zoe_lower_leg': 'm',
        'zoe_pelvis': 'm',
        'zoe_toes': 'm',
        'zoe_torso': 'm',
        'zoe_upper_arm': 'm',
        'zoe_upper_leg': 'm',
    },
    'textures': {
        'action_hero_color': 't',
        'action_hero_color_mask': 't',
        'agent_color': 't',
        'agent_color_mask': 't',
        'ali_color': 't',
        'ali_color_mask': 't',
        'alien_color': 't',
        'alien_color_mask': 't',
        'assassin_color': 't',
        'assassin_color_mask': 't',
        'bear_color': 't',
        'bear_color_mask': 't',
        'bones_color': 't',
        'bones_color_mask': 't',
        'bunny_color': 't',
        'bunny_color_mask': 't',
        'cowboy_color': 't',
        'cowboy_color_mask': 't',
        'cyborg_color': 't',
        'cyborg_color_mask': 't',
        'frosty_color': 't',
        'frosty_color_mask': 't',
        'gladiator_color': 't',
        'gladiator_color_mask': 't',
        'jack_color': 't',
        'jack_color_mask': 't',
        'jumpsuit_color': 't',
        'jumpsuit_color_mask': 't',
        'kronk': 't',
        'kronk_color_mask': 't',
        'mel_color': 't',
        'mel_color_mask': 't',
        'neo_spaz_color': 't',
        'neo_spaz_color_mask': 't',
        'ninja_color': 't',
        'ninja_color_mask': 't',
        'old_lady_color': 't',
        'old_lady_color_mask': 't',
        'opera_singer_color': 't',
        'opera_singer_color_mask': 't',
        'penguin_color': 't',
        'penguin_color_mask': 't',
        'pixie_color': 't',
        'pixie_color_mask': 't',
        'robot_color': 't',
        'robot_color_mask': 't',
        'santa_color': 't',
        'santa_color_mask': 't',
        'superhero_color': 't',
        'superhero_color_mask': 't',
        'warrior_color': 't',
        'warrior_color_mask': 't',
        'witch_color': 't',
        'witch_color_mask': 't',
        'wizard_color': 't',
        'wizard_color_mask': 't',
        'wrestler_color': 't',
        'wrestler_color_mask': 't',
        'zoe_color': 't',
        'zoe_color_mask': 't',
    },
}


if not TYPE_CHECKING:
    audio = AssetGroup(_ASSET_PACKAGE, _TREE['audio'], 'audio')
    meshes = AssetGroup(_ASSET_PACKAGE, _TREE['meshes'], 'meshes')
    textures = AssetGroup(_ASSET_PACKAGE, _TREE['textures'], 'textures')
