# Released under the MIT License. See LICENSE for details.
#
"""Asset-bundle staging for builds.

Mirrors a build's configured asset-bundle (manifest + transitively
referenced CAS blobs) into a staged ``ba_data/``. Split out of
:mod:`batools.staging` to keep that module under the line limit.
"""

import os


def _collect_bundle_hashes(
    projroot: str, bundle_manifest_path: str
) -> set[str]:
    """Walk the top-level bundle and return every transitively
    referenced CAS hash (bucket-manifest blobs plus the data
    blobs those manifests reference)."""
    import json

    with open(bundle_manifest_path, encoding='utf-8') as infile:
        bundle = json.loads(infile.read())

    flavor_manifest_maps = [
        e['flavor_manifests'] for e in bundle['asset_package_versions'].values()
    ]

    hashes: set[str] = set()
    for flavor_manifests in flavor_manifest_maps:
        for manifest_hash in flavor_manifests.values():
            hashes.add(manifest_hash)
            blob_path = (
                f'{projroot}/.cache/assetdata/'
                f'{manifest_hash[:2]}/{manifest_hash[2:]}'
            )
            with open(blob_path, encoding='utf-8') as infile:
                flavor_manifest = json.loads(infile.read())
            # Each entry is a part-keyed component map (decision #16);
            # flatten over parts to collect every data-blob hash.
            hashes.update(
                comp['h']
                for info in flavor_manifest['e'].values()
                for comp in info.values()
            )
    return hashes


def _verify_builtin_apverid_bundled(
    projroot: str, profile: str, bundle_manifest_path: str
) -> None:
    """Fail loudly if the compiled-in builtin apverid isn't bundled.

    ``base.h``'s autogenerated ``kBuiltinAssetsApverid`` is the
    asset-package version the binary's ``LoadBuiltinTexture`` calls
    ask for at startup. If the asset-id splice drifts from the staged
    bundle — a half-applied ``assetpins update``, a lazybuild-skipped
    codegen, a hand-edited pin — every builtin load asks for an
    unbundled package and the binary crashes on launch under a flood
    of ``Asset not found in package`` errors. Catching it here, the
    last step before the artifact is runnable, turns that confusing
    runtime crash into one actionable build-time message.

    Compares apverid strings only (not the full splice): that's the
    field that drifts, and it's robust without a resolved manifest or
    a matching clang-format. Skips quietly if base.h has no splice.
    """
    import re
    import json

    from efro.error import CleanError

    base_h_path = f'{projroot}/src/ballistica/base/base.h'
    if not os.path.exists(base_h_path):
        return
    with open(base_h_path, encoding='utf-8') as infile:
        match = re.search(
            r'kBuiltinAssetsApverid\s*=\s*"([^"]+)"', infile.read()
        )
    if match is None:
        return
    builtin_apverid = match.group(1)

    with open(bundle_manifest_path, encoding='utf-8') as infile:
        bundled = set(json.load(infile).get('asset_package_versions', {}))

    if builtin_apverid not in bundled:
        raise CleanError(
            f"Builtin-asset splice is stale: base.h kBuiltinAssetsApverid"
            f" is '{builtin_apverid}', but the staged"
            f" '{profile}' bundle contains"
            f' {sorted(bundled)}. The compiled-in builtin package is not'
            f' in the bundle, so this build would crash on launch. Re-sync'
            f' the splice with `tools/pcommand assetpins update'
            f' babuiltinassets <ver>` (now self-healing) or `tools/pcommand'
            f' gen_builtin_asset_ids`, then rebuild.'
        )


def sync_asset_bundle(
    projroot: str, dst: str, profile: str, blob_suffix: str = ''
) -> None:
    """Stage the build's asset bundle into ba_data/.

    ``blob_suffix`` is appended to staged blob file names (their
    sources stay canonically named); Android uses ``.bablob`` so the
    blobs can be packed uncompressed in the apk via gradle's
    suffix-matched ``noCompress`` and served as spans from a boot-time
    apk mapping. The suffix participates in the wanted-vs-existing
    diff below, so repeat syncs remain incremental (steady state does
    no copying); the one-time switchover prunes/re-copies the set.

    Reads ``.cache/asset_bundle/<profile>/manifest.json``
    for whichever bundle profile (e.g. ``gui-minimal`` /
    ``headless-minimal``) this build was configured for, walks
    it to collect every transitively-referenced CAS blob
    (bucket-manifests plus the data blobs those manifests
    reference), and mirrors
    the resulting set into ``<staged>/ba_data/assets/``.
    Already-correct blobs (right hash already at the right
    path) are left alone, missing ones are copied in, and
    anything else under ``assets/`` — stale orphans from
    prior builds, cruft like ``.DS_Store`` — is pruned.
    Also copies the top-level ``manifest.json`` itself to
    ``<staged>/ba_data/manifest.json``.
    """
    import shutil
    import concurrent.futures

    bundle_manifest_path = (
        f'{projroot}/.cache/asset_bundle/{profile}/manifest.json'
    )
    if not os.path.exists(bundle_manifest_path):
        bundle_root = f'{projroot}/.cache/asset_bundle'
        siblings = (
            sorted(
                e
                for e in os.listdir(bundle_root)
                if os.path.isdir(os.path.join(bundle_root, e))
            )
            if os.path.isdir(bundle_root)
            else []
        )
        if siblings:
            # Our profile is missing but *other* profiles are present:
            # this is a corrupt/partial asset cache, not an asset-target
            # wiring bug. lazybuild guards the assets sub-build on the
            # existence of the shared .cache/asset_bundle dir (so a full
            # `rm -rf .cache/asset_bundle` re-triggers it), but a sibling
            # profile's presence satisfies that dir-level check -- so with
            # a stale lazybuild marker a single missing profile gets
            # skipped rather than rebuilt. Clearing the whole dir restores
            # the guard's ability to fire.
            raise RuntimeError(
                f"Asset bundle manifest for profile"
                f" '{profile}' was not found at"
                f' {bundle_manifest_path}, but other profiles are present'
                f' ({', '.join(siblings)}). This is a corrupt/partial'
                f' asset cache (a single bundle profile is missing while'
                f' siblings remain), so lazybuild -- which guards the'
                f' assets sub-build on the existence of the shared'
                f' .cache/asset_bundle dir -- saw the dir present (via a'
                f' sibling) and skipped the rebuild. Clear the asset'
                f' bundle cache and rebuild:\n'
                f'    rm -rf .cache/asset_bundle\n'
                f' (with the dir fully gone, lazybuild re-triggers the'
                f' assets build and regenerates every profile).'
            )
        raise RuntimeError(
            f"Asset bundle manifest for profile"
            f" '{profile}' was not found at"
            f' {bundle_manifest_path}. The'
            f' asset-build phase should have produced it (the manifest'
            f' rides the COMMON_GUI / COMMON_SERVER target lists in'
            f' src/assets/Makefile). This almost always means this build'
            f' stages a different bundle variant than its asset'
            f' prerequisite builds -- e.g. a server staging path'
            f' (-cmakeserver / -winserver) sourcing a gui assets target.'
            f' Point the build at the assets target that builds the'
            f' matching variant: gui staging needs a gui assets target'
            f' (assets-cmake / assets-windows), server staging needs a'
            f' server assets target (assets-server /'
            f' assets-windows-server).'
        )

    # Last-chance consistency gate before this bundle becomes a
    # runnable artifact: the compiled-in builtin apverid must be one
    # of the packages we're staging (see the function docstring).
    _verify_builtin_apverid_bundled(projroot, profile, bundle_manifest_path)

    wanted_hashes = _collect_bundle_hashes(projroot, bundle_manifest_path)
    wanted: set[tuple[str, str]] = {
        (h[:2], h[2:] + blob_suffix) for h in wanted_hashes
    }
    wanted_prefixes: set[str] = {p for p, _ in wanted}

    # Scan the existing staged tree once. CAS naming means
    # "file at the right path = right content", so anything
    # already present that matches a wanted entry needs no
    # work; anything present that doesn't is an orphan to
    # prune (covers both stale hashes from prior builds and
    # cruft files like .DS_Store — no special-case needed).
    assets_root = f'{dst}/ba_data/assets'
    existing: set[tuple[str, str]] = set()
    existing_prefixes: set[str] = set()
    if os.path.isdir(assets_root):
        for entry in os.scandir(assets_root):
            if entry.is_dir(follow_symlinks=False):
                existing_prefixes.add(entry.name)
                for sub in os.scandir(entry.path):
                    if sub.is_file(follow_symlinks=False):
                        existing.add((entry.name, sub.name))
            elif entry.is_file(follow_symlinks=False):
                # Stray file at assets/ root (.DS_Store, etc.);
                # the wanted set lives only under prefix dirs.
                os.unlink(entry.path)

    to_copy = wanted - existing
    to_delete = existing - wanted

    # Pre-create any prefix dirs we'll be writing into.
    for prefix in wanted_prefixes:
        os.makedirs(f'{assets_root}/{prefix}', exist_ok=True)

    def _copy_one(item: tuple[str, str]) -> None:
        prefix, rest = item
        srcname = rest.removesuffix(blob_suffix) if blob_suffix else rest
        src = f'{projroot}/.cache/assetdata/{prefix}/{srcname}'
        blobdst = f'{assets_root}/{prefix}/{rest}'
        shutil.copyfile(src, blobdst)
        shutil.copystat(src, blobdst)

    def _delete_one(item: tuple[str, str]) -> None:
        prefix, rest = item
        os.unlink(f'{assets_root}/{prefix}/{rest}')

    # Parallel I/O for the two bulk passes. The pool exits
    # eagerly on exception so a copy/delete failure surfaces
    # rather than getting swallowed.
    if to_copy or to_delete:
        with concurrent.futures.ThreadPoolExecutor(max_workers=16) as pool:
            for _ in pool.map(_copy_one, to_copy):
                pass
            for _ in pool.map(_delete_one, to_delete):
                pass

    # Drop now-empty prefix dirs (existing − wanted). Silently
    # skip non-empty ones — those carry leftover non-CAS junk
    # we'd rather not touch.
    for prefix in existing_prefixes - wanted_prefixes:
        try:
            os.rmdir(f'{assets_root}/{prefix}')
        except OSError:
            pass

    # And the top-level pointer.
    bundle_dst = f'{dst}/ba_data/manifest.json'
    os.makedirs(os.path.dirname(bundle_dst), exist_ok=True)
    shutil.copyfile(bundle_manifest_path, bundle_dst)
    shutil.copystat(bundle_manifest_path, bundle_dst)
