# Released under the MIT License. See LICENSE for details.
#
"""A nice collection of ready-to-use pcommands for this package."""

from __future__ import annotations

# Note: import as little as possible here at the module level to
# keep launch times fast for small snippets.
import sys
from typing import TYPE_CHECKING

from efrotools import pcommand

if TYPE_CHECKING:
    from libcst import BaseExpression
    from libcst.metadata import CodeRange


#: Root under which ``test_game_run`` stores per-instance silo dirs.
#: Each silo is self-contained state for one running instance
#: (``ba_root/``, ``pid``, ``out``, etc.) so multiple instances can run
#: concurrently without stepping on each other.
_TEST_GAME_SILO_ROOT = 'build/test_run'

#: Default UDP port for newly-created server silos. Override with
#: ``--port`` at silo creation time (or edit the silo's ``config.toml``
#: after the fact) when running multiple servers concurrently.
_TEST_GAME_DEFAULT_PORT = 43210


def _test_game_run_parse_args() -> dict[str, object]:
    """Parse ``test_game_run`` argv.

    Returns a dict with keys ``instance``, ``log_levels``, ``timeout``,
    ``fleet``, ``headless``, ``exec_code``, ``background``, and
    ``port``.
    """
    args = sys.argv[2:]
    out: dict[str, object] = {
        'instance': 'default',
        'log_levels': '',
        'timeout': 10,
        'fleet': '',
        'headless': False,
        'exec_code': None,
        'background': False,
        'port': None,
    }
    while args:
        if args[0] == '--instance' and len(args) > 1:
            out['instance'] = args[1]
            args = args[2:]
        elif args[0] == '--log' and len(args) > 1:
            out['log_levels'] = args[1]
            args = args[2:]
        elif args[0] == '--timeout' and len(args) > 1:
            out['timeout'] = int(args[1])
            args = args[2:]
        elif args[0] == '--fleet' and len(args) > 1:
            out['fleet'] = args[1]
            args = args[2:]
        elif args[0] == '--headless':
            out['headless'] = True
            args = args[1:]
        elif args[0] == '--exec' and len(args) > 1:
            out['exec_code'] = args[1]
            args = args[2:]
        elif args[0] == '--background':
            out['background'] = True
            args = args[1:]
        elif args[0] == '--port' and len(args) > 1:
            out['port'] = int(args[1])
            args = args[2:]
        else:
            raise RuntimeError(f'Unexpected arg: {args[0]}')
    if out['port'] is not None and not out['headless']:
        raise RuntimeError('--port only applies to --headless instances.')
    return out


def _test_game_silo_path(instance: str) -> str:
    """Return the absolute path of an instance's silo dir."""
    import os

    if not instance or '/' in instance or instance.startswith('.'):
        raise RuntimeError(f'Invalid --instance name: {instance!r}')
    return os.path.abspath(os.path.join(_TEST_GAME_SILO_ROOT, instance))


def _test_game_write_server_config_toml(
    path: str, *, instance: str, port: int
) -> None:
    """Write the per-silo ``config.toml`` for a fresh server instance."""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(
            '# Auto-generated by tools/pcommand test_game_run on first\n'
            f'# creation of silo "{instance}". Edits you make here are\n'
            '# preserved across subsequent launches of this silo.\n'
            f'party_name = "test-{instance}"\n'
            'party_is_public = false\n'
            f'port = {port}\n'
            '\n'
            '# Crank verbosity on the loggers most useful for\n'
            '# connect/handshake debugging.\n'
            '[log_levels]\n'
            '"ba.net" = "DEBUG"\n'
            '"ba.lifecycle" = "DEBUG"\n'
        )


def _test_game_ensure_server_silo(
    silo: str, *, instance: str, port: int | None
) -> None:
    """Create / refresh the server artifacts inside a silo dir.

    Creates ``ba_root/``, symlinks the ``ballisticakit_server`` wrapper
    + its ``dist/`` sibling from the staging dir, and writes a
    ``config.toml`` template on first use.
    """
    import os

    staged = os.path.abspath('build/cmake/server-debug/staged')
    staged_wrapper = os.path.join(staged, 'ballisticakit_server')
    staged_dist = os.path.join(staged, 'dist')
    staged_headless = os.path.join(staged_dist, 'ballisticakit_headless')
    if not os.path.exists(staged_headless):
        raise RuntimeError(
            f'Headless binary not found at {staged_headless}. '
            f'Run "make cmake-server-build" first.'
        )
    if not os.path.exists(staged_wrapper):
        raise RuntimeError(
            f'Server wrapper not found at {staged_wrapper}. '
            f'Run "make cmake-server-build" first.'
        )

    os.makedirs(silo, exist_ok=True)
    os.makedirs(os.path.join(silo, 'ba_root'), exist_ok=True)

    # Symlink the wrapper + dist from staging. Refresh if the target
    # moved (shouldn't happen, but belt-and-suspenders for rebuilds).
    for name, target in (
        ('ballisticakit_server', staged_wrapper),
        ('dist', staged_dist),
    ):
        link_path = os.path.join(silo, name)
        if os.path.islink(link_path):
            if os.readlink(link_path) == target:
                continue
            os.remove(link_path)
        elif os.path.exists(link_path):
            raise RuntimeError(
                f'{link_path} exists and is not a symlink; '
                f'refusing to clobber. Remove it and retry.'
            )
        os.symlink(target, link_path)

    config_path = os.path.join(silo, 'config.toml')
    if not os.path.exists(config_path):
        _test_game_write_server_config_toml(
            config_path,
            instance=instance,
            port=(port if port is not None else _TEST_GAME_DEFAULT_PORT),
        )
    elif port is not None:
        # Silo already exists. Ignoring --port avoids clobbering the
        # user's edits to config.toml.
        print(
            f'Note: --port ignored for existing silo "{instance}" '
            f'(its config.toml is preserved across runs).'
        )


def _test_game_ensure_client_silo(silo: str) -> None:
    """Create minimal client-instance state inside a silo dir."""
    import os

    os.makedirs(silo, exist_ok=True)
    os.makedirs(os.path.join(silo, 'ba_root'), exist_ok=True)


def _test_game_build_cmd(
    *,
    silo: str,
    headless: bool,
    exec_code: str | None,
) -> tuple[str, list[str]]:
    """Return ``(cwd, cmd)`` for launching the binary against a silo."""
    import os

    if headless:
        # Run the wrapper from inside the silo so its subprocess
        # ``cwd='dist'`` resolves to the silo's dist symlink (which
        # points back at the staging dist). --root and --config are
        # absolute so they don't care about the wrapper's cwd. The
        # wrapper's own --exec flag forwards to the underlying
        # ballisticakit_headless subprocess.
        cmd: list[str] = [
            './ballisticakit_server',
            '--root',
            os.path.join(silo, 'ba_root'),
            '--config',
            os.path.join(silo, 'config.toml'),
            '--noninteractive',
        ]
        if exec_code is not None:
            cmd += ['--exec', exec_code]
        return (silo, cmd)

    # Client: run the GUI binary from its staging dir (so bundled
    # ba_data is found) with --config-dir pointing at the silo's
    # ba_root. No need to mirror the binary into the silo.
    staged = os.path.abspath('build/cmake/debug/staged')
    binary = os.path.join(staged, 'ballisticakit')
    if not os.path.exists(binary):
        raise RuntimeError(
            f'Binary not found at {binary}. Run "make cmake-build" first.'
        )
    cmd = [
        './ballisticakit',
        '--config-dir',
        os.path.join(silo, 'ba_root'),
    ]
    if exec_code is not None:
        cmd += ['--exec', exec_code]
    return (staged, cmd)


def test_game_run() -> None:
    """Run the game for testing purposes in a siloed instance dir.

    Usage::

        tools/pcommand test_game_run [--instance NAME] [--headless]
            [--port N] [--exec CODE] [--log LEVELS] [--timeout SECONDS]
            [--fleet FLEET] [--background]

    Each instance lives under ``build/test_run/<name>/`` with its own
    ``ba_root/``, ``config.toml`` (server only), ``pid``, and ``out``.
    Silos auto-create on first use. Run two instances concurrently by
    passing different ``--instance`` names; give server instances
    distinct ``--port`` values so they don't fight over UDP 43210.

    Flags:

    - ``--instance NAME``: Silo name under ``build/test_run/``.
      Defaults to ``default``.
    - ``--headless``: Launch the headless server build via the
      ``ballisticakit_server`` wrapper (honors ``config.toml`` and
      sends ``StartServerModeCommand``). Without this flag, the GUI
      build is launched as a client.
    - ``--port N``: Only valid at silo creation time for
      ``--headless`` instances. Writes the port into the silo's new
      ``config.toml``. Ignored (with a note) for pre-existing silos.
    - ``--exec CODE``: Python snippet passed via the binary's
      ``--exec`` flag. Works for both GUI and headless builds;
      for headless, ``connect_to_party`` calls are allowed in
      developer builds only (shipped builds hard-block this path).
    - ``--log LEVELS``: Comma-separated logger=LEVEL pairs (e.g.
      ``ba.net=DEBUG``). Passed via ``BA_LOG_LEVELS``.
    - ``--timeout SECONDS``: Foreground-mode hard timeout (default 10).
    - ``--fleet FLEET``: Override master-server fleet (``prod``,
      ``test``, ``dev``).
    - ``--background``: Detach and return immediately. Output is
      captured to ``<silo>/out``. Use ``test_game_kill`` to terminate.
    """
    import os
    import signal
    import subprocess

    pcommand.disallow_in_batch()

    opts = _test_game_run_parse_args()
    instance = opts['instance']
    log_levels = opts['log_levels']
    timeout = opts['timeout']
    fleet = opts['fleet']
    headless = opts['headless']
    exec_code = opts['exec_code']
    background = opts['background']
    port = opts['port']
    assert isinstance(instance, str)
    assert isinstance(log_levels, str)
    assert isinstance(timeout, int)
    assert isinstance(fleet, str)
    assert isinstance(headless, bool)
    assert isinstance(background, bool)
    assert exec_code is None or isinstance(exec_code, str)
    assert port is None or isinstance(port, int)

    silo = _test_game_silo_path(instance)
    if headless:
        _test_game_ensure_server_silo(silo, instance=instance, port=port)
    else:
        _test_game_ensure_client_silo(silo)

    cwd, cmd = _test_game_build_cmd(
        silo=silo, headless=headless, exec_code=exec_code
    )
    pid_file = os.path.join(silo, 'pid')
    out_path = os.path.join(silo, 'out')

    env = dict(os.environ)
    if log_levels:
        env['BA_LOG_LEVELS'] = log_levels
    if fleet:
        env['BA_FLEET'] = fleet

    if background:
        # pylint: disable=consider-using-with
        out_f = open(out_path, 'wb')
        proc = subprocess.Popen(
            cmd,
            cwd=cwd,
            stdout=out_f,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            env=env,
            # New session so signals reach the whole process group —
            # important for the wrapper script, which spawns the
            # headless binary as a child.
            start_new_session=True,
        )
        with open(pid_file, 'w', encoding='utf-8') as f:
            f.write(str(proc.pid))
        joined_cmd = ' '.join(cmd)
        role = 'server' if headless else 'client'
        print(f'Launched test game {role} "{instance}" (pid={proc.pid}).')
        print(f'  cmd:    {joined_cmd}')
        print(f'  cwd:    {cwd}')
        print(f'  output: {out_path}')
        print(f'  pidfile: {pid_file}')
        return

    # Foreground mode.
    with subprocess.Popen(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        stdin=subprocess.DEVNULL,
        env=env,
        start_new_session=True,
    ) as proc:
        with open(pid_file, 'w', encoding='utf-8') as f:
            f.write(str(proc.pid))

        try:
            stdout, _ = proc.communicate(timeout=timeout)
        except subprocess.TimeoutExpired:
            # Signal the whole group so the wrapper + its subprocess
            # both come down when --headless.
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            except ProcessLookupError:
                proc.send_signal(signal.SIGTERM)
            stdout, _ = proc.communicate(timeout=5)
        finally:
            if os.path.exists(pid_file):
                os.remove(pid_file)

    if stdout:
        sys.stdout.buffer.write(stdout)
        sys.stdout.buffer.flush()


def _test_game_kill_pid_file(pid_file: str) -> bool:
    """Kill the process referenced by ``pid_file`` if it exists.

    Returns True iff the pid file was present (regardless of whether
    the process itself was still alive).
    """
    import os
    import signal

    if not os.path.exists(pid_file):
        return False

    with open(pid_file, 'r', encoding='utf-8') as f:
        pid = int(f.read().strip())

    # Try killing the whole process group first so wrapper +
    # subprocess both come down; fall back to a plain kill if the
    # group is gone or we can't reach it.
    try:
        os.killpg(os.getpgid(pid), signal.SIGTERM)
        print(f'Sent SIGTERM to process group {pid} ({pid_file}).')
    except (ProcessLookupError, PermissionError):
        try:
            os.kill(pid, signal.SIGTERM)
            print(f'Sent SIGTERM to process {pid} ({pid_file}).')
        except ProcessLookupError:
            print(f'Process {pid} not found ({pid_file}).')

    os.remove(pid_file)
    return True


def test_game_kill() -> None:
    """Kill running test game instances started by ``test_game_run``.

    Usage::

        tools/pcommand test_game_kill [--instance NAME]

    With no ``--instance`` argument, kills every silo that has a live
    ``pid`` file under ``build/test_run/``. With ``--instance NAME``,
    kills only that one. Also sweeps any legacy PID files at the old
    ``build/tmp/test_game_run*.pid`` locations so older runs don't
    strand processes.
    """
    import glob
    import os

    pcommand.disallow_in_batch()

    args = sys.argv[2:]
    only_instance: str | None = None
    while args:
        if args[0] == '--instance' and len(args) > 1:
            only_instance = args[1]
            args = args[2:]
        else:
            raise RuntimeError(f'Unexpected arg: {args[0]}')

    targets: list[str] = []
    if only_instance is not None:
        targets.append(os.path.join(_test_game_silo_path(only_instance), 'pid'))
    else:
        targets.extend(sorted(glob.glob(f'{_TEST_GAME_SILO_ROOT}/*/pid')))
        # Legacy single-slot filenames from before the silo refactor;
        # keep killing them so stale runs don't strand processes.
        for legacy in (
            'build/tmp/test_game_run.pid',
            'build/tmp/test_game_run_client.pid',
            'build/tmp/test_game_run_server.pid',
        ):
            if os.path.exists(legacy):
                targets.append(legacy)

    found_any = False
    for pid_file in targets:
        if _test_game_kill_pid_file(pid_file):
            found_any = True

    if not found_any:
        print('No test game PID files found.')


def compose_docker_gui_release() -> None:
    """Build the docker image with bombsquad cmake gui."""
    import batools.docker

    batools.docker.docker_compose(headless_build=False)


def compose_docker_gui_debug() -> None:
    """Build the docker image with bombsquad debug cmake gui."""
    import batools.docker

    batools.docker.docker_compose(headless_build=False, build_type='Debug')


def compose_docker_server_release() -> None:
    """Build the docker image with bombsquad cmake server."""
    import batools.docker

    batools.docker.docker_compose()


def compose_docker_server_debug() -> None:
    """Build the docker image with bombsquad debug cmake server."""
    import batools.docker

    batools.docker.docker_compose(build_type='Debug')


def compose_docker_arm64_gui_release() -> None:
    """Build the docker image with bombsquad cmake for arm64."""
    import batools.docker

    batools.docker.docker_compose(headless_build=False, platform='linux/arm64')


def compose_docker_arm64_gui_debug() -> None:
    """Build the docker image with bombsquad cmake for arm64."""
    import batools.docker

    batools.docker.docker_compose(
        headless_build=False, platform='linux/arm64', build_type='Debug'
    )


def compose_docker_arm64_server_release() -> None:
    """Build the docker image with bombsquad cmake server for arm64."""
    import batools.docker

    batools.docker.docker_compose(platform='linux/arm64')


def compose_docker_arm64_server_debug() -> None:
    """Build the docker image with bombsquad cmake server for arm64."""
    import batools.docker

    batools.docker.docker_compose(platform='linux/arm64', build_type='Debug')


def save_docker_images() -> None:
    """Saves bombsquad images loaded into docker."""
    import batools.docker

    batools.docker.docker_save_images()


def remove_docker_images() -> None:
    """Remove the bombsquad images loaded in docker."""
    import batools.docker

    batools.docker.docker_remove_images()


# pylint: disable=too-many-locals,too-many-statements
def generate_flathub_manifest() -> None:
    """Generate a Flathub manifest for Ballistica and push to submodule.
    This function is intended to be run within a GitHub Actions workflow.

    This function:
    1. Copies files from config/flatpak/ to config/flatpak/flathub
    2. Generates the manifest from template using latest GitHub release info
    """
    import json
    import os
    import shutil
    import urllib.request
    import subprocess

    from efro.error import CleanError
    from efro.terminal import Clr

    pcommand.disallow_in_batch()
    try:
        github_repo = os.environ['GITHUB_REPOSITORY']
    except KeyError:
        try:
            user_plus_repo: list[str] = (
                subprocess.run(
                    'git config remote.origin.url',
                    check=True,
                    shell=True,
                    capture_output=True,
                    text=True,
                )
                .stdout.strip(' \n')
                .split('/')
            )
            github_repo = (
                user_plus_repo[-2]
                + '/'
                + user_plus_repo[-1].removesuffix('.git')
            )
        except Exception as e:
            raise CleanError(
                f'GITHUB_REPOSITORY env var not'
                f'set and git remote.origin.url not set.'
                f'{e}'
            ) from e

    # Paths
    flatpak_src_dir = os.path.join(pcommand.PROJROOT, 'config', 'flatpak')
    flathub_dir = os.path.join(pcommand.PROJROOT, 'build', 'flathub')
    template_path = os.path.join(
        flatpak_src_dir, 'net.froemling.bombsquad.yml.template'
    )
    os.makedirs(flathub_dir, exist_ok=True)
    manifest_path = os.path.join(flathub_dir, 'net.froemling.bombsquad.yml')

    print(f'{Clr.BLD}Generating Flathub manifest...{Clr.RST}')

    # Step 1: Copy files from config/flatpak/ to config/flatpak/flathub
    print(
        f'{Clr.BLD}Copying files from {flatpak_src_dir} to '
        f'{flathub_dir}...{Clr.RST}'
    )

    # List of files to copy (skip the flathub directory itself)
    files_to_copy = [
        'net.froemling.bombsquad.metainfo.xml',
        'net.froemling.bombsquad.desktop',
        'net.froemling.bombsquad.releases.xml',
    ]

    for filename in files_to_copy:
        src = os.path.join(flatpak_src_dir, filename)
        dst = os.path.join(flathub_dir, filename)
        if os.path.exists(src):
            shutil.copy2(src, dst)
            print(f'  Copied {filename}')
        else:
            print(f'  Warning: {filename} not found at {src}')

    # Step 2: Get latest release information from GitHub
    print(f'{Clr.BLD}Fetching latest GitHub release info...{Clr.RST}')

    try:
        api_url = f'https://api.github.com/repos/{github_repo}/releases/latest'
        req = urllib.request.Request(api_url)

        with urllib.request.urlopen(req) as response:
            release_data = json.loads(response.read().decode())

        # Find the bombsquad_build_env.tar asset
        asset: dict = {}
        asset_url = None
        asset_name = 'bombsquad_build_env.tar'

        for asset in release_data.get('assets', []):
            if asset['name'] == asset_name:
                asset_url = asset['browser_download_url']
                break

        if not asset_url:
            raise CleanError(
                f'Could not find {asset_name} in latest release assets'
            )

        print(f'  Found asset: {asset_url}')

        # Extract version from release tag
        version = release_data.get('tag_name', '').lstrip('v')
        if not version:
            raise CleanError('Could not extract version from release tag')
        print(f'  Release version: {version}')

        # Extract release date from published_at field
        release_date = release_data.get('published_at', '')
        if not release_date:
            raise CleanError('Could not extract release date from API')
        # Convert ISO format date (e.g., '2026-01-25T12:34:56Z')
        # to YYYY-MM-DD
        release_date = release_date.split('T')[0]
        print(f'  Release date: {release_date}')

        print(f'{Clr.BLD}Getting SHA256 checksum...{Clr.RST}')
        digest = asset.get('digest')
        if not digest or not digest.startswith('sha256:'):
            msg = 'No SHA256 digest found in GitHub release asset'
            raise CleanError(msg)
        checksum = digest.split(':', 1)[1]

    except Exception as e:
        raise CleanError(f'Failed to fetch release info: {e}') from e

    print(f'{Clr.BLD}Generating manifest from template...{Clr.RST}')

    with open(template_path, 'r', encoding='utf-8') as infile:
        template = infile.read()

    def _remove_comments_from_xml_template(content: str) -> str:
        import re

        # Pattern matches lines that start with optional spaces/tabs then '#'
        # This removes the entire line including the newline
        pattern = r'^\s*#.*$\n?'
        result = re.sub(pattern, '', content, flags=re.MULTILINE)

        return result

    template = _remove_comments_from_xml_template(template)
    # Replace placeholders
    manifest_content = template.replace('{ ARCHIVE_URL }', asset_url)
    manifest_content = manifest_content.replace('{ SHA256_CHECKSUM }', checksum)

    with open(manifest_path, 'w', encoding='utf-8') as outfile:
        outfile.write(manifest_content)

    print(f'  Generated manifest at {manifest_path}')

    # Call generate_flatpak_release_manifest with
    # the extracted version, repo URL, and date
    print(f'{Clr.BLD}Generating Flatpak release manifest...{Clr.RST}')
    generate_flatpak_release_manifest(
        version, asset_url, checksum, github_repo, release_date
    )

    print(f'{Clr.BLD}{Clr.GRN}Flathub manifest generation complete!{Clr.RST}')


# pylint: disable=too-many-locals
def generate_flatpak_release_manifest(
    version: str,
    asset_url: str,
    checksum: str,
    github_repo: str,
    release_date: str,
) -> None:
    """Generate a Flatpak release manifest for Ballistica.

    This function:

    1. Adds a new release entry to net.froemling.bombsquad.releases.xml
    2. Updates the net.froemling.bombsquad.releases.xml file with the
       new release information

    Args:
        version: Version string from GitHub release (e.g., '1.7.60')
        asset_url: URL to the release asset
        checksum: SHA256 checksum of the release asset
        github_repo: GitHub repository in format 'owner/repo'
        release_date: Release date in YYYY-MM-DD format
    """
    import os
    from xml.etree import ElementTree as ET

    from efro.error import CleanError
    from efro.terminal import Clr
    from batools.changelog import get_version_changelog

    pcommand.disallow_in_batch()

    # Paths
    flathub_dir = os.path.join(pcommand.PROJROOT, 'build', 'flathub')
    releases_xml_path = os.path.join(
        flathub_dir, 'net.froemling.bombsquad.releases.xml'
    )

    print(f'{Clr.BLD}Adding release {version} to releases.xml...{Clr.RST}')

    # Parse the existing releases.xml
    if not os.path.exists(releases_xml_path):
        raise CleanError(f'releases.xml not found at {releases_xml_path}')

    try:
        tree = ET.parse(releases_xml_path)
        root = tree.getroot()
    except ET.ParseError as e:
        raise CleanError(f'Failed to parse releases.xml: {e}') from e

    # Check if release with this version already exists
    existing_release = root.find(f".//release[@version='{version}']")
    if existing_release is not None:
        print(
            f'{Clr.YLW}Warning: Release {version} '
            f'already exists in releases.xml, skipping...{Clr.RST}'
        )
        return

    # Create new release element
    new_release = ET.Element('release')
    new_release.set('version', version)
    new_release.set('date', release_date)
    new_release.set('urgency', 'low')
    new_release.set('type', 'stable')

    # Add description
    description = ET.SubElement(new_release, 'description')
    changelog_list = get_version_changelog(
        version, projroot=str(pcommand.PROJROOT)
    )
    ul = ET.SubElement(description, 'ul')
    for line in changelog_list:
        li = ET.SubElement(ul, 'li')
        li.text = line

    # Add URL element for release page
    release_url = ET.SubElement(new_release, 'url')
    release_url.text = (
        f'https://github.com/{github_repo}/releases/tag/v{version}'
    )

    # Add artifacts section with binary information
    artifacts = ET.SubElement(new_release, 'artifacts')

    # Add source artifact
    source_artifact = ET.SubElement(artifacts, 'artifact')
    source_artifact.set('type', 'source')

    source_location = ET.SubElement(source_artifact, 'location')
    source_location.text = (
        f'https://github.com/{github_repo}/archive/refs/tags/v{version}.tar.gz'
    )

    # Add binary artifact for linux
    binary_artifact = ET.SubElement(artifacts, 'artifact')
    binary_artifact.set('type', 'source')
    binary_artifact.set('platform', 'x86_64-linux-gnu')

    binary_location = ET.SubElement(binary_artifact, 'location')
    binary_location.text = asset_url

    binary_checksum = ET.SubElement(binary_artifact, 'checksum')
    binary_checksum.set('type', 'sha256')
    binary_checksum.text = checksum

    # Insert the new release at the beginning (after the root element)
    root.insert(0, new_release)

    # Format the XML with proper indentation
    def _indent(elem: ET.Element[str], level: int = 0) -> None:
        """Add pretty-printing indentation to XML tree."""
        indent_str = '\n' + ('    ' * level)
        if len(elem):
            if not elem.text or not elem.text.strip():
                elem.text = indent_str + '    '
            if not elem.tail or not elem.tail.strip():
                elem.tail = indent_str
            child: ET.Element | None = None
            for child in elem:
                _indent(child, level + 1)
            if child and (not child.tail or not child.tail.strip()):
                child.tail = indent_str
        else:
            if level and (not elem.tail or not elem.tail.strip()):
                elem.tail = indent_str

    _indent(root)

    # Write back to file
    try:
        tree.write(releases_xml_path, encoding='utf-8', xml_declaration=True)
        print(f'  Added release {version} to releases.xml')
        print(f'  Generated flatpak release manifest at {releases_xml_path}')
        print(
            f'{Clr.BLD}{Clr.GRN}Flatpak release manifest '
            f'generation complete!{Clr.RST}'
        )
    except Exception as e:
        raise CleanError(f'Failed to write releases.xml: {e}') from e
