name: 'Setup BombSquad Environment'
description: 'Common setup steps for BombSquad builds'
runs:
  using: 'composite'
  steps:    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: config/requirements.txt
    - uses: actions/checkout@v4
    - name: Cache Bombsquad assets
      id: cache-assets
      uses: actions/cache@v4
      env:
        cache-name: cache-bombsquad-assets
      with:
        path: |
          build/assets
          .cache/efrocache/
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.efrocachemap') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
    - name: Setup project environment
      run: make env
      shell: bash