# if provided it will make debug build
ARG cmake_build_type=Release

# system to start with  the build with
# currently will break for non alpine system
ARG base_image=alpine:latest

#-------------------------------BUILDER--------------------------------
# Start with the base image
FROM --platform=$BUILDPLATFORM ${base_image} AS builder

# Renew the arg
ARG cmake_build_type

ENV LANG en_US.utf8
ENV LANGUAGE=en_US
ENV CMAKE_BUILD_TYPE=${cmake_build_type}

# Install build dependencies
RUN apk update && \
    apk add --no-cache \
        python3 \
        python3-dev \
        py3-pip \
        sdl2-dev \
        libvorbis \
        freeglut-dev \
        openal-soft-dev \
        make \
        curl \
        rsync \
        cmake \
        libvorbis-dev \
        clang-dev

# Copy source code
COPY ./ /home/ballistica/ballistica

WORKDIR /home/ballistica/ballistica

# Compile the application
RUN make cmake-server-build \
    && mkdir ../ballistica_cmake_server \
    && mv build/cmake/* ../ballistica_cmake_server

#-------------------------------RUNNER--------------------------------
# Create a new stage for the runtime environment
FROM ${base_image}

ENV LANG en_US.utf8
ENV LANGUAGE=en_US

# Renew the arg
ARG cmake_build_type
LABEL BUILD_TYPE=${cmake_build_type}

ARG bombsquad_build=N/A
LABEL BOMBSQUAD_BUILD=${bombsquad_build}

ARG bombsquad_version=N/A
LABEL BOMBSQUAD_VERSION=${bombsquad_version}

# Install runtime dependencies
RUN apk update && \
    apk add --no-cache \
        python3 \
    && python3 -c "import uuid;print(uuid.uuid4())">/etc/machine-id

# Copy the compiled application from the builder stage
COPY --from=builder /home/ballistica/ballistica_cmake_server/*/staged \
                    /home/ballistica/ballistica
# ballisticakit_headless in staged is a symlink
COPY --from=builder /home/ballistica/ballistica_cmake_server/*/ballisticakit_headless \
                    /home/ballistica/ballistica/dist

WORKDIR /home/ballistica/ballistica

# Set the default command to run the application
CMD ["./ballisticakit_server"]
