// Released under the MIT License. See LICENSE for details.

#include "ballistica/base/assets/asset_name_compat.h"

#include <string>
#include <unordered_map>
#include <utility>

#include "ballistica/core/core.h"
#include "ballistica/core/logging/logging.h"

namespace ballistica::base {

struct Row_ {
  const char* legacy;
  const char* package_key;
  const char* logical_path;
};

// One row per migrated asset. The legacy side is frozen (old peers and
// replays speak these names forever); the (package_key, logical_path)
// side must track package contents - update_project --check verifies
// it against the wrapper modules. Add a row here whenever an asset
// migrates out of the legacy tree.
static const Row_ kRows[] = {
    {"achievement", "classicassets", "audio/achievement"},
    {"achievementBoxer", "classicassets", "textures/achievement_boxer"},
    {"achievementCrossHair", "classicassets",
     "textures/achievement_cross_hair"},
    {"achievementDualWielding", "classicassets",
     "textures/achievement_dual_wielding"},
    {"achievementEmpty", "classicassets", "textures/achievement_empty"},
    {"achievementFlawlessVictory", "classicassets",
     "textures/achievement_flawless_victory"},
    {"achievementFootballShutout", "classicassets",
     "textures/achievement_football_shutout"},
    {"achievementFootballVictory", "classicassets",
     "textures/achievement_football_victory"},
    {"achievementFreeLoader", "classicassets",
     "textures/achievement_free_loader"},
    {"achievementGotTheMoves", "classicassets",
     "textures/achievement_got_the_moves"},
    {"achievementInControl", "classicassets",
     "textures/achievement_in_control"},
    {"achievementMedalLarge", "classicassets",
     "textures/achievement_medal_large"},
    {"achievementMedalMedium", "classicassets",
     "textures/achievement_medal_medium"},
    {"achievementMedalSmall", "classicassets",
     "textures/achievement_medal_small"},
    {"achievementMine", "classicassets", "textures/achievement_mine"},
    {"achievementOffYouGo", "classicassets", "textures/achievement_off_you_go"},
    {"achievementOnslaught", "classicassets", "textures/achievement_onslaught"},
    {"achievementOutline", "classicassets", "meshes/achievement_outline"},
    {"achievementOutline", "classicassets", "textures/achievement_outline"},
    {"achievementRunaround", "classicassets", "textures/achievement_runaround"},
    {"achievementSharingIsCaring", "classicassets",
     "textures/achievement_sharing_is_caring"},
    {"achievementStayinAlive", "classicassets",
     "textures/achievement_stayin_alive"},
    {"achievementSuperPunch", "classicassets",
     "textures/achievement_super_punch"},
    {"achievementTNT", "classicassets", "textures/achievement_tnt"},
    {"achievementTeamPlayer", "classicassets",
     "textures/achievement_team_player"},
    {"achievementWall", "classicassets", "textures/achievement_wall"},
    {"achievementsIcon", "classicassets", "textures/achievements_icon"},
    {"actionButtonBottom", "builtinassets", "meshes/action_button_bottom"},
    {"actionButtonLeft", "builtinassets", "meshes/action_button_left"},
    {"actionButtonRight", "builtinassets", "meshes/action_button_right"},
    {"actionButtonTop", "builtinassets", "meshes/action_button_top"},
    {"actionButtons", "builtinassets", "textures/action_buttons"},
    {"actionHero1", "classicassets", "audio/action_hero1"},
    {"actionHero2", "classicassets", "audio/action_hero2"},
    {"actionHero3", "classicassets", "audio/action_hero3"},
    {"actionHero4", "classicassets", "audio/action_hero4"},
    {"actionHeroColor", "classicassets", "textures/action_hero_color"},
    {"actionHeroColorMask", "classicassets", "textures/action_hero_color_mask"},
    {"actionHeroDeath", "classicassets", "audio/action_hero_death"},
    {"actionHeroFall", "classicassets", "audio/action_hero_fall"},
    {"actionHeroForeArm", "classicassets", "meshes/action_hero_fore_arm"},
    {"actionHeroHand", "classicassets", "meshes/action_hero_hand"},
    {"actionHeroHead", "classicassets", "meshes/action_hero_head"},
    {"actionHeroHit1", "classicassets", "audio/action_hero_hit1"},
    {"actionHeroHit2", "classicassets", "audio/action_hero_hit2"},
    {"actionHeroIcon", "classicassets", "textures/action_hero_icon"},
    {"actionHeroIconColorMask", "classicassets",
     "textures/action_hero_icon_color_mask"},
    {"actionHeroLowerLeg", "classicassets", "meshes/action_hero_lower_leg"},
    {"actionHeroPelvis", "classicassets", "meshes/action_hero_pelvis"},
    {"actionHeroToes", "classicassets", "meshes/action_hero_toes"},
    {"actionHeroTorso", "classicassets", "meshes/action_hero_torso"},
    {"actionHeroUpperArm", "classicassets", "meshes/action_hero_upper_arm"},
    {"actionHeroUpperLeg", "classicassets", "meshes/action_hero_upper_leg"},
    {"activateBeep", "classicassets", "audio/activate_beep"},
    {"advancedIcon", "classicassets", "textures/advanced_icon"},
    {"agent1", "classicassets", "audio/agent1"},
    {"agent2", "classicassets", "audio/agent2"},
    {"agent3", "classicassets", "audio/agent3"},
    {"agent4", "classicassets", "audio/agent4"},
    {"agentColor", "classicassets", "textures/agent_color"},
    {"agentColorMask", "classicassets", "textures/agent_color_mask"},
    {"agentDeath", "classicassets", "audio/agent_death"},
    {"agentFall", "classicassets", "audio/agent_fall"},
    {"agentForeArm", "classicassets", "meshes/agent_fore_arm"},
    {"agentHand", "classicassets", "meshes/agent_hand"},
    {"agentHead", "classicassets", "meshes/agent_head"},
    {"agentHit1", "classicassets", "audio/agent_hit1"},
    {"agentHit2", "classicassets", "audio/agent_hit2"},
    {"agentIcon", "classicassets", "textures/agent_icon"},
    {"agentIconColorMask", "classicassets", "textures/agent_icon_color_mask"},
    {"agentLowerLeg", "classicassets", "meshes/agent_lower_leg"},
    {"agentPelvis", "classicassets", "meshes/agent_pelvis"},
    {"agentToes", "classicassets", "meshes/agent_toes"},
    {"agentTorso", "classicassets", "meshes/agent_torso"},
    {"agentUpperArm", "classicassets", "meshes/agent_upper_arm"},
    {"agentUpperLeg", "classicassets", "meshes/agent_upper_leg"},
    {"alarm", "classicassets", "audio/alarm"},
    {"ali1", "classicassets", "audio/ali1"},
    {"ali2", "classicassets", "audio/ali2"},
    {"ali3", "classicassets", "audio/ali3"},
    {"ali4", "classicassets", "audio/ali4"},
    {"aliColor", "classicassets", "textures/ali_color"},
    {"aliColorMask", "classicassets", "textures/ali_color_mask"},
    {"aliDeath", "classicassets", "audio/ali_death"},
    {"aliFall", "classicassets", "audio/ali_fall"},
    {"aliForeArm", "classicassets", "meshes/ali_fore_arm"},
    {"aliHand", "classicassets", "meshes/ali_hand"},
    {"aliHead", "classicassets", "meshes/ali_head"},
    {"aliHit1", "classicassets", "audio/ali_hit1"},
    {"aliHit2", "classicassets", "audio/ali_hit2"},
    {"aliIcon", "classicassets", "textures/ali_icon"},
    {"aliIconColorMask", "classicassets", "textures/ali_icon_color_mask"},
    {"aliLowerLeg", "classicassets", "meshes/ali_lower_leg"},
    {"aliPelvis", "classicassets", "meshes/ali_pelvis"},
    {"aliSplash", "classicassets", "textures/ali_splash"},
    {"aliToes", "classicassets", "meshes/ali_toes"},
    {"aliTorso", "classicassets", "meshes/ali_torso"},
    {"aliUpperArm", "classicassets", "meshes/ali_upper_arm"},
    {"aliUpperLeg", "classicassets", "meshes/ali_upper_leg"},
    {"alien1", "classicassets", "audio/alien1"},
    {"alien2", "classicassets", "audio/alien2"},
    {"alien3", "classicassets", "audio/alien3"},
    {"alien4", "classicassets", "audio/alien4"},
    {"alienColor", "classicassets", "textures/alien_color"},
    {"alienColorMask", "classicassets", "textures/alien_color_mask"},
    {"alienDeath", "classicassets", "audio/alien_death"},
    {"alienFall", "classicassets", "audio/alien_fall"},
    {"alienForeArm", "classicassets", "meshes/alien_fore_arm"},
    {"alienHand", "classicassets", "meshes/alien_hand"},
    {"alienHead", "classicassets", "meshes/alien_head"},
    {"alienHit1", "classicassets", "audio/alien_hit1"},
    {"alienHit2", "classicassets", "audio/alien_hit2"},
    {"alienIcon", "classicassets", "textures/alien_icon"},
    {"alienIconColorMask", "classicassets", "textures/alien_icon_color_mask"},
    {"alienLowerLeg", "classicassets", "meshes/alien_lower_leg"},
    {"alienPelvis", "classicassets", "meshes/alien_pelvis"},
    {"alienToes", "classicassets", "meshes/alien_toes"},
    {"alienTorso", "classicassets", "meshes/alien_torso"},
    {"alienUpperArm", "classicassets", "meshes/alien_upper_arm"},
    {"alienUpperLeg", "classicassets", "meshes/alien_upper_leg"},
    {"alwaysLandBG", "classicassets", "meshes/always_land_bg"},
    {"alwaysLandBGColor", "classicassets", "textures/always_land_bgcolor"},
    {"alwaysLandLevel", "classicassets", "meshes/always_land_level"},
    {"alwaysLandLevelBottom", "classicassets",
     "meshes/always_land_level_bottom"},
    {"alwaysLandLevelCollide", "classicassets",
     "meshes/always_land_level_collide"},
    {"alwaysLandLevelColor", "classicassets",
     "textures/always_land_level_color"},
    {"alwaysLandPreview", "classicassets", "textures/always_land_preview"},
    {"alwaysLandVRFillMound", "classicassets",
     "meshes/always_land_vrfill_mound"},
    {"analogStick", "classicassets", "textures/analog_stick"},
    {"angryComputerTransparent", "classicassets",
     "meshes/angry_computer_transparent"},
    {"announceEight", "classicassets", "audio/announce_eight"},
    {"announceFive", "classicassets", "audio/announce_five"},
    {"announceFour", "classicassets", "audio/announce_four"},
    {"announceNine", "classicassets", "audio/announce_nine"},
    {"announceOne", "classicassets", "audio/announce_one"},
    {"announceSeven", "classicassets", "audio/announce_seven"},
    {"announceSix", "classicassets", "audio/announce_six"},
    {"announceTen", "classicassets", "audio/announce_ten"},
    {"announceThree", "classicassets", "audio/announce_three"},
    {"announceTwo", "classicassets", "audio/announce_two"},
    {"arrow", "builtinassets", "textures/arrow"},
    {"arrowBack", "builtinassets", "meshes/arrow_back"},
    {"arrowFront", "builtinassets", "meshes/arrow_front"},
    {"assassin1", "classicassets", "audio/assassin1"},
    {"assassin2", "classicassets", "audio/assassin2"},
    {"assassin3", "classicassets", "audio/assassin3"},
    {"assassin4", "classicassets", "audio/assassin4"},
    {"assassinColor", "classicassets", "textures/assassin_color"},
    {"assassinColorMask", "classicassets", "textures/assassin_color_mask"},
    {"assassinDeath", "classicassets", "audio/assassin_death"},
    {"assassinFall", "classicassets", "audio/assassin_fall"},
    {"assassinForeArm", "classicassets", "meshes/assassin_fore_arm"},
    {"assassinHand", "classicassets", "meshes/assassin_hand"},
    {"assassinHead", "classicassets", "meshes/assassin_head"},
    {"assassinHit1", "classicassets", "audio/assassin_hit1"},
    {"assassinHit2", "classicassets", "audio/assassin_hit2"},
    {"assassinIcon", "classicassets", "textures/assassin_icon"},
    {"assassinIconColorMask", "classicassets",
     "textures/assassin_icon_color_mask"},
    {"assassinLowerLeg", "classicassets", "meshes/assassin_lower_leg"},
    {"assassinPelvis", "classicassets", "meshes/assassin_pelvis"},
    {"assassinToes", "classicassets", "meshes/assassin_toes"},
    {"assassinTorso", "classicassets", "meshes/assassin_torso"},
    {"assassinUpperArm", "classicassets", "meshes/assassin_upper_arm"},
    {"assassinUpperLeg", "classicassets", "meshes/assassin_upper_leg"},
    {"audioIcon", "classicassets", "textures/audio_icon"},
    {"aww", "classicassets", "audio/aww"},
    {"backIcon", "builtinassets", "textures/back_icon"},
    {"bar", "classicassets", "textures/bar"},
    {"bear1", "classicassets", "audio/bear1"},
    {"bear2", "classicassets", "audio/bear2"},
    {"bear3", "classicassets", "audio/bear3"},
    {"bear4", "classicassets", "audio/bear4"},
    {"bearColor", "classicassets", "textures/bear_color"},
    {"bearColorMask", "classicassets", "textures/bear_color_mask"},
    {"bearDeath", "classicassets", "audio/bear_death"},
    {"bearFall", "classicassets", "audio/bear_fall"},
    {"bearForeArm", "classicassets", "meshes/bear_fore_arm"},
    {"bearHand", "classicassets", "meshes/bear_hand"},
    {"bearHead", "classicassets", "meshes/bear_head"},
    {"bearHit1", "classicassets", "audio/bear_hit1"},
    {"bearHit2", "classicassets", "audio/bear_hit2"},
    {"bearIcon", "classicassets", "textures/bear_icon"},
    {"bearIconColorMask", "classicassets", "textures/bear_icon_color_mask"},
    {"bearLowerLeg", "classicassets", "meshes/bear_lower_leg"},
    {"bearPelvis", "classicassets", "meshes/bear_pelvis"},
    {"bearToes", "classicassets", "meshes/bear_toes"},
    {"bearTorso", "classicassets", "meshes/bear_torso"},
    {"bearUpperArm", "classicassets", "meshes/bear_upper_arm"},
    {"bearUpperLeg", "classicassets", "meshes/bear_upper_leg"},
    {"bellHigh", "classicassets", "audio/bell_high"},
    {"bellLow", "classicassets", "audio/bell_low"},
    {"bellMed", "classicassets", "audio/bell_med"},
    {"bg", "classicassets", "textures/bg"},
    {"bigG", "classicassets", "meshes/big_g"},
    {"bigG", "classicassets", "textures/big_g"},
    {"bigGBottom", "classicassets", "meshes/big_gbottom"},
    {"bigGBumper", "classicassets", "meshes/big_gbumper"},
    {"bigGCollide", "classicassets", "meshes/big_gcollide"},
    {"bigGPreview", "classicassets", "textures/big_gpreview"},
    {"bigImpact", "classicassets", "audio/big_impact"},
    {"bigImpact2", "classicassets", "audio/big_impact2"},
    {"black", "builtinassets", "textures/black"},
    {"blank", "builtinassets", "audio/blank"},
    {"blip", "builtinassets", "audio/blip"},
    {"block", "classicassets", "audio/block"},
    {"bomb", "classicassets", "meshes/bomb"},
    {"bombButton", "builtinassets", "textures/bomb_button"},
    {"bombColor", "classicassets", "textures/bomb_color"},
    {"bombColorIce", "classicassets", "textures/bomb_color_ice"},
    {"bombDrop01", "classicassets", "audio/bomb_drop01"},
    {"bombDrop02", "classicassets", "audio/bomb_drop02"},
    {"bombRoll01", "classicassets", "audio/bomb_roll01"},
    {"bombSticky", "classicassets", "meshes/bomb_sticky"},
    {"bombStickyColor", "classicassets", "textures/bomb_sticky_color"},
    {"bones1", "classicassets", "audio/bones1"},
    {"bones2", "classicassets", "audio/bones2"},
    {"bones3", "classicassets", "audio/bones3"},
    {"bonesColor", "classicassets", "textures/bones_color"},
    {"bonesColorMask", "classicassets", "textures/bones_color_mask"},
    {"bonesDeath", "classicassets", "audio/bones_death"},
    {"bonesFall", "classicassets", "audio/bones_fall"},
    {"bonesForeArm", "classicassets", "meshes/bones_fore_arm"},
    {"bonesHand", "classicassets", "meshes/bones_hand"},
    {"bonesHead", "classicassets", "meshes/bones_head"},
    {"bonesIcon", "classicassets", "textures/bones_icon"},
    {"bonesIconColorMask", "classicassets", "textures/bones_icon_color_mask"},
    {"bonesLowerLeg", "classicassets", "meshes/bones_lower_leg"},
    {"bonesPelvis", "classicassets", "meshes/bones_pelvis"},
    {"bonesToes", "classicassets", "meshes/bones_toes"},
    {"bonesTorso", "classicassets", "meshes/bones_torso"},
    {"bonesUpperArm", "classicassets", "meshes/bones_upper_arm"},
    {"bonesUpperLeg", "classicassets", "meshes/bones_upper_leg"},
    {"boo", "classicassets", "audio/boo"},
    {"box", "builtinassets", "meshes/box"},
    {"boxDrop", "classicassets", "audio/box_drop"},
    {"boxingBell", "classicassets", "audio/boxing_bell"},
    {"boxingGlove", "builtinassets", "meshes/boxing_glove"},
    {"boxingGlovesColor", "builtinassets", "textures/boxing_gloves_color"},
    {"bridgitLevelBottom", "classicassets", "meshes/bridgit_level_bottom"},
    {"bridgitLevelCollide", "classicassets", "meshes/bridgit_level_collide"},
    {"bridgitLevelColor", "classicassets", "textures/bridgit_level_color"},
    {"bridgitLevelRailingCollide", "classicassets",
     "meshes/bridgit_level_railing_collide"},
    {"bridgitLevelTop", "classicassets", "meshes/bridgit_level_top"},
    {"bridgitPreview", "classicassets", "textures/bridgit_preview"},
    {"bunny1", "classicassets", "audio/bunny1"},
    {"bunny2", "classicassets", "audio/bunny2"},
    {"bunny3", "classicassets", "audio/bunny3"},
    {"bunny4", "classicassets", "audio/bunny4"},
    {"bunnyColor", "classicassets", "textures/bunny_color"},
    {"bunnyColorMask", "classicassets", "textures/bunny_color_mask"},
    {"bunnyDeath", "classicassets", "audio/bunny_death"},
    {"bunnyFall", "classicassets", "audio/bunny_fall"},
    {"bunnyForeArm", "classicassets", "meshes/bunny_fore_arm"},
    {"bunnyHand", "classicassets", "meshes/bunny_hand"},
    {"bunnyHead", "classicassets", "meshes/bunny_head"},
    {"bunnyHit1", "classicassets", "audio/bunny_hit1"},
    {"bunnyHit2", "classicassets", "audio/bunny_hit2"},
    {"bunnyIcon", "classicassets", "textures/bunny_icon"},
    {"bunnyIconColorMask", "classicassets", "textures/bunny_icon_color_mask"},
    {"bunnyJump", "classicassets", "audio/bunny_jump"},
    {"bunnyLowerLeg", "classicassets", "meshes/bunny_lower_leg"},
    {"bunnyPelvis", "classicassets", "meshes/bunny_pelvis"},
    {"bunnyToes", "classicassets", "meshes/bunny_toes"},
    {"bunnyTorso", "classicassets", "meshes/bunny_torso"},
    {"bunnyUpperArm", "classicassets", "meshes/bunny_upper_arm"},
    {"bunnyUpperLeg", "classicassets", "meshes/bunny_upper_leg"},
    {"buttonBackOpaque", "builtinassets", "meshes/button_back_opaque"},
    {"buttonBackSmallOpaque", "builtinassets",
     "meshes/button_back_small_opaque"},
    {"buttonBackSmallTransparent", "builtinassets",
     "meshes/button_back_small_transparent"},
    {"buttonBackTransparent", "builtinassets",
     "meshes/button_back_transparent"},
    {"buttonBomb", "classicassets", "textures/button_bomb"},
    {"buttonJump", "classicassets", "textures/button_jump"},
    {"buttonLargeOpaque", "builtinassets", "meshes/button_large_opaque"},
    {"buttonLargeTransparent", "builtinassets",
     "meshes/button_large_transparent"},
    {"buttonLargerOpaque", "builtinassets", "meshes/button_larger_opaque"},
    {"buttonLargerTransparent", "builtinassets",
     "meshes/button_larger_transparent"},
    {"buttonMediumOpaque", "builtinassets", "meshes/button_medium_opaque"},
    {"buttonMediumTransparent", "builtinassets",
     "meshes/button_medium_transparent"},
    {"buttonNull", "classicassets", "meshes/button_null"},
    {"buttonPickUp", "classicassets", "textures/button_pick_up"},
    {"buttonPunch", "classicassets", "textures/button_punch"},
    {"buttonSmallOpaque", "builtinassets", "meshes/button_small_opaque"},
    {"buttonSmallTransparent", "builtinassets",
     "meshes/button_small_transparent"},
    {"buttonSquare", "builtinassets", "textures/button_square"},
    {"buttonSquareOpaque", "builtinassets", "meshes/button_square_opaque"},
    {"buttonSquareTransparent", "builtinassets",
     "meshes/button_square_transparent"},
    {"buttonSquareWide", "builtinassets", "textures/button_square_wide"},
    {"buttonTabOpaque", "builtinassets", "meshes/button_tab_opaque"},
    {"buttonTabTransparent", "builtinassets", "meshes/button_tab_transparent"},
    {"cashRegister", "builtinassets", "audio/cash_register"},
    {"cashRegister2", "classicassets", "audio/cash_register2"},
    {"chTitleChar1", "classicassets", "textures/ch_title_char1"},
    {"chTitleChar2", "classicassets", "textures/ch_title_char2"},
    {"chTitleChar3", "classicassets", "textures/ch_title_char3"},
    {"chTitleChar4", "classicassets", "textures/ch_title_char4"},
    {"chTitleChar5", "classicassets", "textures/ch_title_char5"},
    {"charSelectMusic", "classicassets", "audio/char_select_music"},
    {"characterIconMask", "builtinassets", "textures/character_icon_mask"},
    {"checkTransparent", "builtinassets", "meshes/check_transparent"},
    {"cheer", "classicassets", "audio/cheer"},
    {"chestIcon", "classicassets", "textures/chest_icon"},
    {"chestIconEmpty", "classicassets", "textures/chest_icon_empty"},
    {"chestIconMulti", "classicassets", "textures/chest_icon_multi"},
    {"chestIconTint", "classicassets", "textures/chest_icon_tint"},
    {"chestOpenIcon", "classicassets", "textures/chest_open_icon"},
    {"chestOpenIconTint", "classicassets", "textures/chest_open_icon_tint"},
    {"circle", "builtinassets", "textures/circle"},
    {"circleNoAlpha", "builtinassets", "textures/circle_no_alpha"},
    {"circleOutline", "builtinassets", "textures/circle_outline"},
    {"circleOutlineNoAlpha", "builtinassets",
     "textures/circle_outline_no_alpha"},
    {"circleShadow", "builtinassets", "textures/circle_shadow"},
    {"circleSoft", "builtinassets", "textures/circle_soft"},
    {"circleZigZag", "classicassets", "textures/circle_zig_zag"},
    {"clayStroke", "classicassets", "textures/clay_stroke"},
    {"click01", "builtinassets", "audio/click01"},
    {"coin", "classicassets", "textures/coin"},
    {"controllerIcon", "classicassets", "textures/controller_icon"},
    {"corkPop", "builtinassets", "audio/cork_pop"},
    {"corkPop2", "classicassets", "audio/cork_pop2"},
    {"courtyardLevel", "classicassets", "meshes/courtyard_level"},
    {"courtyardLevelBottom", "classicassets", "meshes/courtyard_level_bottom"},
    {"courtyardLevelCollide", "classicassets",
     "meshes/courtyard_level_collide"},
    {"courtyardLevelColor", "classicassets", "textures/courtyard_level_color"},
    {"courtyardPlayerWall", "classicassets", "meshes/courtyard_player_wall"},
    {"courtyardPreview", "classicassets", "textures/courtyard_preview"},
    {"cowboy1", "classicassets", "audio/cowboy1"},
    {"cowboy2", "classicassets", "audio/cowboy2"},
    {"cowboy3", "classicassets", "audio/cowboy3"},
    {"cowboy4", "classicassets", "audio/cowboy4"},
    {"cowboyColor", "classicassets", "textures/cowboy_color"},
    {"cowboyColorMask", "classicassets", "textures/cowboy_color_mask"},
    {"cowboyDeath", "classicassets", "audio/cowboy_death"},
    {"cowboyFall", "classicassets", "audio/cowboy_fall"},
    {"cowboyForeArm", "classicassets", "meshes/cowboy_fore_arm"},
    {"cowboyHand", "classicassets", "meshes/cowboy_hand"},
    {"cowboyHead", "classicassets", "meshes/cowboy_head"},
    {"cowboyHit1", "classicassets", "audio/cowboy_hit1"},
    {"cowboyHit2", "classicassets", "audio/cowboy_hit2"},
    {"cowboyIcon", "classicassets", "textures/cowboy_icon"},
    {"cowboyIconColorMask", "classicassets", "textures/cowboy_icon_color_mask"},
    {"cowboyLowerLeg", "classicassets", "meshes/cowboy_lower_leg"},
    {"cowboyPelvis", "classicassets", "meshes/cowboy_pelvis"},
    {"cowboyToes", "classicassets", "meshes/cowboy_toes"},
    {"cowboyTorso", "classicassets", "meshes/cowboy_torso"},
    {"cowboyUpperArm", "classicassets", "meshes/cowboy_upper_arm"},
    {"cowboyUpperLeg", "classicassets", "meshes/cowboy_upper_leg"},
    {"cragCastleLevel", "classicassets", "meshes/crag_castle_level"},
    {"cragCastleLevelBottom", "classicassets",
     "meshes/crag_castle_level_bottom"},
    {"cragCastleLevelBumper", "classicassets",
     "meshes/crag_castle_level_bumper"},
    {"cragCastleLevelCollide", "classicassets",
     "meshes/crag_castle_level_collide"},
    {"cragCastleLevelColor", "classicassets",
     "textures/crag_castle_level_color"},
    {"cragCastlePreview", "classicassets", "textures/crag_castle_preview"},
    {"cragCastleVRFillMound", "classicassets",
     "meshes/crag_castle_vrfill_mound"},
    {"crossOut", "builtinassets", "meshes/cross_out"},
    {"crossOut", "classicassets", "textures/cross_out"},
    {"crossOutMask", "classicassets", "textures/cross_out_mask"},
    {"crowdChant", "classicassets", "audio/crowd_chant"},
    {"currencyMeter", "classicassets", "meshes/currency_meter"},
    {"currencyPlusButton", "classicassets", "meshes/currency_plus_button"},
    {"cursor", "builtinassets", "textures/cursor"},
    {"cuteSpaz", "classicassets", "textures/cute_spaz"},
    {"cyborg1", "classicassets", "audio/cyborg1"},
    {"cyborg2", "classicassets", "audio/cyborg2"},
    {"cyborg3", "classicassets", "audio/cyborg3"},
    {"cyborg4", "classicassets", "audio/cyborg4"},
    {"cyborgColor", "classicassets", "textures/cyborg_color"},
    {"cyborgColorMask", "classicassets", "textures/cyborg_color_mask"},
    {"cyborgDeath", "classicassets", "audio/cyborg_death"},
    {"cyborgFall", "classicassets", "audio/cyborg_fall"},
    {"cyborgForeArm", "classicassets", "meshes/cyborg_fore_arm"},
    {"cyborgHand", "classicassets", "meshes/cyborg_hand"},
    {"cyborgHead", "classicassets", "meshes/cyborg_head"},
    {"cyborgHit1", "classicassets", "audio/cyborg_hit1"},
    {"cyborgHit2", "classicassets", "audio/cyborg_hit2"},
    {"cyborgIcon", "classicassets", "textures/cyborg_icon"},
    {"cyborgIconColorMask", "classicassets", "textures/cyborg_icon_color_mask"},
    {"cyborgLowerLeg", "classicassets", "meshes/cyborg_lower_leg"},
    {"cyborgPelvis", "classicassets", "meshes/cyborg_pelvis"},
    {"cyborgToes", "classicassets", "meshes/cyborg_toes"},
    {"cyborgTorso", "classicassets", "meshes/cyborg_torso"},
    {"cyborgUpperArm", "classicassets", "meshes/cyborg_upper_arm"},
    {"cyborgUpperLeg", "classicassets", "meshes/cyborg_upper_leg"},
    {"cylinder", "builtinassets", "meshes/cylinder"},
    {"cymbal", "classicassets", "audio/cymbal"},
    {"debrisFall", "classicassets", "audio/debris_fall"},
    {"deek", "builtinassets", "audio/deek"},
    {"deek2", "classicassets", "audio/deek2"},
    {"ding", "builtinassets", "audio/ding"},
    {"dingSmall", "classicassets", "audio/ding_small"},
    {"dingSmallHigh", "classicassets", "audio/ding_small_high"},
    {"discordIcon", "classicassets", "textures/discord_icon"},
    {"discordLogo", "classicassets", "textures/discord_logo"},
    {"discordServer", "classicassets", "textures/discord_server"},
    {"doomShroomBG", "classicassets", "meshes/doom_shroom_bg"},
    {"doomShroomBGColor", "classicassets", "textures/doom_shroom_bgcolor"},
    {"doomShroomLevel", "classicassets", "meshes/doom_shroom_level"},
    {"doomShroomLevelCollide", "classicassets",
     "meshes/doom_shroom_level_collide"},
    {"doomShroomLevelColor", "classicassets",
     "textures/doom_shroom_level_color"},
    {"doomShroomPreview", "classicassets", "textures/doom_shroom_preview"},
    {"doomShroomStem", "classicassets", "meshes/doom_shroom_stem"},
    {"doomShroomStemCollide", "classicassets",
     "meshes/doom_shroom_stem_collide"},
    {"doomShroomVRFill", "classicassets", "meshes/doom_shroom_vrfill"},
    {"downButton", "classicassets", "textures/down_button"},
    {"dripity", "classicassets", "audio/dripity"},
    {"drumRoll", "classicassets", "audio/drum_roll"},
    {"drumRollShort", "classicassets", "audio/drum_roll_short"},
    {"egg", "classicassets", "meshes/egg"},
    {"egg1", "classicassets", "textures/egg1"},
    {"egg2", "classicassets", "textures/egg2"},
    {"egg3", "classicassets", "textures/egg3"},
    {"egg4", "classicassets", "textures/egg4"},
    {"eggTex1", "classicassets", "textures/egg_tex1"},
    {"eggTex2", "classicassets", "textures/egg_tex2"},
    {"eggTex3", "classicassets", "textures/egg_tex3"},
    {"empty", "classicassets", "textures/empty"},
    {"error", "builtinassets", "audio/error"},
    {"explosion", "builtinassets", "textures/explosion"},
    {"explosion01", "classicassets", "audio/explosion01"},
    {"explosion02", "classicassets", "audio/explosion02"},
    {"explosion03", "classicassets", "audio/explosion03"},
    {"explosion04", "classicassets", "audio/explosion04"},
    {"explosion05", "classicassets", "audio/explosion05"},
    {"eyeBall", "builtinassets", "meshes/eye_ball"},
    {"eyeBallIris", "builtinassets", "meshes/eye_ball_iris"},
    {"eyeColor", "builtinassets", "textures/eye_color"},
    {"eyeColorTintMask", "builtinassets", "textures/eye_color_tint_mask"},
    {"eyeLid", "builtinassets", "meshes/eye_lid"},
    {"fanfare", "classicassets", "audio/fanfare"},
    {"file", "classicassets", "textures/file"},
    {"flagCatcherMusic", "classicassets", "audio/flag_catcher_music"},
    {"flagColor", "classicassets", "textures/flag_color"},
    {"flagPole", "builtinassets", "meshes/flag_pole"},
    {"flagPoleColor", "builtinassets", "textures/flag_pole_color"},
    {"flagStand", "builtinassets", "meshes/flag_stand"},
    {"flash", "builtinassets", "meshes/flash"},
    {"flyingMusic", "classicassets", "audio/flying_music"},
    {"foghorn", "classicassets", "audio/foghorn"},
    {"folder", "classicassets", "textures/folder"},
    {"fontBig", "builtinassets", "textures/font_big"},
    {"fontExtras", "builtinassets", "textures/font_extras"},
    {"fontExtras2", "builtinassets", "textures/font_extras2"},
    {"fontExtras3", "builtinassets", "textures/font_extras3"},
    {"fontExtras4", "builtinassets", "textures/font_extras4"},
    {"fontExtras5", "builtinassets", "textures/font_extras5"},
    {"fontSmall0", "builtinassets", "textures/font_small0"},
    {"fontSmall1", "builtinassets", "textures/font_small1"},
    {"fontSmall2", "builtinassets", "textures/font_small2"},
    {"fontSmall3", "builtinassets", "textures/font_small3"},
    {"fontSmall4", "builtinassets", "textures/font_small4"},
    {"fontSmall5", "builtinassets", "textures/font_small5"},
    {"fontSmall6", "builtinassets", "textures/font_small6"},
    {"fontSmall7", "builtinassets", "textures/font_small7"},
    {"footImpact01", "classicassets", "audio/foot_impact01"},
    {"footImpact02", "classicassets", "audio/foot_impact02"},
    {"footImpact03", "classicassets", "audio/foot_impact03"},
    {"footballStadium", "classicassets", "meshes/football_stadium"},
    {"footballStadium", "classicassets", "textures/football_stadium"},
    {"footballStadiumCollide", "classicassets",
     "meshes/football_stadium_collide"},
    {"footballStadiumPreview", "classicassets",
     "textures/football_stadium_preview"},
    {"footballStadiumVRFill", "classicassets",
     "meshes/football_stadium_vrfill"},
    {"forwardMarchMusic", "classicassets", "audio/forward_march_music"},
    {"frameInset", "classicassets", "meshes/frame_inset"},
    {"frameInset", "classicassets", "textures/frame_inset"},
    {"freeze", "classicassets", "audio/freeze"},
    {"frosty01", "classicassets", "audio/frosty01"},
    {"frosty02", "classicassets", "audio/frosty02"},
    {"frosty03", "classicassets", "audio/frosty03"},
    {"frosty04", "classicassets", "audio/frosty04"},
    {"frosty05", "classicassets", "audio/frosty05"},
    {"frostyColor", "classicassets", "textures/frosty_color"},
    {"frostyColorMask", "classicassets", "textures/frosty_color_mask"},
    {"frostyDeath", "classicassets", "audio/frosty_death"},
    {"frostyFall", "classicassets", "audio/frosty_fall"},
    {"frostyForeArm", "classicassets", "meshes/frosty_fore_arm"},
    {"frostyHand", "classicassets", "meshes/frosty_hand"},
    {"frostyHead", "classicassets", "meshes/frosty_head"},
    {"frostyHit01", "classicassets", "audio/frosty_hit01"},
    {"frostyHit02", "classicassets", "audio/frosty_hit02"},
    {"frostyHit03", "classicassets", "audio/frosty_hit03"},
    {"frostyIcon", "classicassets", "textures/frosty_icon"},
    {"frostyIconColorMask", "classicassets", "textures/frosty_icon_color_mask"},
    {"frostyLowerLeg", "classicassets", "meshes/frosty_lower_leg"},
    {"frostyPelvis", "classicassets", "meshes/frosty_pelvis"},
    {"frostyToes", "classicassets", "meshes/frosty_toes"},
    {"frostyTorso", "classicassets", "meshes/frosty_torso"},
    {"frostyUpperArm", "classicassets", "meshes/frosty_upper_arm"},
    {"frostyUpperLeg", "classicassets", "meshes/frosty_upper_leg"},
    {"fuse", "builtinassets", "textures/fuse"},
    {"fuse01", "classicassets", "audio/fuse01"},
    {"gameCenterIcon", "classicassets", "textures/game_center_icon"},
    {"gasp", "classicassets", "audio/gasp"},
    {"githubLogo", "classicassets", "textures/github_logo"},
    {"gladiator1", "classicassets", "audio/gladiator1"},
    {"gladiator2", "classicassets", "audio/gladiator2"},
    {"gladiator3", "classicassets", "audio/gladiator3"},
    {"gladiator4", "classicassets", "audio/gladiator4"},
    {"gladiatorColor", "classicassets", "textures/gladiator_color"},
    {"gladiatorColorMask", "classicassets", "textures/gladiator_color_mask"},
    {"gladiatorDeath", "classicassets", "audio/gladiator_death"},
    {"gladiatorFall", "classicassets", "audio/gladiator_fall"},
    {"gladiatorForeArm", "classicassets", "meshes/gladiator_fore_arm"},
    {"gladiatorHand", "classicassets", "meshes/gladiator_hand"},
    {"gladiatorHead", "classicassets", "meshes/gladiator_head"},
    {"gladiatorHit1", "classicassets", "audio/gladiator_hit1"},
    {"gladiatorHit2", "classicassets", "audio/gladiator_hit2"},
    {"gladiatorIcon", "classicassets", "textures/gladiator_icon"},
    {"gladiatorIconColorMask", "classicassets",
     "textures/gladiator_icon_color_mask"},
    {"gladiatorLowerLeg", "classicassets", "meshes/gladiator_lower_leg"},
    {"gladiatorPelvis", "classicassets", "meshes/gladiator_pelvis"},
    {"gladiatorToes", "classicassets", "meshes/gladiator_toes"},
    {"gladiatorTorso", "classicassets", "meshes/gladiator_torso"},
    {"gladiatorUpperArm", "classicassets", "meshes/gladiator_upper_arm"},
    {"gladiatorUpperLeg", "classicassets", "meshes/gladiator_upper_leg"},
    {"glow", "builtinassets", "textures/glow"},
    {"goldPass", "classicassets", "textures/gold_pass"},
    {"gong", "classicassets", "audio/gong"},
    {"googlePlayAchievementsIcon", "classicassets",
     "textures/google_play_achievements_icon"},
    {"googlePlayGamesIcon", "classicassets", "textures/google_play_games_icon"},
    {"googlePlayLeaderboardsIcon", "classicassets",
     "textures/google_play_leaderboards_icon"},
    {"googlePlusIcon", "classicassets", "textures/google_plus_icon"},
    {"googlePlusSignInButton", "classicassets",
     "textures/google_plus_sign_in_button"},
    {"grandRompMusic", "classicassets", "audio/grand_romp_music"},
    {"graphicsIcon", "classicassets", "textures/graphics_icon"},
    {"gravelSkid", "classicassets", "audio/gravel_skid"},
    {"gunCocking", "builtinassets", "audio/gun_cocking"},
    {"hairTuft1", "builtinassets", "meshes/hair_tuft1"},
    {"hairTuft1b", "builtinassets", "meshes/hair_tuft1b"},
    {"hairTuft2", "builtinassets", "meshes/hair_tuft2"},
    {"hairTuft3", "builtinassets", "meshes/hair_tuft3"},
    {"hairTuft4", "builtinassets", "meshes/hair_tuft4"},
    {"healthPowerup", "classicassets", "audio/health_powerup"},
    {"heart", "classicassets", "textures/heart"},
    {"heartOpaque", "classicassets", "meshes/heart_opaque"},
    {"heartTransparent", "classicassets", "meshes/heart_transparent"},
    {"hiss", "classicassets", "audio/hiss"},
    {"hockeyStadium", "classicassets", "textures/hockey_stadium"},
    {"hockeyStadiumCollide", "classicassets", "meshes/hockey_stadium_collide"},
    {"hockeyStadiumInner", "classicassets", "meshes/hockey_stadium_inner"},
    {"hockeyStadiumOuter", "classicassets", "meshes/hockey_stadium_outer"},
    {"hockeyStadiumPreview", "classicassets",
     "textures/hockey_stadium_preview"},
    {"hockeyStadiumStands", "classicassets", "meshes/hockey_stadium_stands"},
    {"iconOnslaught", "classicassets", "textures/icon_onslaught"},
    {"iconRunaround", "classicassets", "textures/icon_runaround"},
    {"image16x1", "builtinassets", "meshes/image16x1"},
    {"image1x1", "builtinassets", "meshes/image1x1"},
    {"image1x1FullScreen", "builtinassets", "meshes/image1x1_full_screen"},
    {"image1x1VRFullScreen", "builtinassets", "meshes/image1x1_vrfull_screen"},
    {"image2x1", "builtinassets", "meshes/image2x1"},
    {"image2x1Vertical", "classicassets", "meshes/image2x1_vertical"},
    {"image4x1", "builtinassets", "meshes/image4x1"},
    {"impactBomb", "classicassets", "meshes/impact_bomb"},
    {"impactBombColor", "classicassets", "textures/impact_bomb_color"},
    {"impactBombColorLit", "classicassets", "textures/impact_bomb_color_lit"},
    {"impactHard", "classicassets", "audio/impact_hard"},
    {"impactHard2", "classicassets", "audio/impact_hard2"},
    {"impactHard3", "classicassets", "audio/impact_hard3"},
    {"impactMedium", "classicassets", "audio/impact_medium"},
    {"impactMedium2", "classicassets", "audio/impact_medium2"},
    {"inventoryIcon", "classicassets", "textures/inventory_icon"},
    {"jack01", "classicassets", "audio/jack01"},
    {"jack02", "classicassets", "audio/jack02"},
    {"jack03", "classicassets", "audio/jack03"},
    {"jack04", "classicassets", "audio/jack04"},
    {"jack05", "classicassets", "audio/jack05"},
    {"jack06", "classicassets", "audio/jack06"},
    {"jackColor", "classicassets", "textures/jack_color"},
    {"jackColorMask", "classicassets", "textures/jack_color_mask"},
    {"jackDeath01", "classicassets", "audio/jack_death01"},
    {"jackFall01", "classicassets", "audio/jack_fall01"},
    {"jackForeArm", "classicassets", "meshes/jack_fore_arm"},
    {"jackHand", "classicassets", "meshes/jack_hand"},
    {"jackHead", "classicassets", "meshes/jack_head"},
    {"jackHit01", "classicassets", "audio/jack_hit01"},
    {"jackHit02", "classicassets", "audio/jack_hit02"},
    {"jackHit03", "classicassets", "audio/jack_hit03"},
    {"jackHit04", "classicassets", "audio/jack_hit04"},
    {"jackHit05", "classicassets", "audio/jack_hit05"},
    {"jackHit06", "classicassets", "audio/jack_hit06"},
    {"jackHit07", "classicassets", "audio/jack_hit07"},
    {"jackIcon", "classicassets", "textures/jack_icon"},
    {"jackIconColorMask", "classicassets", "textures/jack_icon_color_mask"},
    {"jackLowerLeg", "classicassets", "meshes/jack_lower_leg"},
    {"jackToes", "classicassets", "meshes/jack_toes"},
    {"jackTorso", "classicassets", "meshes/jack_torso"},
    {"jackUpperArm", "classicassets", "meshes/jack_upper_arm"},
    {"jackUpperLeg", "classicassets", "meshes/jack_upper_leg"},
    {"jumpsuit1", "classicassets", "audio/jumpsuit1"},
    {"jumpsuit2", "classicassets", "audio/jumpsuit2"},
    {"jumpsuit3", "classicassets", "audio/jumpsuit3"},
    {"jumpsuit4", "classicassets", "audio/jumpsuit4"},
    {"jumpsuitColor", "classicassets", "textures/jumpsuit_color"},
    {"jumpsuitColorMask", "classicassets", "textures/jumpsuit_color_mask"},
    {"jumpsuitDeath", "classicassets", "audio/jumpsuit_death"},
    {"jumpsuitFall", "classicassets", "audio/jumpsuit_fall"},
    {"jumpsuitForeArm", "classicassets", "meshes/jumpsuit_fore_arm"},
    {"jumpsuitHand", "classicassets", "meshes/jumpsuit_hand"},
    {"jumpsuitHead", "classicassets", "meshes/jumpsuit_head"},
    {"jumpsuitHit1", "classicassets", "audio/jumpsuit_hit1"},
    {"jumpsuitHit2", "classicassets", "audio/jumpsuit_hit2"},
    {"jumpsuitIcon", "classicassets", "textures/jumpsuit_icon"},
    {"jumpsuitIconColorMask", "classicassets",
     "textures/jumpsuit_icon_color_mask"},
    {"jumpsuitLowerLeg", "classicassets", "meshes/jumpsuit_lower_leg"},
    {"jumpsuitPelvis", "classicassets", "meshes/jumpsuit_pelvis"},
    {"jumpsuitToes", "classicassets", "meshes/jumpsuit_toes"},
    {"jumpsuitTorso", "classicassets", "meshes/jumpsuit_torso"},
    {"jumpsuitUpperArm", "classicassets", "meshes/jumpsuit_upper_arm"},
    {"jumpsuitUpperLeg", "classicassets", "meshes/jumpsuit_upper_leg"},
    {"kronk", "classicassets", "textures/kronk"},
    {"kronk1", "classicassets", "audio/kronk1"},
    {"kronk10", "classicassets", "audio/kronk10"},
    {"kronk2", "classicassets", "audio/kronk2"},
    {"kronk3", "classicassets", "audio/kronk3"},
    {"kronk4", "classicassets", "audio/kronk4"},
    {"kronk5", "classicassets", "audio/kronk5"},
    {"kronk6", "classicassets", "audio/kronk6"},
    {"kronk7", "classicassets", "audio/kronk7"},
    {"kronk8", "classicassets", "audio/kronk8"},
    {"kronk9", "classicassets", "audio/kronk9"},
    {"kronkColorMask", "classicassets", "textures/kronk_color_mask"},
    {"kronkDeath", "classicassets", "audio/kronk_death"},
    {"kronkFall", "classicassets", "audio/kronk_fall"},
    {"kronkForeArm", "classicassets", "meshes/kronk_fore_arm"},
    {"kronkHand", "classicassets", "meshes/kronk_hand"},
    {"kronkHead", "classicassets", "meshes/kronk_head"},
    {"kronkIcon", "classicassets", "textures/kronk_icon"},
    {"kronkIconColorMask", "classicassets", "textures/kronk_icon_color_mask"},
    {"kronkLowerLeg", "classicassets", "meshes/kronk_lower_leg"},
    {"kronkPelvis", "classicassets", "meshes/kronk_pelvis"},
    {"kronkToes", "classicassets", "meshes/kronk_toes"},
    {"kronkTorso", "classicassets", "meshes/kronk_torso"},
    {"kronkUpperArm", "classicassets", "meshes/kronk_upper_arm"},
    {"kronkUpperLeg", "classicassets", "meshes/kronk_upper_leg"},
    {"lakeFrigid", "classicassets", "meshes/lake_frigid"},
    {"lakeFrigid", "classicassets", "textures/lake_frigid"},
    {"lakeFrigidCollide", "classicassets", "meshes/lake_frigid_collide"},
    {"lakeFrigidPreview", "classicassets", "textures/lake_frigid_preview"},
    {"lakeFrigidReflections", "classicassets",
     "meshes/lake_frigid_reflections"},
    {"lakeFrigidReflections", "classicassets",
     "textures/lake_frigid_reflections"},
    {"lakeFrigidTop", "classicassets", "meshes/lake_frigid_top"},
    {"lakeFrigidVRFill", "classicassets", "meshes/lake_frigid_vrfill"},
    {"landMine", "classicassets", "meshes/land_mine"},
    {"landMine", "classicassets", "textures/land_mine"},
    {"landMineLit", "classicassets", "textures/land_mine_lit"},
    {"laser", "classicassets", "audio/laser"},
    {"laserReverse", "classicassets", "audio/laser_reverse"},
    {"leaderboardsIcon", "classicassets", "textures/leaderboards_icon"},
    {"leftButton", "classicassets", "textures/left_button"},
    {"levelIcon", "classicassets", "textures/level_icon"},
    {"level_select_button_opaque", "classicassets",
     "meshes/level_select_button_opaque"},
    {"level_select_button_transparent", "classicassets",
     "meshes/level_select_button_transparent"},
    {"light", "builtinassets", "textures/light"},
    {"lightSharp", "builtinassets", "textures/light_sharp"},
    {"lightSoft", "builtinassets", "textures/light_soft"},
    {"locator", "builtinassets", "meshes/locator"},
    {"locatorBox", "builtinassets", "meshes/locator_box"},
    {"locatorCircle", "builtinassets", "meshes/locator_circle"},
    {"locatorCircleOutline", "builtinassets", "meshes/locator_circle_outline"},
    {"lock", "classicassets", "textures/lock"},
    {"logIcon", "classicassets", "textures/log_icon"},
    {"logo", "classicassets", "meshes/logo"},
    {"logo", "classicassets", "textures/logo"},
    {"logoEaster", "classicassets", "textures/logo_easter"},
    {"logoTransparent", "classicassets", "meshes/logo_transparent"},
    {"mapPreviewMask", "classicassets", "textures/map_preview_mask"},
    {"medalBronze", "classicassets", "textures/medal_bronze"},
    {"medalComplete", "classicassets", "textures/medal_complete"},
    {"medalGold", "classicassets", "textures/medal_gold"},
    {"medalSilver", "classicassets", "textures/medal_silver"},
    {"mel01", "classicassets", "audio/mel01"},
    {"mel02", "classicassets", "audio/mel02"},
    {"mel03", "classicassets", "audio/mel03"},
    {"mel04", "classicassets", "audio/mel04"},
    {"mel05", "classicassets", "audio/mel05"},
    {"mel06", "classicassets", "audio/mel06"},
    {"mel07", "classicassets", "audio/mel07"},
    {"mel08", "classicassets", "audio/mel08"},
    {"mel09", "classicassets", "audio/mel09"},
    {"mel10", "classicassets", "audio/mel10"},
    {"melColor", "classicassets", "textures/mel_color"},
    {"melColorMask", "classicassets", "textures/mel_color_mask"},
    {"melDeath01", "classicassets", "audio/mel_death01"},
    {"melFall01", "classicassets", "audio/mel_fall01"},
    {"melForeArm", "classicassets", "meshes/mel_fore_arm"},
    {"melHand", "classicassets", "meshes/mel_hand"},
    {"melHead", "classicassets", "meshes/mel_head"},
    {"melIcon", "classicassets", "textures/mel_icon"},
    {"melIconColorMask", "classicassets", "textures/mel_icon_color_mask"},
    {"melLowerLeg", "classicassets", "meshes/mel_lower_leg"},
    {"melToes", "classicassets", "meshes/mel_toes"},
    {"melTorso", "classicassets", "meshes/mel_torso"},
    {"melUpperArm", "classicassets", "meshes/mel_upper_arm"},
    {"melUpperLeg", "classicassets", "meshes/mel_upper_leg"},
    {"menuBG", "classicassets", "textures/menu_bg"},
    {"menuButton", "builtinassets", "textures/menu_button"},
    {"menuIcon", "classicassets", "textures/menu_icon"},
    {"menuMusic", "classicassets", "audio/menu_music"},
    {"merch", "classicassets", "textures/merch"},
    {"metalHit", "classicassets", "audio/metal_hit"},
    {"metalSkid", "classicassets", "audio/metal_skid"},
    {"meter", "classicassets", "textures/meter"},
    {"meterTransparent", "classicassets", "meshes/meter_transparent"},
    {"monkeyFaceLevel", "classicassets", "meshes/monkey_face_level"},
    {"monkeyFaceLevelBottom", "classicassets",
     "meshes/monkey_face_level_bottom"},
    {"monkeyFaceLevelBumper", "classicassets",
     "meshes/monkey_face_level_bumper"},
    {"monkeyFaceLevelCollide", "classicassets",
     "meshes/monkey_face_level_collide"},
    {"monkeyFaceLevelColor", "classicassets",
     "textures/monkey_face_level_color"},
    {"monkeyFacePreview", "classicassets", "textures/monkey_face_preview"},
    {"multiplayerExamples", "classicassets", "textures/multiplayer_examples"},
    {"natureBackground", "classicassets", "meshes/nature_background"},
    {"natureBackgroundCollide", "classicassets",
     "meshes/nature_background_collide"},
    {"natureBackgroundColor", "classicassets",
     "textures/nature_background_color"},
    {"natureBackgroundVRFill", "classicassets",
     "meshes/nature_background_vrfill"},
    {"neoSpazColor", "classicassets", "textures/neo_spaz_color"},
    {"neoSpazColorMask", "classicassets", "textures/neo_spaz_color_mask"},
    {"neoSpazForeArm", "classicassets", "meshes/neo_spaz_fore_arm"},
    {"neoSpazHand", "classicassets", "meshes/neo_spaz_hand"},
    {"neoSpazHead", "classicassets", "meshes/neo_spaz_head"},
    {"neoSpazIcon", "classicassets", "textures/neo_spaz_icon"},
    {"neoSpazIconColorMask", "classicassets",
     "textures/neo_spaz_icon_color_mask"},
    {"neoSpazLowerLeg", "classicassets", "meshes/neo_spaz_lower_leg"},
    {"neoSpazPelvis", "classicassets", "meshes/neo_spaz_pelvis"},
    {"neoSpazToes", "classicassets", "meshes/neo_spaz_toes"},
    {"neoSpazTorso", "classicassets", "meshes/neo_spaz_torso"},
    {"neoSpazUpperArm", "classicassets", "meshes/neo_spaz_upper_arm"},
    {"neoSpazUpperLeg", "classicassets", "meshes/neo_spaz_upper_leg"},
    {"nextLevelIcon", "classicassets", "textures/next_level_icon"},
    {"nice", "classicassets", "audio/nice"},
    {"ninjaAttack1", "classicassets", "audio/ninja_attack1"},
    {"ninjaAttack2", "classicassets", "audio/ninja_attack2"},
    {"ninjaAttack3", "classicassets", "audio/ninja_attack3"},
    {"ninjaAttack4", "classicassets", "audio/ninja_attack4"},
    {"ninjaAttack5", "classicassets", "audio/ninja_attack5"},
    {"ninjaAttack6", "classicassets", "audio/ninja_attack6"},
    {"ninjaAttack7", "classicassets", "audio/ninja_attack7"},
    {"ninjaColor", "classicassets", "textures/ninja_color"},
    {"ninjaColorMask", "classicassets", "textures/ninja_color_mask"},
    {"ninjaDeath1", "classicassets", "audio/ninja_death1"},
    {"ninjaFall1", "classicassets", "audio/ninja_fall1"},
    {"ninjaForeArm", "classicassets", "meshes/ninja_fore_arm"},
    {"ninjaHand", "classicassets", "meshes/ninja_hand"},
    {"ninjaHead", "classicassets", "meshes/ninja_head"},
    {"ninjaHit1", "classicassets", "audio/ninja_hit1"},
    {"ninjaHit2", "classicassets", "audio/ninja_hit2"},
    {"ninjaHit3", "classicassets", "audio/ninja_hit3"},
    {"ninjaHit4", "classicassets", "audio/ninja_hit4"},
    {"ninjaHit5", "classicassets", "audio/ninja_hit5"},
    {"ninjaHit6", "classicassets", "audio/ninja_hit6"},
    {"ninjaHit7", "classicassets", "audio/ninja_hit7"},
    {"ninjaHit8", "classicassets", "audio/ninja_hit8"},
    {"ninjaIcon", "classicassets", "textures/ninja_icon"},
    {"ninjaIconColorMask", "classicassets", "textures/ninja_icon_color_mask"},
    {"ninjaLowerLeg", "classicassets", "meshes/ninja_lower_leg"},
    {"ninjaPelvis", "classicassets", "meshes/ninja_pelvis"},
    {"ninjaToes", "classicassets", "meshes/ninja_toes"},
    {"ninjaTorso", "classicassets", "meshes/ninja_torso"},
    {"ninjaUpperArm", "classicassets", "meshes/ninja_upper_arm"},
    {"ninjaUpperLeg", "classicassets", "meshes/ninja_upper_leg"},
    {"nub", "builtinassets", "textures/nub"},
    {"null", "classicassets", "textures/null"},
    {"oldLady1", "classicassets", "audio/old_lady1"},
    {"oldLady2", "classicassets", "audio/old_lady2"},
    {"oldLady3", "classicassets", "audio/old_lady3"},
    {"oldLady4", "classicassets", "audio/old_lady4"},
    {"oldLadyColor", "classicassets", "textures/old_lady_color"},
    {"oldLadyColorMask", "classicassets", "textures/old_lady_color_mask"},
    {"oldLadyDeath", "classicassets", "audio/old_lady_death"},
    {"oldLadyFall", "classicassets", "audio/old_lady_fall"},
    {"oldLadyForeArm", "classicassets", "meshes/old_lady_fore_arm"},
    {"oldLadyHand", "classicassets", "meshes/old_lady_hand"},
    {"oldLadyHead", "classicassets", "meshes/old_lady_head"},
    {"oldLadyHit1", "classicassets", "audio/old_lady_hit1"},
    {"oldLadyHit2", "classicassets", "audio/old_lady_hit2"},
    {"oldLadyIcon", "classicassets", "textures/old_lady_icon"},
    {"oldLadyIconColorMask", "classicassets",
     "textures/old_lady_icon_color_mask"},
    {"oldLadyLowerLeg", "classicassets", "meshes/old_lady_lower_leg"},
    {"oldLadyPelvis", "classicassets", "meshes/old_lady_pelvis"},
    {"oldLadyToes", "classicassets", "meshes/old_lady_toes"},
    {"oldLadyTorso", "classicassets", "meshes/old_lady_torso"},
    {"oldLadyUpperArm", "classicassets", "meshes/old_lady_upper_arm"},
    {"oldLadyUpperLeg", "classicassets", "meshes/old_lady_upper_leg"},
    {"ooh", "classicassets", "audio/ooh"},
    {"operaSinger1", "classicassets", "audio/opera_singer1"},
    {"operaSinger2", "classicassets", "audio/opera_singer2"},
    {"operaSinger3", "classicassets", "audio/opera_singer3"},
    {"operaSinger4", "classicassets", "audio/opera_singer4"},
    {"operaSingerColor", "classicassets", "textures/opera_singer_color"},
    {"operaSingerColorMask", "classicassets",
     "textures/opera_singer_color_mask"},
    {"operaSingerDeath", "classicassets", "audio/opera_singer_death"},
    {"operaSingerFall", "classicassets", "audio/opera_singer_fall"},
    {"operaSingerForeArm", "classicassets", "meshes/opera_singer_fore_arm"},
    {"operaSingerHand", "classicassets", "meshes/opera_singer_hand"},
    {"operaSingerHead", "classicassets", "meshes/opera_singer_head"},
    {"operaSingerHit1", "classicassets", "audio/opera_singer_hit1"},
    {"operaSingerHit2", "classicassets", "audio/opera_singer_hit2"},
    {"operaSingerIcon", "classicassets", "textures/opera_singer_icon"},
    {"operaSingerIconColorMask", "classicassets",
     "textures/opera_singer_icon_color_mask"},
    {"operaSingerLowerLeg", "classicassets", "meshes/opera_singer_lower_leg"},
    {"operaSingerPelvis", "classicassets", "meshes/opera_singer_pelvis"},
    {"operaSingerToes", "classicassets", "meshes/opera_singer_toes"},
    {"operaSingerTorso", "classicassets", "meshes/opera_singer_torso"},
    {"operaSingerUpperArm", "classicassets", "meshes/opera_singer_upper_arm"},
    {"operaSingerUpperLeg", "classicassets", "meshes/opera_singer_upper_leg"},
    {"orchestraHit", "classicassets", "audio/orchestra_hit"},
    {"orchestraHit2", "classicassets", "audio/orchestra_hit2"},
    {"orchestraHit3", "classicassets", "audio/orchestra_hit3"},
    {"orchestraHit4", "classicassets", "audio/orchestra_hit4"},
    {"orchestraHitBig1", "classicassets", "audio/orchestra_hit_big1"},
    {"orchestraHitBig2", "classicassets", "audio/orchestra_hit_big2"},
    {"ouyaAButton", "builtinassets", "textures/ouya_abutton"},
    {"ouyaIcon", "classicassets", "textures/ouya_icon"},
    {"ouyaOButton", "classicassets", "textures/ouya_obutton"},
    {"ouyaUButton", "classicassets", "textures/ouya_ubutton"},
    {"ouyaYButton", "classicassets", "textures/ouya_ybutton"},
    {"overlayGuide", "builtinassets", "meshes/overlay_guide"},
    {"pageLeftRight", "builtinassets", "textures/page_left_right"},
    {"penguin1", "classicassets", "audio/penguin1"},
    {"penguin2", "classicassets", "audio/penguin2"},
    {"penguin3", "classicassets", "audio/penguin3"},
    {"penguin4", "classicassets", "audio/penguin4"},
    {"penguinColor", "classicassets", "textures/penguin_color"},
    {"penguinColorMask", "classicassets", "textures/penguin_color_mask"},
    {"penguinDeath", "classicassets", "audio/penguin_death"},
    {"penguinFall", "classicassets", "audio/penguin_fall"},
    {"penguinForeArm", "classicassets", "meshes/penguin_fore_arm"},
    {"penguinHand", "classicassets", "meshes/penguin_hand"},
    {"penguinHead", "classicassets", "meshes/penguin_head"},
    {"penguinHit1", "classicassets", "audio/penguin_hit1"},
    {"penguinHit2", "classicassets", "audio/penguin_hit2"},
    {"penguinIcon", "classicassets", "textures/penguin_icon"},
    {"penguinIconColorMask", "classicassets",
     "textures/penguin_icon_color_mask"},
    {"penguinLowerLeg", "classicassets", "meshes/penguin_lower_leg"},
    {"penguinPelvis", "classicassets", "meshes/penguin_pelvis"},
    {"penguinToes", "classicassets", "meshes/penguin_toes"},
    {"penguinTorso", "classicassets", "meshes/penguin_torso"},
    {"penguinUpperArm", "classicassets", "meshes/penguin_upper_arm"},
    {"penguinUpperLeg", "classicassets", "meshes/penguin_upper_leg"},
    {"pixie1", "classicassets", "audio/pixie1"},
    {"pixie2", "classicassets", "audio/pixie2"},
    {"pixie3", "classicassets", "audio/pixie3"},
    {"pixie4", "classicassets", "audio/pixie4"},
    {"pixieColor", "classicassets", "textures/pixie_color"},
    {"pixieColorMask", "classicassets", "textures/pixie_color_mask"},
    {"pixieDeath", "classicassets", "audio/pixie_death"},
    {"pixieFall", "classicassets", "audio/pixie_fall"},
    {"pixieForeArm", "classicassets", "meshes/pixie_fore_arm"},
    {"pixieHand", "classicassets", "meshes/pixie_hand"},
    {"pixieHead", "classicassets", "meshes/pixie_head"},
    {"pixieHit1", "classicassets", "audio/pixie_hit1"},
    {"pixieHit2", "classicassets", "audio/pixie_hit2"},
    {"pixieIcon", "classicassets", "textures/pixie_icon"},
    {"pixieIconColorMask", "classicassets", "textures/pixie_icon_color_mask"},
    {"pixieLowerLeg", "classicassets", "meshes/pixie_lower_leg"},
    {"pixiePelvis", "classicassets", "meshes/pixie_pelvis"},
    {"pixieToes", "classicassets", "meshes/pixie_toes"},
    {"pixieTorso", "classicassets", "meshes/pixie_torso"},
    {"pixieUpperArm", "classicassets", "meshes/pixie_upper_arm"},
    {"pixieUpperLeg", "classicassets", "meshes/pixie_upper_leg"},
    {"plasticEyesTransparent", "classicassets",
     "meshes/plastic_eyes_transparent"},
    {"playerDeath", "classicassets", "audio/player_death"},
    {"playerLeft", "classicassets", "audio/player_left"},
    {"playerLineup", "classicassets", "textures/player_lineup"},
    {"playerLineup1Transparent", "classicassets",
     "meshes/player_lineup1_transparent"},
    {"playerLineup2Transparent", "classicassets",
     "meshes/player_lineup2_transparent"},
    {"playerLineup3Transparent", "classicassets",
     "meshes/player_lineup3_transparent"},
    {"playerLineup4Transparent", "classicassets",
     "meshes/player_lineup4_transparent"},
    {"plusButton", "classicassets", "textures/plus_button"},
    {"pop01", "classicassets", "audio/pop01"},
    {"powerdown01", "builtinassets", "audio/powerdown01"},
    {"powerup", "classicassets", "meshes/powerup"},
    {"powerup01", "classicassets", "audio/powerup01"},
    {"powerupBomb", "classicassets", "textures/powerup_bomb"},
    {"powerupCurse", "classicassets", "textures/powerup_curse"},
    {"powerupHealth", "classicassets", "textures/powerup_health"},
    {"powerupIceBombs", "classicassets", "textures/powerup_ice_bombs"},
    {"powerupImpactBombs", "classicassets", "textures/powerup_impact_bombs"},
    {"powerupLandMines", "classicassets", "textures/powerup_land_mines"},
    {"powerupPunch", "classicassets", "textures/powerup_punch"},
    {"powerupShield", "classicassets", "textures/powerup_shield"},
    {"powerupSimple", "classicassets", "meshes/powerup_simple"},
    {"powerupSpeed", "classicassets", "textures/powerup_speed"},
    {"powerupStickyBombs", "classicassets", "textures/powerup_sticky_bombs"},
    {"puck", "classicassets", "meshes/puck"},
    {"puckColor", "classicassets", "textures/puck_color"},
    {"punch01", "builtinassets", "audio/punch01"},
    {"punchStrong01", "classicassets", "audio/punch_strong01"},
    {"punchStrong02", "classicassets", "audio/punch_strong02"},
    {"punchSwish", "classicassets", "audio/punch_swish"},
    {"punchWeak01", "classicassets", "audio/punch_weak01"},
    {"quoteBubble", "classicassets", "textures/quote_bubble"},
    {"raceBeep1", "classicassets", "audio/race_beep1"},
    {"raceBeep2", "classicassets", "audio/race_beep2"},
    {"rampageBG", "classicassets", "meshes/rampage_bg"},
    {"rampageBG2", "classicassets", "meshes/rampage_bg2"},
    {"rampageBGColor", "classicassets", "textures/rampage_bgcolor"},
    {"rampageBGColor2", "classicassets", "textures/rampage_bgcolor2"},
    {"rampageBumper", "classicassets", "meshes/rampage_bumper"},
    {"rampageLevel", "classicassets", "meshes/rampage_level"},
    {"rampageLevelBottom", "classicassets", "meshes/rampage_level_bottom"},
    {"rampageLevelCollide", "classicassets", "meshes/rampage_level_collide"},
    {"rampageLevelColor", "classicassets", "textures/rampage_level_color"},
    {"rampagePreview", "classicassets", "textures/rampage_preview"},
    {"rampageVRFill", "classicassets", "meshes/rampage_vrfill"},
    {"refWhistle", "classicassets", "audio/ref_whistle"},
    {"replayIcon", "classicassets", "textures/replay_icon"},
    {"revUp", "classicassets", "audio/rev_up"},
    {"rgbStripes", "builtinassets", "textures/rgb_stripes"},
    {"rightButton", "classicassets", "textures/right_button"},
    {"robot1", "classicassets", "audio/robot1"},
    {"robot2", "classicassets", "audio/robot2"},
    {"robot3", "classicassets", "audio/robot3"},
    {"robot4", "classicassets", "audio/robot4"},
    {"robotColor", "classicassets", "textures/robot_color"},
    {"robotColorMask", "classicassets", "textures/robot_color_mask"},
    {"robotDeath", "classicassets", "audio/robot_death"},
    {"robotFall", "classicassets", "audio/robot_fall"},
    {"robotForeArm", "classicassets", "meshes/robot_fore_arm"},
    {"robotHand", "classicassets", "meshes/robot_hand"},
    {"robotHead", "classicassets", "meshes/robot_head"},
    {"robotHit1", "classicassets", "audio/robot_hit1"},
    {"robotHit2", "classicassets", "audio/robot_hit2"},
    {"robotIcon", "classicassets", "textures/robot_icon"},
    {"robotIconColorMask", "classicassets", "textures/robot_icon_color_mask"},
    {"robotLowerLeg", "classicassets", "meshes/robot_lower_leg"},
    {"robotPelvis", "classicassets", "meshes/robot_pelvis"},
    {"robotToes", "classicassets", "meshes/robot_toes"},
    {"robotTorso", "classicassets", "meshes/robot_torso"},
    {"robotUpperArm", "classicassets", "meshes/robot_upper_arm"},
    {"robotUpperLeg", "classicassets", "meshes/robot_upper_leg"},
    {"roundaboutLevel", "classicassets", "meshes/roundabout_level"},
    {"roundaboutLevelBottom", "classicassets",
     "meshes/roundabout_level_bottom"},
    {"roundaboutLevelBumper", "classicassets",
     "meshes/roundabout_level_bumper"},
    {"roundaboutLevelCollide", "classicassets",
     "meshes/roundabout_level_collide"},
    {"roundaboutLevelColor", "classicassets",
     "textures/roundabout_level_color"},
    {"roundaboutPreview", "classicassets", "textures/roundabout_preview"},
    {"runAwayMusic", "classicassets", "audio/run_away_music"},
    {"runningShoes", "classicassets", "meshes/running_shoes"},
    {"santa01", "classicassets", "audio/santa01"},
    {"santa02", "classicassets", "audio/santa02"},
    {"santa03", "classicassets", "audio/santa03"},
    {"santa04", "classicassets", "audio/santa04"},
    {"santa05", "classicassets", "audio/santa05"},
    {"santaColor", "classicassets", "textures/santa_color"},
    {"santaColorMask", "classicassets", "textures/santa_color_mask"},
    {"santaDeath", "classicassets", "audio/santa_death"},
    {"santaFall", "classicassets", "audio/santa_fall"},
    {"santaForeArm", "classicassets", "meshes/santa_fore_arm"},
    {"santaHand", "classicassets", "meshes/santa_hand"},
    {"santaHead", "classicassets", "meshes/santa_head"},
    {"santaHit01", "classicassets", "audio/santa_hit01"},
    {"santaHit02", "classicassets", "audio/santa_hit02"},
    {"santaHit03", "classicassets", "audio/santa_hit03"},
    {"santaHit04", "classicassets", "audio/santa_hit04"},
    {"santaIcon", "classicassets", "textures/santa_icon"},
    {"santaIconColorMask", "classicassets", "textures/santa_icon_color_mask"},
    {"santaLowerLeg", "classicassets", "meshes/santa_lower_leg"},
    {"santaToes", "classicassets", "meshes/santa_toes"},
    {"santaTorso", "classicassets", "meshes/santa_torso"},
    {"santaUpperArm", "classicassets", "meshes/santa_upper_arm"},
    {"santaUpperLeg", "classicassets", "meshes/santa_upper_leg"},
    {"scamper01", "classicassets", "audio/scamper01"},
    {"scaryMusic", "classicassets", "audio/scary_music"},
    {"scorch", "builtinassets", "meshes/scorch"},
    {"scorch", "builtinassets", "textures/scorch"},
    {"scorchBig", "builtinassets", "textures/scorch_big"},
    {"score", "classicassets", "audio/score"},
    {"scoreHit01", "classicassets", "audio/score_hit01"},
    {"scoreHit02", "classicassets", "audio/score_hit02"},
    {"scoreIncrease", "builtinassets", "audio/score_increase"},
    {"scoresEpicMusic", "classicassets", "audio/scores_epic_music"},
    {"scrollBarThumbOpaque", "builtinassets", "meshes/scroll_bar_thumb_opaque"},
    {"scrollBarThumbShortOpaque", "builtinassets",
     "meshes/scroll_bar_thumb_short_opaque"},
    {"scrollBarThumbShortSimple", "builtinassets",
     "meshes/scroll_bar_thumb_short_simple"},
    {"scrollBarThumbShortTransparent", "builtinassets",
     "meshes/scroll_bar_thumb_short_transparent"},
    {"scrollBarThumbSimple", "builtinassets", "meshes/scroll_bar_thumb_simple"},
    {"scrollBarThumbTransparent", "builtinassets",
     "meshes/scroll_bar_thumb_transparent"},
    {"scrollBarTroughTransparent", "builtinassets",
     "meshes/scroll_bar_trough_transparent"},
    {"scrollWidget", "builtinassets", "textures/scroll_widget"},
    {"scrollWidgetGlow", "builtinassets", "textures/scroll_widget_glow"},
    {"scrollWidgetShort", "classicassets", "meshes/scroll_widget_short"},
    {"settingsIcon", "classicassets", "textures/settings_icon"},
    {"shadow", "builtinassets", "textures/shadow"},
    {"shadowSharp", "builtinassets", "textures/shadow_sharp"},
    {"shadowSoft", "builtinassets", "textures/shadow_soft"},
    {"shatter", "classicassets", "audio/shatter"},
    {"shield", "builtinassets", "meshes/shield"},
    {"shield", "builtinassets", "textures/shield"},
    {"shieldDown", "classicassets", "audio/shield_down"},
    {"shieldHit", "classicassets", "audio/shield_hit"},
    {"shieldUp", "classicassets", "audio/shield_up"},
    {"shockWave", "builtinassets", "meshes/shock_wave"},
    {"shrapnel1", "builtinassets", "meshes/shrapnel1"},
    {"shrapnel1Color", "builtinassets", "textures/shrapnel1_color"},
    {"shrapnelBoard", "builtinassets", "meshes/shrapnel_board"},
    {"shrapnelSlime", "builtinassets", "meshes/shrapnel_slime"},
    {"skid01", "classicassets", "audio/skid01"},
    {"slash", "classicassets", "textures/slash"},
    {"slowEpicMusic", "classicassets", "audio/slow_epic_music"},
    {"smoke", "builtinassets", "textures/smoke"},
    {"softEdgeInside", "builtinassets", "meshes/soft_edge_inside"},
    {"softEdgeOutside", "builtinassets", "meshes/soft_edge_outside"},
    {"softRect", "builtinassets", "textures/soft_rect"},
    {"softRect2", "builtinassets", "textures/soft_rect2"},
    {"softRectVertical", "builtinassets", "textures/soft_rect_vertical"},
    {"sparkle01", "builtinassets", "audio/sparkle01"},
    {"sparkle02", "builtinassets", "audio/sparkle02"},
    {"sparkle03", "builtinassets", "audio/sparkle03"},
    {"sparks", "builtinassets", "textures/sparks"},
    {"spawn", "classicassets", "audio/spawn"},
    {"spazAttack01", "classicassets", "audio/spaz_attack01"},
    {"spazAttack02", "classicassets", "audio/spaz_attack02"},
    {"spazAttack03", "classicassets", "audio/spaz_attack03"},
    {"spazAttack04", "classicassets", "audio/spaz_attack04"},
    {"spazDeath01", "classicassets", "audio/spaz_death01"},
    {"spazEff", "classicassets", "audio/spaz_eff"},
    {"spazFall01", "classicassets", "audio/spaz_fall01"},
    {"spazImpact01", "classicassets", "audio/spaz_impact01"},
    {"spazImpact02", "classicassets", "audio/spaz_impact02"},
    {"spazImpact03", "classicassets", "audio/spaz_impact03"},
    {"spazImpact04", "classicassets", "audio/spaz_impact04"},
    {"spazJump01", "classicassets", "audio/spaz_jump01"},
    {"spazJump02", "classicassets", "audio/spaz_jump02"},
    {"spazJump03", "classicassets", "audio/spaz_jump03"},
    {"spazJump04", "classicassets", "audio/spaz_jump04"},
    {"spazOw", "classicassets", "audio/spaz_ow"},
    {"spazPickup01", "classicassets", "audio/spaz_pickup01"},
    {"spazScream01", "classicassets", "audio/spaz_scream01"},
    {"spinner", "builtinassets", "textures/spinner"},
    {"spinner0", "builtinassets", "textures/spinner0"},
    {"spinner1", "builtinassets", "textures/spinner1"},
    {"spinner10", "builtinassets", "textures/spinner10"},
    {"spinner11", "builtinassets", "textures/spinner11"},
    {"spinner2", "builtinassets", "textures/spinner2"},
    {"spinner3", "builtinassets", "textures/spinner3"},
    {"spinner4", "builtinassets", "textures/spinner4"},
    {"spinner5", "builtinassets", "textures/spinner5"},
    {"spinner6", "builtinassets", "textures/spinner6"},
    {"spinner7", "builtinassets", "textures/spinner7"},
    {"spinner8", "builtinassets", "textures/spinner8"},
    {"spinner9", "builtinassets", "textures/spinner9"},
    {"splatter", "classicassets", "audio/splatter"},
    {"sportsMusic", "classicassets", "audio/sports_music"},
    {"star", "classicassets", "textures/star"},
    {"startButton", "builtinassets", "textures/start_button"},
    {"stepRightUpLevel", "classicassets", "meshes/step_right_up_level"},
    {"stepRightUpLevelBottom", "classicassets",
     "meshes/step_right_up_level_bottom"},
    {"stepRightUpLevelCollide", "classicassets",
     "meshes/step_right_up_level_collide"},
    {"stepRightUpLevelColor", "classicassets",
     "textures/step_right_up_level_color"},
    {"stepRightUpPreview", "classicassets", "textures/step_right_up_preview"},
    {"stepRightUpVRFillMound", "classicassets",
     "meshes/step_right_up_vrfill_mound"},
    {"stickyImpact", "classicassets", "audio/sticky_impact"},
    {"storeCharacter", "classicassets", "textures/store_character"},
    {"storeCharacterEaster", "classicassets",
     "textures/store_character_easter"},
    {"storeCharacterXmas", "classicassets", "textures/store_character_xmas"},
    {"storeIcon", "classicassets", "textures/store_icon"},
    {"superPunch", "classicassets", "audio/super_punch"},
    {"superhero1", "classicassets", "audio/superhero1"},
    {"superhero2", "classicassets", "audio/superhero2"},
    {"superhero3", "classicassets", "audio/superhero3"},
    {"superhero4", "classicassets", "audio/superhero4"},
    {"superheroColor", "classicassets", "textures/superhero_color"},
    {"superheroColorMask", "classicassets", "textures/superhero_color_mask"},
    {"superheroDeath", "classicassets", "audio/superhero_death"},
    {"superheroFall", "classicassets", "audio/superhero_fall"},
    {"superheroForeArm", "classicassets", "meshes/superhero_fore_arm"},
    {"superheroHand", "classicassets", "meshes/superhero_hand"},
    {"superheroHead", "classicassets", "meshes/superhero_head"},
    {"superheroHit1", "classicassets", "audio/superhero_hit1"},
    {"superheroHit2", "classicassets", "audio/superhero_hit2"},
    {"superheroIcon", "classicassets", "textures/superhero_icon"},
    {"superheroIconColorMask", "classicassets",
     "textures/superhero_icon_color_mask"},
    {"superheroLowerLeg", "classicassets", "meshes/superhero_lower_leg"},
    {"superheroPelvis", "classicassets", "meshes/superhero_pelvis"},
    {"superheroToes", "classicassets", "meshes/superhero_toes"},
    {"superheroTorso", "classicassets", "meshes/superhero_torso"},
    {"superheroUpperArm", "classicassets", "meshes/superhero_upper_arm"},
    {"superheroUpperLeg", "classicassets", "meshes/superhero_upper_leg"},
    {"survivalMusic", "classicassets", "audio/survival_music"},
    {"swip", "classicassets", "audio/swip"},
    {"swip2", "classicassets", "audio/swip2"},
    {"swish", "builtinassets", "audio/swish"},
    {"swish2", "builtinassets", "audio/swish2"},
    {"swish3", "builtinassets", "audio/swish3"},
    {"tap", "builtinassets", "audio/tap"},
    {"technoHit01", "classicassets", "audio/techno_hit01"},
    {"textBoxTransparent", "builtinassets", "meshes/text_box_transparent"},
    {"textClearButton", "builtinassets", "textures/text_clear_button"},
    {"thePadBG", "classicassets", "meshes/the_pad_bg"},
    {"thePadBGSmall", "classicassets", "meshes/the_pad_bgsmall"},
    {"thePadLevel", "classicassets", "meshes/the_pad_level"},
    {"thePadLevelBottom", "classicassets", "meshes/the_pad_level_bottom"},
    {"thePadLevelBumper", "classicassets", "meshes/the_pad_level_bumper"},
    {"thePadLevelCollide", "classicassets", "meshes/the_pad_level_collide"},
    {"thePadLevelColor", "classicassets", "textures/the_pad_level_color"},
    {"thePadPreview", "classicassets", "textures/the_pad_preview"},
    {"thePadVRFillBottom", "classicassets", "meshes/the_pad_vrfill_bottom"},
    {"thePadVRFillMound", "classicassets", "meshes/the_pad_vrfill_mound"},
    {"thePadVRFillTop", "classicassets", "meshes/the_pad_vrfill_top"},
    {"tick", "classicassets", "audio/tick"},
    {"ticketRoll", "classicassets", "textures/ticket_roll"},
    {"ticketRollBig", "classicassets", "textures/ticket_roll_big"},
    {"ticketRolls", "classicassets", "textures/ticket_rolls"},
    {"tickets", "classicassets", "textures/tickets"},
    {"ticketsMore", "classicassets", "textures/tickets_more"},
    {"ticketsPurple", "classicassets", "textures/tickets_purple"},
    {"ticking", "classicassets", "audio/ticking"},
    {"tickingCrazy", "builtinassets", "audio/ticking_crazy"},
    {"tipTopBG", "classicassets", "meshes/tip_top_bg"},
    {"tipTopBGColor", "classicassets", "textures/tip_top_bgcolor"},
    {"tipTopLevel", "classicassets", "meshes/tip_top_level"},
    {"tipTopLevelBottom", "classicassets", "meshes/tip_top_level_bottom"},
    {"tipTopLevelBumper", "classicassets", "meshes/tip_top_level_bumper"},
    {"tipTopLevelCollide", "classicassets", "meshes/tip_top_level_collide"},
    {"tipTopLevelColor", "classicassets", "textures/tip_top_level_color"},
    {"tipTopPreview", "classicassets", "textures/tip_top_preview"},
    {"tnt", "classicassets", "meshes/tnt"},
    {"tnt", "classicassets", "textures/tnt"},
    {"toTheDeathMusic", "classicassets", "audio/to_the_death_music"},
    {"tokens1", "classicassets", "textures/tokens1"},
    {"tokens2", "classicassets", "textures/tokens2"},
    {"tokens3", "classicassets", "textures/tokens3"},
    {"tokens4", "classicassets", "textures/tokens4"},
    {"toolbarBacking", "classicassets", "meshes/toolbar_backing"},
    {"toolbarBackingBottom", "classicassets", "meshes/toolbar_backing_bottom"},
    {"toolbarBackingBottom2", "classicassets",
     "meshes/toolbar_backing_bottom2"},
    {"toolbarBackingOpaque", "classicassets", "meshes/toolbar_backing_opaque"},
    {"toolbarBackingTop", "classicassets", "meshes/toolbar_backing_top"},
    {"toolbarBackingTop2", "classicassets", "meshes/toolbar_backing_top2"},
    {"toolbarBackingTransparent", "classicassets",
     "meshes/toolbar_backing_transparent"},
    {"touchArrows", "builtinassets", "textures/touch_arrows"},
    {"touchArrowsActions", "builtinassets", "textures/touch_arrows_actions"},
    {"towerDLevel", "classicassets", "meshes/tower_dlevel"},
    {"towerDLevelBottom", "classicassets", "meshes/tower_dlevel_bottom"},
    {"towerDLevelCollide", "classicassets", "meshes/tower_dlevel_collide"},
    {"towerDLevelColor", "classicassets", "textures/tower_dlevel_color"},
    {"towerDPlayerWall", "classicassets", "meshes/tower_dplayer_wall"},
    {"towerDPreview", "classicassets", "textures/tower_dpreview"},
    {"trashRummage", "classicassets", "audio/trash_rummage"},
    {"trees", "classicassets", "meshes/trees"},
    {"treesColor", "classicassets", "textures/trees_color"},
    {"trophy", "classicassets", "textures/trophy"},
    {"tv", "classicassets", "textures/tv"},
    {"uiAtlas", "builtinassets", "textures/ui_atlas"},
    {"uiAtlas2", "builtinassets", "textures/ui_atlas2"},
    {"upButton", "classicassets", "textures/up_button"},
    {"usersButton", "builtinassets", "textures/users_button"},
    {"victoryMusic", "classicassets", "audio/victory_music"},
    {"vrFade", "builtinassets", "meshes/vr_fade"},
    {"vrFillMound", "classicassets", "textures/vr_fill_mound"},
    {"vrOverlay", "builtinassets", "meshes/vr_overlay"},
    {"warnBeep", "classicassets", "audio/warn_beep"},
    {"warnBeeps", "classicassets", "audio/warn_beeps"},
    {"warrior1", "classicassets", "audio/warrior1"},
    {"warrior2", "classicassets", "audio/warrior2"},
    {"warrior3", "classicassets", "audio/warrior3"},
    {"warrior4", "classicassets", "audio/warrior4"},
    {"warriorColor", "classicassets", "textures/warrior_color"},
    {"warriorColorMask", "classicassets", "textures/warrior_color_mask"},
    {"warriorDeath", "classicassets", "audio/warrior_death"},
    {"warriorFall", "classicassets", "audio/warrior_fall"},
    {"warriorForeArm", "classicassets", "meshes/warrior_fore_arm"},
    {"warriorHand", "classicassets", "meshes/warrior_hand"},
    {"warriorHead", "classicassets", "meshes/warrior_head"},
    {"warriorHit1", "classicassets", "audio/warrior_hit1"},
    {"warriorHit2", "classicassets", "audio/warrior_hit2"},
    {"warriorIcon", "classicassets", "textures/warrior_icon"},
    {"warriorIconColorMask", "classicassets",
     "textures/warrior_icon_color_mask"},
    {"warriorLowerLeg", "classicassets", "meshes/warrior_lower_leg"},
    {"warriorPelvis", "classicassets", "meshes/warrior_pelvis"},
    {"warriorToes", "classicassets", "meshes/warrior_toes"},
    {"warriorTorso", "classicassets", "meshes/warrior_torso"},
    {"warriorUpperArm", "classicassets", "meshes/warrior_upper_arm"},
    {"warriorUpperLeg", "classicassets", "meshes/warrior_upper_leg"},
    {"whenJohnnyComesMarchingHomeMusic", "classicassets",
     "audio/when_johnny_comes_marching_home_music"},
    {"white", "builtinassets", "textures/white"},
    {"windowBGBlotch", "classicassets", "meshes/window_bgblotch"},
    {"windowBottomCap", "classicassets", "textures/window_bottom_cap"},
    {"windowHSmallVMed", "builtinassets", "textures/window_hsmall_vmed"},
    {"windowHSmallVMedOpaque", "builtinassets",
     "meshes/window_hsmall_vmed_opaque"},
    {"windowHSmallVMedTransparent", "builtinassets",
     "meshes/window_hsmall_vmed_transparent"},
    {"windowHSmallVSmall", "builtinassets", "textures/window_hsmall_vsmall"},
    {"windowHSmallVSmallOpaque", "builtinassets",
     "meshes/window_hsmall_vsmall_opaque"},
    {"windowHSmallVSmallTransparent", "builtinassets",
     "meshes/window_hsmall_vsmall_transparent"},
    {"wing", "builtinassets", "meshes/wing"},
    {"wings", "builtinassets", "textures/wings"},
    {"witch1", "classicassets", "audio/witch1"},
    {"witch2", "classicassets", "audio/witch2"},
    {"witch3", "classicassets", "audio/witch3"},
    {"witch4", "classicassets", "audio/witch4"},
    {"witchColor", "classicassets", "textures/witch_color"},
    {"witchColorMask", "classicassets", "textures/witch_color_mask"},
    {"witchDeath", "classicassets", "audio/witch_death"},
    {"witchFall", "classicassets", "audio/witch_fall"},
    {"witchForeArm", "classicassets", "meshes/witch_fore_arm"},
    {"witchHand", "classicassets", "meshes/witch_hand"},
    {"witchHead", "classicassets", "meshes/witch_head"},
    {"witchHit1", "classicassets", "audio/witch_hit1"},
    {"witchHit2", "classicassets", "audio/witch_hit2"},
    {"witchIcon", "classicassets", "textures/witch_icon"},
    {"witchIconColorMask", "classicassets", "textures/witch_icon_color_mask"},
    {"witchLowerLeg", "classicassets", "meshes/witch_lower_leg"},
    {"witchPelvis", "classicassets", "meshes/witch_pelvis"},
    {"witchToes", "classicassets", "meshes/witch_toes"},
    {"witchTorso", "classicassets", "meshes/witch_torso"},
    {"witchUpperArm", "classicassets", "meshes/witch_upper_arm"},
    {"witchUpperLeg", "classicassets", "meshes/witch_upper_leg"},
    {"wizard1", "classicassets", "audio/wizard1"},
    {"wizard2", "classicassets", "audio/wizard2"},
    {"wizard3", "classicassets", "audio/wizard3"},
    {"wizard4", "classicassets", "audio/wizard4"},
    {"wizardColor", "classicassets", "textures/wizard_color"},
    {"wizardColorMask", "classicassets", "textures/wizard_color_mask"},
    {"wizardDeath", "classicassets", "audio/wizard_death"},
    {"wizardFall", "classicassets", "audio/wizard_fall"},
    {"wizardForeArm", "classicassets", "meshes/wizard_fore_arm"},
    {"wizardHand", "classicassets", "meshes/wizard_hand"},
    {"wizardHead", "classicassets", "meshes/wizard_head"},
    {"wizardHit1", "classicassets", "audio/wizard_hit1"},
    {"wizardHit2", "classicassets", "audio/wizard_hit2"},
    {"wizardIcon", "classicassets", "textures/wizard_icon"},
    {"wizardIconColorMask", "classicassets", "textures/wizard_icon_color_mask"},
    {"wizardLowerLeg", "classicassets", "meshes/wizard_lower_leg"},
    {"wizardPelvis", "classicassets", "meshes/wizard_pelvis"},
    {"wizardToes", "classicassets", "meshes/wizard_toes"},
    {"wizardTorso", "classicassets", "meshes/wizard_torso"},
    {"wizardUpperArm", "classicassets", "meshes/wizard_upper_arm"},
    {"wizardUpperLeg", "classicassets", "meshes/wizard_upper_leg"},
    {"woo", "classicassets", "audio/woo"},
    {"woo2", "classicassets", "audio/woo2"},
    {"woo3", "classicassets", "audio/woo3"},
    {"woodDebrisFall", "classicassets", "audio/wood_debris_fall"},
    {"wow", "classicassets", "audio/wow"},
    {"wrestler1", "classicassets", "audio/wrestler1"},
    {"wrestler2", "classicassets", "audio/wrestler2"},
    {"wrestler3", "classicassets", "audio/wrestler3"},
    {"wrestler4", "classicassets", "audio/wrestler4"},
    {"wrestlerColor", "classicassets", "textures/wrestler_color"},
    {"wrestlerColorMask", "classicassets", "textures/wrestler_color_mask"},
    {"wrestlerDeath", "classicassets", "audio/wrestler_death"},
    {"wrestlerFall", "classicassets", "audio/wrestler_fall"},
    {"wrestlerForeArm", "classicassets", "meshes/wrestler_fore_arm"},
    {"wrestlerHand", "classicassets", "meshes/wrestler_hand"},
    {"wrestlerHead", "classicassets", "meshes/wrestler_head"},
    {"wrestlerHit1", "classicassets", "audio/wrestler_hit1"},
    {"wrestlerHit2", "classicassets", "audio/wrestler_hit2"},
    {"wrestlerIcon", "classicassets", "textures/wrestler_icon"},
    {"wrestlerIconColorMask", "classicassets",
     "textures/wrestler_icon_color_mask"},
    {"wrestlerLowerLeg", "classicassets", "meshes/wrestler_lower_leg"},
    {"wrestlerPelvis", "classicassets", "meshes/wrestler_pelvis"},
    {"wrestlerToes", "classicassets", "meshes/wrestler_toes"},
    {"wrestlerTorso", "classicassets", "meshes/wrestler_torso"},
    {"wrestlerUpperArm", "classicassets", "meshes/wrestler_upper_arm"},
    {"wrestlerUpperLeg", "classicassets", "meshes/wrestler_upper_leg"},
    {"yeah", "classicassets", "audio/yeah"},
    {"zigZagLevel", "classicassets", "meshes/zig_zag_level"},
    {"zigZagLevelBottom", "classicassets", "meshes/zig_zag_level_bottom"},
    {"zigZagLevelBumper", "classicassets", "meshes/zig_zag_level_bumper"},
    {"zigZagLevelCollide", "classicassets", "meshes/zig_zag_level_collide"},
    {"zigZagLevelColor", "classicassets", "textures/zig_zag_level_color"},
    {"zigzagPreview", "classicassets", "textures/zigzag_preview"},
    {"zoeAttack01", "classicassets", "audio/zoe_attack01"},
    {"zoeAttack02", "classicassets", "audio/zoe_attack02"},
    {"zoeAttack03", "classicassets", "audio/zoe_attack03"},
    {"zoeAttack04", "classicassets", "audio/zoe_attack04"},
    {"zoeColor", "classicassets", "textures/zoe_color"},
    {"zoeColorMask", "classicassets", "textures/zoe_color_mask"},
    {"zoeDeath01", "classicassets", "audio/zoe_death01"},
    {"zoeEff", "classicassets", "audio/zoe_eff"},
    {"zoeFall01", "classicassets", "audio/zoe_fall01"},
    {"zoeForeArm", "classicassets", "meshes/zoe_fore_arm"},
    {"zoeHand", "classicassets", "meshes/zoe_hand"},
    {"zoeHead", "classicassets", "meshes/zoe_head"},
    {"zoeIcon", "classicassets", "textures/zoe_icon"},
    {"zoeIconColorMask", "classicassets", "textures/zoe_icon_color_mask"},
    {"zoeImpact01", "classicassets", "audio/zoe_impact01"},
    {"zoeImpact02", "classicassets", "audio/zoe_impact02"},
    {"zoeImpact03", "classicassets", "audio/zoe_impact03"},
    {"zoeImpact04", "classicassets", "audio/zoe_impact04"},
    {"zoeJump01", "classicassets", "audio/zoe_jump01"},
    {"zoeJump02", "classicassets", "audio/zoe_jump02"},
    {"zoeJump03", "classicassets", "audio/zoe_jump03"},
    {"zoeLowerLeg", "classicassets", "meshes/zoe_lower_leg"},
    {"zoeOw", "classicassets", "audio/zoe_ow"},
    {"zoePelvis", "classicassets", "meshes/zoe_pelvis"},
    {"zoePickup01", "classicassets", "audio/zoe_pickup01"},
    {"zoeScream01", "classicassets", "audio/zoe_scream01"},
    {"zoeToes", "classicassets", "meshes/zoe_toes"},
    {"zoeTorso", "classicassets", "meshes/zoe_torso"},
    {"zoeUpperArm", "classicassets", "meshes/zoe_upper_arm"},
    {"zoeUpperLeg", "classicassets", "meshes/zoe_upper_leg"},
};

struct State_ {
  // '<kind>|<legacy name>' -> (package_key, logical_path), where kind
  // is the logical path's first segment ('textures', 'audio',
  // 'meshes', ...). Kind-scoped because legacy names were only unique
  // per asset type: 'shield' names both a texture and a mesh, and each
  // Get* call site knows which kind it wants.
  std::unordered_map<std::string, std::pair<std::string, std::string>>
      from_legacy;
  // 'package_key:logical_path' -> legacy name.
  std::unordered_map<std::string, std::string> to_legacy;
  // package_key -> registered full apverid.
  std::unordered_map<std::string, std::string> package_versions;
  // Versionless apverid prefix ('a-0.babuiltinassets') -> package_key.
  std::unordered_map<std::string, std::string> versionless_to_key;
};

static auto GetState_() -> State_& {
  static State_* state = [] {
    auto* st = new State_();
    for (const Row_& row : kRows) {
      std::string logical(row.logical_path);
      std::string kind = logical.substr(0, logical.find('/'));
      st->from_legacy[kind + "|" + row.legacy] = {row.package_key,
                                                  row.logical_path};
      st->to_legacy[std::string(row.package_key) + ":" + row.logical_path] =
          row.legacy;
    }
    return st;
  }();
  return *state;
}

// Strip the trailing version segment off an apverid
// ('a-0.babuiltinassets.dev260610e' -> 'a-0.babuiltinassets').
static auto VersionlessApverid_(const std::string& apverid) -> std::string {
  size_t pos = apverid.rfind('.');
  return pos == std::string::npos ? apverid : apverid.substr(0, pos);
}

void AssetNameCompat::SetPackageVersion(const std::string& package_key,
                                        const std::string& apverid) {
  assert(g_base->InLogicThread());
  auto& state = GetState_();
  // Drop any versionless mapping from a previous registration.
  auto old = state.package_versions.find(package_key);
  if (old != state.package_versions.end()) {
    state.versionless_to_key.erase(VersionlessApverid_(old->second));
  }
  state.package_versions[package_key] = apverid;
  state.versionless_to_key[VersionlessApverid_(apverid)] = package_key;
}

auto AssetNameCompat::FromLegacy(const std::string& name, const char* kind)
    -> std::string {
  assert(g_base->InLogicThread());
  if (name.find(':') != std::string::npos) {
    return name;  // Already qualified.
  }
  auto& state = GetState_();
  auto row = state.from_legacy.find(std::string(kind) + "|" + name);
  if (row == state.from_legacy.end()) {
    return name;  // No asset-package home; a true legacy name.
  }
  auto version = state.package_versions.find(row->second.first);
  if (version == state.package_versions.end()) {
    return name;  // Package version not registered (yet).
  }
  std::string mapped = version->second + ":" + row->second.second;
  g_core->logging->Log(
      LogName::kBaAssets, LogLevel::kDebug,
      "AssetNameCompat: from-legacy '" + name + "' -> '" + mapped + "'.");
  return mapped;
}

auto AssetNameCompat::ToLegacy(const std::string& name) -> std::string {
  assert(g_base->InLogicThread());
  size_t colon = name.find(':');
  if (colon == std::string::npos) {
    return name;  // Already a bare name.
  }
  auto& state = GetState_();
  auto key =
      state.versionless_to_key.find(VersionlessApverid_(name.substr(0, colon)));
  if (key == state.versionless_to_key.end()) {
    return name;  // Not a package we know about.
  }
  auto legacy =
      state.to_legacy.find(key->second + ":" + name.substr(colon + 1));
  if (legacy == state.to_legacy.end()) {
    return name;
  }
  g_core->logging->Log(
      LogName::kBaAssets, LogLevel::kDebug,
      "AssetNameCompat: to-legacy '" + name + "' -> '" + legacy->second + "'.");
  return legacy->second;
}

}  // namespace ballistica::base
