// Released under the MIT License. See LICENSE for details.

#include "ballistica/base/assets/asset_name_compat.h"

#include <string>
#include <unordered_map>
#include <utility>

#include "ballistica/core/core.h"
#include "ballistica/core/logging/logging.h"

namespace ballistica::base {

struct Row_ {
  const char* legacy;
  const char* package_key;
  const char* logical_path;
};

// One row per migrated asset. The legacy side is frozen (old peers and
// replays speak these names forever); the (package_key, logical_path)
// side must track package contents - update_project --check verifies
// it against the wrapper modules. Add a row here whenever an asset
// migrates out of the legacy tree.
static const Row_ kRows[] = {
    {"achievement", "stdassets", "audio/achievement"},
    {"achievementBoxer", "stdassets", "textures/achievement_boxer"},
    {"achievementCrossHair", "stdassets", "textures/achievement_cross_hair"},
    {"achievementDualWielding", "stdassets",
     "textures/achievement_dual_wielding"},
    {"achievementEmpty", "stdassets", "textures/achievement_empty"},
    {"achievementFlawlessVictory", "stdassets",
     "textures/achievement_flawless_victory"},
    {"achievementFootballShutout", "stdassets",
     "textures/achievement_football_shutout"},
    {"achievementFootballVictory", "stdassets",
     "textures/achievement_football_victory"},
    {"achievementFreeLoader", "stdassets", "textures/achievement_free_loader"},
    {"achievementGotTheMoves", "stdassets",
     "textures/achievement_got_the_moves"},
    {"achievementInControl", "stdassets", "textures/achievement_in_control"},
    {"achievementMedalLarge", "stdassets", "textures/achievement_medal_large"},
    {"achievementMedalMedium", "stdassets",
     "textures/achievement_medal_medium"},
    {"achievementMedalSmall", "stdassets", "textures/achievement_medal_small"},
    {"achievementMine", "stdassets", "textures/achievement_mine"},
    {"achievementOffYouGo", "stdassets", "textures/achievement_off_you_go"},
    {"achievementOnslaught", "stdassets", "textures/achievement_onslaught"},
    {"achievementOutline", "stdassets", "meshes/achievement_outline"},
    {"achievementOutline", "stdassets", "textures/achievement_outline"},
    {"achievementRunaround", "stdassets", "textures/achievement_runaround"},
    {"achievementSharingIsCaring", "stdassets",
     "textures/achievement_sharing_is_caring"},
    {"achievementStayinAlive", "stdassets",
     "textures/achievement_stayin_alive"},
    {"achievementSuperPunch", "stdassets", "textures/achievement_super_punch"},
    {"achievementTNT", "stdassets", "textures/achievement_tnt"},
    {"achievementTeamPlayer", "stdassets", "textures/achievement_team_player"},
    {"achievementWall", "stdassets", "textures/achievement_wall"},
    {"achievementsIcon", "stdassets", "textures/achievements_icon"},
    {"actionButtonBottom", "builtinassets", "meshes/action_button_bottom"},
    {"actionButtonLeft", "builtinassets", "meshes/action_button_left"},
    {"actionButtonRight", "builtinassets", "meshes/action_button_right"},
    {"actionButtonTop", "builtinassets", "meshes/action_button_top"},
    {"actionButtons", "builtinassets", "textures/action_buttons"},
    {"actionHero1", "stdassets", "audio/action_hero1"},
    {"actionHero2", "stdassets", "audio/action_hero2"},
    {"actionHero3", "stdassets", "audio/action_hero3"},
    {"actionHero4", "stdassets", "audio/action_hero4"},
    {"actionHeroColor", "stdassets", "textures/action_hero_color"},
    {"actionHeroColorMask", "stdassets", "textures/action_hero_color_mask"},
    {"actionHeroDeath", "stdassets", "audio/action_hero_death"},
    {"actionHeroFall", "stdassets", "audio/action_hero_fall"},
    {"actionHeroForeArm", "stdassets", "meshes/action_hero_fore_arm"},
    {"actionHeroHand", "stdassets", "meshes/action_hero_hand"},
    {"actionHeroHead", "stdassets", "meshes/action_hero_head"},
    {"actionHeroHit1", "stdassets", "audio/action_hero_hit1"},
    {"actionHeroHit2", "stdassets", "audio/action_hero_hit2"},
    {"actionHeroIcon", "stdassets", "textures/action_hero_icon"},
    {"actionHeroIconColorMask", "stdassets",
     "textures/action_hero_icon_color_mask"},
    {"actionHeroLowerLeg", "stdassets", "meshes/action_hero_lower_leg"},
    {"actionHeroPelvis", "stdassets", "meshes/action_hero_pelvis"},
    {"actionHeroToes", "stdassets", "meshes/action_hero_toes"},
    {"actionHeroTorso", "stdassets", "meshes/action_hero_torso"},
    {"actionHeroUpperArm", "stdassets", "meshes/action_hero_upper_arm"},
    {"actionHeroUpperLeg", "stdassets", "meshes/action_hero_upper_leg"},
    {"activateBeep", "stdassets", "audio/activate_beep"},
    {"advancedIcon", "stdassets", "textures/advanced_icon"},
    {"agent1", "stdassets", "audio/agent1"},
    {"agent2", "stdassets", "audio/agent2"},
    {"agent3", "stdassets", "audio/agent3"},
    {"agent4", "stdassets", "audio/agent4"},
    {"agentColor", "stdassets", "textures/agent_color"},
    {"agentColorMask", "stdassets", "textures/agent_color_mask"},
    {"agentDeath", "stdassets", "audio/agent_death"},
    {"agentFall", "stdassets", "audio/agent_fall"},
    {"agentForeArm", "stdassets", "meshes/agent_fore_arm"},
    {"agentHand", "stdassets", "meshes/agent_hand"},
    {"agentHead", "stdassets", "meshes/agent_head"},
    {"agentHit1", "stdassets", "audio/agent_hit1"},
    {"agentHit2", "stdassets", "audio/agent_hit2"},
    {"agentIcon", "stdassets", "textures/agent_icon"},
    {"agentIconColorMask", "stdassets", "textures/agent_icon_color_mask"},
    {"agentLowerLeg", "stdassets", "meshes/agent_lower_leg"},
    {"agentPelvis", "stdassets", "meshes/agent_pelvis"},
    {"agentToes", "stdassets", "meshes/agent_toes"},
    {"agentTorso", "stdassets", "meshes/agent_torso"},
    {"agentUpperArm", "stdassets", "meshes/agent_upper_arm"},
    {"agentUpperLeg", "stdassets", "meshes/agent_upper_leg"},
    {"alarm", "stdassets", "audio/alarm"},
    {"ali1", "stdassets", "audio/ali1"},
    {"ali2", "stdassets", "audio/ali2"},
    {"ali3", "stdassets", "audio/ali3"},
    {"ali4", "stdassets", "audio/ali4"},
    {"aliColor", "stdassets", "textures/ali_color"},
    {"aliColorMask", "stdassets", "textures/ali_color_mask"},
    {"aliDeath", "stdassets", "audio/ali_death"},
    {"aliFall", "stdassets", "audio/ali_fall"},
    {"aliForeArm", "stdassets", "meshes/ali_fore_arm"},
    {"aliHand", "stdassets", "meshes/ali_hand"},
    {"aliHead", "stdassets", "meshes/ali_head"},
    {"aliHit1", "stdassets", "audio/ali_hit1"},
    {"aliHit2", "stdassets", "audio/ali_hit2"},
    {"aliIcon", "stdassets", "textures/ali_icon"},
    {"aliIconColorMask", "stdassets", "textures/ali_icon_color_mask"},
    {"aliLowerLeg", "stdassets", "meshes/ali_lower_leg"},
    {"aliPelvis", "stdassets", "meshes/ali_pelvis"},
    {"aliSplash", "stdassets", "textures/ali_splash"},
    {"aliToes", "stdassets", "meshes/ali_toes"},
    {"aliTorso", "stdassets", "meshes/ali_torso"},
    {"aliUpperArm", "stdassets", "meshes/ali_upper_arm"},
    {"aliUpperLeg", "stdassets", "meshes/ali_upper_leg"},
    {"alien1", "stdassets", "audio/alien1"},
    {"alien2", "stdassets", "audio/alien2"},
    {"alien3", "stdassets", "audio/alien3"},
    {"alien4", "stdassets", "audio/alien4"},
    {"alienColor", "stdassets", "textures/alien_color"},
    {"alienColorMask", "stdassets", "textures/alien_color_mask"},
    {"alienDeath", "stdassets", "audio/alien_death"},
    {"alienFall", "stdassets", "audio/alien_fall"},
    {"alienForeArm", "stdassets", "meshes/alien_fore_arm"},
    {"alienHand", "stdassets", "meshes/alien_hand"},
    {"alienHead", "stdassets", "meshes/alien_head"},
    {"alienHit1", "stdassets", "audio/alien_hit1"},
    {"alienHit2", "stdassets", "audio/alien_hit2"},
    {"alienIcon", "stdassets", "textures/alien_icon"},
    {"alienIconColorMask", "stdassets", "textures/alien_icon_color_mask"},
    {"alienLowerLeg", "stdassets", "meshes/alien_lower_leg"},
    {"alienPelvis", "stdassets", "meshes/alien_pelvis"},
    {"alienToes", "stdassets", "meshes/alien_toes"},
    {"alienTorso", "stdassets", "meshes/alien_torso"},
    {"alienUpperArm", "stdassets", "meshes/alien_upper_arm"},
    {"alienUpperLeg", "stdassets", "meshes/alien_upper_leg"},
    {"alwaysLandBG", "stdassets", "meshes/always_land_bg"},
    {"alwaysLandBGColor", "stdassets", "textures/always_land_bgcolor"},
    {"alwaysLandLevel", "stdassets", "meshes/always_land_level"},
    {"alwaysLandLevelBottom", "stdassets", "meshes/always_land_level_bottom"},
    {"alwaysLandLevelCollide", "stdassets", "meshes/always_land_level_collide"},
    {"alwaysLandLevelColor", "stdassets", "textures/always_land_level_color"},
    {"alwaysLandPreview", "stdassets", "textures/always_land_preview"},
    {"alwaysLandVRFillMound", "stdassets", "meshes/always_land_vrfill_mound"},
    {"analogStick", "stdassets", "textures/analog_stick"},
    {"angryComputerTransparent", "stdassets",
     "meshes/angry_computer_transparent"},
    {"announceEight", "stdassets", "audio/announce_eight"},
    {"announceFive", "stdassets", "audio/announce_five"},
    {"announceFour", "stdassets", "audio/announce_four"},
    {"announceNine", "stdassets", "audio/announce_nine"},
    {"announceOne", "stdassets", "audio/announce_one"},
    {"announceSeven", "stdassets", "audio/announce_seven"},
    {"announceSix", "stdassets", "audio/announce_six"},
    {"announceTen", "stdassets", "audio/announce_ten"},
    {"announceThree", "stdassets", "audio/announce_three"},
    {"announceTwo", "stdassets", "audio/announce_two"},
    {"arrow", "builtinassets", "textures/arrow"},
    {"arrowBack", "builtinassets", "meshes/arrow_back"},
    {"arrowFront", "builtinassets", "meshes/arrow_front"},
    {"assassin1", "stdassets", "audio/assassin1"},
    {"assassin2", "stdassets", "audio/assassin2"},
    {"assassin3", "stdassets", "audio/assassin3"},
    {"assassin4", "stdassets", "audio/assassin4"},
    {"assassinColor", "stdassets", "textures/assassin_color"},
    {"assassinColorMask", "stdassets", "textures/assassin_color_mask"},
    {"assassinDeath", "stdassets", "audio/assassin_death"},
    {"assassinFall", "stdassets", "audio/assassin_fall"},
    {"assassinForeArm", "stdassets", "meshes/assassin_fore_arm"},
    {"assassinHand", "stdassets", "meshes/assassin_hand"},
    {"assassinHead", "stdassets", "meshes/assassin_head"},
    {"assassinHit1", "stdassets", "audio/assassin_hit1"},
    {"assassinHit2", "stdassets", "audio/assassin_hit2"},
    {"assassinIcon", "stdassets", "textures/assassin_icon"},
    {"assassinIconColorMask", "stdassets", "textures/assassin_icon_color_mask"},
    {"assassinLowerLeg", "stdassets", "meshes/assassin_lower_leg"},
    {"assassinPelvis", "stdassets", "meshes/assassin_pelvis"},
    {"assassinToes", "stdassets", "meshes/assassin_toes"},
    {"assassinTorso", "stdassets", "meshes/assassin_torso"},
    {"assassinUpperArm", "stdassets", "meshes/assassin_upper_arm"},
    {"assassinUpperLeg", "stdassets", "meshes/assassin_upper_leg"},
    {"audioIcon", "stdassets", "textures/audio_icon"},
    {"aww", "stdassets", "audio/aww"},
    {"backIcon", "builtinassets", "textures/back_icon"},
    {"bar", "stdassets", "textures/bar"},
    {"bear1", "stdassets", "audio/bear1"},
    {"bear2", "stdassets", "audio/bear2"},
    {"bear3", "stdassets", "audio/bear3"},
    {"bear4", "stdassets", "audio/bear4"},
    {"bearColor", "stdassets", "textures/bear_color"},
    {"bearColorMask", "stdassets", "textures/bear_color_mask"},
    {"bearDeath", "stdassets", "audio/bear_death"},
    {"bearFall", "stdassets", "audio/bear_fall"},
    {"bearForeArm", "stdassets", "meshes/bear_fore_arm"},
    {"bearHand", "stdassets", "meshes/bear_hand"},
    {"bearHead", "stdassets", "meshes/bear_head"},
    {"bearHit1", "stdassets", "audio/bear_hit1"},
    {"bearHit2", "stdassets", "audio/bear_hit2"},
    {"bearIcon", "stdassets", "textures/bear_icon"},
    {"bearIconColorMask", "stdassets", "textures/bear_icon_color_mask"},
    {"bearLowerLeg", "stdassets", "meshes/bear_lower_leg"},
    {"bearPelvis", "stdassets", "meshes/bear_pelvis"},
    {"bearToes", "stdassets", "meshes/bear_toes"},
    {"bearTorso", "stdassets", "meshes/bear_torso"},
    {"bearUpperArm", "stdassets", "meshes/bear_upper_arm"},
    {"bearUpperLeg", "stdassets", "meshes/bear_upper_leg"},
    {"bellHigh", "stdassets", "audio/bell_high"},
    {"bellLow", "stdassets", "audio/bell_low"},
    {"bellMed", "stdassets", "audio/bell_med"},
    {"bg", "stdassets", "textures/bg"},
    {"bigG", "stdassets", "meshes/big_g"},
    {"bigG", "stdassets", "textures/big_g"},
    {"bigGBottom", "stdassets", "meshes/big_gbottom"},
    {"bigGBumper", "stdassets", "meshes/big_gbumper"},
    {"bigGCollide", "stdassets", "meshes/big_gcollide"},
    {"bigGPreview", "stdassets", "textures/big_gpreview"},
    {"bigImpact", "stdassets", "audio/big_impact"},
    {"bigImpact2", "stdassets", "audio/big_impact2"},
    {"black", "builtinassets", "textures/black"},
    {"blank", "builtinassets", "audio/blank"},
    {"blip", "builtinassets", "audio/blip"},
    {"block", "stdassets", "audio/block"},
    {"bomb", "stdassets", "meshes/bomb"},
    {"bombButton", "builtinassets", "textures/bomb_button"},
    {"bombColor", "stdassets", "textures/bomb_color"},
    {"bombColorIce", "stdassets", "textures/bomb_color_ice"},
    {"bombDrop01", "stdassets", "audio/bomb_drop01"},
    {"bombDrop02", "stdassets", "audio/bomb_drop02"},
    {"bombRoll01", "stdassets", "audio/bomb_roll01"},
    {"bombSticky", "stdassets", "meshes/bomb_sticky"},
    {"bombStickyColor", "stdassets", "textures/bomb_sticky_color"},
    {"bones1", "stdassets", "audio/bones1"},
    {"bones2", "stdassets", "audio/bones2"},
    {"bones3", "stdassets", "audio/bones3"},
    {"bonesColor", "stdassets", "textures/bones_color"},
    {"bonesColorMask", "stdassets", "textures/bones_color_mask"},
    {"bonesDeath", "stdassets", "audio/bones_death"},
    {"bonesFall", "stdassets", "audio/bones_fall"},
    {"bonesForeArm", "stdassets", "meshes/bones_fore_arm"},
    {"bonesHand", "stdassets", "meshes/bones_hand"},
    {"bonesHead", "stdassets", "meshes/bones_head"},
    {"bonesIcon", "stdassets", "textures/bones_icon"},
    {"bonesIconColorMask", "stdassets", "textures/bones_icon_color_mask"},
    {"bonesLowerLeg", "stdassets", "meshes/bones_lower_leg"},
    {"bonesPelvis", "stdassets", "meshes/bones_pelvis"},
    {"bonesToes", "stdassets", "meshes/bones_toes"},
    {"bonesTorso", "stdassets", "meshes/bones_torso"},
    {"bonesUpperArm", "stdassets", "meshes/bones_upper_arm"},
    {"bonesUpperLeg", "stdassets", "meshes/bones_upper_leg"},
    {"boo", "stdassets", "audio/boo"},
    {"box", "builtinassets", "meshes/box"},
    {"boxDrop", "stdassets", "audio/box_drop"},
    {"boxingBell", "stdassets", "audio/boxing_bell"},
    {"boxingGlove", "builtinassets", "meshes/boxing_glove"},
    {"boxingGlovesColor", "builtinassets", "textures/boxing_gloves_color"},
    {"bridgitLevelBottom", "stdassets", "meshes/bridgit_level_bottom"},
    {"bridgitLevelCollide", "stdassets", "meshes/bridgit_level_collide"},
    {"bridgitLevelColor", "stdassets", "textures/bridgit_level_color"},
    {"bridgitLevelRailingCollide", "stdassets",
     "meshes/bridgit_level_railing_collide"},
    {"bridgitLevelTop", "stdassets", "meshes/bridgit_level_top"},
    {"bridgitPreview", "stdassets", "textures/bridgit_preview"},
    {"bunny1", "stdassets", "audio/bunny1"},
    {"bunny2", "stdassets", "audio/bunny2"},
    {"bunny3", "stdassets", "audio/bunny3"},
    {"bunny4", "stdassets", "audio/bunny4"},
    {"bunnyColor", "stdassets", "textures/bunny_color"},
    {"bunnyColorMask", "stdassets", "textures/bunny_color_mask"},
    {"bunnyDeath", "stdassets", "audio/bunny_death"},
    {"bunnyFall", "stdassets", "audio/bunny_fall"},
    {"bunnyForeArm", "stdassets", "meshes/bunny_fore_arm"},
    {"bunnyHand", "stdassets", "meshes/bunny_hand"},
    {"bunnyHead", "stdassets", "meshes/bunny_head"},
    {"bunnyHit1", "stdassets", "audio/bunny_hit1"},
    {"bunnyHit2", "stdassets", "audio/bunny_hit2"},
    {"bunnyIcon", "stdassets", "textures/bunny_icon"},
    {"bunnyIconColorMask", "stdassets", "textures/bunny_icon_color_mask"},
    {"bunnyJump", "stdassets", "audio/bunny_jump"},
    {"bunnyLowerLeg", "stdassets", "meshes/bunny_lower_leg"},
    {"bunnyPelvis", "stdassets", "meshes/bunny_pelvis"},
    {"bunnyToes", "stdassets", "meshes/bunny_toes"},
    {"bunnyTorso", "stdassets", "meshes/bunny_torso"},
    {"bunnyUpperArm", "stdassets", "meshes/bunny_upper_arm"},
    {"bunnyUpperLeg", "stdassets", "meshes/bunny_upper_leg"},
    {"buttonBackOpaque", "builtinassets", "meshes/button_back_opaque"},
    {"buttonBackSmallOpaque", "builtinassets",
     "meshes/button_back_small_opaque"},
    {"buttonBackSmallTransparent", "builtinassets",
     "meshes/button_back_small_transparent"},
    {"buttonBackTransparent", "builtinassets",
     "meshes/button_back_transparent"},
    {"buttonBomb", "stdassets", "textures/button_bomb"},
    {"buttonJump", "stdassets", "textures/button_jump"},
    {"buttonLargeOpaque", "builtinassets", "meshes/button_large_opaque"},
    {"buttonLargeTransparent", "builtinassets",
     "meshes/button_large_transparent"},
    {"buttonLargerOpaque", "builtinassets", "meshes/button_larger_opaque"},
    {"buttonLargerTransparent", "builtinassets",
     "meshes/button_larger_transparent"},
    {"buttonMediumOpaque", "builtinassets", "meshes/button_medium_opaque"},
    {"buttonMediumTransparent", "builtinassets",
     "meshes/button_medium_transparent"},
    {"buttonNull", "stdassets", "meshes/button_null"},
    {"buttonPickUp", "stdassets", "textures/button_pick_up"},
    {"buttonPunch", "stdassets", "textures/button_punch"},
    {"buttonSmallOpaque", "builtinassets", "meshes/button_small_opaque"},
    {"buttonSmallTransparent", "builtinassets",
     "meshes/button_small_transparent"},
    {"buttonSquare", "builtinassets", "textures/button_square"},
    {"buttonSquareOpaque", "builtinassets", "meshes/button_square_opaque"},
    {"buttonSquareTransparent", "builtinassets",
     "meshes/button_square_transparent"},
    {"buttonSquareWide", "builtinassets", "textures/button_square_wide"},
    {"buttonTabOpaque", "builtinassets", "meshes/button_tab_opaque"},
    {"buttonTabTransparent", "builtinassets", "meshes/button_tab_transparent"},
    {"cashRegister", "builtinassets", "audio/cash_register"},
    {"cashRegister2", "stdassets", "audio/cash_register2"},
    {"chTitleChar1", "stdassets", "textures/ch_title_char1"},
    {"chTitleChar2", "stdassets", "textures/ch_title_char2"},
    {"chTitleChar3", "stdassets", "textures/ch_title_char3"},
    {"chTitleChar4", "stdassets", "textures/ch_title_char4"},
    {"chTitleChar5", "stdassets", "textures/ch_title_char5"},
    {"charSelectMusic", "stdassets", "audio/char_select_music"},
    {"characterIconMask", "builtinassets", "textures/character_icon_mask"},
    {"checkTransparent", "builtinassets", "meshes/check_transparent"},
    {"cheer", "stdassets", "audio/cheer"},
    {"chestIcon", "stdassets", "textures/chest_icon"},
    {"chestIconEmpty", "stdassets", "textures/chest_icon_empty"},
    {"chestIconMulti", "stdassets", "textures/chest_icon_multi"},
    {"chestIconTint", "stdassets", "textures/chest_icon_tint"},
    {"chestOpenIcon", "stdassets", "textures/chest_open_icon"},
    {"chestOpenIconTint", "stdassets", "textures/chest_open_icon_tint"},
    {"circle", "builtinassets", "textures/circle"},
    {"circleNoAlpha", "builtinassets", "textures/circle_no_alpha"},
    {"circleOutline", "builtinassets", "textures/circle_outline"},
    {"circleOutlineNoAlpha", "builtinassets",
     "textures/circle_outline_no_alpha"},
    {"circleShadow", "builtinassets", "textures/circle_shadow"},
    {"circleSoft", "builtinassets", "textures/circle_soft"},
    {"circleZigZag", "stdassets", "textures/circle_zig_zag"},
    {"clayStroke", "stdassets", "textures/clay_stroke"},
    {"click01", "builtinassets", "audio/click01"},
    {"coin", "stdassets", "textures/coin"},
    {"controllerIcon", "stdassets", "textures/controller_icon"},
    {"corkPop", "builtinassets", "audio/cork_pop"},
    {"corkPop2", "stdassets", "audio/cork_pop2"},
    {"courtyardLevel", "stdassets", "meshes/courtyard_level"},
    {"courtyardLevelBottom", "stdassets", "meshes/courtyard_level_bottom"},
    {"courtyardLevelCollide", "stdassets", "meshes/courtyard_level_collide"},
    {"courtyardLevelColor", "stdassets", "textures/courtyard_level_color"},
    {"courtyardPlayerWall", "stdassets", "meshes/courtyard_player_wall"},
    {"courtyardPreview", "stdassets", "textures/courtyard_preview"},
    {"cowboy1", "stdassets", "audio/cowboy1"},
    {"cowboy2", "stdassets", "audio/cowboy2"},
    {"cowboy3", "stdassets", "audio/cowboy3"},
    {"cowboy4", "stdassets", "audio/cowboy4"},
    {"cowboyColor", "stdassets", "textures/cowboy_color"},
    {"cowboyColorMask", "stdassets", "textures/cowboy_color_mask"},
    {"cowboyDeath", "stdassets", "audio/cowboy_death"},
    {"cowboyFall", "stdassets", "audio/cowboy_fall"},
    {"cowboyForeArm", "stdassets", "meshes/cowboy_fore_arm"},
    {"cowboyHand", "stdassets", "meshes/cowboy_hand"},
    {"cowboyHead", "stdassets", "meshes/cowboy_head"},
    {"cowboyHit1", "stdassets", "audio/cowboy_hit1"},
    {"cowboyHit2", "stdassets", "audio/cowboy_hit2"},
    {"cowboyIcon", "stdassets", "textures/cowboy_icon"},
    {"cowboyIconColorMask", "stdassets", "textures/cowboy_icon_color_mask"},
    {"cowboyLowerLeg", "stdassets", "meshes/cowboy_lower_leg"},
    {"cowboyPelvis", "stdassets", "meshes/cowboy_pelvis"},
    {"cowboyToes", "stdassets", "meshes/cowboy_toes"},
    {"cowboyTorso", "stdassets", "meshes/cowboy_torso"},
    {"cowboyUpperArm", "stdassets", "meshes/cowboy_upper_arm"},
    {"cowboyUpperLeg", "stdassets", "meshes/cowboy_upper_leg"},
    {"cragCastleLevel", "stdassets", "meshes/crag_castle_level"},
    {"cragCastleLevelBottom", "stdassets", "meshes/crag_castle_level_bottom"},
    {"cragCastleLevelBumper", "stdassets", "meshes/crag_castle_level_bumper"},
    {"cragCastleLevelCollide", "stdassets", "meshes/crag_castle_level_collide"},
    {"cragCastleLevelColor", "stdassets", "textures/crag_castle_level_color"},
    {"cragCastlePreview", "stdassets", "textures/crag_castle_preview"},
    {"cragCastleVRFillMound", "stdassets", "meshes/crag_castle_vrfill_mound"},
    {"crossOut", "builtinassets", "meshes/cross_out"},
    {"crossOut", "stdassets", "textures/cross_out"},
    {"crossOutMask", "stdassets", "textures/cross_out_mask"},
    {"crowdChant", "stdassets", "audio/crowd_chant"},
    {"currencyMeter", "stdassets", "meshes/currency_meter"},
    {"currencyPlusButton", "stdassets", "meshes/currency_plus_button"},
    {"cursor", "builtinassets", "textures/cursor"},
    {"cuteSpaz", "stdassets", "textures/cute_spaz"},
    {"cyborg1", "stdassets", "audio/cyborg1"},
    {"cyborg2", "stdassets", "audio/cyborg2"},
    {"cyborg3", "stdassets", "audio/cyborg3"},
    {"cyborg4", "stdassets", "audio/cyborg4"},
    {"cyborgColor", "stdassets", "textures/cyborg_color"},
    {"cyborgColorMask", "stdassets", "textures/cyborg_color_mask"},
    {"cyborgDeath", "stdassets", "audio/cyborg_death"},
    {"cyborgFall", "stdassets", "audio/cyborg_fall"},
    {"cyborgForeArm", "stdassets", "meshes/cyborg_fore_arm"},
    {"cyborgHand", "stdassets", "meshes/cyborg_hand"},
    {"cyborgHead", "stdassets", "meshes/cyborg_head"},
    {"cyborgHit1", "stdassets", "audio/cyborg_hit1"},
    {"cyborgHit2", "stdassets", "audio/cyborg_hit2"},
    {"cyborgIcon", "stdassets", "textures/cyborg_icon"},
    {"cyborgIconColorMask", "stdassets", "textures/cyborg_icon_color_mask"},
    {"cyborgLowerLeg", "stdassets", "meshes/cyborg_lower_leg"},
    {"cyborgPelvis", "stdassets", "meshes/cyborg_pelvis"},
    {"cyborgToes", "stdassets", "meshes/cyborg_toes"},
    {"cyborgTorso", "stdassets", "meshes/cyborg_torso"},
    {"cyborgUpperArm", "stdassets", "meshes/cyborg_upper_arm"},
    {"cyborgUpperLeg", "stdassets", "meshes/cyborg_upper_leg"},
    {"cylinder", "builtinassets", "meshes/cylinder"},
    {"cymbal", "stdassets", "audio/cymbal"},
    {"debrisFall", "stdassets", "audio/debris_fall"},
    {"deek", "builtinassets", "audio/deek"},
    {"deek2", "stdassets", "audio/deek2"},
    {"ding", "builtinassets", "audio/ding"},
    {"dingSmall", "stdassets", "audio/ding_small"},
    {"dingSmallHigh", "stdassets", "audio/ding_small_high"},
    {"discordIcon", "stdassets", "textures/discord_icon"},
    {"discordLogo", "stdassets", "textures/discord_logo"},
    {"discordServer", "stdassets", "textures/discord_server"},
    {"doomShroomBG", "stdassets", "meshes/doom_shroom_bg"},
    {"doomShroomBGColor", "stdassets", "textures/doom_shroom_bgcolor"},
    {"doomShroomLevel", "stdassets", "meshes/doom_shroom_level"},
    {"doomShroomLevelCollide", "stdassets", "meshes/doom_shroom_level_collide"},
    {"doomShroomLevelColor", "stdassets", "textures/doom_shroom_level_color"},
    {"doomShroomPreview", "stdassets", "textures/doom_shroom_preview"},
    {"doomShroomStem", "stdassets", "meshes/doom_shroom_stem"},
    {"doomShroomStemCollide", "stdassets", "meshes/doom_shroom_stem_collide"},
    {"doomShroomVRFill", "stdassets", "meshes/doom_shroom_vrfill"},
    {"downButton", "stdassets", "textures/down_button"},
    {"dripity", "stdassets", "audio/dripity"},
    {"drumRoll", "stdassets", "audio/drum_roll"},
    {"drumRollShort", "stdassets", "audio/drum_roll_short"},
    {"egg", "stdassets", "meshes/egg"},
    {"egg1", "stdassets", "textures/egg1"},
    {"egg2", "stdassets", "textures/egg2"},
    {"egg3", "stdassets", "textures/egg3"},
    {"egg4", "stdassets", "textures/egg4"},
    {"eggTex1", "stdassets", "textures/egg_tex1"},
    {"eggTex2", "stdassets", "textures/egg_tex2"},
    {"eggTex3", "stdassets", "textures/egg_tex3"},
    {"empty", "stdassets", "textures/empty"},
    {"error", "builtinassets", "audio/error"},
    {"explosion", "builtinassets", "textures/explosion"},
    {"explosion01", "stdassets", "audio/explosion01"},
    {"explosion02", "stdassets", "audio/explosion02"},
    {"explosion03", "stdassets", "audio/explosion03"},
    {"explosion04", "stdassets", "audio/explosion04"},
    {"explosion05", "stdassets", "audio/explosion05"},
    {"eyeBall", "builtinassets", "meshes/eye_ball"},
    {"eyeBallIris", "builtinassets", "meshes/eye_ball_iris"},
    {"eyeColor", "builtinassets", "textures/eye_color"},
    {"eyeColorTintMask", "builtinassets", "textures/eye_color_tint_mask"},
    {"eyeLid", "builtinassets", "meshes/eye_lid"},
    {"fanfare", "stdassets", "audio/fanfare"},
    {"file", "stdassets", "textures/file"},
    {"flagCatcherMusic", "stdassets", "audio/flag_catcher_music"},
    {"flagColor", "stdassets", "textures/flag_color"},
    {"flagPole", "builtinassets", "meshes/flag_pole"},
    {"flagPoleColor", "builtinassets", "textures/flag_pole_color"},
    {"flagStand", "builtinassets", "meshes/flag_stand"},
    {"flash", "builtinassets", "meshes/flash"},
    {"flyingMusic", "stdassets", "audio/flying_music"},
    {"foghorn", "stdassets", "audio/foghorn"},
    {"folder", "stdassets", "textures/folder"},
    {"fontBig", "builtinassets", "textures/font_big"},
    {"fontExtras", "builtinassets", "textures/font_extras"},
    {"fontExtras2", "builtinassets", "textures/font_extras2"},
    {"fontExtras3", "builtinassets", "textures/font_extras3"},
    {"fontExtras4", "builtinassets", "textures/font_extras4"},
    {"fontExtras5", "builtinassets", "textures/font_extras5"},
    {"fontSmall0", "builtinassets", "textures/font_small0"},
    {"fontSmall1", "builtinassets", "textures/font_small1"},
    {"fontSmall2", "builtinassets", "textures/font_small2"},
    {"fontSmall3", "builtinassets", "textures/font_small3"},
    {"fontSmall4", "builtinassets", "textures/font_small4"},
    {"fontSmall5", "builtinassets", "textures/font_small5"},
    {"fontSmall6", "builtinassets", "textures/font_small6"},
    {"fontSmall7", "builtinassets", "textures/font_small7"},
    {"footImpact01", "stdassets", "audio/foot_impact01"},
    {"footImpact02", "stdassets", "audio/foot_impact02"},
    {"footImpact03", "stdassets", "audio/foot_impact03"},
    {"footballStadium", "stdassets", "meshes/football_stadium"},
    {"footballStadium", "stdassets", "textures/football_stadium"},
    {"footballStadiumCollide", "stdassets", "meshes/football_stadium_collide"},
    {"footballStadiumPreview", "stdassets",
     "textures/football_stadium_preview"},
    {"footballStadiumVRFill", "stdassets", "meshes/football_stadium_vrfill"},
    {"forwardMarchMusic", "stdassets", "audio/forward_march_music"},
    {"frameInset", "stdassets", "meshes/frame_inset"},
    {"frameInset", "stdassets", "textures/frame_inset"},
    {"freeze", "stdassets", "audio/freeze"},
    {"frosty01", "stdassets", "audio/frosty01"},
    {"frosty02", "stdassets", "audio/frosty02"},
    {"frosty03", "stdassets", "audio/frosty03"},
    {"frosty04", "stdassets", "audio/frosty04"},
    {"frosty05", "stdassets", "audio/frosty05"},
    {"frostyColor", "stdassets", "textures/frosty_color"},
    {"frostyColorMask", "stdassets", "textures/frosty_color_mask"},
    {"frostyDeath", "stdassets", "audio/frosty_death"},
    {"frostyFall", "stdassets", "audio/frosty_fall"},
    {"frostyForeArm", "stdassets", "meshes/frosty_fore_arm"},
    {"frostyHand", "stdassets", "meshes/frosty_hand"},
    {"frostyHead", "stdassets", "meshes/frosty_head"},
    {"frostyHit01", "stdassets", "audio/frosty_hit01"},
    {"frostyHit02", "stdassets", "audio/frosty_hit02"},
    {"frostyHit03", "stdassets", "audio/frosty_hit03"},
    {"frostyIcon", "stdassets", "textures/frosty_icon"},
    {"frostyIconColorMask", "stdassets", "textures/frosty_icon_color_mask"},
    {"frostyLowerLeg", "stdassets", "meshes/frosty_lower_leg"},
    {"frostyPelvis", "stdassets", "meshes/frosty_pelvis"},
    {"frostyToes", "stdassets", "meshes/frosty_toes"},
    {"frostyTorso", "stdassets", "meshes/frosty_torso"},
    {"frostyUpperArm", "stdassets", "meshes/frosty_upper_arm"},
    {"frostyUpperLeg", "stdassets", "meshes/frosty_upper_leg"},
    {"fuse", "builtinassets", "textures/fuse"},
    {"fuse01", "stdassets", "audio/fuse01"},
    {"gameCenterIcon", "stdassets", "textures/game_center_icon"},
    {"gasp", "stdassets", "audio/gasp"},
    {"githubLogo", "stdassets", "textures/github_logo"},
    {"gladiator1", "stdassets", "audio/gladiator1"},
    {"gladiator2", "stdassets", "audio/gladiator2"},
    {"gladiator3", "stdassets", "audio/gladiator3"},
    {"gladiator4", "stdassets", "audio/gladiator4"},
    {"gladiatorColor", "stdassets", "textures/gladiator_color"},
    {"gladiatorColorMask", "stdassets", "textures/gladiator_color_mask"},
    {"gladiatorDeath", "stdassets", "audio/gladiator_death"},
    {"gladiatorFall", "stdassets", "audio/gladiator_fall"},
    {"gladiatorForeArm", "stdassets", "meshes/gladiator_fore_arm"},
    {"gladiatorHand", "stdassets", "meshes/gladiator_hand"},
    {"gladiatorHead", "stdassets", "meshes/gladiator_head"},
    {"gladiatorHit1", "stdassets", "audio/gladiator_hit1"},
    {"gladiatorHit2", "stdassets", "audio/gladiator_hit2"},
    {"gladiatorIcon", "stdassets", "textures/gladiator_icon"},
    {"gladiatorIconColorMask", "stdassets",
     "textures/gladiator_icon_color_mask"},
    {"gladiatorLowerLeg", "stdassets", "meshes/gladiator_lower_leg"},
    {"gladiatorPelvis", "stdassets", "meshes/gladiator_pelvis"},
    {"gladiatorToes", "stdassets", "meshes/gladiator_toes"},
    {"gladiatorTorso", "stdassets", "meshes/gladiator_torso"},
    {"gladiatorUpperArm", "stdassets", "meshes/gladiator_upper_arm"},
    {"gladiatorUpperLeg", "stdassets", "meshes/gladiator_upper_leg"},
    {"glow", "builtinassets", "textures/glow"},
    {"goldPass", "stdassets", "textures/gold_pass"},
    {"gong", "stdassets", "audio/gong"},
    {"googlePlayAchievementsIcon", "stdassets",
     "textures/google_play_achievements_icon"},
    {"googlePlayGamesIcon", "stdassets", "textures/google_play_games_icon"},
    {"googlePlayLeaderboardsIcon", "stdassets",
     "textures/google_play_leaderboards_icon"},
    {"googlePlusIcon", "stdassets", "textures/google_plus_icon"},
    {"googlePlusSignInButton", "stdassets",
     "textures/google_plus_sign_in_button"},
    {"grandRompMusic", "stdassets", "audio/grand_romp_music"},
    {"graphicsIcon", "stdassets", "textures/graphics_icon"},
    {"gravelSkid", "stdassets", "audio/gravel_skid"},
    {"gunCocking", "builtinassets", "audio/gun_cocking"},
    {"hairTuft1", "builtinassets", "meshes/hair_tuft1"},
    {"hairTuft1b", "builtinassets", "meshes/hair_tuft1b"},
    {"hairTuft2", "builtinassets", "meshes/hair_tuft2"},
    {"hairTuft3", "builtinassets", "meshes/hair_tuft3"},
    {"hairTuft4", "builtinassets", "meshes/hair_tuft4"},
    {"healthPowerup", "stdassets", "audio/health_powerup"},
    {"heart", "stdassets", "textures/heart"},
    {"heartOpaque", "stdassets", "meshes/heart_opaque"},
    {"heartTransparent", "stdassets", "meshes/heart_transparent"},
    {"hiss", "stdassets", "audio/hiss"},
    {"hockeyStadium", "stdassets", "textures/hockey_stadium"},
    {"hockeyStadiumCollide", "stdassets", "meshes/hockey_stadium_collide"},
    {"hockeyStadiumInner", "stdassets", "meshes/hockey_stadium_inner"},
    {"hockeyStadiumOuter", "stdassets", "meshes/hockey_stadium_outer"},
    {"hockeyStadiumPreview", "stdassets", "textures/hockey_stadium_preview"},
    {"hockeyStadiumStands", "stdassets", "meshes/hockey_stadium_stands"},
    {"iconOnslaught", "stdassets", "textures/icon_onslaught"},
    {"iconRunaround", "stdassets", "textures/icon_runaround"},
    {"image16x1", "builtinassets", "meshes/image16x1"},
    {"image1x1", "builtinassets", "meshes/image1x1"},
    {"image1x1FullScreen", "builtinassets", "meshes/image1x1_full_screen"},
    {"image1x1VRFullScreen", "builtinassets", "meshes/image1x1_vrfull_screen"},
    {"image2x1", "builtinassets", "meshes/image2x1"},
    {"image2x1Vertical", "stdassets", "meshes/image2x1_vertical"},
    {"image4x1", "builtinassets", "meshes/image4x1"},
    {"impactBomb", "stdassets", "meshes/impact_bomb"},
    {"impactBombColor", "stdassets", "textures/impact_bomb_color"},
    {"impactBombColorLit", "stdassets", "textures/impact_bomb_color_lit"},
    {"impactHard", "stdassets", "audio/impact_hard"},
    {"impactHard2", "stdassets", "audio/impact_hard2"},
    {"impactHard3", "stdassets", "audio/impact_hard3"},
    {"impactMedium", "stdassets", "audio/impact_medium"},
    {"impactMedium2", "stdassets", "audio/impact_medium2"},
    {"inventoryIcon", "stdassets", "textures/inventory_icon"},
    {"jack01", "stdassets", "audio/jack01"},
    {"jack02", "stdassets", "audio/jack02"},
    {"jack03", "stdassets", "audio/jack03"},
    {"jack04", "stdassets", "audio/jack04"},
    {"jack05", "stdassets", "audio/jack05"},
    {"jack06", "stdassets", "audio/jack06"},
    {"jackColor", "stdassets", "textures/jack_color"},
    {"jackColorMask", "stdassets", "textures/jack_color_mask"},
    {"jackDeath01", "stdassets", "audio/jack_death01"},
    {"jackFall01", "stdassets", "audio/jack_fall01"},
    {"jackForeArm", "stdassets", "meshes/jack_fore_arm"},
    {"jackHand", "stdassets", "meshes/jack_hand"},
    {"jackHead", "stdassets", "meshes/jack_head"},
    {"jackHit01", "stdassets", "audio/jack_hit01"},
    {"jackHit02", "stdassets", "audio/jack_hit02"},
    {"jackHit03", "stdassets", "audio/jack_hit03"},
    {"jackHit04", "stdassets", "audio/jack_hit04"},
    {"jackHit05", "stdassets", "audio/jack_hit05"},
    {"jackHit06", "stdassets", "audio/jack_hit06"},
    {"jackHit07", "stdassets", "audio/jack_hit07"},
    {"jackIcon", "stdassets", "textures/jack_icon"},
    {"jackIconColorMask", "stdassets", "textures/jack_icon_color_mask"},
    {"jackLowerLeg", "stdassets", "meshes/jack_lower_leg"},
    {"jackToes", "stdassets", "meshes/jack_toes"},
    {"jackTorso", "stdassets", "meshes/jack_torso"},
    {"jackUpperArm", "stdassets", "meshes/jack_upper_arm"},
    {"jackUpperLeg", "stdassets", "meshes/jack_upper_leg"},
    {"jumpsuit1", "stdassets", "audio/jumpsuit1"},
    {"jumpsuit2", "stdassets", "audio/jumpsuit2"},
    {"jumpsuit3", "stdassets", "audio/jumpsuit3"},
    {"jumpsuit4", "stdassets", "audio/jumpsuit4"},
    {"jumpsuitColor", "stdassets", "textures/jumpsuit_color"},
    {"jumpsuitColorMask", "stdassets", "textures/jumpsuit_color_mask"},
    {"jumpsuitDeath", "stdassets", "audio/jumpsuit_death"},
    {"jumpsuitFall", "stdassets", "audio/jumpsuit_fall"},
    {"jumpsuitForeArm", "stdassets", "meshes/jumpsuit_fore_arm"},
    {"jumpsuitHand", "stdassets", "meshes/jumpsuit_hand"},
    {"jumpsuitHead", "stdassets", "meshes/jumpsuit_head"},
    {"jumpsuitHit1", "stdassets", "audio/jumpsuit_hit1"},
    {"jumpsuitHit2", "stdassets", "audio/jumpsuit_hit2"},
    {"jumpsuitIcon", "stdassets", "textures/jumpsuit_icon"},
    {"jumpsuitIconColorMask", "stdassets", "textures/jumpsuit_icon_color_mask"},
    {"jumpsuitLowerLeg", "stdassets", "meshes/jumpsuit_lower_leg"},
    {"jumpsuitPelvis", "stdassets", "meshes/jumpsuit_pelvis"},
    {"jumpsuitToes", "stdassets", "meshes/jumpsuit_toes"},
    {"jumpsuitTorso", "stdassets", "meshes/jumpsuit_torso"},
    {"jumpsuitUpperArm", "stdassets", "meshes/jumpsuit_upper_arm"},
    {"jumpsuitUpperLeg", "stdassets", "meshes/jumpsuit_upper_leg"},
    {"kronk", "stdassets", "textures/kronk"},
    {"kronk1", "stdassets", "audio/kronk1"},
    {"kronk10", "stdassets", "audio/kronk10"},
    {"kronk2", "stdassets", "audio/kronk2"},
    {"kronk3", "stdassets", "audio/kronk3"},
    {"kronk4", "stdassets", "audio/kronk4"},
    {"kronk5", "stdassets", "audio/kronk5"},
    {"kronk6", "stdassets", "audio/kronk6"},
    {"kronk7", "stdassets", "audio/kronk7"},
    {"kronk8", "stdassets", "audio/kronk8"},
    {"kronk9", "stdassets", "audio/kronk9"},
    {"kronkColorMask", "stdassets", "textures/kronk_color_mask"},
    {"kronkDeath", "stdassets", "audio/kronk_death"},
    {"kronkFall", "stdassets", "audio/kronk_fall"},
    {"kronkForeArm", "stdassets", "meshes/kronk_fore_arm"},
    {"kronkHand", "stdassets", "meshes/kronk_hand"},
    {"kronkHead", "stdassets", "meshes/kronk_head"},
    {"kronkIcon", "stdassets", "textures/kronk_icon"},
    {"kronkIconColorMask", "stdassets", "textures/kronk_icon_color_mask"},
    {"kronkLowerLeg", "stdassets", "meshes/kronk_lower_leg"},
    {"kronkPelvis", "stdassets", "meshes/kronk_pelvis"},
    {"kronkToes", "stdassets", "meshes/kronk_toes"},
    {"kronkTorso", "stdassets", "meshes/kronk_torso"},
    {"kronkUpperArm", "stdassets", "meshes/kronk_upper_arm"},
    {"kronkUpperLeg", "stdassets", "meshes/kronk_upper_leg"},
    {"lakeFrigid", "stdassets", "meshes/lake_frigid"},
    {"lakeFrigid", "stdassets", "textures/lake_frigid"},
    {"lakeFrigidCollide", "stdassets", "meshes/lake_frigid_collide"},
    {"lakeFrigidPreview", "stdassets", "textures/lake_frigid_preview"},
    {"lakeFrigidReflections", "stdassets", "meshes/lake_frigid_reflections"},
    {"lakeFrigidReflections", "stdassets", "textures/lake_frigid_reflections"},
    {"lakeFrigidTop", "stdassets", "meshes/lake_frigid_top"},
    {"lakeFrigidVRFill", "stdassets", "meshes/lake_frigid_vrfill"},
    {"landMine", "stdassets", "meshes/land_mine"},
    {"landMine", "stdassets", "textures/land_mine"},
    {"landMineLit", "stdassets", "textures/land_mine_lit"},
    {"laser", "stdassets", "audio/laser"},
    {"laserReverse", "stdassets", "audio/laser_reverse"},
    {"leaderboardsIcon", "stdassets", "textures/leaderboards_icon"},
    {"leftButton", "stdassets", "textures/left_button"},
    {"levelIcon", "stdassets", "textures/level_icon"},
    {"level_select_button_opaque", "stdassets",
     "meshes/level_select_button_opaque"},
    {"level_select_button_transparent", "stdassets",
     "meshes/level_select_button_transparent"},
    {"light", "builtinassets", "textures/light"},
    {"lightSharp", "builtinassets", "textures/light_sharp"},
    {"lightSoft", "builtinassets", "textures/light_soft"},
    {"locator", "builtinassets", "meshes/locator"},
    {"locatorBox", "builtinassets", "meshes/locator_box"},
    {"locatorCircle", "builtinassets", "meshes/locator_circle"},
    {"locatorCircleOutline", "builtinassets", "meshes/locator_circle_outline"},
    {"lock", "stdassets", "textures/lock"},
    {"logIcon", "stdassets", "textures/log_icon"},
    {"logo", "stdassets", "meshes/logo"},
    {"logo", "stdassets", "textures/logo"},
    {"logoEaster", "stdassets", "textures/logo_easter"},
    {"logoTransparent", "stdassets", "meshes/logo_transparent"},
    {"mapPreviewMask", "stdassets", "textures/map_preview_mask"},
    {"medalBronze", "stdassets", "textures/medal_bronze"},
    {"medalComplete", "stdassets", "textures/medal_complete"},
    {"medalGold", "stdassets", "textures/medal_gold"},
    {"medalSilver", "stdassets", "textures/medal_silver"},
    {"mel01", "stdassets", "audio/mel01"},
    {"mel02", "stdassets", "audio/mel02"},
    {"mel03", "stdassets", "audio/mel03"},
    {"mel04", "stdassets", "audio/mel04"},
    {"mel05", "stdassets", "audio/mel05"},
    {"mel06", "stdassets", "audio/mel06"},
    {"mel07", "stdassets", "audio/mel07"},
    {"mel08", "stdassets", "audio/mel08"},
    {"mel09", "stdassets", "audio/mel09"},
    {"mel10", "stdassets", "audio/mel10"},
    {"melColor", "stdassets", "textures/mel_color"},
    {"melColorMask", "stdassets", "textures/mel_color_mask"},
    {"melDeath01", "stdassets", "audio/mel_death01"},
    {"melFall01", "stdassets", "audio/mel_fall01"},
    {"melForeArm", "stdassets", "meshes/mel_fore_arm"},
    {"melHand", "stdassets", "meshes/mel_hand"},
    {"melHead", "stdassets", "meshes/mel_head"},
    {"melIcon", "stdassets", "textures/mel_icon"},
    {"melIconColorMask", "stdassets", "textures/mel_icon_color_mask"},
    {"melLowerLeg", "stdassets", "meshes/mel_lower_leg"},
    {"melToes", "stdassets", "meshes/mel_toes"},
    {"melTorso", "stdassets", "meshes/mel_torso"},
    {"melUpperArm", "stdassets", "meshes/mel_upper_arm"},
    {"melUpperLeg", "stdassets", "meshes/mel_upper_leg"},
    {"menuBG", "stdassets", "textures/menu_bg"},
    {"menuButton", "builtinassets", "textures/menu_button"},
    {"menuIcon", "stdassets", "textures/menu_icon"},
    {"menuMusic", "stdassets", "audio/menu_music"},
    {"merch", "stdassets", "textures/merch"},
    {"metalHit", "stdassets", "audio/metal_hit"},
    {"metalSkid", "stdassets", "audio/metal_skid"},
    {"meter", "stdassets", "textures/meter"},
    {"meterTransparent", "stdassets", "meshes/meter_transparent"},
    {"monkeyFaceLevel", "stdassets", "meshes/monkey_face_level"},
    {"monkeyFaceLevelBottom", "stdassets", "meshes/monkey_face_level_bottom"},
    {"monkeyFaceLevelBumper", "stdassets", "meshes/monkey_face_level_bumper"},
    {"monkeyFaceLevelCollide", "stdassets", "meshes/monkey_face_level_collide"},
    {"monkeyFaceLevelColor", "stdassets", "textures/monkey_face_level_color"},
    {"monkeyFacePreview", "stdassets", "textures/monkey_face_preview"},
    {"multiplayerExamples", "stdassets", "textures/multiplayer_examples"},
    {"natureBackground", "stdassets", "meshes/nature_background"},
    {"natureBackgroundCollide", "stdassets",
     "meshes/nature_background_collide"},
    {"natureBackgroundColor", "stdassets", "textures/nature_background_color"},
    {"natureBackgroundVRFill", "stdassets", "meshes/nature_background_vrfill"},
    {"neoSpazColor", "stdassets", "textures/neo_spaz_color"},
    {"neoSpazColorMask", "stdassets", "textures/neo_spaz_color_mask"},
    {"neoSpazForeArm", "stdassets", "meshes/neo_spaz_fore_arm"},
    {"neoSpazHand", "stdassets", "meshes/neo_spaz_hand"},
    {"neoSpazHead", "stdassets", "meshes/neo_spaz_head"},
    {"neoSpazIcon", "stdassets", "textures/neo_spaz_icon"},
    {"neoSpazIconColorMask", "stdassets", "textures/neo_spaz_icon_color_mask"},
    {"neoSpazLowerLeg", "stdassets", "meshes/neo_spaz_lower_leg"},
    {"neoSpazPelvis", "stdassets", "meshes/neo_spaz_pelvis"},
    {"neoSpazToes", "stdassets", "meshes/neo_spaz_toes"},
    {"neoSpazTorso", "stdassets", "meshes/neo_spaz_torso"},
    {"neoSpazUpperArm", "stdassets", "meshes/neo_spaz_upper_arm"},
    {"neoSpazUpperLeg", "stdassets", "meshes/neo_spaz_upper_leg"},
    {"nextLevelIcon", "stdassets", "textures/next_level_icon"},
    {"nice", "stdassets", "audio/nice"},
    {"ninjaAttack1", "stdassets", "audio/ninja_attack1"},
    {"ninjaAttack2", "stdassets", "audio/ninja_attack2"},
    {"ninjaAttack3", "stdassets", "audio/ninja_attack3"},
    {"ninjaAttack4", "stdassets", "audio/ninja_attack4"},
    {"ninjaAttack5", "stdassets", "audio/ninja_attack5"},
    {"ninjaAttack6", "stdassets", "audio/ninja_attack6"},
    {"ninjaAttack7", "stdassets", "audio/ninja_attack7"},
    {"ninjaColor", "stdassets", "textures/ninja_color"},
    {"ninjaColorMask", "stdassets", "textures/ninja_color_mask"},
    {"ninjaDeath1", "stdassets", "audio/ninja_death1"},
    {"ninjaFall1", "stdassets", "audio/ninja_fall1"},
    {"ninjaForeArm", "stdassets", "meshes/ninja_fore_arm"},
    {"ninjaHand", "stdassets", "meshes/ninja_hand"},
    {"ninjaHead", "stdassets", "meshes/ninja_head"},
    {"ninjaHit1", "stdassets", "audio/ninja_hit1"},
    {"ninjaHit2", "stdassets", "audio/ninja_hit2"},
    {"ninjaHit3", "stdassets", "audio/ninja_hit3"},
    {"ninjaHit4", "stdassets", "audio/ninja_hit4"},
    {"ninjaHit5", "stdassets", "audio/ninja_hit5"},
    {"ninjaHit6", "stdassets", "audio/ninja_hit6"},
    {"ninjaHit7", "stdassets", "audio/ninja_hit7"},
    {"ninjaHit8", "stdassets", "audio/ninja_hit8"},
    {"ninjaIcon", "stdassets", "textures/ninja_icon"},
    {"ninjaIconColorMask", "stdassets", "textures/ninja_icon_color_mask"},
    {"ninjaLowerLeg", "stdassets", "meshes/ninja_lower_leg"},
    {"ninjaPelvis", "stdassets", "meshes/ninja_pelvis"},
    {"ninjaToes", "stdassets", "meshes/ninja_toes"},
    {"ninjaTorso", "stdassets", "meshes/ninja_torso"},
    {"ninjaUpperArm", "stdassets", "meshes/ninja_upper_arm"},
    {"ninjaUpperLeg", "stdassets", "meshes/ninja_upper_leg"},
    {"nub", "builtinassets", "textures/nub"},
    {"null", "stdassets", "textures/null"},
    {"oldLady1", "stdassets", "audio/old_lady1"},
    {"oldLady2", "stdassets", "audio/old_lady2"},
    {"oldLady3", "stdassets", "audio/old_lady3"},
    {"oldLady4", "stdassets", "audio/old_lady4"},
    {"oldLadyColor", "stdassets", "textures/old_lady_color"},
    {"oldLadyColorMask", "stdassets", "textures/old_lady_color_mask"},
    {"oldLadyDeath", "stdassets", "audio/old_lady_death"},
    {"oldLadyFall", "stdassets", "audio/old_lady_fall"},
    {"oldLadyForeArm", "stdassets", "meshes/old_lady_fore_arm"},
    {"oldLadyHand", "stdassets", "meshes/old_lady_hand"},
    {"oldLadyHead", "stdassets", "meshes/old_lady_head"},
    {"oldLadyHit1", "stdassets", "audio/old_lady_hit1"},
    {"oldLadyHit2", "stdassets", "audio/old_lady_hit2"},
    {"oldLadyIcon", "stdassets", "textures/old_lady_icon"},
    {"oldLadyIconColorMask", "stdassets", "textures/old_lady_icon_color_mask"},
    {"oldLadyLowerLeg", "stdassets", "meshes/old_lady_lower_leg"},
    {"oldLadyPelvis", "stdassets", "meshes/old_lady_pelvis"},
    {"oldLadyToes", "stdassets", "meshes/old_lady_toes"},
    {"oldLadyTorso", "stdassets", "meshes/old_lady_torso"},
    {"oldLadyUpperArm", "stdassets", "meshes/old_lady_upper_arm"},
    {"oldLadyUpperLeg", "stdassets", "meshes/old_lady_upper_leg"},
    {"ooh", "stdassets", "audio/ooh"},
    {"operaSinger1", "stdassets", "audio/opera_singer1"},
    {"operaSinger2", "stdassets", "audio/opera_singer2"},
    {"operaSinger3", "stdassets", "audio/opera_singer3"},
    {"operaSinger4", "stdassets", "audio/opera_singer4"},
    {"operaSingerColor", "stdassets", "textures/opera_singer_color"},
    {"operaSingerColorMask", "stdassets", "textures/opera_singer_color_mask"},
    {"operaSingerDeath", "stdassets", "audio/opera_singer_death"},
    {"operaSingerFall", "stdassets", "audio/opera_singer_fall"},
    {"operaSingerForeArm", "stdassets", "meshes/opera_singer_fore_arm"},
    {"operaSingerHand", "stdassets", "meshes/opera_singer_hand"},
    {"operaSingerHead", "stdassets", "meshes/opera_singer_head"},
    {"operaSingerHit1", "stdassets", "audio/opera_singer_hit1"},
    {"operaSingerHit2", "stdassets", "audio/opera_singer_hit2"},
    {"operaSingerIcon", "stdassets", "textures/opera_singer_icon"},
    {"operaSingerIconColorMask", "stdassets",
     "textures/opera_singer_icon_color_mask"},
    {"operaSingerLowerLeg", "stdassets", "meshes/opera_singer_lower_leg"},
    {"operaSingerPelvis", "stdassets", "meshes/opera_singer_pelvis"},
    {"operaSingerToes", "stdassets", "meshes/opera_singer_toes"},
    {"operaSingerTorso", "stdassets", "meshes/opera_singer_torso"},
    {"operaSingerUpperArm", "stdassets", "meshes/opera_singer_upper_arm"},
    {"operaSingerUpperLeg", "stdassets", "meshes/opera_singer_upper_leg"},
    {"orchestraHit", "stdassets", "audio/orchestra_hit"},
    {"orchestraHit2", "stdassets", "audio/orchestra_hit2"},
    {"orchestraHit3", "stdassets", "audio/orchestra_hit3"},
    {"orchestraHit4", "stdassets", "audio/orchestra_hit4"},
    {"orchestraHitBig1", "stdassets", "audio/orchestra_hit_big1"},
    {"orchestraHitBig2", "stdassets", "audio/orchestra_hit_big2"},
    {"ouyaAButton", "builtinassets", "textures/ouya_abutton"},
    {"ouyaIcon", "stdassets", "textures/ouya_icon"},
    {"ouyaOButton", "stdassets", "textures/ouya_obutton"},
    {"ouyaUButton", "stdassets", "textures/ouya_ubutton"},
    {"ouyaYButton", "stdassets", "textures/ouya_ybutton"},
    {"overlayGuide", "builtinassets", "meshes/overlay_guide"},
    {"pageLeftRight", "builtinassets", "textures/page_left_right"},
    {"penguin1", "stdassets", "audio/penguin1"},
    {"penguin2", "stdassets", "audio/penguin2"},
    {"penguin3", "stdassets", "audio/penguin3"},
    {"penguin4", "stdassets", "audio/penguin4"},
    {"penguinColor", "stdassets", "textures/penguin_color"},
    {"penguinColorMask", "stdassets", "textures/penguin_color_mask"},
    {"penguinDeath", "stdassets", "audio/penguin_death"},
    {"penguinFall", "stdassets", "audio/penguin_fall"},
    {"penguinForeArm", "stdassets", "meshes/penguin_fore_arm"},
    {"penguinHand", "stdassets", "meshes/penguin_hand"},
    {"penguinHead", "stdassets", "meshes/penguin_head"},
    {"penguinHit1", "stdassets", "audio/penguin_hit1"},
    {"penguinHit2", "stdassets", "audio/penguin_hit2"},
    {"penguinIcon", "stdassets", "textures/penguin_icon"},
    {"penguinIconColorMask", "stdassets", "textures/penguin_icon_color_mask"},
    {"penguinLowerLeg", "stdassets", "meshes/penguin_lower_leg"},
    {"penguinPelvis", "stdassets", "meshes/penguin_pelvis"},
    {"penguinToes", "stdassets", "meshes/penguin_toes"},
    {"penguinTorso", "stdassets", "meshes/penguin_torso"},
    {"penguinUpperArm", "stdassets", "meshes/penguin_upper_arm"},
    {"penguinUpperLeg", "stdassets", "meshes/penguin_upper_leg"},
    {"pixie1", "stdassets", "audio/pixie1"},
    {"pixie2", "stdassets", "audio/pixie2"},
    {"pixie3", "stdassets", "audio/pixie3"},
    {"pixie4", "stdassets", "audio/pixie4"},
    {"pixieColor", "stdassets", "textures/pixie_color"},
    {"pixieColorMask", "stdassets", "textures/pixie_color_mask"},
    {"pixieDeath", "stdassets", "audio/pixie_death"},
    {"pixieFall", "stdassets", "audio/pixie_fall"},
    {"pixieForeArm", "stdassets", "meshes/pixie_fore_arm"},
    {"pixieHand", "stdassets", "meshes/pixie_hand"},
    {"pixieHead", "stdassets", "meshes/pixie_head"},
    {"pixieHit1", "stdassets", "audio/pixie_hit1"},
    {"pixieHit2", "stdassets", "audio/pixie_hit2"},
    {"pixieIcon", "stdassets", "textures/pixie_icon"},
    {"pixieIconColorMask", "stdassets", "textures/pixie_icon_color_mask"},
    {"pixieLowerLeg", "stdassets", "meshes/pixie_lower_leg"},
    {"pixiePelvis", "stdassets", "meshes/pixie_pelvis"},
    {"pixieToes", "stdassets", "meshes/pixie_toes"},
    {"pixieTorso", "stdassets", "meshes/pixie_torso"},
    {"pixieUpperArm", "stdassets", "meshes/pixie_upper_arm"},
    {"pixieUpperLeg", "stdassets", "meshes/pixie_upper_leg"},
    {"plasticEyesTransparent", "stdassets", "meshes/plastic_eyes_transparent"},
    {"playerDeath", "stdassets", "audio/player_death"},
    {"playerLeft", "stdassets", "audio/player_left"},
    {"playerLineup", "stdassets", "textures/player_lineup"},
    {"playerLineup1Transparent", "stdassets",
     "meshes/player_lineup1_transparent"},
    {"playerLineup2Transparent", "stdassets",
     "meshes/player_lineup2_transparent"},
    {"playerLineup3Transparent", "stdassets",
     "meshes/player_lineup3_transparent"},
    {"playerLineup4Transparent", "stdassets",
     "meshes/player_lineup4_transparent"},
    {"plusButton", "stdassets", "textures/plus_button"},
    {"pop01", "stdassets", "audio/pop01"},
    {"powerdown01", "builtinassets", "audio/powerdown01"},
    {"powerup", "stdassets", "meshes/powerup"},
    {"powerup01", "stdassets", "audio/powerup01"},
    {"powerupBomb", "stdassets", "textures/powerup_bomb"},
    {"powerupCurse", "stdassets", "textures/powerup_curse"},
    {"powerupHealth", "stdassets", "textures/powerup_health"},
    {"powerupIceBombs", "stdassets", "textures/powerup_ice_bombs"},
    {"powerupImpactBombs", "stdassets", "textures/powerup_impact_bombs"},
    {"powerupLandMines", "stdassets", "textures/powerup_land_mines"},
    {"powerupPunch", "stdassets", "textures/powerup_punch"},
    {"powerupShield", "stdassets", "textures/powerup_shield"},
    {"powerupSimple", "stdassets", "meshes/powerup_simple"},
    {"powerupSpeed", "stdassets", "textures/powerup_speed"},
    {"powerupStickyBombs", "stdassets", "textures/powerup_sticky_bombs"},
    {"puck", "stdassets", "meshes/puck"},
    {"puckColor", "stdassets", "textures/puck_color"},
    {"punch01", "builtinassets", "audio/punch01"},
    {"punchStrong01", "stdassets", "audio/punch_strong01"},
    {"punchStrong02", "stdassets", "audio/punch_strong02"},
    {"punchSwish", "stdassets", "audio/punch_swish"},
    {"punchWeak01", "stdassets", "audio/punch_weak01"},
    {"quoteBubble", "stdassets", "textures/quote_bubble"},
    {"raceBeep1", "stdassets", "audio/race_beep1"},
    {"raceBeep2", "stdassets", "audio/race_beep2"},
    {"rampageBG", "stdassets", "meshes/rampage_bg"},
    {"rampageBG2", "stdassets", "meshes/rampage_bg2"},
    {"rampageBGColor", "stdassets", "textures/rampage_bgcolor"},
    {"rampageBGColor2", "stdassets", "textures/rampage_bgcolor2"},
    {"rampageBumper", "stdassets", "meshes/rampage_bumper"},
    {"rampageLevel", "stdassets", "meshes/rampage_level"},
    {"rampageLevelBottom", "stdassets", "meshes/rampage_level_bottom"},
    {"rampageLevelCollide", "stdassets", "meshes/rampage_level_collide"},
    {"rampageLevelColor", "stdassets", "textures/rampage_level_color"},
    {"rampagePreview", "stdassets", "textures/rampage_preview"},
    {"rampageVRFill", "stdassets", "meshes/rampage_vrfill"},
    {"refWhistle", "stdassets", "audio/ref_whistle"},
    {"replayIcon", "stdassets", "textures/replay_icon"},
    {"revUp", "stdassets", "audio/rev_up"},
    {"rgbStripes", "builtinassets", "textures/rgb_stripes"},
    {"rightButton", "stdassets", "textures/right_button"},
    {"robot1", "stdassets", "audio/robot1"},
    {"robot2", "stdassets", "audio/robot2"},
    {"robot3", "stdassets", "audio/robot3"},
    {"robot4", "stdassets", "audio/robot4"},
    {"robotColor", "stdassets", "textures/robot_color"},
    {"robotColorMask", "stdassets", "textures/robot_color_mask"},
    {"robotDeath", "stdassets", "audio/robot_death"},
    {"robotFall", "stdassets", "audio/robot_fall"},
    {"robotForeArm", "stdassets", "meshes/robot_fore_arm"},
    {"robotHand", "stdassets", "meshes/robot_hand"},
    {"robotHead", "stdassets", "meshes/robot_head"},
    {"robotHit1", "stdassets", "audio/robot_hit1"},
    {"robotHit2", "stdassets", "audio/robot_hit2"},
    {"robotIcon", "stdassets", "textures/robot_icon"},
    {"robotIconColorMask", "stdassets", "textures/robot_icon_color_mask"},
    {"robotLowerLeg", "stdassets", "meshes/robot_lower_leg"},
    {"robotPelvis", "stdassets", "meshes/robot_pelvis"},
    {"robotToes", "stdassets", "meshes/robot_toes"},
    {"robotTorso", "stdassets", "meshes/robot_torso"},
    {"robotUpperArm", "stdassets", "meshes/robot_upper_arm"},
    {"robotUpperLeg", "stdassets", "meshes/robot_upper_leg"},
    {"roundaboutLevel", "stdassets", "meshes/roundabout_level"},
    {"roundaboutLevelBottom", "stdassets", "meshes/roundabout_level_bottom"},
    {"roundaboutLevelBumper", "stdassets", "meshes/roundabout_level_bumper"},
    {"roundaboutLevelCollide", "stdassets", "meshes/roundabout_level_collide"},
    {"roundaboutLevelColor", "stdassets", "textures/roundabout_level_color"},
    {"roundaboutPreview", "stdassets", "textures/roundabout_preview"},
    {"runAwayMusic", "stdassets", "audio/run_away_music"},
    {"runningShoes", "stdassets", "meshes/running_shoes"},
    {"santa01", "stdassets", "audio/santa01"},
    {"santa02", "stdassets", "audio/santa02"},
    {"santa03", "stdassets", "audio/santa03"},
    {"santa04", "stdassets", "audio/santa04"},
    {"santa05", "stdassets", "audio/santa05"},
    {"santaColor", "stdassets", "textures/santa_color"},
    {"santaColorMask", "stdassets", "textures/santa_color_mask"},
    {"santaDeath", "stdassets", "audio/santa_death"},
    {"santaFall", "stdassets", "audio/santa_fall"},
    {"santaForeArm", "stdassets", "meshes/santa_fore_arm"},
    {"santaHand", "stdassets", "meshes/santa_hand"},
    {"santaHead", "stdassets", "meshes/santa_head"},
    {"santaHit01", "stdassets", "audio/santa_hit01"},
    {"santaHit02", "stdassets", "audio/santa_hit02"},
    {"santaHit03", "stdassets", "audio/santa_hit03"},
    {"santaHit04", "stdassets", "audio/santa_hit04"},
    {"santaIcon", "stdassets", "textures/santa_icon"},
    {"santaIconColorMask", "stdassets", "textures/santa_icon_color_mask"},
    {"santaLowerLeg", "stdassets", "meshes/santa_lower_leg"},
    {"santaToes", "stdassets", "meshes/santa_toes"},
    {"santaTorso", "stdassets", "meshes/santa_torso"},
    {"santaUpperArm", "stdassets", "meshes/santa_upper_arm"},
    {"santaUpperLeg", "stdassets", "meshes/santa_upper_leg"},
    {"scamper01", "stdassets", "audio/scamper01"},
    {"scaryMusic", "stdassets", "audio/scary_music"},
    {"scorch", "builtinassets", "meshes/scorch"},
    {"scorch", "builtinassets", "textures/scorch"},
    {"scorchBig", "builtinassets", "textures/scorch_big"},
    {"score", "stdassets", "audio/score"},
    {"scoreHit01", "stdassets", "audio/score_hit01"},
    {"scoreHit02", "stdassets", "audio/score_hit02"},
    {"scoreIncrease", "builtinassets", "audio/score_increase"},
    {"scoresEpicMusic", "stdassets", "audio/scores_epic_music"},
    {"scrollBarThumbOpaque", "builtinassets", "meshes/scroll_bar_thumb_opaque"},
    {"scrollBarThumbShortOpaque", "builtinassets",
     "meshes/scroll_bar_thumb_short_opaque"},
    {"scrollBarThumbShortSimple", "builtinassets",
     "meshes/scroll_bar_thumb_short_simple"},
    {"scrollBarThumbShortTransparent", "builtinassets",
     "meshes/scroll_bar_thumb_short_transparent"},
    {"scrollBarThumbSimple", "builtinassets", "meshes/scroll_bar_thumb_simple"},
    {"scrollBarThumbTransparent", "builtinassets",
     "meshes/scroll_bar_thumb_transparent"},
    {"scrollBarTroughTransparent", "builtinassets",
     "meshes/scroll_bar_trough_transparent"},
    {"scrollWidget", "builtinassets", "textures/scroll_widget"},
    {"scrollWidgetGlow", "builtinassets", "textures/scroll_widget_glow"},
    {"scrollWidgetShort", "stdassets", "meshes/scroll_widget_short"},
    {"settingsIcon", "stdassets", "textures/settings_icon"},
    {"shadow", "builtinassets", "textures/shadow"},
    {"shadowSharp", "builtinassets", "textures/shadow_sharp"},
    {"shadowSoft", "builtinassets", "textures/shadow_soft"},
    {"shatter", "stdassets", "audio/shatter"},
    {"shield", "builtinassets", "meshes/shield"},
    {"shield", "builtinassets", "textures/shield"},
    {"shieldDown", "stdassets", "audio/shield_down"},
    {"shieldHit", "stdassets", "audio/shield_hit"},
    {"shieldUp", "stdassets", "audio/shield_up"},
    {"shockWave", "builtinassets", "meshes/shock_wave"},
    {"shrapnel1", "builtinassets", "meshes/shrapnel1"},
    {"shrapnel1Color", "builtinassets", "textures/shrapnel1_color"},
    {"shrapnelBoard", "builtinassets", "meshes/shrapnel_board"},
    {"shrapnelSlime", "builtinassets", "meshes/shrapnel_slime"},
    {"skid01", "stdassets", "audio/skid01"},
    {"slash", "stdassets", "textures/slash"},
    {"slowEpicMusic", "stdassets", "audio/slow_epic_music"},
    {"smoke", "builtinassets", "textures/smoke"},
    {"softEdgeInside", "builtinassets", "meshes/soft_edge_inside"},
    {"softEdgeOutside", "builtinassets", "meshes/soft_edge_outside"},
    {"softRect", "builtinassets", "textures/soft_rect"},
    {"softRect2", "builtinassets", "textures/soft_rect2"},
    {"softRectVertical", "builtinassets", "textures/soft_rect_vertical"},
    {"sparkle01", "builtinassets", "audio/sparkle01"},
    {"sparkle02", "builtinassets", "audio/sparkle02"},
    {"sparkle03", "builtinassets", "audio/sparkle03"},
    {"sparks", "builtinassets", "textures/sparks"},
    {"spawn", "stdassets", "audio/spawn"},
    {"spazAttack01", "stdassets", "audio/spaz_attack01"},
    {"spazAttack02", "stdassets", "audio/spaz_attack02"},
    {"spazAttack03", "stdassets", "audio/spaz_attack03"},
    {"spazAttack04", "stdassets", "audio/spaz_attack04"},
    {"spazDeath01", "stdassets", "audio/spaz_death01"},
    {"spazEff", "stdassets", "audio/spaz_eff"},
    {"spazFall01", "stdassets", "audio/spaz_fall01"},
    {"spazImpact01", "stdassets", "audio/spaz_impact01"},
    {"spazImpact02", "stdassets", "audio/spaz_impact02"},
    {"spazImpact03", "stdassets", "audio/spaz_impact03"},
    {"spazImpact04", "stdassets", "audio/spaz_impact04"},
    {"spazJump01", "stdassets", "audio/spaz_jump01"},
    {"spazJump02", "stdassets", "audio/spaz_jump02"},
    {"spazJump03", "stdassets", "audio/spaz_jump03"},
    {"spazJump04", "stdassets", "audio/spaz_jump04"},
    {"spazOw", "stdassets", "audio/spaz_ow"},
    {"spazPickup01", "stdassets", "audio/spaz_pickup01"},
    {"spazScream01", "stdassets", "audio/spaz_scream01"},
    {"spinner", "builtinassets", "textures/spinner"},
    {"spinner0", "builtinassets", "textures/spinner0"},
    {"spinner1", "builtinassets", "textures/spinner1"},
    {"spinner10", "builtinassets", "textures/spinner10"},
    {"spinner11", "builtinassets", "textures/spinner11"},
    {"spinner2", "builtinassets", "textures/spinner2"},
    {"spinner3", "builtinassets", "textures/spinner3"},
    {"spinner4", "builtinassets", "textures/spinner4"},
    {"spinner5", "builtinassets", "textures/spinner5"},
    {"spinner6", "builtinassets", "textures/spinner6"},
    {"spinner7", "builtinassets", "textures/spinner7"},
    {"spinner8", "builtinassets", "textures/spinner8"},
    {"spinner9", "builtinassets", "textures/spinner9"},
    {"splatter", "stdassets", "audio/splatter"},
    {"sportsMusic", "stdassets", "audio/sports_music"},
    {"star", "stdassets", "textures/star"},
    {"startButton", "builtinassets", "textures/start_button"},
    {"stepRightUpLevel", "stdassets", "meshes/step_right_up_level"},
    {"stepRightUpLevelBottom", "stdassets",
     "meshes/step_right_up_level_bottom"},
    {"stepRightUpLevelCollide", "stdassets",
     "meshes/step_right_up_level_collide"},
    {"stepRightUpLevelColor", "stdassets",
     "textures/step_right_up_level_color"},
    {"stepRightUpPreview", "stdassets", "textures/step_right_up_preview"},
    {"stepRightUpVRFillMound", "stdassets",
     "meshes/step_right_up_vrfill_mound"},
    {"stickyImpact", "stdassets", "audio/sticky_impact"},
    {"storeCharacter", "stdassets", "textures/store_character"},
    {"storeCharacterEaster", "stdassets", "textures/store_character_easter"},
    {"storeCharacterXmas", "stdassets", "textures/store_character_xmas"},
    {"storeIcon", "stdassets", "textures/store_icon"},
    {"superPunch", "stdassets", "audio/super_punch"},
    {"superhero1", "stdassets", "audio/superhero1"},
    {"superhero2", "stdassets", "audio/superhero2"},
    {"superhero3", "stdassets", "audio/superhero3"},
    {"superhero4", "stdassets", "audio/superhero4"},
    {"superheroColor", "stdassets", "textures/superhero_color"},
    {"superheroColorMask", "stdassets", "textures/superhero_color_mask"},
    {"superheroDeath", "stdassets", "audio/superhero_death"},
    {"superheroFall", "stdassets", "audio/superhero_fall"},
    {"superheroForeArm", "stdassets", "meshes/superhero_fore_arm"},
    {"superheroHand", "stdassets", "meshes/superhero_hand"},
    {"superheroHead", "stdassets", "meshes/superhero_head"},
    {"superheroHit1", "stdassets", "audio/superhero_hit1"},
    {"superheroHit2", "stdassets", "audio/superhero_hit2"},
    {"superheroIcon", "stdassets", "textures/superhero_icon"},
    {"superheroIconColorMask", "stdassets",
     "textures/superhero_icon_color_mask"},
    {"superheroLowerLeg", "stdassets", "meshes/superhero_lower_leg"},
    {"superheroPelvis", "stdassets", "meshes/superhero_pelvis"},
    {"superheroToes", "stdassets", "meshes/superhero_toes"},
    {"superheroTorso", "stdassets", "meshes/superhero_torso"},
    {"superheroUpperArm", "stdassets", "meshes/superhero_upper_arm"},
    {"superheroUpperLeg", "stdassets", "meshes/superhero_upper_leg"},
    {"survivalMusic", "stdassets", "audio/survival_music"},
    {"swip", "stdassets", "audio/swip"},
    {"swip2", "stdassets", "audio/swip2"},
    {"swish", "builtinassets", "audio/swish"},
    {"swish2", "builtinassets", "audio/swish2"},
    {"swish3", "builtinassets", "audio/swish3"},
    {"tap", "builtinassets", "audio/tap"},
    {"technoHit01", "stdassets", "audio/techno_hit01"},
    {"textBoxTransparent", "builtinassets", "meshes/text_box_transparent"},
    {"textClearButton", "builtinassets", "textures/text_clear_button"},
    {"thePadBG", "stdassets", "meshes/the_pad_bg"},
    {"thePadBGSmall", "stdassets", "meshes/the_pad_bgsmall"},
    {"thePadLevel", "stdassets", "meshes/the_pad_level"},
    {"thePadLevelBottom", "stdassets", "meshes/the_pad_level_bottom"},
    {"thePadLevelBumper", "stdassets", "meshes/the_pad_level_bumper"},
    {"thePadLevelCollide", "stdassets", "meshes/the_pad_level_collide"},
    {"thePadLevelColor", "stdassets", "textures/the_pad_level_color"},
    {"thePadPreview", "stdassets", "textures/the_pad_preview"},
    {"thePadVRFillBottom", "stdassets", "meshes/the_pad_vrfill_bottom"},
    {"thePadVRFillMound", "stdassets", "meshes/the_pad_vrfill_mound"},
    {"thePadVRFillTop", "stdassets", "meshes/the_pad_vrfill_top"},
    {"tick", "stdassets", "audio/tick"},
    {"ticketRoll", "stdassets", "textures/ticket_roll"},
    {"ticketRollBig", "stdassets", "textures/ticket_roll_big"},
    {"ticketRolls", "stdassets", "textures/ticket_rolls"},
    {"tickets", "stdassets", "textures/tickets"},
    {"ticketsMore", "stdassets", "textures/tickets_more"},
    {"ticketsPurple", "stdassets", "textures/tickets_purple"},
    {"ticking", "stdassets", "audio/ticking"},
    {"tickingCrazy", "builtinassets", "audio/ticking_crazy"},
    {"tipTopBG", "stdassets", "meshes/tip_top_bg"},
    {"tipTopBGColor", "stdassets", "textures/tip_top_bgcolor"},
    {"tipTopLevel", "stdassets", "meshes/tip_top_level"},
    {"tipTopLevelBottom", "stdassets", "meshes/tip_top_level_bottom"},
    {"tipTopLevelBumper", "stdassets", "meshes/tip_top_level_bumper"},
    {"tipTopLevelCollide", "stdassets", "meshes/tip_top_level_collide"},
    {"tipTopLevelColor", "stdassets", "textures/tip_top_level_color"},
    {"tipTopPreview", "stdassets", "textures/tip_top_preview"},
    {"tnt", "stdassets", "meshes/tnt"},
    {"tnt", "stdassets", "textures/tnt"},
    {"toTheDeathMusic", "stdassets", "audio/to_the_death_music"},
    {"tokens1", "stdassets", "textures/tokens1"},
    {"tokens2", "stdassets", "textures/tokens2"},
    {"tokens3", "stdassets", "textures/tokens3"},
    {"tokens4", "stdassets", "textures/tokens4"},
    {"toolbarBacking", "stdassets", "meshes/toolbar_backing"},
    {"toolbarBackingBottom", "stdassets", "meshes/toolbar_backing_bottom"},
    {"toolbarBackingBottom2", "stdassets", "meshes/toolbar_backing_bottom2"},
    {"toolbarBackingOpaque", "stdassets", "meshes/toolbar_backing_opaque"},
    {"toolbarBackingTop", "stdassets", "meshes/toolbar_backing_top"},
    {"toolbarBackingTop2", "stdassets", "meshes/toolbar_backing_top2"},
    {"toolbarBackingTransparent", "stdassets",
     "meshes/toolbar_backing_transparent"},
    {"touchArrows", "builtinassets", "textures/touch_arrows"},
    {"touchArrowsActions", "builtinassets", "textures/touch_arrows_actions"},
    {"towerDLevel", "stdassets", "meshes/tower_dlevel"},
    {"towerDLevelBottom", "stdassets", "meshes/tower_dlevel_bottom"},
    {"towerDLevelCollide", "stdassets", "meshes/tower_dlevel_collide"},
    {"towerDLevelColor", "stdassets", "textures/tower_dlevel_color"},
    {"towerDPlayerWall", "stdassets", "meshes/tower_dplayer_wall"},
    {"towerDPreview", "stdassets", "textures/tower_dpreview"},
    {"trashRummage", "stdassets", "audio/trash_rummage"},
    {"trees", "stdassets", "meshes/trees"},
    {"treesColor", "stdassets", "textures/trees_color"},
    {"trophy", "stdassets", "textures/trophy"},
    {"tv", "stdassets", "textures/tv"},
    {"uiAtlas", "builtinassets", "textures/ui_atlas"},
    {"uiAtlas2", "builtinassets", "textures/ui_atlas2"},
    {"upButton", "stdassets", "textures/up_button"},
    {"usersButton", "builtinassets", "textures/users_button"},
    {"victoryMusic", "stdassets", "audio/victory_music"},
    {"vrFade", "builtinassets", "meshes/vr_fade"},
    {"vrFillMound", "stdassets", "textures/vr_fill_mound"},
    {"vrOverlay", "builtinassets", "meshes/vr_overlay"},
    {"warnBeep", "stdassets", "audio/warn_beep"},
    {"warnBeeps", "stdassets", "audio/warn_beeps"},
    {"warrior1", "stdassets", "audio/warrior1"},
    {"warrior2", "stdassets", "audio/warrior2"},
    {"warrior3", "stdassets", "audio/warrior3"},
    {"warrior4", "stdassets", "audio/warrior4"},
    {"warriorColor", "stdassets", "textures/warrior_color"},
    {"warriorColorMask", "stdassets", "textures/warrior_color_mask"},
    {"warriorDeath", "stdassets", "audio/warrior_death"},
    {"warriorFall", "stdassets", "audio/warrior_fall"},
    {"warriorForeArm", "stdassets", "meshes/warrior_fore_arm"},
    {"warriorHand", "stdassets", "meshes/warrior_hand"},
    {"warriorHead", "stdassets", "meshes/warrior_head"},
    {"warriorHit1", "stdassets", "audio/warrior_hit1"},
    {"warriorHit2", "stdassets", "audio/warrior_hit2"},
    {"warriorIcon", "stdassets", "textures/warrior_icon"},
    {"warriorIconColorMask", "stdassets", "textures/warrior_icon_color_mask"},
    {"warriorLowerLeg", "stdassets", "meshes/warrior_lower_leg"},
    {"warriorPelvis", "stdassets", "meshes/warrior_pelvis"},
    {"warriorToes", "stdassets", "meshes/warrior_toes"},
    {"warriorTorso", "stdassets", "meshes/warrior_torso"},
    {"warriorUpperArm", "stdassets", "meshes/warrior_upper_arm"},
    {"warriorUpperLeg", "stdassets", "meshes/warrior_upper_leg"},
    {"whenJohnnyComesMarchingHomeMusic", "stdassets",
     "audio/when_johnny_comes_marching_home_music"},
    {"white", "builtinassets", "textures/white"},
    {"windowBGBlotch", "stdassets", "meshes/window_bgblotch"},
    {"windowBottomCap", "stdassets", "textures/window_bottom_cap"},
    {"windowHSmallVMed", "builtinassets", "textures/window_hsmall_vmed"},
    {"windowHSmallVMedOpaque", "builtinassets",
     "meshes/window_hsmall_vmed_opaque"},
    {"windowHSmallVMedTransparent", "builtinassets",
     "meshes/window_hsmall_vmed_transparent"},
    {"windowHSmallVSmall", "builtinassets", "textures/window_hsmall_vsmall"},
    {"windowHSmallVSmallOpaque", "builtinassets",
     "meshes/window_hsmall_vsmall_opaque"},
    {"windowHSmallVSmallTransparent", "builtinassets",
     "meshes/window_hsmall_vsmall_transparent"},
    {"wing", "builtinassets", "meshes/wing"},
    {"wings", "builtinassets", "textures/wings"},
    {"witch1", "stdassets", "audio/witch1"},
    {"witch2", "stdassets", "audio/witch2"},
    {"witch3", "stdassets", "audio/witch3"},
    {"witch4", "stdassets", "audio/witch4"},
    {"witchColor", "stdassets", "textures/witch_color"},
    {"witchColorMask", "stdassets", "textures/witch_color_mask"},
    {"witchDeath", "stdassets", "audio/witch_death"},
    {"witchFall", "stdassets", "audio/witch_fall"},
    {"witchForeArm", "stdassets", "meshes/witch_fore_arm"},
    {"witchHand", "stdassets", "meshes/witch_hand"},
    {"witchHead", "stdassets", "meshes/witch_head"},
    {"witchHit1", "stdassets", "audio/witch_hit1"},
    {"witchHit2", "stdassets", "audio/witch_hit2"},
    {"witchIcon", "stdassets", "textures/witch_icon"},
    {"witchIconColorMask", "stdassets", "textures/witch_icon_color_mask"},
    {"witchLowerLeg", "stdassets", "meshes/witch_lower_leg"},
    {"witchPelvis", "stdassets", "meshes/witch_pelvis"},
    {"witchToes", "stdassets", "meshes/witch_toes"},
    {"witchTorso", "stdassets", "meshes/witch_torso"},
    {"witchUpperArm", "stdassets", "meshes/witch_upper_arm"},
    {"witchUpperLeg", "stdassets", "meshes/witch_upper_leg"},
    {"wizard1", "stdassets", "audio/wizard1"},
    {"wizard2", "stdassets", "audio/wizard2"},
    {"wizard3", "stdassets", "audio/wizard3"},
    {"wizard4", "stdassets", "audio/wizard4"},
    {"wizardColor", "stdassets", "textures/wizard_color"},
    {"wizardColorMask", "stdassets", "textures/wizard_color_mask"},
    {"wizardDeath", "stdassets", "audio/wizard_death"},
    {"wizardFall", "stdassets", "audio/wizard_fall"},
    {"wizardForeArm", "stdassets", "meshes/wizard_fore_arm"},
    {"wizardHand", "stdassets", "meshes/wizard_hand"},
    {"wizardHead", "stdassets", "meshes/wizard_head"},
    {"wizardHit1", "stdassets", "audio/wizard_hit1"},
    {"wizardHit2", "stdassets", "audio/wizard_hit2"},
    {"wizardIcon", "stdassets", "textures/wizard_icon"},
    {"wizardIconColorMask", "stdassets", "textures/wizard_icon_color_mask"},
    {"wizardLowerLeg", "stdassets", "meshes/wizard_lower_leg"},
    {"wizardPelvis", "stdassets", "meshes/wizard_pelvis"},
    {"wizardToes", "stdassets", "meshes/wizard_toes"},
    {"wizardTorso", "stdassets", "meshes/wizard_torso"},
    {"wizardUpperArm", "stdassets", "meshes/wizard_upper_arm"},
    {"wizardUpperLeg", "stdassets", "meshes/wizard_upper_leg"},
    {"woo", "stdassets", "audio/woo"},
    {"woo2", "stdassets", "audio/woo2"},
    {"woo3", "stdassets", "audio/woo3"},
    {"woodDebrisFall", "stdassets", "audio/wood_debris_fall"},
    {"wow", "stdassets", "audio/wow"},
    {"wrestler1", "stdassets", "audio/wrestler1"},
    {"wrestler2", "stdassets", "audio/wrestler2"},
    {"wrestler3", "stdassets", "audio/wrestler3"},
    {"wrestler4", "stdassets", "audio/wrestler4"},
    {"wrestlerColor", "stdassets", "textures/wrestler_color"},
    {"wrestlerColorMask", "stdassets", "textures/wrestler_color_mask"},
    {"wrestlerDeath", "stdassets", "audio/wrestler_death"},
    {"wrestlerFall", "stdassets", "audio/wrestler_fall"},
    {"wrestlerForeArm", "stdassets", "meshes/wrestler_fore_arm"},
    {"wrestlerHand", "stdassets", "meshes/wrestler_hand"},
    {"wrestlerHead", "stdassets", "meshes/wrestler_head"},
    {"wrestlerHit1", "stdassets", "audio/wrestler_hit1"},
    {"wrestlerHit2", "stdassets", "audio/wrestler_hit2"},
    {"wrestlerIcon", "stdassets", "textures/wrestler_icon"},
    {"wrestlerIconColorMask", "stdassets", "textures/wrestler_icon_color_mask"},
    {"wrestlerLowerLeg", "stdassets", "meshes/wrestler_lower_leg"},
    {"wrestlerPelvis", "stdassets", "meshes/wrestler_pelvis"},
    {"wrestlerToes", "stdassets", "meshes/wrestler_toes"},
    {"wrestlerTorso", "stdassets", "meshes/wrestler_torso"},
    {"wrestlerUpperArm", "stdassets", "meshes/wrestler_upper_arm"},
    {"wrestlerUpperLeg", "stdassets", "meshes/wrestler_upper_leg"},
    {"yeah", "stdassets", "audio/yeah"},
    {"zigZagLevel", "stdassets", "meshes/zig_zag_level"},
    {"zigZagLevelBottom", "stdassets", "meshes/zig_zag_level_bottom"},
    {"zigZagLevelBumper", "stdassets", "meshes/zig_zag_level_bumper"},
    {"zigZagLevelCollide", "stdassets", "meshes/zig_zag_level_collide"},
    {"zigZagLevelColor", "stdassets", "textures/zig_zag_level_color"},
    {"zigzagPreview", "stdassets", "textures/zigzag_preview"},
    {"zoeAttack01", "stdassets", "audio/zoe_attack01"},
    {"zoeAttack02", "stdassets", "audio/zoe_attack02"},
    {"zoeAttack03", "stdassets", "audio/zoe_attack03"},
    {"zoeAttack04", "stdassets", "audio/zoe_attack04"},
    {"zoeColor", "stdassets", "textures/zoe_color"},
    {"zoeColorMask", "stdassets", "textures/zoe_color_mask"},
    {"zoeDeath01", "stdassets", "audio/zoe_death01"},
    {"zoeEff", "stdassets", "audio/zoe_eff"},
    {"zoeFall01", "stdassets", "audio/zoe_fall01"},
    {"zoeForeArm", "stdassets", "meshes/zoe_fore_arm"},
    {"zoeHand", "stdassets", "meshes/zoe_hand"},
    {"zoeHead", "stdassets", "meshes/zoe_head"},
    {"zoeIcon", "stdassets", "textures/zoe_icon"},
    {"zoeIconColorMask", "stdassets", "textures/zoe_icon_color_mask"},
    {"zoeImpact01", "stdassets", "audio/zoe_impact01"},
    {"zoeImpact02", "stdassets", "audio/zoe_impact02"},
    {"zoeImpact03", "stdassets", "audio/zoe_impact03"},
    {"zoeImpact04", "stdassets", "audio/zoe_impact04"},
    {"zoeJump01", "stdassets", "audio/zoe_jump01"},
    {"zoeJump02", "stdassets", "audio/zoe_jump02"},
    {"zoeJump03", "stdassets", "audio/zoe_jump03"},
    {"zoeLowerLeg", "stdassets", "meshes/zoe_lower_leg"},
    {"zoeOw", "stdassets", "audio/zoe_ow"},
    {"zoePelvis", "stdassets", "meshes/zoe_pelvis"},
    {"zoePickup01", "stdassets", "audio/zoe_pickup01"},
    {"zoeScream01", "stdassets", "audio/zoe_scream01"},
    {"zoeToes", "stdassets", "meshes/zoe_toes"},
    {"zoeTorso", "stdassets", "meshes/zoe_torso"},
    {"zoeUpperArm", "stdassets", "meshes/zoe_upper_arm"},
    {"zoeUpperLeg", "stdassets", "meshes/zoe_upper_leg"},
};

struct State_ {
  // '<kind>|<legacy name>' -> (package_key, logical_path), where kind
  // is the logical path's first segment ('textures', 'audio',
  // 'meshes', ...). Kind-scoped because legacy names were only unique
  // per asset type: 'shield' names both a texture and a mesh, and each
  // Get* call site knows which kind it wants.
  std::unordered_map<std::string, std::pair<std::string, std::string>>
      from_legacy;
  // 'package_key:logical_path' -> legacy name.
  std::unordered_map<std::string, std::string> to_legacy;
  // package_key -> registered full apverid.
  std::unordered_map<std::string, std::string> package_versions;
  // Versionless apverid prefix ('a-0.babuiltinassets') -> package_key.
  std::unordered_map<std::string, std::string> versionless_to_key;
};

static auto GetState_() -> State_& {
  static State_* state = [] {
    auto* st = new State_();
    for (const Row_& row : kRows) {
      std::string logical(row.logical_path);
      std::string kind = logical.substr(0, logical.find('/'));
      st->from_legacy[kind + "|" + row.legacy] = {row.package_key,
                                                  row.logical_path};
      st->to_legacy[std::string(row.package_key) + ":" + row.logical_path] =
          row.legacy;
    }
    return st;
  }();
  return *state;
}

// Strip the trailing version segment off an apverid
// ('a-0.babuiltinassets.dev260610e' -> 'a-0.babuiltinassets').
static auto VersionlessApverid_(const std::string& apverid) -> std::string {
  size_t pos = apverid.rfind('.');
  return pos == std::string::npos ? apverid : apverid.substr(0, pos);
}

void AssetNameCompat::SetPackageVersion(const std::string& package_key,
                                        const std::string& apverid) {
  assert(g_base->InLogicThread());
  auto& state = GetState_();
  // Drop any versionless mapping from a previous registration.
  auto old = state.package_versions.find(package_key);
  if (old != state.package_versions.end()) {
    state.versionless_to_key.erase(VersionlessApverid_(old->second));
  }
  state.package_versions[package_key] = apverid;
  state.versionless_to_key[VersionlessApverid_(apverid)] = package_key;
}

auto AssetNameCompat::FromLegacy(const std::string& name, const char* kind)
    -> std::string {
  assert(g_base->InLogicThread());
  if (name.find(':') != std::string::npos) {
    return name;  // Already qualified.
  }
  auto& state = GetState_();
  auto row = state.from_legacy.find(std::string(kind) + "|" + name);
  if (row == state.from_legacy.end()) {
    return name;  // No asset-package home; a true legacy name.
  }
  auto version = state.package_versions.find(row->second.first);
  if (version == state.package_versions.end()) {
    return name;  // Package version not registered (yet).
  }
  std::string mapped = version->second + ":" + row->second.second;
  g_core->logging->Log(
      LogName::kBaAssets, LogLevel::kDebug,
      "AssetNameCompat: from-legacy '" + name + "' -> '" + mapped + "'.");
  return mapped;
}

auto AssetNameCompat::ToLegacy(const std::string& name) -> std::string {
  assert(g_base->InLogicThread());
  size_t colon = name.find(':');
  if (colon == std::string::npos) {
    return name;  // Already a bare name.
  }
  auto& state = GetState_();
  auto key =
      state.versionless_to_key.find(VersionlessApverid_(name.substr(0, colon)));
  if (key == state.versionless_to_key.end()) {
    return name;  // Not a package we know about.
  }
  auto legacy =
      state.to_legacy.find(key->second + ":" + name.substr(colon + 1));
  if (legacy == state.to_legacy.end()) {
    return name;
  }
  g_core->logging->Log(
      LogName::kBaAssets, LogLevel::kDebug,
      "AssetNameCompat: to-legacy '" + name + "' -> '" + legacy->second + "'.");
  return legacy->second;
}

}  // namespace ballistica::base
