// Released under the MIT License. See LICENSE for details.
//
// AUTOGENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by ``tools/pcommand gen_builtin_asset_ids`` (run by
// ``assetpins`` when the construct asset-package pin in
// ``pconfig/projectconfig.json`` changes) from that pin's asset
// listing. Rerun ``make assetpins-latest`` to regenerate.

#include "ballistica/base/assets/builtin_strings.h"

#include <memory>
#include <utility>
#include <vector>

#include "ballistica/base/support/lang_str.h"

namespace ballistica::base {

static auto MakeResource_(const char* name,
                          std::vector<LangStr::SubEntry> subs = {})
    -> std::shared_ptr<const LangStr> {
  auto out = std::make_shared<LangStr>();
  out->form = LangStr::Form::kResource;
  out->apverid = kBuiltinAssetsApverid;
  out->name = name;
  out->subs = std::move(subs);
  return out;
}

auto BuiltinStrings::Assets::AccessDeniedGuidance(LangStr::Sub detail)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/access_denied_guidance",
                       {{"detail", std::move(detail)}});
}

auto BuiltinStrings::Assets::Authenticating()
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/authenticating");
}

auto BuiltinStrings::Assets::BuildingAssets(int64_t count, LangStr::Sub package)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/building_assets",
                       {{"count", count}, {"package", std::move(package)}});
}

auto BuiltinStrings::Assets::ClientTooOld() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/client_too_old");
}

auto BuiltinStrings::Assets::ContentErrorGuidance(LangStr::Sub detail)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/content_error_guidance",
                       {{"detail", std::move(detail)}});
}

auto BuiltinStrings::Assets::DownloadingAssets(int64_t count)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/downloading_assets", {{"count", count}});
}

auto BuiltinStrings::Assets::LoadError() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/load_error");
}

auto BuiltinStrings::Assets::PreparingBuild(LangStr::Sub package)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/preparing_build",
                       {{"package", std::move(package)}});
}

auto BuiltinStrings::Assets::SignInFailed() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/sign_in_failed");
}

auto BuiltinStrings::Assets::SignInNeededBrowser(LangStr::Sub address)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/sign_in_needed_browser",
                       {{"address", std::move(address)}});
}

auto BuiltinStrings::Assets::SignInNeededOtherDevice(LangStr::Sub address)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/sign_in_needed_other_device",
                       {{"address", std::move(address)}});
}

auto BuiltinStrings::Assets::SigningIn() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/assets/signing_in");
}

auto BuiltinStrings::Audio::MusicPlayError(LangStr::Sub music)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/audio/music_play_error",
                       {{"music", std::move(music)}});
}

auto BuiltinStrings::Input::Axis(LangStr::Sub number)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/axis", {{"number", std::move(number)}});
}

auto BuiltinStrings::Input::Button(LangStr::Sub number)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/button", {{"number", std::move(number)}});
}

auto BuiltinStrings::Input::ControllerConnected(LangStr::Sub controller)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/controller_connected",
                       {{"controller", std::move(controller)}});
}

auto BuiltinStrings::Input::ControllerDetected()
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/controller_detected");
}

auto BuiltinStrings::Input::ControllerDisconnected(LangStr::Sub controller)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/controller_disconnected",
                       {{"controller", std::move(controller)}});
}

auto BuiltinStrings::Input::ControllerReconnected(LangStr::Sub controller)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/controller_reconnected",
                       {{"controller", std::move(controller)}});
}

auto BuiltinStrings::Input::ControllersConnected(int64_t count)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/controllers_connected",
                       {{"count", count}});
}

auto BuiltinStrings::Input::ControllersDetected(int64_t count)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/controllers_detected",
                       {{"count", count}});
}

auto BuiltinStrings::Input::ControllersDisconnected(int64_t count)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/controllers_disconnected",
                       {{"count", count}});
}

auto BuiltinStrings::Input::Keyboard() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/keyboard");
}

auto BuiltinStrings::Input::TouchScreen() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/touch_screen");
}

auto BuiltinStrings::Input::TouchScreenJoinWarning()
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/touch_screen_join_warning");
}

auto BuiltinStrings::Input::VrOrientationReset()
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/input/vr_orientation_reset");
}

auto BuiltinStrings::Net::AccountRejected() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/net/account_rejected");
}

auto BuiltinStrings::Net::AuthError() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/net/auth_error");
}

auto BuiltinStrings::Net::IncorrectPassword()
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/net/incorrect_password");
}

auto BuiltinStrings::Net::InvalidAddress() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/net/invalid_address");
}

auto BuiltinStrings::Net::MustSignIn() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/net/must_sign_in");
}

auto BuiltinStrings::Net::UnavailableNoConnection()
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/net/unavailable_no_connection");
}

auto BuiltinStrings::Replay::ReadError() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/replay/read_error");
}

auto BuiltinStrings::Replay::VersionError() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/replay/version_error");
}

auto BuiltinStrings::Session::KickIdleKicked(LangStr::Sub name)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/session/kick_idle_kicked",
                       {{"name", std::move(name)}});
}

auto BuiltinStrings::Session::KickIdleWarning(int64_t seconds,
                                              LangStr::Sub name)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/session/kick_idle_warning",
                       {{"seconds", seconds}, {"name", std::move(name)}});
}

auto BuiltinStrings::Session::KickIdleWarningSettings()
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/session/kick_idle_warning_settings");
}

auto BuiltinStrings::Ui::ArrowsToExitList(LangStr::Sub left, LangStr::Sub right)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_(
      "strings/ui/arrows_to_exit_list",
      {{"left", std::move(left)}, {"right", std::move(right)}});
}

auto BuiltinStrings::Ui::Cancel() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/cancel");
}

auto BuiltinStrings::Ui::Error() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/error");
}

auto BuiltinStrings::Ui::HasMenuControl(LangStr::Sub name)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/has_menu_control",
                       {{"name", std::move(name)}});
}

auto BuiltinStrings::Ui::MenuControlTimeOut(int64_t seconds)
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/menu_control_time_out",
                       {{"seconds", seconds}});
}

auto BuiltinStrings::Ui::MenuControlWillTimeOut()
    -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/menu_control_will_time_out");
}

auto BuiltinStrings::Ui::Ok() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/ok");
}

auto BuiltinStrings::Ui::Retry() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/retry");
}

auto BuiltinStrings::Ui::SignIn() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/sign_in");
}

auto BuiltinStrings::Ui::Updating() -> std::shared_ptr<const LangStr> {
  return MakeResource_("strings/ui/updating");
}

}  // namespace ballistica::base
