// Released under the MIT License. See LICENSE for details.

#ifndef BALLISTICA_BASE_ASSETS_BUILTIN_STRINGS_H_
#define BALLISTICA_BASE_ASSETS_BUILTIN_STRINGS_H_

// AUTOGENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by ``tools/pcommand gen_builtin_asset_ids`` (run by
// ``assetpins`` when the construct asset-package pin in
// ``pconfig/projectconfig.json`` changes) from that pin's asset
// listing. Rerun ``make assetpins-latest`` to regenerate.
//
// Generated from: "a-0.babuiltinassets.260831f"

#include <memory>

#include "ballistica/base/base.h"
#include "ballistica/base/support/lang_str.h"

namespace ballistica::base {

/// Typed accessors for the language-strings shipped in the
/// builtin asset package (strings-asset-migration decision D22).
/// Each accessor mirrors one `.bstr` source in the package
/// (nested classes mirror its dir tree; classes stand in for
/// namespaces per the one-namespace-per-featureset rule) and
/// builds a resource-form LangStr addressing that string in the
/// pinned builtin package (kBuiltinAssetsApverid), with any
/// parameters attached as keyword substitutions.
///
/// The returned values hold tokens, not text: call Evaluate() at
/// the point flat display text is needed (it resolves against
/// the current locale's native tables and re-runs correctly
/// after a language switch). Values are immutable and may be
/// built, held, and evaluated from any thread.
class BuiltinStrings {
 public:
  class Account {
   public:
    /// Error screen-message shown to a player who attempts to join a party or
    /// server that requires account authentication while they are not signed in
    /// to an account.
    ///
    /// English: "You must sign in to do this."
    static auto MustSignIn() -> std::shared_ptr<const LangStr>;

    /// Notice that a platform account is being ignored.
    ///
    /// English: "Note: Ignoring that {service} account. Go to 'Account -> Sign
    /// in' if you want to use it."
    static auto NotUsingAccount(LangStr::Sub service)
        -> std::shared_ptr<const LangStr>;

    /// Error message shown when signing in fails.
    ///
    /// English: "Error signing in."
    static auto SignInError() -> std::shared_ptr<const LangStr>;

    /// Notice that the account is being updated.
    ///
    /// English: "Updating your account..."
    static auto UpdatingAccount() -> std::shared_ptr<const LangStr>;

    /// Screen-message acknowledging the player received a purchased/awarded
    /// item; the placeholder is the item name (may be raw text or a nested
    /// translated name).
    ///
    /// English: "You got a {item}!"
    static auto YouGotItem(LangStr::Sub item) -> std::shared_ptr<const LangStr>;
  };

  class Assets {
   public:
    /// Wraps a server-supplied asset access-denial explanation with guidance
    /// for the user; shown on the boot-time asset dialog.
    ///
    /// English: "{detail} Remove these mods/changes and try again."
    static auto AccessDeniedGuidance(LangStr::Sub detail)
        -> std::shared_ptr<const LangStr>;

    /// Screen message shown when a resolve finally lands full asset quality
    /// after previously showing reduced-quality versions. Paired with
    /// requested_quality_assets_building.
    ///
    /// English: "All assets are now full quality."
    static auto AllAssetsRequestedQuality() -> std::shared_ptr<const LangStr>;

    /// Status line in the boot-time asset dialog while waiting for account
    /// sign-in so restricted assets can load.
    ///
    /// English: "Authenticating…"
    static auto Authenticating() -> std::shared_ptr<const LangStr>;

    /// Progress-dialog line shown while the server builds assets; updates live
    /// as the remaining count drops. Spans every package being built, so it
    /// names no package.
    ///
    /// English: (one) "Building assets (# remaining)…" / (other) "Building
    /// assets (# remaining)…"
    static auto BuildingAssets(int64_t count) -> std::shared_ptr<const LangStr>;

    /// Progress-dialog line shown once asset builds have started but before the
    /// total step count is known (some packages have not reported yet).
    /// Replaced by the counted line once it is.
    ///
    /// English: "Building assets…"
    static auto BuildingAssetsNoCount() -> std::shared_ptr<const LangStr>;

    /// Error on the boot-time asset dialog when this app build is too old to
    /// load current assets (fallback wording when the server didn't supply its
    /// own).
    ///
    /// English: "This app version is too old to load current assets. Please
    /// update to continue."
    static auto ClientTooOld() -> std::shared_ptr<const LangStr>;

    /// Wraps a server-supplied asset build-failure explanation with guidance
    /// for the package author; shown on the boot-time asset dialog (this state
    /// is nearly always seen by the author, since dev/test versions only
    /// resolve for them).
    ///
    /// English: "{detail} Fix the file in the source Workspace and try again."
    static auto ContentErrorGuidance(LangStr::Sub detail)
        -> std::shared_ptr<const LangStr>;

    /// Progress-dialog line shown while asset files download; updates live as
    /// the remaining count drops.
    ///
    /// English: (one) "Downloading assets (# remaining)…" / (other)
    /// "Downloading assets (# remaining)…"
    static auto DownloadingAssets(int64_t count)
        -> std::shared_ptr<const LangStr>;

    /// Generic error on the boot-time asset dialog when asset loading fails
    /// unexpectedly.
    ///
    /// English: "An error occurred loading assets; see log for details."
    static auto LoadError() -> std::shared_ptr<const LangStr>;

    /// Progress-dialog line shown while server-side asset builds are being
    /// prepared, before per-step progress is known.
    ///
    /// English: "Preparing to build assets…"
    static auto PreparingBuild() -> std::shared_ptr<const LangStr>;

    /// Screen message shown after a resolve that had to serve lower-quality
    /// textures because the requested quality was still being built. Paired
    /// with all_assets_requested_quality, which announces the recovery.
    ///
    /// English: "Assets are still building; some may appear with reduced
    /// quality."
    static auto RequestedQualityAssetsBuilding()
        -> std::shared_ptr<const LangStr>;

    /// Error on the boot-time asset dialog when a required sign-in was not
    /// completed (attempted and failed, or timed out); a Retry button sits
    /// below it.
    ///
    /// English: "You must sign in to an account with access to these assets to
    /// continue. Retry to sign in, or remove these mods/changes."
    static auto SignInFailed() -> std::shared_ptr<const LangStr>;

    /// Message on the boot-time sign-in dialog when required assets need a
    /// signed-in account and a web browser is available; a Sign In button sits
    /// below it.
    ///
    /// English: "Sign-in is required to load these assets. Press the button
    /// below, or visit {address}"
    static auto SignInNeededBrowser(LangStr::Sub address)
        -> std::shared_ptr<const LangStr>;

    /// Message on the boot-time sign-in dialog when required assets need a
    /// signed-in account and this device has no web browser.
    ///
    /// English: "Sign-in is required to load these assets. On another device,
    /// visit {address}"
    static auto SignInNeededOtherDevice(LangStr::Sub address)
        -> std::shared_ptr<const LangStr>;

    /// Status line in the boot-time asset dialog after a browser sign-in
    /// completes, while the account finishes validating.
    ///
    /// English: "Signing in…"
    static auto SigningIn() -> std::shared_ptr<const LangStr>;
  };

  class Audio {
   public:
    /// Error screen-message shown when a custom-soundtrack music file fails to
    /// play; the placeholder is the quoted filename.
    ///
    /// English: "Error playing music: {music}"
    static auto MusicPlayError(LangStr::Sub music)
        -> std::shared_ptr<const LangStr>;
  };

  class Input {
   public:
    /// Short lowercase label identifying a numbered joystick axis by index;
    /// used inline in axis-name displays such as the controls-configuration UI.
    /// The {number} placeholder is the axis index.
    ///
    /// English: "axis {number}"
    static auto Axis(LangStr::Sub number) -> std::shared_ptr<const LangStr>;

    /// Short lowercase label identifying a numbered controller button by index;
    /// used inline in button-name displays such as the controls-configuration
    /// UI. The {number} placeholder is the button index.
    ///
    /// English: "button {number}"
    static auto Button(LangStr::Sub number) -> std::shared_ptr<const LangStr>;

    /// Transient screen-message shown when a single game controller connects,
    /// naming the device (several connecting at once use a separate counted
    /// message).
    ///
    /// English: "{controller} connected."
    static auto ControllerConnected(LangStr::Sub controller)
        -> std::shared_ptr<const LangStr>;

    /// Transient screen-message shown at app startup when exactly one game
    /// controller is detected (multiple controllers at startup use a separate
    /// counted message).
    ///
    /// English: "1 controller detected."
    static auto ControllerDetected() -> std::shared_ptr<const LangStr>;

    /// Transient screen-message shown when a single game controller
    /// disconnects, naming the device (several disconnecting at once use a
    /// separate counted message).
    ///
    /// English: "{controller} disconnected."
    static auto ControllerDisconnected(LangStr::Sub controller)
        -> std::shared_ptr<const LangStr>;

    /// Notice that a controller works only in menus.
    ///
    /// English: "This controller can not be used to play; only to navigate
    /// menus."
    static auto ControllerMenusOnly() -> std::shared_ptr<const LangStr>;

    /// Transient screen-message shown when a previously-connected game
    /// controller (e.g. a BombSquad Remote phone client) reconnects, naming the
    /// device.
    ///
    /// English: "{controller} reconnected."
    static auto ControllerReconnected(LangStr::Sub controller)
        -> std::shared_ptr<const LangStr>;

    /// Transient screen-message shown when multiple game controllers connect at
    /// the same time (a single controller connecting shows a different message
    /// naming that controller).
    ///
    /// English: (one) "# controller connected." / (other) "# controllers
    /// connected."
    static auto ControllersConnected(int64_t count)
        -> std::shared_ptr<const LangStr>;

    /// Transient screen-message shown at app startup when more than one game
    /// controller is detected at once (a single controller at startup uses a
    /// separate message).
    ///
    /// English: (one) "# controller detected." / (other) "# controllers
    /// detected."
    static auto ControllersDetected(int64_t count)
        -> std::shared_ptr<const LangStr>;

    /// Transient screen-message shown when multiple game controllers disconnect
    /// at the same time (a single controller disconnecting shows a different
    /// message naming that controller).
    ///
    /// English: (one) "# controller disconnected." / (other) "# controllers
    /// disconnected."
    static auto ControllersDisconnected(int64_t count)
        -> std::shared_ptr<const LangStr>;

    /// Display name for the keyboard input device; shown in input-device lists,
    /// controls-configuration UI, and messages naming the device.
    ///
    /// English: "Keyboard"
    static auto Keyboard() -> std::shared_ptr<const LangStr>;

    /// Display name for the touch-screen input device; shown in input-device
    /// lists, controls-configuration UI, and messages naming the device.
    ///
    /// English: "TouchScreen"
    static auto TouchScreen() -> std::shared_ptr<const LangStr>;

    /// Warning screen-message shown when the touchscreen joins the game while
    /// physical controllers are already active (touch joins are often
    /// accidental then); tells the player how to back out. 'Menu' and 'Leave
    /// Game' refer to in-game menu items.
    ///
    /// English: "You have joined with the touchscreen. If this was a mistake,
    /// tap Menu -> Leave Game with it to back out."
    static auto TouchScreenJoinWarning() -> std::shared_ptr<const LangStr>;

    /// Notice that a controller is not supported.
    ///
    /// English: "Sorry, the {name} controller is not supported."
    static auto UnsupportedController(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Confirmation screen-message shown in VR mode when the player resets the
    /// headset's forward orientation via their controller.
    ///
    /// English: "VR orientation reset."
    static auto VrOrientationReset() -> std::shared_ptr<const LangStr>;

    /// Explanation of the VR orientation reset on Cardboard.
    ///
    /// English: "Use this to reset the VR orientation. To play, you'll need an
    /// external controller."
    static auto VrOrientationResetCardboard() -> std::shared_ptr<const LangStr>;
  };

  class Net {
   public:
    /// Error screen-message shown to a player whose attempt to join a party or
    /// server was rejected because the host could not validate their account.
    ///
    /// English: "Your account was rejected. Are you signed in?"
    static auto AccountRejected() -> std::shared_ptr<const LangStr>;

    /// Generic error screen-message shown to a player whose attempt to join a
    /// party or server failed due to an authentication or server error (with no
    /// more-specific cause available).
    ///
    /// English: "An error has occurred."
    static auto AuthError() -> std::shared_ptr<const LangStr>;

    /// Screen-message after successfully joining a named hosted game; the
    /// placeholder is the game/party name (already quoted in the English form).
    ///
    /// English: "Joined '{name}'"
    static auto ConnectedToGame(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Screen-message after successfully joining another player's party; the
    /// placeholder is that player's display name.
    ///
    /// English: "Joined {name}'s party!"
    static auto ConnectedToParty(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Progress screen-message shown while attempting to connect to a
    /// multiplayer party.
    ///
    /// English: "Connecting..."
    static auto Connecting() -> std::shared_ptr<const LangStr>;

    /// Notice that connecting to a server failed.
    ///
    /// English: "Connection failed."
    static auto ConnectionFailed() -> std::shared_ptr<const LangStr>;

    /// Screen-message when connecting fails because the target host is itself
    /// in another party.
    ///
    /// English: "Connection failed; host is in another party."
    static auto ConnectionFailedHostInOtherParty()
        -> std::shared_ptr<const LangStr>;

    /// Screen-message when connecting fails because the party has no free
    /// slots.
    ///
    /// English: "Connection failed; the party is full."
    static auto ConnectionFailedPartyFull() -> std::shared_ptr<const LangStr>;

    /// Screen-message when connecting fails because the host runs a different
    /// game version.
    ///
    /// English: "Connection failed; host is running a different version of the
    /// game. Make sure you are both up-to-date and try again."
    static auto ConnectionFailedVersionMismatch()
        -> std::shared_ptr<const LangStr>;

    /// Generic screen-message when a host refuses the connection for an
    /// unspecified reason.
    ///
    /// English: "Connection rejected."
    static auto ConnectionRejected() -> std::shared_ptr<const LangStr>;

    /// Warning shown when the device clock differs substantially from real-
    /// world time; the placeholder is how many hours off it is.
    ///
    /// English: "Your device's time is incorrect by {hours} hours. This is
    /// likely to cause problems. Please check your time and time-zone
    /// settings."
    static auto DeviceTimeIncorrect(LangStr::Sub hours)
        -> std::shared_ptr<const LangStr>;

    /// Screen-message when connecting fails because the host runs a NEWER game
    /// version (so updating locally will fix it).
    ///
    /// English: "Host is running a newer version. Update your game and try
    /// again."
    static auto IncompatibleNewerVersionHost()
        -> std::shared_ptr<const LangStr>;

    /// Screen-message when connecting fails because the host runs a different
    /// game version (direction unknown).
    ///
    /// English: "Host is running a different version of the game. Make sure you
    /// are both up-to-date and try again."
    static auto IncompatibleVersionHost() -> std::shared_ptr<const LangStr>;

    /// Screen-message when a joining player is refused because their game
    /// version differs from the host; the placeholder is their display name.
    ///
    /// English: "{name} is running a different version of the game. Make sure
    /// you are both up-to-date and try again."
    static auto IncompatibleVersionPlayer(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Error screen-message shown to a player whose attempt to join a password-
    /// protected party or server was rejected for entering the wrong party
    /// password.
    ///
    /// English: "Incorrect password."
    static auto IncorrectPassword() -> std::shared_ptr<const LangStr>;

    /// Error screen-message shown when the player enters a malformed network
    /// address trying to connect to a game party.
    ///
    /// English: "Error: invalid address."
    static auto InvalidAddress() -> std::shared_ptr<const LangStr>;

    /// Screen-message after leaving a named hosted game; the placeholder is the
    /// game/party name (already quoted in the English form).
    ///
    /// English: "Left '{name}'."
    static auto LeftGame(LangStr::Sub name) -> std::shared_ptr<const LangStr>;

    /// Screen-message after leaving another player's party; the placeholder is
    /// that player's display name.
    ///
    /// English: "Left {name}'s party."
    static auto LeftParty(LangStr::Sub name) -> std::shared_ptr<const LangStr>;

    /// Screen-message when another player joins the party you are in; the
    /// placeholder is their display name.
    ///
    /// English: "{name} joined the party!"
    static auto PlayerJoinedParty(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Screen-message when another player leaves the party you are in; the
    /// placeholder is their display name.
    ///
    /// English: "{name} left the party."
    static auto PlayerLeftParty(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Screen-message shown when the client cannot establish its secure
    /// connection to the cloud.
    ///
    /// English: "Unable to establish secure cloud connection; network
    /// functionality may fail."
    static auto SecureConnectionFailed() -> std::shared_ptr<const LangStr>;

    /// Screen-message when connecting to game servers is refused because this
    /// app version is too old for them.
    ///
    /// English: "Server functionality is no longer supported in this version of
    /// the game; Please update to a newer version."
    static auto ServerUnsupported() -> std::shared_ptr<const LangStr>;

    /// Error shown when something cannot be reached, most likely because there
    /// is no internet connection (dialog messages and screen-messages).
    ///
    /// English: "This is currently unavailable (no internet connection?)"
    static auto UnavailableNoConnection() -> std::shared_ptr<const LangStr>;
  };

  class Plugins {
   public:
    /// Error message for a plugin class that failed to load.
    ///
    /// English: "Error loading plugin class '{plugin}': {error}"
    static auto ClassLoadError(LangStr::Sub plugin, LangStr::Sub error)
        -> std::shared_ptr<const LangStr>;

    /// Notice that new plugins were found.
    ///
    /// English: "New plugin(s) detected. Restart to activate them, or configure
    /// them in settings."
    static auto Detected() -> std::shared_ptr<const LangStr>;

    /// Error message for a plugin that failed to initialize.
    ///
    /// English: "Error initializing plugin {plugin}: {error}"
    static auto InitError(LangStr::Sub plugin, LangStr::Sub error)
        -> std::shared_ptr<const LangStr>;

    /// Notice that previously-present plugins are gone.
    ///
    /// English: (one) "# plugin no longer found." / (other) "# plugins no
    /// longer found."
    static auto Removed(int64_t count) -> std::shared_ptr<const LangStr>;
  };

  class Replay {
   public:
    /// Error screen-message shown when a game replay file can't be read
    /// (corrupt or truncated).
    ///
    /// English: "Error reading replay file."
    static auto ReadError() -> std::shared_ptr<const LangStr>;

    /// Error screen-message shown when a saved game replay was recorded by an
    /// incompatible game version and can't be played back.
    ///
    /// English: "Sorry, this replay was made in a different version of the game
    /// and can't be used."
    static auto VersionError() -> std::shared_ptr<const LangStr>;
  };

  class Scripts {
   public:
    /// Notice that one script module is out of date.
    ///
    /// English: "The module at {path} must be updated for API version {api}."
    static auto ModuleNeedsUpdate(LangStr::Sub path, LangStr::Sub api)
        -> std::shared_ptr<const LangStr>;

    /// Notice that several script modules are out of date.
    ///
    /// English: (one) "{path} and # other module must be updated for API {api}"
    /// / (other) "{path} and # other modules must be updated for API {api}"
    static auto ModulesNeedUpdate(LangStr::Sub path, int64_t count,
                                  LangStr::Sub api)
        -> std::shared_ptr<const LangStr>;

    /// Notice that errors occurred scanning scripts.
    ///
    /// English: "Error(s) scanning scripts. See log for details."
    static auto ScanError() -> std::shared_ptr<const LangStr>;
  };

  class Session {
   public:
    /// Screen-message when a player is temporarily blocked from chatting;
    /// placeholders are their display name and the block duration in seconds.
    ///
    /// English: (one) "{name} is chat-blocked for # second." / (other) "{name}
    /// is chat-blocked for # seconds."
    static auto ChatBlocked(int64_t seconds, LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Screen-message telling a recently-departed player how long until they
    /// may rejoin the game session.
    ///
    /// English: (one) "You can join in # second." / (other) "You can join in #
    /// seconds."
    static auto JoinCooldown(int64_t seconds) -> std::shared_ptr<const LangStr>;

    /// Screen-message shown on the host when a player is removed from the game
    /// for being idle too long (the kick-idle-players option).
    ///
    /// English: "Kicking {name} for being idle."
    static auto KickIdleKicked(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Screen-message warning shown on the host shortly before an idle player
    /// gets kicked (the kick-idle-players option); followed by the
    /// kick_idle_warning_settings note.
    ///
    /// English: (one) "{name} will be kicked in # second if still idle." /
    /// (other) "{name} will be kicked in # seconds if still idle."
    static auto KickIdleWarning(int64_t seconds, LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Parenthesized note shown right after the kick_idle_warning message,
    /// pointing at where the kick-idle-players behavior can be disabled.
    /// 'Settings' and 'Advanced' refer to the in-game settings menu sections.
    ///
    /// English: "(you can turn this off in Settings -> Advanced)"
    static auto KickIdleWarningSettings() -> std::shared_ptr<const LangStr>;

    /// Screen-message when a player is kicked from the party after a successful
    /// vote; the placeholder is their display name.
    ///
    /// English: "{name} was kicked."
    static auto KickOccurred(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Prompt asking the party whether a player should be kicked; the
    /// placeholder is their display name.
    ///
    /// English: "Kick {name}?"
    static auto KickQuestion(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Error screen-message when a player tries to start a kick vote against a
    /// server admin.
    ///
    /// English: "Admins can't be kicked."
    static auto KickVoteCantKickAdmins() -> std::shared_ptr<const LangStr>;

    /// Error screen-message when a player tries to start a kick vote against
    /// themselves.
    ///
    /// English: "You can't kick yourself."
    static auto KickVoteCantKickSelf() -> std::shared_ptr<const LangStr>;

    /// Screen-message when a kick vote ends without enough yes votes.
    ///
    /// English: "Kick-vote failed."
    static auto KickVoteFailed() -> std::shared_ptr<const LangStr>;

    /// Error screen-message when there are too few players present for a kick
    /// vote to be meaningful.
    ///
    /// English: "Not enough players for a vote."
    static auto KickVoteNotEnoughPlayers() -> std::shared_ptr<const LangStr>;

    /// Screen-message announcing that a kick vote has begun against a player;
    /// the placeholder is their display name.
    ///
    /// English: "A kick vote has been started for {name}."
    static auto KickVoteStarted(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Screen-message showing how many more yes votes a kick vote needs to
    /// pass.
    ///
    /// English: (one) "# vote needed" / (other) "# votes needed"
    static auto KickVotesNeeded(int64_t count)
        -> std::shared_ptr<const LangStr>;

    /// Error screen-message when kick voting is turned off on this server.
    ///
    /// English: "Kick voting is disabled."
    static auto KickVotingDisabled() -> std::shared_ptr<const LangStr>;

    /// Instructions for voting via chat; the placeholders are the exact text to
    /// type into chat for yes and for no (e.g. "1" and "2").
    ///
    /// English: "Type {yes} in chat for yes and {no} for no."
    static auto KickWithChat(LangStr::Sub yes, LangStr::Sub no)
        -> std::shared_ptr<const LangStr>;

    /// Screen-message when a client tries to do something while the host is
    /// still loading.
    ///
    /// English: "Loading; try again in a moment..."
    static auto LoadingTryAgain() -> std::shared_ptr<const LangStr>;

    /// Error screen-message telling a player how long until they may start
    /// another vote.
    ///
    /// English: (one) "You can't start another vote for # second." / (other)
    /// "You can't start another vote for # seconds."
    static auto VoteDelay(int64_t seconds) -> std::shared_ptr<const LangStr>;

    /// Error screen-message when a player tries to start a vote while another
    /// vote is still running.
    ///
    /// English: "A vote is already in progress."
    static auto VoteInProgress() -> std::shared_ptr<const LangStr>;

    /// Error screen-message when a player tries to vote twice in the same vote.
    ///
    /// English: "You already voted"
    static auto VotedAlready() -> std::shared_ptr<const LangStr>;
  };

  class Store {
   public:
    /// Notice that Google Play purchases are unavailable.
    ///
    /// English: "Google Play purchases are not available. You may need to
    /// update your store app."
    static auto GooglePlayPurchasesUnavailable()
        -> std::shared_ptr<const LangStr>;

    /// Notice that Google Play Services is unavailable.
    ///
    /// English: "Google Play Services is not available. Some app functionality
    /// may be disabled."
    static auto GooglePlayServicesUnavailable()
        -> std::shared_ptr<const LangStr>;

    /// Notice that this item is already being purchased.
    ///
    /// English: "A purchase of this item is already in progress."
    static auto PurchaseAlreadyInProgress() -> std::shared_ptr<const LangStr>;

    /// Error message that a purchase was not valid.
    ///
    /// English: "Purchase not valid. Contact {email} if this is an error."
    static auto PurchaseNotValid(LangStr::Sub email)
        -> std::shared_ptr<const LangStr>;

    /// Confirmation that past purchases were restored.
    ///
    /// English: "Purchases restored."
    static auto PurchasesRestored() -> std::shared_ptr<const LangStr>;

    /// Status shown while a purchase is being processed.
    ///
    /// English: "Purchasing..."
    static auto Purchasing() -> std::shared_ptr<const LangStr>;

    /// Limited-time offer to remove ads via a token pack.
    ///
    /// English: "LIMITED TIME OFFER: PURCHASE ANY TOKEN PACK TO REMOVE IN-GAME
    /// ADS."
    static auto RemoveAdsTokenOffer() -> std::shared_ptr<const LangStr>;

    /// Status shown while a free (zero-price) item is being requested; the
    /// counterpart of the purchasing message.
    ///
    /// English: "Requesting..."
    static auto Requesting() -> std::shared_ptr<const LangStr>;

    /// Notice that a transaction is already underway.
    ///
    /// English: "A transaction is in progress; please try again in a moment."
    static auto TransactionInProgress() -> std::shared_ptr<const LangStr>;

    /// Notice that a store item is not available.
    ///
    /// English: "Sorry, this is not available."
    static auto Unavailable() -> std::shared_ptr<const LangStr>;

    /// Notice that something is unavailable for now.
    ///
    /// English: "This is currently unavailable; please try again later."
    static auto UnavailableTemporarily() -> std::shared_ptr<const LangStr>;
  };

  class Time {
   public:
    /// A bare length of time such as "1h 23m", shown by itself as a plain
    /// value. Doubles as the string that keeps the duration formatter
    /// components embedded in this package: engine-level displays (the
    /// timedisplay node, the toolbar chest countdowns) read their unit words
    /// from those embedded components, so this entry must always exist here.
    ///
    /// English: "{t}"
    static auto DurationValue(int64_t t) -> std::shared_ptr<const LangStr>;

    /// Compact hours suffix used in formatted time values.
    ///
    /// English: "{count}h"
    static auto SuffixHours(LangStr::Sub count)
        -> std::shared_ptr<const LangStr>;

    /// Compact minutes suffix used in formatted time values.
    ///
    /// English: "{count}m"
    static auto SuffixMinutes(LangStr::Sub count)
        -> std::shared_ptr<const LangStr>;

    /// Compact seconds suffix used in formatted time values.
    ///
    /// English: "{count}s"
    static auto SuffixSeconds(LangStr::Sub count)
        -> std::shared_ptr<const LangStr>;
  };

  class Ui {
   public:
    /// Lowercase hint shown (with an error sound) when the player hits the edge
    /// of a UI list; tells them how to move focus out of it. The two
    /// placeholders are substituted with left/right arrow glyph characters.
    ///
    /// English: "press {left} or {right} to exit list"
    static auto ArrowsToExitList(LangStr::Sub left, LangStr::Sub right)
        -> std::shared_ptr<const LangStr>;

    /// Generic Cancel button label (used by e.g. asset-download progress
    /// dialogs).
    ///
    /// English: "Cancel"
    static auto Cancel() -> std::shared_ptr<const LangStr>;

    /// Notice that the clipboard is unavailable in this build.
    ///
    /// English: "Clipboard not supported on this build."
    static auto ClipboardNotSupported() -> std::shared_ptr<const LangStr>;

    /// Confirmation that text was copied to the clipboard.
    ///
    /// English: "Copied to clipboard."
    static auto CopiedToClipboard() -> std::shared_ptr<const LangStr>;

    /// Generic Error title used on error dialogs (e.g. the boot-time asset-
    /// update dialog when a load fails).
    ///
    /// English: "Error"
    static auto Error() -> std::shared_ptr<const LangStr>;

    /// Name label for the Apple Game Center service.
    ///
    /// English: "Game Center"
    static auto GameCenter() -> std::shared_ptr<const LangStr>;

    /// Name label for the Google Play service.
    ///
    /// English: "Google Play"
    static auto GooglePlay() -> std::shared_ptr<const LangStr>;

    /// Screen-message shown when an input device tries to use a menu another
    /// device currently controls; names the controlling device. A timeout
    /// suffix (menu_control_time_out or menu_control_will_time_out) is appended
    /// after it.
    ///
    /// English: "{name} has menu control."
    static auto HasMenuControl(LangStr::Sub name)
        -> std::shared_ptr<const LangStr>;

    /// Parenthesized suffix appended after the has_menu_control message once
    /// the controlling device's ownership is close to expiring; gives the
    /// remaining seconds.
    ///
    /// English: (one) "(times out in # second)" / (other) "(times out in #
    /// seconds)"
    static auto MenuControlTimeOut(int64_t seconds)
        -> std::shared_ptr<const LangStr>;

    /// Parenthesized suffix appended after the has_menu_control message while
    /// the controlling device's ownership is not yet close to expiring.
    ///
    /// English: "(will time out if idle)"
    static auto MenuControlWillTimeOut() -> std::shared_ptr<const LangStr>;

    /// Generic label for a button acknowledging/dismissing a message (used by
    /// e.g. asset-update error dialogs).
    ///
    /// English: "OK"
    static auto Ok() -> std::shared_ptr<const LangStr>;

    /// Label on an unopenable-yet treasure chest slot in the root UI inviting
    /// the player to open it once its timer completes. Replaces the legacy
    /// openMeText resource.
    ///
    /// English: "Open Me!"
    static auto OpenMe() -> std::shared_ptr<const LangStr>;

    /// Name label for the remote-control companion app.
    ///
    /// English: "BombSquad Remote"
    static auto RemoteAppName() -> std::shared_ptr<const LangStr>;

    /// Generic label for a button that retries a failed operation (used by e.g.
    /// the boot-time asset-update dialog).
    ///
    /// English: "Retry"
    static auto Retry() -> std::shared_ptr<const LangStr>;

    /// Generic Sign In label used for dialog titles and buttons (e.g. the boot-
    /// time asset gate's browser sign-in dialog).
    ///
    /// English: "Sign In"
    static auto SignIn() -> std::shared_ptr<const LangStr>;

    /// Pure-formatting template joining two labels with a space; substitution-
    /// only.
    ///
    /// English: "{first} {second}"
    static auto SpacedPair(LangStr::Sub first, LangStr::Sub second)
        -> std::shared_ptr<const LangStr>;

    /// Notice that storage access permission is required.
    ///
    /// English: "This requires storage access"
    static auto StoragePermissionNeeded() -> std::shared_ptr<const LangStr>;

    /// Confirmation label that an operation succeeded.
    ///
    /// English: "Success!"
    static auto Success() -> std::shared_ptr<const LangStr>;

    /// Generic screen-message for a failure with no more specific explanation
    /// available.
    ///
    /// English: "Unknown error"
    static auto UnknownError() -> std::shared_ptr<const LangStr>;

    /// Gentle non-urgent screen-message notice, shown once shortly after
    /// connectivity comes up, telling the player that a newer version of the
    /// app is available to download.
    ///
    /// English: "A newer version of this app is available."
    static auto UpdateAvailable() -> std::shared_ptr<const LangStr>;

    /// Generic title for progress dialogs applying updates: asset
    /// downloads/builds at boot, locale switches, pre-game package fetches.
    ///
    /// English: "Updating…"
    static auto Updating() -> std::shared_ptr<const LangStr>;
  };

  class Workspace {
   public:
    /// Confirmation that a workspace was activated.
    ///
    /// English: "Workspace {thing} activated."
    static auto Activated(LangStr::Sub thing) -> std::shared_ptr<const LangStr>;

    /// Error message that a workspace failed to sync.
    ///
    /// English: "Error syncing Workspace {workspace}. See log for details."
    static auto SyncError(LangStr::Sub workspace)
        -> std::shared_ptr<const LangStr>;

    /// Notice that a previously synced workspace is being reused.
    ///
    /// English: "Can't sync Workspace '{workspace}'. Reusing previously synced
    /// version."
    static auto SyncReuse(LangStr::Sub workspace)
        -> std::shared_ptr<const LangStr>;
  };
};

}  // namespace ballistica::base

#endif  // BALLISTICA_BASE_ASSETS_BUILTIN_STRINGS_H_
