// Released under the MIT License. See LICENSE for details.

#ifndef BALLISTICA_CORE_MGEN_PYTHON_MODULES_MONOLITHIC_H_
#define BALLISTICA_CORE_MGEN_PYTHON_MODULES_MONOLITHIC_H_

// THIS CODE IS AUTOGENERATED BY META BUILD; DO NOT EDIT BY HAND.

#include "ballistica/shared/ballistica.h"
#include "ballistica/shared/python/python_macros.h"

extern "C" {
auto PyInit__babase() -> PyObject*;
auto PyInit__baclassic() -> PyObject*;
auto DoPyInit__baplus() -> PyObject*;
auto PyInit__bascenev1() -> PyObject*;
auto PyInit__batemplatefs() -> PyObject*;
auto PyInit__bauiv1() -> PyObject*;
}

namespace ballistica {

/// Register init calls for all of our built-in Python modules.
/// Should only be used in monolithic builds. In modular builds
/// binary modules get located as .so files on disk as per regular
/// Python behavior.
void MonolithicRegisterPythonModules() {
  if (g_buildconfig.monolithic_build()) {
    PyImport_AppendInittab("_babase", &PyInit__babase);
    PyImport_AppendInittab("_baclassic", &PyInit__baclassic);
    PyImport_AppendInittab("_baplus", &DoPyInit__baplus);
    PyImport_AppendInittab("_bascenev1", &PyInit__bascenev1);
    PyImport_AppendInittab("_batemplatefs", &PyInit__batemplatefs);
    PyImport_AppendInittab("_bauiv1", &PyInit__bauiv1);
  } else {
    FatalError(
        "MonolithicRegisterPythonModules should not be called"
        " in modular builds.");
  }
}

// Slight hack: because we are currently building baplus as a static module
// and linking it in, symbols exported there (namely PyInit__baplus) do not
// seem to be available through us when we are compiled as a dynamic
// library. This leads to Python being unable to load baplus. While I'm sure
// there is some way to get those symbols exported, I'm worried it might be
// a messy platform-specific affair. So instead we're just defining that
// function here when baplus is present and forwarding it through to the
// static library version.
extern "C" auto PyInit__baplus() -> PyObject* {
  return DoPyInit__baplus();
}

}  // namespace ballistica

#endif  // BALLISTICA_CORE_MGEN_PYTHON_MODULES_MONOLITHIC_H_
