// Released under the MIT License. See LICENSE for details.

#ifndef BALLISTICA_SHARED_FOUNDATION_INPUT_TYPES_H_
#define BALLISTICA_SHARED_FOUNDATION_INPUT_TYPES_H_

#include <cstdint>

// Ballistica-native input types: keycodes, scancodes, keymods, keysyms,
// event types/structs, mouse buttons, and joystick hats.
//
// These mirror the layout AND values of the SDL types they historically
// replaced (see core/platform/support/min_sdl.h) so that (a) the SDL
// boundary -- the SDL app-adapter -- can convert SDL<->native with
// near-identity casts, and (b) Python-facing keycode/scancode integer
// values stay unchanged. Nothing here depends on SDL or any build flag;
// this is the engine's own input vocabulary.
//
// See docs/initiatives/sdl-type-decoupling.md.

typedef int32_t BAKeycode;

typedef enum {
  BA_SCANCODE_UNKNOWN = 0,

  BA_SCANCODE_A = 4,
  BA_SCANCODE_B = 5,
  BA_SCANCODE_C = 6,
  BA_SCANCODE_D = 7,
  BA_SCANCODE_E = 8,
  BA_SCANCODE_F = 9,
  BA_SCANCODE_G = 10,
  BA_SCANCODE_H = 11,
  BA_SCANCODE_I = 12,
  BA_SCANCODE_J = 13,
  BA_SCANCODE_K = 14,
  BA_SCANCODE_L = 15,
  BA_SCANCODE_M = 16,
  BA_SCANCODE_N = 17,
  BA_SCANCODE_O = 18,
  BA_SCANCODE_P = 19,
  BA_SCANCODE_Q = 20,
  BA_SCANCODE_R = 21,
  BA_SCANCODE_S = 22,
  BA_SCANCODE_T = 23,
  BA_SCANCODE_U = 24,
  BA_SCANCODE_V = 25,
  BA_SCANCODE_W = 26,
  BA_SCANCODE_X = 27,
  BA_SCANCODE_Y = 28,
  BA_SCANCODE_Z = 29,

  BA_SCANCODE_1 = 30,
  BA_SCANCODE_2 = 31,
  BA_SCANCODE_3 = 32,
  BA_SCANCODE_4 = 33,
  BA_SCANCODE_5 = 34,
  BA_SCANCODE_6 = 35,
  BA_SCANCODE_7 = 36,
  BA_SCANCODE_8 = 37,
  BA_SCANCODE_9 = 38,
  BA_SCANCODE_0 = 39,

  BA_SCANCODE_RETURN = 40,
  BA_SCANCODE_ESCAPE = 41,
  BA_SCANCODE_BACKSPACE = 42,
  BA_SCANCODE_TAB = 43,
  BA_SCANCODE_SPACE = 44,

  BA_SCANCODE_MINUS = 45,
  BA_SCANCODE_EQUALS = 46,
  BA_SCANCODE_LEFTBRACKET = 47,
  BA_SCANCODE_RIGHTBRACKET = 48,
  BA_SCANCODE_BACKSLASH = 49,
  BA_SCANCODE_NONUSHASH = 50,
  BA_SCANCODE_SEMICOLON = 51,
  BA_SCANCODE_APOSTROPHE = 52,
  BA_SCANCODE_GRAVE = 53,
  BA_SCANCODE_COMMA = 54,
  BA_SCANCODE_PERIOD = 55,
  BA_SCANCODE_SLASH = 56,

  BA_SCANCODE_CAPSLOCK = 57,

  BA_SCANCODE_F1 = 58,
  BA_SCANCODE_F2 = 59,
  BA_SCANCODE_F3 = 60,
  BA_SCANCODE_F4 = 61,
  BA_SCANCODE_F5 = 62,
  BA_SCANCODE_F6 = 63,
  BA_SCANCODE_F7 = 64,
  BA_SCANCODE_F8 = 65,
  BA_SCANCODE_F9 = 66,
  BA_SCANCODE_F10 = 67,
  BA_SCANCODE_F11 = 68,
  BA_SCANCODE_F12 = 69,

  BA_SCANCODE_PRINTSCREEN = 70,
  BA_SCANCODE_SCROLLLOCK = 71,
  BA_SCANCODE_PAUSE = 72,
  BA_SCANCODE_INSERT = 73,
  BA_SCANCODE_HOME = 74,
  BA_SCANCODE_PAGEUP = 75,
  BA_SCANCODE_DELETE = 76,
  BA_SCANCODE_END = 77,
  BA_SCANCODE_PAGEDOWN = 78,
  BA_SCANCODE_RIGHT = 79,
  BA_SCANCODE_LEFT = 80,
  BA_SCANCODE_DOWN = 81,
  BA_SCANCODE_UP = 82,

  BA_SCANCODE_NUMLOCKCLEAR = 83,
  BA_SCANCODE_KP_DIVIDE = 84,
  BA_SCANCODE_KP_MULTIPLY = 85,
  BA_SCANCODE_KP_MINUS = 86,
  BA_SCANCODE_KP_PLUS = 87,
  BA_SCANCODE_KP_ENTER = 88,
  BA_SCANCODE_KP_1 = 89,
  BA_SCANCODE_KP_2 = 90,
  BA_SCANCODE_KP_3 = 91,
  BA_SCANCODE_KP_4 = 92,
  BA_SCANCODE_KP_5 = 93,
  BA_SCANCODE_KP_6 = 94,
  BA_SCANCODE_KP_7 = 95,
  BA_SCANCODE_KP_8 = 96,
  BA_SCANCODE_KP_9 = 97,
  BA_SCANCODE_KP_0 = 98,
  BA_SCANCODE_KP_PERIOD = 99,

  BA_SCANCODE_NONUSBACKSLASH = 100,
  BA_SCANCODE_APPLICATION = 101,
  BA_SCANCODE_POWER = 102,
  BA_SCANCODE_KP_EQUALS = 103,
  BA_SCANCODE_F13 = 104,
  BA_SCANCODE_F14 = 105,
  BA_SCANCODE_F15 = 106,
  BA_SCANCODE_F16 = 107,
  BA_SCANCODE_F17 = 108,
  BA_SCANCODE_F18 = 109,
  BA_SCANCODE_F19 = 110,
  BA_SCANCODE_F20 = 111,
  BA_SCANCODE_F21 = 112,
  BA_SCANCODE_F22 = 113,
  BA_SCANCODE_F23 = 114,
  BA_SCANCODE_F24 = 115,
  BA_SCANCODE_EXECUTE = 116,
  BA_SCANCODE_HELP = 117,
  BA_SCANCODE_MENU = 118,
  BA_SCANCODE_SELECT = 119,
  BA_SCANCODE_STOP = 120,
  BA_SCANCODE_AGAIN = 121,
  BA_SCANCODE_UNDO = 122,
  BA_SCANCODE_CUT = 123,
  BA_SCANCODE_COPY = 124,
  BA_SCANCODE_PASTE = 125,
  BA_SCANCODE_FIND = 126,
  BA_SCANCODE_MUTE = 127,
  BA_SCANCODE_VOLUMEUP = 128,
  BA_SCANCODE_VOLUMEDOWN = 129,

  BA_SCANCODE_KP_COMMA = 133,
  BA_SCANCODE_KP_EQUALSAS400 = 134,

  BA_SCANCODE_INTERNATIONAL1 = 135,
  BA_SCANCODE_INTERNATIONAL2 = 136,
  BA_SCANCODE_INTERNATIONAL3 = 137,
  BA_SCANCODE_INTERNATIONAL4 = 138,
  BA_SCANCODE_INTERNATIONAL5 = 139,
  BA_SCANCODE_INTERNATIONAL6 = 140,
  BA_SCANCODE_INTERNATIONAL7 = 141,
  BA_SCANCODE_INTERNATIONAL8 = 142,
  BA_SCANCODE_INTERNATIONAL9 = 143,
  BA_SCANCODE_LANG1 = 144,
  BA_SCANCODE_LANG2 = 145,
  BA_SCANCODE_LANG3 = 146,
  BA_SCANCODE_LANG4 = 147,
  BA_SCANCODE_LANG5 = 148,
  BA_SCANCODE_LANG6 = 149,
  BA_SCANCODE_LANG7 = 150,
  BA_SCANCODE_LANG8 = 151,
  BA_SCANCODE_LANG9 = 152,

  BA_SCANCODE_ALTERASE = 153,
  BA_SCANCODE_SYSREQ = 154,
  BA_SCANCODE_CANCEL = 155,
  BA_SCANCODE_CLEAR = 156,
  BA_SCANCODE_PRIOR = 157,
  BA_SCANCODE_RETURN2 = 158,
  BA_SCANCODE_SEPARATOR = 159,
  BA_SCANCODE_OUT = 160,
  BA_SCANCODE_OPER = 161,
  BA_SCANCODE_CLEARAGAIN = 162,
  BA_SCANCODE_CRSEL = 163,
  BA_SCANCODE_EXSEL = 164,

  BA_SCANCODE_KP_00 = 176,
  BA_SCANCODE_KP_000 = 177,
  BA_SCANCODE_THOUSANDSSEPARATOR = 178,
  BA_SCANCODE_DECIMALSEPARATOR = 179,
  BA_SCANCODE_CURRENCYUNIT = 180,
  BA_SCANCODE_CURRENCYSUBUNIT = 181,
  BA_SCANCODE_KP_LEFTPAREN = 182,
  BA_SCANCODE_KP_RIGHTPAREN = 183,
  BA_SCANCODE_KP_LEFTBRACE = 184,
  BA_SCANCODE_KP_RIGHTBRACE = 185,
  BA_SCANCODE_KP_TAB = 186,
  BA_SCANCODE_KP_BACKSPACE = 187,
  BA_SCANCODE_KP_A = 188,
  BA_SCANCODE_KP_B = 189,
  BA_SCANCODE_KP_C = 190,
  BA_SCANCODE_KP_D = 191,
  BA_SCANCODE_KP_E = 192,
  BA_SCANCODE_KP_F = 193,
  BA_SCANCODE_KP_XOR = 194,
  BA_SCANCODE_KP_POWER = 195,
  BA_SCANCODE_KP_PERCENT = 196,
  BA_SCANCODE_KP_LESS = 197,
  BA_SCANCODE_KP_GREATER = 198,
  BA_SCANCODE_KP_AMPERSAND = 199,
  BA_SCANCODE_KP_DBLAMPERSAND = 200,
  BA_SCANCODE_KP_VERTICALBAR = 201,
  BA_SCANCODE_KP_DBLVERTICALBAR = 202,
  BA_SCANCODE_KP_COLON = 203,
  BA_SCANCODE_KP_HASH = 204,
  BA_SCANCODE_KP_SPACE = 205,
  BA_SCANCODE_KP_AT = 206,
  BA_SCANCODE_KP_EXCLAM = 207,
  BA_SCANCODE_KP_MEMSTORE = 208,
  BA_SCANCODE_KP_MEMRECALL = 209,
  BA_SCANCODE_KP_MEMCLEAR = 210,
  BA_SCANCODE_KP_MEMADD = 211,
  BA_SCANCODE_KP_MEMSUBTRACT = 212,
  BA_SCANCODE_KP_MEMMULTIPLY = 213,
  BA_SCANCODE_KP_MEMDIVIDE = 214,
  BA_SCANCODE_KP_PLUSMINUS = 215,
  BA_SCANCODE_KP_CLEAR = 216,
  BA_SCANCODE_KP_CLEARENTRY = 217,
  BA_SCANCODE_KP_BINARY = 218,
  BA_SCANCODE_KP_OCTAL = 219,
  BA_SCANCODE_KP_DECIMAL = 220,
  BA_SCANCODE_KP_HEXADECIMAL = 221,

  BA_SCANCODE_LCTRL = 224,
  BA_SCANCODE_LSHIFT = 225,
  BA_SCANCODE_LALT = 226,
  BA_SCANCODE_LGUI = 227,
  BA_SCANCODE_RCTRL = 228,
  BA_SCANCODE_RSHIFT = 229,
  BA_SCANCODE_RALT = 230,
  BA_SCANCODE_RGUI = 231,

  BA_SCANCODE_MODE = 257,

  BA_SCANCODE_AUDIONEXT = 258,
  BA_SCANCODE_AUDIOPREV = 259,
  BA_SCANCODE_AUDIOSTOP = 260,
  BA_SCANCODE_AUDIOPLAY = 261,
  BA_SCANCODE_AUDIOMUTE = 262,
  BA_SCANCODE_MEDIASELECT = 263,
  BA_SCANCODE_WWW = 264,
  BA_SCANCODE_MAIL = 265,
  BA_SCANCODE_CALCULATOR = 266,
  BA_SCANCODE_COMPUTER = 267,
  BA_SCANCODE_AC_SEARCH = 268,
  BA_SCANCODE_AC_HOME = 269,
  BA_SCANCODE_AC_BACK = 270,
  BA_SCANCODE_AC_FORWARD = 271,
  BA_SCANCODE_AC_STOP = 272,
  BA_SCANCODE_AC_REFRESH = 273,
  BA_SCANCODE_AC_BOOKMARKS = 274,

  BA_SCANCODE_BRIGHTNESSDOWN = 275,
  BA_SCANCODE_BRIGHTNESSUP = 276,
  BA_SCANCODE_DISPLAYSWITCH = 277,
  BA_SCANCODE_KBDILLUMTOGGLE = 278,
  BA_SCANCODE_KBDILLUMDOWN = 279,
  BA_SCANCODE_KBDILLUMUP = 280,
  BA_SCANCODE_EJECT = 281,
  BA_SCANCODE_SLEEP = 282,

  BA_NUM_SCANCODES = 512
} BAScancode;

#define BAK_SCANCODE_MASK (1 << 30)
#define BA_SCANCODE_TO_KEYCODE(X) (X | BAK_SCANCODE_MASK)

enum BAKeycodeEnum {
  BAK_UNKNOWN = 0,

  BAK_RETURN = '\r',
  BAK_ESCAPE = '\033',
  BAK_BACKSPACE = '\b',
  BAK_TAB = '\t',
  BAK_SPACE = ' ',
  BAK_EXCLAIM = '!',
  BAK_QUOTEDBL = '"',
  BAK_HASH = '#',
  BAK_PERCENT = '%',
  BAK_DOLLAR = '$',
  BAK_AMPERSAND = '&',
  BAK_QUOTE = '\'',
  BAK_LEFTPAREN = '(',
  BAK_RIGHTPAREN = ')',
  BAK_ASTERISK = '*',
  BAK_PLUS = '+',
  BAK_COMMA = ',',
  BAK_MINUS = '-',
  BAK_PERIOD = '.',
  BAK_SLASH = '/',
  BAK_0 = '0',
  BAK_1 = '1',
  BAK_2 = '2',
  BAK_3 = '3',
  BAK_4 = '4',
  BAK_5 = '5',
  BAK_6 = '6',
  BAK_7 = '7',
  BAK_8 = '8',
  BAK_9 = '9',
  BAK_COLON = ':',
  BAK_SEMICOLON = ';',
  BAK_LESS = '<',
  BAK_EQUALS = '=',
  BAK_GREATER = '>',
  BAK_QUESTION = '?',
  BAK_AT = '@',
  /*
     Skip uppercase letters
   */
  BAK_LEFTBRACKET = '[',
  BAK_BACKSLASH = '\\',
  BAK_RIGHTBRACKET = ']',
  BAK_CARET = '^',
  BAK_UNDERSCORE = '_',
  BAK_BACKQUOTE = '`',
  BAK_a = 'a',
  BAK_b = 'b',
  BAK_c = 'c',
  BAK_d = 'd',
  BAK_e = 'e',
  BAK_f = 'f',
  BAK_g = 'g',
  BAK_h = 'h',
  BAK_i = 'i',
  BAK_j = 'j',
  BAK_k = 'k',
  BAK_l = 'l',
  BAK_m = 'm',
  BAK_n = 'n',
  BAK_o = 'o',
  BAK_p = 'p',
  BAK_q = 'q',
  BAK_r = 'r',
  BAK_s = 's',
  BAK_t = 't',
  BAK_u = 'u',
  BAK_v = 'v',
  BAK_w = 'w',
  BAK_x = 'x',
  BAK_y = 'y',
  BAK_z = 'z',

  BAK_CAPSLOCK = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CAPSLOCK),

  BAK_F1 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F1),
  BAK_F2 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F2),
  BAK_F3 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F3),
  BAK_F4 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F4),
  BAK_F5 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F5),
  BAK_F6 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F6),
  BAK_F7 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F7),
  BAK_F8 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F8),
  BAK_F9 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F9),
  BAK_F10 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F10),
  BAK_F11 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F11),
  BAK_F12 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F12),

  BAK_PRINTSCREEN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_PRINTSCREEN),
  BAK_SCROLLLOCK = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_SCROLLLOCK),
  BAK_PAUSE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_PAUSE),
  BAK_INSERT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_INSERT),
  BAK_HOME = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_HOME),
  BAK_PAGEUP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_PAGEUP),
  BAK_DELETE = '\177',
  BAK_END = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_END),
  BAK_PAGEDOWN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_PAGEDOWN),
  BAK_RIGHT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_RIGHT),
  BAK_LEFT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_LEFT),
  BAK_DOWN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_DOWN),
  BAK_UP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_UP),

  BAK_NUMLOCKCLEAR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_NUMLOCKCLEAR),
  BAK_KP_DIVIDE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_DIVIDE),
  BAK_KP_MULTIPLY = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MULTIPLY),
  BAK_KP_MINUS = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MINUS),
  BAK_KP_PLUS = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_PLUS),
  BAK_KP_ENTER = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_ENTER),
  BAK_KP_1 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_1),
  BAK_KP_2 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_2),
  BAK_KP_3 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_3),
  BAK_KP_4 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_4),
  BAK_KP_5 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_5),
  BAK_KP_6 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_6),
  BAK_KP_7 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_7),
  BAK_KP_8 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_8),
  BAK_KP_9 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_9),
  BAK_KP_0 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_0),
  BAK_KP_PERIOD = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_PERIOD),

  BAK_APPLICATION = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_APPLICATION),
  BAK_POWER = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_POWER),
  BAK_KP_EQUALS = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_EQUALS),
  BAK_F13 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F13),
  BAK_F14 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F14),
  BAK_F15 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F15),
  BAK_F16 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F16),
  BAK_F17 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F17),
  BAK_F18 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F18),
  BAK_F19 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F19),
  BAK_F20 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F20),
  BAK_F21 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F21),
  BAK_F22 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F22),
  BAK_F23 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F23),
  BAK_F24 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_F24),
  BAK_EXECUTE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_EXECUTE),
  BAK_HELP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_HELP),
  BAK_MENU = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_MENU),
  BAK_SELECT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_SELECT),
  BAK_STOP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_STOP),
  BAK_AGAIN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AGAIN),
  BAK_UNDO = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_UNDO),
  BAK_CUT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CUT),
  BAK_COPY = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_COPY),
  BAK_PASTE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_PASTE),
  BAK_FIND = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_FIND),
  BAK_MUTE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_MUTE),
  BAK_VOLUMEUP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_VOLUMEUP),
  BAK_VOLUMEDOWN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_VOLUMEDOWN),
  BAK_KP_COMMA = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_COMMA),
  BAK_KP_EQUALSAS400 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_EQUALSAS400),

  BAK_ALTERASE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_ALTERASE),
  BAK_SYSREQ = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_SYSREQ),
  BAK_CANCEL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CANCEL),
  BAK_CLEAR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CLEAR),
  BAK_PRIOR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_PRIOR),
  BAK_RETURN2 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_RETURN2),
  BAK_SEPARATOR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_SEPARATOR),
  BAK_OUT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_OUT),
  BAK_OPER = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_OPER),
  BAK_CLEARAGAIN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CLEARAGAIN),
  BAK_CRSEL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CRSEL),
  BAK_EXSEL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_EXSEL),

  BAK_KP_00 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_00),
  BAK_KP_000 = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_000),
  BAK_THOUSANDSSEPARATOR =
      BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_THOUSANDSSEPARATOR),
  BAK_DECIMALSEPARATOR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_DECIMALSEPARATOR),
  BAK_CURRENCYUNIT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CURRENCYUNIT),
  BAK_CURRENCYSUBUNIT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CURRENCYSUBUNIT),
  BAK_KP_LEFTPAREN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_LEFTPAREN),
  BAK_KP_RIGHTPAREN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_RIGHTPAREN),
  BAK_KP_LEFTBRACE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_LEFTBRACE),
  BAK_KP_RIGHTBRACE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_RIGHTBRACE),
  BAK_KP_TAB = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_TAB),
  BAK_KP_BACKSPACE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_BACKSPACE),
  BAK_KP_A = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_A),
  BAK_KP_B = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_B),
  BAK_KP_C = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_C),
  BAK_KP_D = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_D),
  BAK_KP_E = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_E),
  BAK_KP_F = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_F),
  BAK_KP_XOR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_XOR),
  BAK_KP_POWER = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_POWER),
  BAK_KP_PERCENT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_PERCENT),
  BAK_KP_LESS = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_LESS),
  BAK_KP_GREATER = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_GREATER),
  BAK_KP_AMPERSAND = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_AMPERSAND),
  BAK_KP_DBLAMPERSAND = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_DBLAMPERSAND),
  BAK_KP_VERTICALBAR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_VERTICALBAR),
  BAK_KP_DBLVERTICALBAR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_DBLVERTICALBAR),
  BAK_KP_COLON = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_COLON),
  BAK_KP_HASH = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_HASH),
  BAK_KP_SPACE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_SPACE),
  BAK_KP_AT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_AT),
  BAK_KP_EXCLAM = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_EXCLAM),
  BAK_KP_MEMSTORE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MEMSTORE),
  BAK_KP_MEMRECALL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MEMRECALL),
  BAK_KP_MEMCLEAR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MEMCLEAR),
  BAK_KP_MEMADD = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MEMADD),
  BAK_KP_MEMSUBTRACT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MEMSUBTRACT),
  BAK_KP_MEMMULTIPLY = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MEMMULTIPLY),
  BAK_KP_MEMDIVIDE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_MEMDIVIDE),
  BAK_KP_PLUSMINUS = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_PLUSMINUS),
  BAK_KP_CLEAR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_CLEAR),
  BAK_KP_CLEARENTRY = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_CLEARENTRY),
  BAK_KP_BINARY = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_BINARY),
  BAK_KP_OCTAL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_OCTAL),
  BAK_KP_DECIMAL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_DECIMAL),
  BAK_KP_HEXADECIMAL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KP_HEXADECIMAL),

  BAK_LCTRL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_LCTRL),
  BAK_LSHIFT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_LSHIFT),
  BAK_LALT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_LALT),
  BAK_LGUI = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_LGUI),
  BAK_RCTRL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_RCTRL),
  BAK_RSHIFT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_RSHIFT),
  BAK_RALT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_RALT),
  BAK_RGUI = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_RGUI),

  BAK_MODE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_MODE),

  BAK_AUDIONEXT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AUDIONEXT),
  BAK_AUDIOPREV = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AUDIOPREV),
  BAK_AUDIOSTOP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AUDIOSTOP),
  BAK_AUDIOPLAY = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AUDIOPLAY),
  BAK_AUDIOMUTE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AUDIOMUTE),
  BAK_MEDIASELECT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_MEDIASELECT),
  BAK_WWW = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_WWW),
  BAK_MAIL = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_MAIL),
  BAK_CALCULATOR = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_CALCULATOR),
  BAK_COMPUTER = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_COMPUTER),
  BAK_AC_SEARCH = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AC_SEARCH),
  BAK_AC_HOME = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AC_HOME),
  BAK_AC_BACK = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AC_BACK),
  BAK_AC_FORWARD = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AC_FORWARD),
  BAK_AC_STOP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AC_STOP),
  BAK_AC_REFRESH = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AC_REFRESH),
  BAK_AC_BOOKMARKS = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_AC_BOOKMARKS),

  BAK_BRIGHTNESSDOWN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_BRIGHTNESSDOWN),
  BAK_BRIGHTNESSUP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_BRIGHTNESSUP),
  BAK_DISPLAYSWITCH = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_DISPLAYSWITCH),
  BAK_KBDILLUMTOGGLE = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KBDILLUMTOGGLE),
  BAK_KBDILLUMDOWN = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KBDILLUMDOWN),
  BAK_KBDILLUMUP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_KBDILLUMUP),
  BAK_EJECT = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_EJECT),
  BAK_SLEEP = BA_SCANCODE_TO_KEYCODE(BA_SCANCODE_SLEEP)
};

typedef enum {
  BA_KMOD_NONE = 0x0000,
  BA_KMOD_LSHIFT = 0x0001,
  BA_KMOD_RSHIFT = 0x0002,
  BA_KMOD_LCTRL = 0x0040,
  BA_KMOD_RCTRL = 0x0080,
  BA_KMOD_LALT = 0x0100,
  BA_KMOD_RALT = 0x0200,
  BA_KMOD_LGUI = 0x0400,
  BA_KMOD_RGUI = 0x0800,
  BA_KMOD_NUM = 0x1000,
  BA_KMOD_CAPS = 0x2000,
  BA_KMOD_MODE = 0x4000,
  BA_KMOD_RESERVED = 0x8000
} BAKeymod;

#define BA_KMOD_CTRL (BA_KMOD_LCTRL | BA_KMOD_RCTRL)
#define BA_KMOD_SHIFT (BA_KMOD_LSHIFT | BA_KMOD_RSHIFT)
#define BA_KMOD_ALT (BA_KMOD_LALT | BA_KMOD_RALT)
#define BA_KMOD_GUI (BA_KMOD_LGUI | BA_KMOD_RGUI)

typedef struct BAKeysym {
  int scancode;
  BAKeycode sym;
  uint16_t mod;
  uint32_t unicode;
} BAKeysym;

typedef enum {
  BA_FIRSTEVENT = 0,

  BA_QUIT = 0x100,

  BA_WINDOWEVENT = 0x200,
  BA_SYSWMEVENT,

  BA_KEYDOWN = 0x300,
  BA_KEYUP,
  BA_TEXTEDITING,
  BA_TEXTINPUT,

  BA_MOUSEMOTION = 0x400,
  BA_MOUSEBUTTONDOWN,
  BA_MOUSEBUTTONUP,
  BA_MOUSEWHEEL,

  BA_INPUTMOTION = 0x500,
  BA_INPUTBUTTONDOWN,
  BA_INPUTBUTTONUP,
  BA_INPUTWHEEL,
  BA_INPUTPROXIMITYIN,
  BA_INPUTPROXIMITYOUT,

  BA_JOYAXISMOTION = 0x600,
  BA_JOYBALLMOTION,
  BA_JOYHATMOTION,
  BA_JOYBUTTONDOWN,
  BA_JOYBUTTONUP,
  BA_JOYDEVICEADDED,
  BA_JOYDEVICEREMOVED,

  BA_CONTROLLERAXISMOTION = 0x650,
  BA_CONTROLLERBUTTONDOWN,
  BA_CONTROLLERBUTTONUP,
  BA_CONTROLLERDEVICEADDED,
  BA_CONTROLLERDEVICEREMOVED,

  BA_FINGERDOWN = 0x700,
  BA_FINGERUP,
  BA_FINGERMOTION,
  BA_TOUCHBUTTONDOWN,
  BA_TOUCHBUTTONUP,

  BA_DOLLARGESTURE = 0x800,
  BA_DOLLARRECORD,
  BA_MULTIGESTURE,

  BA_CLIPBOARDUPDATE = 0x900,

  BA_DROPFILE = 0x1000,

  // ericf additions
  BA_DRAWEVENT = 0x1100,
  BA_RESIZEDRAWEVENT,
  BA_CONTEXTLOSTEVENT,

  BA_USEREVENT = 0x8000,

  BA_LASTEVENT = 0xFFFF
} BAEventType;

/// High-level touch event phases forwarded from the platform layer (currently
/// Apple/UIKit) across the Swift bridge into base::Input::PushTouchEvent. A
/// flat global enum (like BAKeycodeEnum) so Swift imports it cleanly; mirrors
/// ballistica::base::TouchEvent::Type. Distinct from the SDL-style
/// BA_FINGER*/BA_TOUCHBUTTON* event ids above.
enum BATouchEventType {
  BA_TOUCH_EVENT_DOWN = 0,
  BA_TOUCH_EVENT_UP = 1,
  BA_TOUCH_EVENT_MOVED = 2,
  BA_TOUCH_EVENT_CANCELED = 3,
};

typedef struct BAJoyAxisEvent {
  uint32_t type;
  uint32_t timestamp;
  uint8_t which;
  uint8_t axis;
  uint8_t padding1;
  uint8_t padding2;
  int value;
} BAJoyAxisEvent;

typedef struct BAJoyHatEvent {
  uint32_t type;
  uint32_t timestamp;
  uint8_t which;
  uint8_t hat;
  uint8_t value;
  uint8_t padding1;
} BAJoyHatEvent;

#define BA_HAT_CENTERED 0x00
#define BA_HAT_UP 0x01
#define BA_HAT_RIGHT 0x02
#define BA_HAT_DOWN 0x04
#define BA_HAT_LEFT 0x08
#define BA_HAT_RIGHTUP (BA_HAT_RIGHT | BA_HAT_UP)
#define BA_HAT_RIGHTDOWN (BA_HAT_RIGHT | BA_HAT_DOWN)
#define BA_HAT_LEFTUP (BA_HAT_LEFT | BA_HAT_UP)
#define BA_HAT_LEFTDOWN (BA_HAT_LEFT | BA_HAT_DOWN)

typedef struct BAMouseMotionEvent {
  uint32_t type;
  uint32_t timestamp;
  uint32_t windowID;
  uint8_t state;
  uint8_t padding1;
  uint8_t padding2;
  uint8_t padding3;
  int x;
  int y;
  int xrel;
  int yrel;
} BAMouseMotionEvent;

typedef struct BAJoyButtonEvent {
  uint32_t type;
  uint32_t timestamp;
  uint8_t which;
  uint8_t button;
  uint8_t state;
  uint8_t padding1;
} BAJoyButtonEvent;

typedef struct BAMouseWheelEvent {
  uint32_t type;
  uint32_t timestamp;
  uint32_t windowID;
  int x;
  int y;
} BAMouseWheelEvent;

typedef struct BAMouseButtonEvent {
  uint32_t type;
  uint32_t timestamp;
  uint32_t windowID;
  uint8_t button;
  uint8_t state;
  uint8_t padding1;
  uint8_t padding2;
  int x;
  int y;
} BAMouseButtonEvent;

#define BA_BUTTON(X) (1 << ((X) - 1))
#define BA_BUTTON_LEFT 1
#define BA_BUTTON_MIDDLE 2
#define BA_BUTTON_RIGHT 3
#define BA_BUTTON_X1 4
#define BA_BUTTON_X2 5
#define BA_BUTTON_LMASK BA_BUTTON(BA_BUTTON_LEFT)
#define BA_BUTTON_MMASK BA_BUTTON(BA_BUTTON_MIDDLE)
#define BA_BUTTON_RMASK BA_BUTTON(BA_BUTTON_RIGHT)
#define BA_BUTTON_X1MASK BA_BUTTON(BA_BUTTON_X1)
#define BA_BUTTON_X2MASK BA_BUTTON(BA_BUTTON_X2)

#define BA_TEXTINPUTEVENT_TEXT_SIZE (32)

typedef struct BATextInputEvent {
  uint32_t type;
  uint32_t timestamp;
  uint32_t windowID;
  char text[BA_TEXTINPUTEVENT_TEXT_SIZE];
} BATextInputEvent;

typedef struct BAKeyboardEvent {
  uint32_t type;
  uint32_t timestamp;
  uint32_t windowID;
  uint8_t state;
  uint8_t repeat;
  uint8_t padding2;
  uint8_t padding3;
  BAKeysym keysym;
} BAKeyboardEvent;

typedef union BAEvent {
  uint32_t type;
  BAKeyboardEvent key;
  BATextInputEvent text;
  BAMouseMotionEvent motion;
  BAMouseButtonEvent button;
  BAMouseWheelEvent wheel;
  BAJoyAxisEvent jaxis;
  BAJoyHatEvent jhat;
  BAJoyButtonEvent jbutton;
} BAEvent;

#endif  // BALLISTICA_SHARED_FOUNDATION_INPUT_TYPES_H_
