# Released under the MIT License. See LICENSE for details.
#
# AUTO-GENERATED by bacommon.langstr codegen; do not edit by hand.
"""Type-safe language-string accessors for a-0.bamvpstrings.260626.

Client-side authoring wrapper for the bamvpstrings test package, used to
build doc-ui-v2 documents locally (see ``bauiv1lib.docuitest``). This is a
hand-vendored preview of what the server-side wrapper generator will emit;
the language values themselves arrive at render time through the asset
package machinery, exactly as texture/mesh data does for the live-asset
wrappers.
"""

from typing import TYPE_CHECKING

from bacommon.langstr import LangStrDir

__asset_package__ = 'a-0.bamvpstrings.260626'

if TYPE_CHECKING:
    from bacommon.langstr import Lstr, WrapperTree

    class StringsGroup:
        """Type-safe language-string accessors (strings)."""

        def mvpapples(self, *, apples: int) -> Lstr: ...

        mvpbanana: Lstr

        def mvpbananacount(self, *, bananas: int) -> Lstr: ...

        mvpcolor: Lstr
        mvpfarewell: Lstr
        mvpgreeting: Lstr

        def mvphello(self, *, player: str | Lstr) -> Lstr: ...

    class StringsLibrary:
        """Type-safe language-string accessors (library root)."""

        strings: StringsGroup

    strings: StringsLibrary

_TREE: WrapperTree = {
    'strings': {
        'mvpapples': ('apples',),
        'mvpbanana': (),
        'mvpbananacount': ('bananas',),
        'mvpcolor': (),
        'mvpfarewell': (),
        'mvpgreeting': (),
        'mvphello': ('player',),
    }
}

if not TYPE_CHECKING:
    strings = LangStrDir(__asset_package__, _TREE)
