# Released under the MIT License. See LICENSE for details.
#
"""Asset-package wrapper for ``a-0.babuiltinassets.260617`` (bauiv1).

Auto-generated; do not edit by hand.
"""

# ba_meta require api 9
# ba_meta require asset-package a-0.babuiltinassets.260617
# pylint: disable=useless-suppression
# pylint: disable=too-many-lines
# pylint: disable=too-few-public-methods, disallowed-name
from typing import TYPE_CHECKING

from bauiv1._assetwrap import AssetDir

if TYPE_CHECKING:
    import bauiv1

__asset_package__ = 'a-0.babuiltinassets.260617'
_APVERID = __asset_package__

_TREE = {
    'audio': {
        'blank': 's',
        'blip': 's',
        'cash_register': 's',
        'click01': 's',
        'cork_pop': 's',
        'deek': 's',
        'ding': 's',
        'error': 's',
        'gun_cocking': 's',
        'powerdown01': 's',
        'punch01': 's',
        'score_increase': 's',
        'sparkle01': 's',
        'sparkle02': 's',
        'sparkle03': 's',
        'swish': 's',
        'swish2': 's',
        'swish3': 's',
        'tap': 's',
        'ticking_crazy': 's',
    },
    'meshes': {
        'action_button_bottom': 'm',
        'action_button_left': 'm',
        'action_button_right': 'm',
        'action_button_top': 'm',
        'arrow_back': 'm',
        'arrow_front': 'm',
        'box': 'm',
        'boxing_glove': 'm',
        'button_back_opaque': 'm',
        'button_back_small_opaque': 'm',
        'button_back_small_transparent': 'm',
        'button_back_transparent': 'm',
        'button_large_opaque': 'm',
        'button_large_transparent': 'm',
        'button_larger_opaque': 'm',
        'button_larger_transparent': 'm',
        'button_medium_opaque': 'm',
        'button_medium_transparent': 'm',
        'button_small_opaque': 'm',
        'button_small_transparent': 'm',
        'button_square_opaque': 'm',
        'button_square_transparent': 'm',
        'button_tab_opaque': 'm',
        'button_tab_transparent': 'm',
        'check_transparent': 'm',
        'cross_out': 'm',
        'cylinder': 'm',
        'eye_ball': 'm',
        'eye_ball_iris': 'm',
        'eye_lid': 'm',
        'flag_pole': 'm',
        'flag_stand': 'm',
        'flash': 'm',
        'hair_tuft1': 'm',
        'hair_tuft1b': 'm',
        'hair_tuft2': 'm',
        'hair_tuft3': 'm',
        'hair_tuft4': 'm',
        'image16x1': 'm',
        'image1x1': 'm',
        'image1x1_full_screen': 'm',
        'image1x1_vrfull_screen': 'm',
        'image2x1': 'm',
        'image4x1': 'm',
        'locator': 'm',
        'locator_box': 'm',
        'locator_circle': 'm',
        'locator_circle_outline': 'm',
        'overlay_guide': 'm',
        'scorch': 'm',
        'scroll_bar_thumb_opaque': 'm',
        'scroll_bar_thumb_short_opaque': 'm',
        'scroll_bar_thumb_short_simple': 'm',
        'scroll_bar_thumb_short_transparent': 'm',
        'scroll_bar_thumb_simple': 'm',
        'scroll_bar_thumb_transparent': 'm',
        'scroll_bar_trough_transparent': 'm',
        'shield': 'm',
        'shock_wave': 'm',
        'shrapnel1': 'm',
        'shrapnel_board': 'm',
        'shrapnel_slime': 'm',
        'soft_edge_inside': 'm',
        'soft_edge_outside': 'm',
        'text_box_transparent': 'm',
        'vr_fade': 'm',
        'vr_overlay': 'm',
        'window_hsmall_vmed_opaque': 'm',
        'window_hsmall_vmed_transparent': 'm',
        'window_hsmall_vsmall_opaque': 'm',
        'window_hsmall_vsmall_transparent': 'm',
        'wing': 'm',
    },
    'textures': {
        'action_buttons': 't',
        'arrow': 't',
        'back_icon': 't',
        'black': 't',
        'bomb_button': 't',
        'boxing_gloves_color': 't',
        'button_square': 't',
        'button_square_wide': 't',
        'character_icon_mask': 't',
        'circle': 't',
        'circle_no_alpha': 't',
        'circle_outline': 't',
        'circle_outline_no_alpha': 't',
        'circle_shadow': 't',
        'circle_soft': 't',
        'cursor': 't',
        'explosion': 't',
        'eye_color': 't',
        'eye_color_tint_mask': 't',
        'flag_pole_color': 't',
        'font_big': 't',
        'font_extras': 't',
        'font_extras2': 't',
        'font_extras3': 't',
        'font_extras4': 't',
        'font_extras5': 't',
        'font_small0': 't',
        'font_small1': 't',
        'font_small2': 't',
        'font_small3': 't',
        'font_small4': 't',
        'font_small5': 't',
        'font_small6': 't',
        'font_small7': 't',
        'fuse': 't',
        'glow': 't',
        'light': 't',
        'light_sharp': 't',
        'light_soft': 't',
        'menu_button': 't',
        'nub': 't',
        'ouya_abutton': 't',
        'page_left_right': 't',
        'rgb_stripes': 't',
        'scorch': 't',
        'scorch_big': 't',
        'scroll_widget': 't',
        'scroll_widget_glow': 't',
        'shadow': 't',
        'shadow_sharp': 't',
        'shadow_soft': 't',
        'shield': 't',
        'shrapnel1_color': 't',
        'smoke': 't',
        'soft_rect': 't',
        'soft_rect2': 't',
        'soft_rect_vertical': 't',
        'sparks': 't',
        'spinner': 't',
        'spinner0': 't',
        'spinner1': 't',
        'spinner10': 't',
        'spinner11': 't',
        'spinner2': 't',
        'spinner3': 't',
        'spinner4': 't',
        'spinner5': 't',
        'spinner6': 't',
        'spinner7': 't',
        'spinner8': 't',
        'spinner9': 't',
        'start_button': 't',
        'text_clear_button': 't',
        'touch_arrows': 't',
        'touch_arrows_actions': 't',
        'ui_atlas': 't',
        'ui_atlas2': 't',
        'users_button': 't',
        'white': 't',
        'window_hsmall_vmed': 't',
        'window_hsmall_vsmall': 't',
        'wings': 't',
    },
}


if TYPE_CHECKING:

    class _Audio:
        blank: bauiv1.Sound
        blip: bauiv1.Sound
        cash_register: bauiv1.Sound
        click01: bauiv1.Sound
        cork_pop: bauiv1.Sound
        deek: bauiv1.Sound
        ding: bauiv1.Sound
        error: bauiv1.Sound
        gun_cocking: bauiv1.Sound
        powerdown01: bauiv1.Sound
        punch01: bauiv1.Sound
        score_increase: bauiv1.Sound
        sparkle01: bauiv1.Sound
        sparkle02: bauiv1.Sound
        sparkle03: bauiv1.Sound
        swish: bauiv1.Sound
        swish2: bauiv1.Sound
        swish3: bauiv1.Sound
        tap: bauiv1.Sound
        ticking_crazy: bauiv1.Sound

    class _Meshes:
        action_button_bottom: bauiv1.Mesh
        action_button_left: bauiv1.Mesh
        action_button_right: bauiv1.Mesh
        action_button_top: bauiv1.Mesh
        arrow_back: bauiv1.Mesh
        arrow_front: bauiv1.Mesh
        box: bauiv1.Mesh
        boxing_glove: bauiv1.Mesh
        button_back_opaque: bauiv1.Mesh
        button_back_small_opaque: bauiv1.Mesh
        button_back_small_transparent: bauiv1.Mesh
        button_back_transparent: bauiv1.Mesh
        button_large_opaque: bauiv1.Mesh
        button_large_transparent: bauiv1.Mesh
        button_larger_opaque: bauiv1.Mesh
        button_larger_transparent: bauiv1.Mesh
        button_medium_opaque: bauiv1.Mesh
        button_medium_transparent: bauiv1.Mesh
        button_small_opaque: bauiv1.Mesh
        button_small_transparent: bauiv1.Mesh
        button_square_opaque: bauiv1.Mesh
        button_square_transparent: bauiv1.Mesh
        button_tab_opaque: bauiv1.Mesh
        button_tab_transparent: bauiv1.Mesh
        check_transparent: bauiv1.Mesh
        cross_out: bauiv1.Mesh
        cylinder: bauiv1.Mesh
        eye_ball: bauiv1.Mesh
        eye_ball_iris: bauiv1.Mesh
        eye_lid: bauiv1.Mesh
        flag_pole: bauiv1.Mesh
        flag_stand: bauiv1.Mesh
        flash: bauiv1.Mesh
        hair_tuft1: bauiv1.Mesh
        hair_tuft1b: bauiv1.Mesh
        hair_tuft2: bauiv1.Mesh
        hair_tuft3: bauiv1.Mesh
        hair_tuft4: bauiv1.Mesh
        image16x1: bauiv1.Mesh
        image1x1: bauiv1.Mesh
        image1x1_full_screen: bauiv1.Mesh
        image1x1_vrfull_screen: bauiv1.Mesh
        image2x1: bauiv1.Mesh
        image4x1: bauiv1.Mesh
        locator: bauiv1.Mesh
        locator_box: bauiv1.Mesh
        locator_circle: bauiv1.Mesh
        locator_circle_outline: bauiv1.Mesh
        overlay_guide: bauiv1.Mesh
        scorch: bauiv1.Mesh
        scroll_bar_thumb_opaque: bauiv1.Mesh
        scroll_bar_thumb_short_opaque: bauiv1.Mesh
        scroll_bar_thumb_short_simple: bauiv1.Mesh
        scroll_bar_thumb_short_transparent: bauiv1.Mesh
        scroll_bar_thumb_simple: bauiv1.Mesh
        scroll_bar_thumb_transparent: bauiv1.Mesh
        scroll_bar_trough_transparent: bauiv1.Mesh
        shield: bauiv1.Mesh
        shock_wave: bauiv1.Mesh
        shrapnel1: bauiv1.Mesh
        shrapnel_board: bauiv1.Mesh
        shrapnel_slime: bauiv1.Mesh
        soft_edge_inside: bauiv1.Mesh
        soft_edge_outside: bauiv1.Mesh
        text_box_transparent: bauiv1.Mesh
        vr_fade: bauiv1.Mesh
        vr_overlay: bauiv1.Mesh
        window_hsmall_vmed_opaque: bauiv1.Mesh
        window_hsmall_vmed_transparent: bauiv1.Mesh
        window_hsmall_vsmall_opaque: bauiv1.Mesh
        window_hsmall_vsmall_transparent: bauiv1.Mesh
        wing: bauiv1.Mesh

    class _Textures:
        action_buttons: bauiv1.Texture
        arrow: bauiv1.Texture
        back_icon: bauiv1.Texture
        black: bauiv1.Texture
        bomb_button: bauiv1.Texture
        boxing_gloves_color: bauiv1.Texture
        button_square: bauiv1.Texture
        button_square_wide: bauiv1.Texture
        character_icon_mask: bauiv1.Texture
        circle: bauiv1.Texture
        circle_no_alpha: bauiv1.Texture
        circle_outline: bauiv1.Texture
        circle_outline_no_alpha: bauiv1.Texture
        circle_shadow: bauiv1.Texture
        circle_soft: bauiv1.Texture
        cursor: bauiv1.Texture
        explosion: bauiv1.Texture
        eye_color: bauiv1.Texture
        eye_color_tint_mask: bauiv1.Texture
        flag_pole_color: bauiv1.Texture
        font_big: bauiv1.Texture
        font_extras: bauiv1.Texture
        font_extras2: bauiv1.Texture
        font_extras3: bauiv1.Texture
        font_extras4: bauiv1.Texture
        font_extras5: bauiv1.Texture
        font_small0: bauiv1.Texture
        font_small1: bauiv1.Texture
        font_small2: bauiv1.Texture
        font_small3: bauiv1.Texture
        font_small4: bauiv1.Texture
        font_small5: bauiv1.Texture
        font_small6: bauiv1.Texture
        font_small7: bauiv1.Texture
        fuse: bauiv1.Texture
        glow: bauiv1.Texture
        light: bauiv1.Texture
        light_sharp: bauiv1.Texture
        light_soft: bauiv1.Texture
        menu_button: bauiv1.Texture
        nub: bauiv1.Texture
        ouya_abutton: bauiv1.Texture
        page_left_right: bauiv1.Texture
        rgb_stripes: bauiv1.Texture
        scorch: bauiv1.Texture
        scorch_big: bauiv1.Texture
        scroll_widget: bauiv1.Texture
        scroll_widget_glow: bauiv1.Texture
        shadow: bauiv1.Texture
        shadow_sharp: bauiv1.Texture
        shadow_soft: bauiv1.Texture
        shield: bauiv1.Texture
        shrapnel1_color: bauiv1.Texture
        smoke: bauiv1.Texture
        soft_rect: bauiv1.Texture
        soft_rect2: bauiv1.Texture
        soft_rect_vertical: bauiv1.Texture
        sparks: bauiv1.Texture
        spinner: bauiv1.Texture
        spinner0: bauiv1.Texture
        spinner1: bauiv1.Texture
        spinner10: bauiv1.Texture
        spinner11: bauiv1.Texture
        spinner2: bauiv1.Texture
        spinner3: bauiv1.Texture
        spinner4: bauiv1.Texture
        spinner5: bauiv1.Texture
        spinner6: bauiv1.Texture
        spinner7: bauiv1.Texture
        spinner8: bauiv1.Texture
        spinner9: bauiv1.Texture
        start_button: bauiv1.Texture
        text_clear_button: bauiv1.Texture
        touch_arrows: bauiv1.Texture
        touch_arrows_actions: bauiv1.Texture
        ui_atlas: bauiv1.Texture
        ui_atlas2: bauiv1.Texture
        users_button: bauiv1.Texture
        white: bauiv1.Texture
        window_hsmall_vmed: bauiv1.Texture
        window_hsmall_vsmall: bauiv1.Texture
        wings: bauiv1.Texture

    audio: _Audio
    meshes: _Meshes
    textures: _Textures
else:
    audio = AssetDir(_APVERID, _TREE['audio'], 'audio')
    meshes = AssetDir(_APVERID, _TREE['meshes'], 'meshes')
    textures = AssetDir(_APVERID, _TREE['textures'], 'textures')
