# Released under the MIT License. See LICENSE for details.
#
# Auto-generated; do not edit by hand.
"""Asset-package wrapper for ``a-0.bastdassets.260620`` (bauiv1).

All assets for classic bombsquad.
"""

# ba_meta require api 9
# ba_meta require asset-package a-0.bastdassets.260620

# pylint: disable=useless-suppression
# pylint: disable=too-many-lines
# pylint: disable=too-few-public-methods, disallowed-name

__asset_package__ = 'a-0.bastdassets.260620'

from typing import TYPE_CHECKING

from bauiv1._assetwrap import AssetDir

if TYPE_CHECKING:
    import bauiv1

    class AudioGroup:
        """Asset-group type; see source for the full list."""

        achievement: bauiv1.Sound
        action_hero1: bauiv1.Sound
        action_hero2: bauiv1.Sound
        action_hero3: bauiv1.Sound
        action_hero4: bauiv1.Sound
        action_hero_death: bauiv1.Sound
        action_hero_fall: bauiv1.Sound
        action_hero_hit1: bauiv1.Sound
        action_hero_hit2: bauiv1.Sound
        activate_beep: bauiv1.Sound
        agent1: bauiv1.Sound
        agent2: bauiv1.Sound
        agent3: bauiv1.Sound
        agent4: bauiv1.Sound
        agent_death: bauiv1.Sound
        agent_fall: bauiv1.Sound
        agent_hit1: bauiv1.Sound
        agent_hit2: bauiv1.Sound
        alarm: bauiv1.Sound
        ali1: bauiv1.Sound
        ali2: bauiv1.Sound
        ali3: bauiv1.Sound
        ali4: bauiv1.Sound
        ali_death: bauiv1.Sound
        ali_fall: bauiv1.Sound
        ali_hit1: bauiv1.Sound
        ali_hit2: bauiv1.Sound
        alien1: bauiv1.Sound
        alien2: bauiv1.Sound
        alien3: bauiv1.Sound
        alien4: bauiv1.Sound
        alien_death: bauiv1.Sound
        alien_fall: bauiv1.Sound
        alien_hit1: bauiv1.Sound
        alien_hit2: bauiv1.Sound
        announce_eight: bauiv1.Sound
        announce_five: bauiv1.Sound
        announce_four: bauiv1.Sound
        announce_nine: bauiv1.Sound
        announce_one: bauiv1.Sound
        announce_seven: bauiv1.Sound
        announce_six: bauiv1.Sound
        announce_ten: bauiv1.Sound
        announce_three: bauiv1.Sound
        announce_two: bauiv1.Sound
        assassin1: bauiv1.Sound
        assassin2: bauiv1.Sound
        assassin3: bauiv1.Sound
        assassin4: bauiv1.Sound
        assassin_death: bauiv1.Sound
        assassin_fall: bauiv1.Sound
        assassin_hit1: bauiv1.Sound
        assassin_hit2: bauiv1.Sound
        aww: bauiv1.Sound
        bear1: bauiv1.Sound
        bear2: bauiv1.Sound
        bear3: bauiv1.Sound
        bear4: bauiv1.Sound
        bear_death: bauiv1.Sound
        bear_fall: bauiv1.Sound
        bear_hit1: bauiv1.Sound
        bear_hit2: bauiv1.Sound
        bell_high: bauiv1.Sound
        bell_low: bauiv1.Sound
        bell_med: bauiv1.Sound
        big_impact: bauiv1.Sound
        big_impact2: bauiv1.Sound
        block: bauiv1.Sound
        bomb_drop01: bauiv1.Sound
        bomb_drop02: bauiv1.Sound
        bomb_roll01: bauiv1.Sound
        bones1: bauiv1.Sound
        bones2: bauiv1.Sound
        bones3: bauiv1.Sound
        bones_death: bauiv1.Sound
        bones_fall: bauiv1.Sound
        boo: bauiv1.Sound
        box_drop: bauiv1.Sound
        boxing_bell: bauiv1.Sound
        bunny1: bauiv1.Sound
        bunny2: bauiv1.Sound
        bunny3: bauiv1.Sound
        bunny4: bauiv1.Sound
        bunny_death: bauiv1.Sound
        bunny_fall: bauiv1.Sound
        bunny_hit1: bauiv1.Sound
        bunny_hit2: bauiv1.Sound
        bunny_jump: bauiv1.Sound
        cash_register2: bauiv1.Sound
        char_select_music: bauiv1.Sound
        cheer: bauiv1.Sound
        cork_pop2: bauiv1.Sound
        cowboy1: bauiv1.Sound
        cowboy2: bauiv1.Sound
        cowboy3: bauiv1.Sound
        cowboy4: bauiv1.Sound
        cowboy_death: bauiv1.Sound
        cowboy_fall: bauiv1.Sound
        cowboy_hit1: bauiv1.Sound
        cowboy_hit2: bauiv1.Sound
        crowd_chant: bauiv1.Sound
        cyborg1: bauiv1.Sound
        cyborg2: bauiv1.Sound
        cyborg3: bauiv1.Sound
        cyborg4: bauiv1.Sound
        cyborg_death: bauiv1.Sound
        cyborg_fall: bauiv1.Sound
        cyborg_hit1: bauiv1.Sound
        cyborg_hit2: bauiv1.Sound
        cymbal: bauiv1.Sound
        debris_fall: bauiv1.Sound
        deek2: bauiv1.Sound
        ding_small: bauiv1.Sound
        ding_small_high: bauiv1.Sound
        dripity: bauiv1.Sound
        drum_roll: bauiv1.Sound
        drum_roll_short: bauiv1.Sound
        explosion01: bauiv1.Sound
        explosion02: bauiv1.Sound
        explosion03: bauiv1.Sound
        explosion04: bauiv1.Sound
        explosion05: bauiv1.Sound
        fanfare: bauiv1.Sound
        flag_catcher_music: bauiv1.Sound
        flying_music: bauiv1.Sound
        foghorn: bauiv1.Sound
        foot_impact01: bauiv1.Sound
        foot_impact02: bauiv1.Sound
        foot_impact03: bauiv1.Sound
        forward_march_music: bauiv1.Sound
        freeze: bauiv1.Sound
        frosty01: bauiv1.Sound
        frosty02: bauiv1.Sound
        frosty03: bauiv1.Sound
        frosty04: bauiv1.Sound
        frosty05: bauiv1.Sound
        frosty_death: bauiv1.Sound
        frosty_fall: bauiv1.Sound
        frosty_hit01: bauiv1.Sound
        frosty_hit02: bauiv1.Sound
        frosty_hit03: bauiv1.Sound
        fuse01: bauiv1.Sound
        gasp: bauiv1.Sound
        gladiator1: bauiv1.Sound
        gladiator2: bauiv1.Sound
        gladiator3: bauiv1.Sound
        gladiator4: bauiv1.Sound
        gladiator_death: bauiv1.Sound
        gladiator_fall: bauiv1.Sound
        gladiator_hit1: bauiv1.Sound
        gladiator_hit2: bauiv1.Sound
        gong: bauiv1.Sound
        grand_romp_music: bauiv1.Sound
        gravel_skid: bauiv1.Sound
        health_powerup: bauiv1.Sound
        hiss: bauiv1.Sound
        impact_hard: bauiv1.Sound
        impact_hard2: bauiv1.Sound
        impact_hard3: bauiv1.Sound
        impact_medium: bauiv1.Sound
        impact_medium2: bauiv1.Sound
        jack01: bauiv1.Sound
        jack02: bauiv1.Sound
        jack03: bauiv1.Sound
        jack04: bauiv1.Sound
        jack05: bauiv1.Sound
        jack06: bauiv1.Sound
        jack_death01: bauiv1.Sound
        jack_fall01: bauiv1.Sound
        jack_hit01: bauiv1.Sound
        jack_hit02: bauiv1.Sound
        jack_hit03: bauiv1.Sound
        jack_hit04: bauiv1.Sound
        jack_hit05: bauiv1.Sound
        jack_hit06: bauiv1.Sound
        jack_hit07: bauiv1.Sound
        jumpsuit1: bauiv1.Sound
        jumpsuit2: bauiv1.Sound
        jumpsuit3: bauiv1.Sound
        jumpsuit4: bauiv1.Sound
        jumpsuit_death: bauiv1.Sound
        jumpsuit_fall: bauiv1.Sound
        jumpsuit_hit1: bauiv1.Sound
        jumpsuit_hit2: bauiv1.Sound
        kronk1: bauiv1.Sound
        kronk10: bauiv1.Sound
        kronk2: bauiv1.Sound
        kronk3: bauiv1.Sound
        kronk4: bauiv1.Sound
        kronk5: bauiv1.Sound
        kronk6: bauiv1.Sound
        kronk7: bauiv1.Sound
        kronk8: bauiv1.Sound
        kronk9: bauiv1.Sound
        kronk_death: bauiv1.Sound
        kronk_fall: bauiv1.Sound
        laser: bauiv1.Sound
        laser_reverse: bauiv1.Sound
        mel01: bauiv1.Sound
        mel02: bauiv1.Sound
        mel03: bauiv1.Sound
        mel04: bauiv1.Sound
        mel05: bauiv1.Sound
        mel06: bauiv1.Sound
        mel07: bauiv1.Sound
        mel08: bauiv1.Sound
        mel09: bauiv1.Sound
        mel10: bauiv1.Sound
        mel_death01: bauiv1.Sound
        mel_fall01: bauiv1.Sound
        menu_music: bauiv1.Sound
        metal_hit: bauiv1.Sound
        metal_skid: bauiv1.Sound
        nice: bauiv1.Sound
        ninja_attack1: bauiv1.Sound
        ninja_attack2: bauiv1.Sound
        ninja_attack3: bauiv1.Sound
        ninja_attack4: bauiv1.Sound
        ninja_attack5: bauiv1.Sound
        ninja_attack6: bauiv1.Sound
        ninja_attack7: bauiv1.Sound
        ninja_death1: bauiv1.Sound
        ninja_fall1: bauiv1.Sound
        ninja_hit1: bauiv1.Sound
        ninja_hit2: bauiv1.Sound
        ninja_hit3: bauiv1.Sound
        ninja_hit4: bauiv1.Sound
        ninja_hit5: bauiv1.Sound
        ninja_hit6: bauiv1.Sound
        ninja_hit7: bauiv1.Sound
        ninja_hit8: bauiv1.Sound
        old_lady1: bauiv1.Sound
        old_lady2: bauiv1.Sound
        old_lady3: bauiv1.Sound
        old_lady4: bauiv1.Sound
        old_lady_death: bauiv1.Sound
        old_lady_fall: bauiv1.Sound
        old_lady_hit1: bauiv1.Sound
        old_lady_hit2: bauiv1.Sound
        ooh: bauiv1.Sound
        opera_singer1: bauiv1.Sound
        opera_singer2: bauiv1.Sound
        opera_singer3: bauiv1.Sound
        opera_singer4: bauiv1.Sound
        opera_singer_death: bauiv1.Sound
        opera_singer_fall: bauiv1.Sound
        opera_singer_hit1: bauiv1.Sound
        opera_singer_hit2: bauiv1.Sound
        orchestra_hit: bauiv1.Sound
        orchestra_hit2: bauiv1.Sound
        orchestra_hit3: bauiv1.Sound
        orchestra_hit4: bauiv1.Sound
        orchestra_hit_big1: bauiv1.Sound
        orchestra_hit_big2: bauiv1.Sound
        penguin1: bauiv1.Sound
        penguin2: bauiv1.Sound
        penguin3: bauiv1.Sound
        penguin4: bauiv1.Sound
        penguin_death: bauiv1.Sound
        penguin_fall: bauiv1.Sound
        penguin_hit1: bauiv1.Sound
        penguin_hit2: bauiv1.Sound
        pixie1: bauiv1.Sound
        pixie2: bauiv1.Sound
        pixie3: bauiv1.Sound
        pixie4: bauiv1.Sound
        pixie_death: bauiv1.Sound
        pixie_fall: bauiv1.Sound
        pixie_hit1: bauiv1.Sound
        pixie_hit2: bauiv1.Sound
        player_death: bauiv1.Sound
        player_left: bauiv1.Sound
        pop01: bauiv1.Sound
        powerup01: bauiv1.Sound
        punch_strong01: bauiv1.Sound
        punch_strong02: bauiv1.Sound
        punch_swish: bauiv1.Sound
        punch_weak01: bauiv1.Sound
        race_beep1: bauiv1.Sound
        race_beep2: bauiv1.Sound
        ref_whistle: bauiv1.Sound
        rev_up: bauiv1.Sound
        robot1: bauiv1.Sound
        robot2: bauiv1.Sound
        robot3: bauiv1.Sound
        robot4: bauiv1.Sound
        robot_death: bauiv1.Sound
        robot_fall: bauiv1.Sound
        robot_hit1: bauiv1.Sound
        robot_hit2: bauiv1.Sound
        run_away_music: bauiv1.Sound
        santa01: bauiv1.Sound
        santa02: bauiv1.Sound
        santa03: bauiv1.Sound
        santa04: bauiv1.Sound
        santa05: bauiv1.Sound
        santa_death: bauiv1.Sound
        santa_fall: bauiv1.Sound
        santa_hit01: bauiv1.Sound
        santa_hit02: bauiv1.Sound
        santa_hit03: bauiv1.Sound
        santa_hit04: bauiv1.Sound
        scamper01: bauiv1.Sound
        scary_music: bauiv1.Sound
        score: bauiv1.Sound
        score_hit01: bauiv1.Sound
        score_hit02: bauiv1.Sound
        scores_epic_music: bauiv1.Sound
        shatter: bauiv1.Sound
        shield_down: bauiv1.Sound
        shield_hit: bauiv1.Sound
        shield_up: bauiv1.Sound
        skid01: bauiv1.Sound
        slow_epic_music: bauiv1.Sound
        spawn: bauiv1.Sound
        spaz_attack01: bauiv1.Sound
        spaz_attack02: bauiv1.Sound
        spaz_attack03: bauiv1.Sound
        spaz_attack04: bauiv1.Sound
        spaz_death01: bauiv1.Sound
        spaz_eff: bauiv1.Sound
        spaz_fall01: bauiv1.Sound
        spaz_impact01: bauiv1.Sound
        spaz_impact02: bauiv1.Sound
        spaz_impact03: bauiv1.Sound
        spaz_impact04: bauiv1.Sound
        spaz_jump01: bauiv1.Sound
        spaz_jump02: bauiv1.Sound
        spaz_jump03: bauiv1.Sound
        spaz_jump04: bauiv1.Sound
        spaz_ow: bauiv1.Sound
        spaz_pickup01: bauiv1.Sound
        spaz_scream01: bauiv1.Sound
        splatter: bauiv1.Sound
        sports_music: bauiv1.Sound
        sticky_impact: bauiv1.Sound
        super_punch: bauiv1.Sound
        superhero1: bauiv1.Sound
        superhero2: bauiv1.Sound
        superhero3: bauiv1.Sound
        superhero4: bauiv1.Sound
        superhero_death: bauiv1.Sound
        superhero_fall: bauiv1.Sound
        superhero_hit1: bauiv1.Sound
        superhero_hit2: bauiv1.Sound
        survival_music: bauiv1.Sound
        swip: bauiv1.Sound
        swip2: bauiv1.Sound
        techno_hit01: bauiv1.Sound
        tick: bauiv1.Sound
        ticking: bauiv1.Sound
        to_the_death_music: bauiv1.Sound
        trash_rummage: bauiv1.Sound
        victory_music: bauiv1.Sound
        warn_beep: bauiv1.Sound
        warn_beeps: bauiv1.Sound
        warrior1: bauiv1.Sound
        warrior2: bauiv1.Sound
        warrior3: bauiv1.Sound
        warrior4: bauiv1.Sound
        warrior_death: bauiv1.Sound
        warrior_fall: bauiv1.Sound
        warrior_hit1: bauiv1.Sound
        warrior_hit2: bauiv1.Sound
        when_johnny_comes_marching_home_music: bauiv1.Sound
        witch1: bauiv1.Sound
        witch2: bauiv1.Sound
        witch3: bauiv1.Sound
        witch4: bauiv1.Sound
        witch_death: bauiv1.Sound
        witch_fall: bauiv1.Sound
        witch_hit1: bauiv1.Sound
        witch_hit2: bauiv1.Sound
        wizard1: bauiv1.Sound
        wizard2: bauiv1.Sound
        wizard3: bauiv1.Sound
        wizard4: bauiv1.Sound
        wizard_death: bauiv1.Sound
        wizard_fall: bauiv1.Sound
        wizard_hit1: bauiv1.Sound
        wizard_hit2: bauiv1.Sound
        woo: bauiv1.Sound
        woo2: bauiv1.Sound
        woo3: bauiv1.Sound
        wood_debris_fall: bauiv1.Sound
        wow: bauiv1.Sound
        wrestler1: bauiv1.Sound
        wrestler2: bauiv1.Sound
        wrestler3: bauiv1.Sound
        wrestler4: bauiv1.Sound
        wrestler_death: bauiv1.Sound
        wrestler_fall: bauiv1.Sound
        wrestler_hit1: bauiv1.Sound
        wrestler_hit2: bauiv1.Sound
        yeah: bauiv1.Sound
        zoe_attack01: bauiv1.Sound
        zoe_attack02: bauiv1.Sound
        zoe_attack03: bauiv1.Sound
        zoe_attack04: bauiv1.Sound
        zoe_death01: bauiv1.Sound
        zoe_eff: bauiv1.Sound
        zoe_fall01: bauiv1.Sound
        zoe_impact01: bauiv1.Sound
        zoe_impact02: bauiv1.Sound
        zoe_impact03: bauiv1.Sound
        zoe_impact04: bauiv1.Sound
        zoe_jump01: bauiv1.Sound
        zoe_jump02: bauiv1.Sound
        zoe_jump03: bauiv1.Sound
        zoe_ow: bauiv1.Sound
        zoe_pickup01: bauiv1.Sound
        zoe_scream01: bauiv1.Sound

    class MeshesGroup:
        """Asset-group type; see source for the full list."""

        achievement_outline: bauiv1.Mesh
        action_hero_fore_arm: bauiv1.Mesh
        action_hero_hand: bauiv1.Mesh
        action_hero_head: bauiv1.Mesh
        action_hero_lower_leg: bauiv1.Mesh
        action_hero_pelvis: bauiv1.Mesh
        action_hero_toes: bauiv1.Mesh
        action_hero_torso: bauiv1.Mesh
        action_hero_upper_arm: bauiv1.Mesh
        action_hero_upper_leg: bauiv1.Mesh
        agent_fore_arm: bauiv1.Mesh
        agent_hand: bauiv1.Mesh
        agent_head: bauiv1.Mesh
        agent_lower_leg: bauiv1.Mesh
        agent_pelvis: bauiv1.Mesh
        agent_toes: bauiv1.Mesh
        agent_torso: bauiv1.Mesh
        agent_upper_arm: bauiv1.Mesh
        agent_upper_leg: bauiv1.Mesh
        ali_fore_arm: bauiv1.Mesh
        ali_hand: bauiv1.Mesh
        ali_head: bauiv1.Mesh
        ali_lower_leg: bauiv1.Mesh
        ali_pelvis: bauiv1.Mesh
        ali_toes: bauiv1.Mesh
        ali_torso: bauiv1.Mesh
        ali_upper_arm: bauiv1.Mesh
        ali_upper_leg: bauiv1.Mesh
        alien_fore_arm: bauiv1.Mesh
        alien_hand: bauiv1.Mesh
        alien_head: bauiv1.Mesh
        alien_lower_leg: bauiv1.Mesh
        alien_pelvis: bauiv1.Mesh
        alien_toes: bauiv1.Mesh
        alien_torso: bauiv1.Mesh
        alien_upper_arm: bauiv1.Mesh
        alien_upper_leg: bauiv1.Mesh
        always_land_bg: bauiv1.Mesh
        always_land_level: bauiv1.Mesh
        always_land_level_bottom: bauiv1.Mesh
        always_land_vrfill_mound: bauiv1.Mesh
        angry_computer_transparent: bauiv1.Mesh
        assassin_fore_arm: bauiv1.Mesh
        assassin_hand: bauiv1.Mesh
        assassin_head: bauiv1.Mesh
        assassin_lower_leg: bauiv1.Mesh
        assassin_pelvis: bauiv1.Mesh
        assassin_toes: bauiv1.Mesh
        assassin_torso: bauiv1.Mesh
        assassin_upper_arm: bauiv1.Mesh
        assassin_upper_leg: bauiv1.Mesh
        bear_fore_arm: bauiv1.Mesh
        bear_hand: bauiv1.Mesh
        bear_head: bauiv1.Mesh
        bear_lower_leg: bauiv1.Mesh
        bear_pelvis: bauiv1.Mesh
        bear_toes: bauiv1.Mesh
        bear_torso: bauiv1.Mesh
        bear_upper_arm: bauiv1.Mesh
        bear_upper_leg: bauiv1.Mesh
        big_g: bauiv1.Mesh
        big_gbottom: bauiv1.Mesh
        bomb: bauiv1.Mesh
        bomb_sticky: bauiv1.Mesh
        bones_fore_arm: bauiv1.Mesh
        bones_hand: bauiv1.Mesh
        bones_head: bauiv1.Mesh
        bones_lower_leg: bauiv1.Mesh
        bones_pelvis: bauiv1.Mesh
        bones_toes: bauiv1.Mesh
        bones_torso: bauiv1.Mesh
        bones_upper_arm: bauiv1.Mesh
        bones_upper_leg: bauiv1.Mesh
        bridgit_level_bottom: bauiv1.Mesh
        bridgit_level_top: bauiv1.Mesh
        bunny_fore_arm: bauiv1.Mesh
        bunny_hand: bauiv1.Mesh
        bunny_head: bauiv1.Mesh
        bunny_lower_leg: bauiv1.Mesh
        bunny_pelvis: bauiv1.Mesh
        bunny_toes: bauiv1.Mesh
        bunny_torso: bauiv1.Mesh
        bunny_upper_arm: bauiv1.Mesh
        bunny_upper_leg: bauiv1.Mesh
        button_null: bauiv1.Mesh
        courtyard_level: bauiv1.Mesh
        courtyard_level_bottom: bauiv1.Mesh
        cowboy_fore_arm: bauiv1.Mesh
        cowboy_hand: bauiv1.Mesh
        cowboy_head: bauiv1.Mesh
        cowboy_lower_leg: bauiv1.Mesh
        cowboy_pelvis: bauiv1.Mesh
        cowboy_toes: bauiv1.Mesh
        cowboy_torso: bauiv1.Mesh
        cowboy_upper_arm: bauiv1.Mesh
        cowboy_upper_leg: bauiv1.Mesh
        crag_castle_level: bauiv1.Mesh
        crag_castle_level_bottom: bauiv1.Mesh
        crag_castle_vrfill_mound: bauiv1.Mesh
        currency_meter: bauiv1.Mesh
        currency_plus_button: bauiv1.Mesh
        cyborg_fore_arm: bauiv1.Mesh
        cyborg_hand: bauiv1.Mesh
        cyborg_head: bauiv1.Mesh
        cyborg_lower_leg: bauiv1.Mesh
        cyborg_pelvis: bauiv1.Mesh
        cyborg_toes: bauiv1.Mesh
        cyborg_torso: bauiv1.Mesh
        cyborg_upper_arm: bauiv1.Mesh
        cyborg_upper_leg: bauiv1.Mesh
        doom_shroom_bg: bauiv1.Mesh
        doom_shroom_level: bauiv1.Mesh
        doom_shroom_stem: bauiv1.Mesh
        doom_shroom_vrfill: bauiv1.Mesh
        egg: bauiv1.Mesh
        football_stadium: bauiv1.Mesh
        football_stadium_vrfill: bauiv1.Mesh
        frame_inset: bauiv1.Mesh
        frosty_fore_arm: bauiv1.Mesh
        frosty_hand: bauiv1.Mesh
        frosty_head: bauiv1.Mesh
        frosty_lower_leg: bauiv1.Mesh
        frosty_pelvis: bauiv1.Mesh
        frosty_toes: bauiv1.Mesh
        frosty_torso: bauiv1.Mesh
        frosty_upper_arm: bauiv1.Mesh
        frosty_upper_leg: bauiv1.Mesh
        gladiator_fore_arm: bauiv1.Mesh
        gladiator_hand: bauiv1.Mesh
        gladiator_head: bauiv1.Mesh
        gladiator_lower_leg: bauiv1.Mesh
        gladiator_pelvis: bauiv1.Mesh
        gladiator_toes: bauiv1.Mesh
        gladiator_torso: bauiv1.Mesh
        gladiator_upper_arm: bauiv1.Mesh
        gladiator_upper_leg: bauiv1.Mesh
        heart_opaque: bauiv1.Mesh
        heart_transparent: bauiv1.Mesh
        hockey_stadium_inner: bauiv1.Mesh
        hockey_stadium_outer: bauiv1.Mesh
        hockey_stadium_stands: bauiv1.Mesh
        image2x1_vertical: bauiv1.Mesh
        impact_bomb: bauiv1.Mesh
        jack_fore_arm: bauiv1.Mesh
        jack_hand: bauiv1.Mesh
        jack_head: bauiv1.Mesh
        jack_lower_leg: bauiv1.Mesh
        jack_toes: bauiv1.Mesh
        jack_torso: bauiv1.Mesh
        jack_upper_arm: bauiv1.Mesh
        jack_upper_leg: bauiv1.Mesh
        jumpsuit_fore_arm: bauiv1.Mesh
        jumpsuit_hand: bauiv1.Mesh
        jumpsuit_head: bauiv1.Mesh
        jumpsuit_lower_leg: bauiv1.Mesh
        jumpsuit_pelvis: bauiv1.Mesh
        jumpsuit_toes: bauiv1.Mesh
        jumpsuit_torso: bauiv1.Mesh
        jumpsuit_upper_arm: bauiv1.Mesh
        jumpsuit_upper_leg: bauiv1.Mesh
        kronk_fore_arm: bauiv1.Mesh
        kronk_hand: bauiv1.Mesh
        kronk_head: bauiv1.Mesh
        kronk_lower_leg: bauiv1.Mesh
        kronk_pelvis: bauiv1.Mesh
        kronk_toes: bauiv1.Mesh
        kronk_torso: bauiv1.Mesh
        kronk_upper_arm: bauiv1.Mesh
        kronk_upper_leg: bauiv1.Mesh
        lake_frigid: bauiv1.Mesh
        lake_frigid_reflections: bauiv1.Mesh
        lake_frigid_top: bauiv1.Mesh
        lake_frigid_vrfill: bauiv1.Mesh
        land_mine: bauiv1.Mesh
        level_select_button_opaque: bauiv1.Mesh
        level_select_button_transparent: bauiv1.Mesh
        logo: bauiv1.Mesh
        logo_transparent: bauiv1.Mesh
        mel_fore_arm: bauiv1.Mesh
        mel_hand: bauiv1.Mesh
        mel_head: bauiv1.Mesh
        mel_lower_leg: bauiv1.Mesh
        mel_toes: bauiv1.Mesh
        mel_torso: bauiv1.Mesh
        mel_upper_arm: bauiv1.Mesh
        mel_upper_leg: bauiv1.Mesh
        meter_transparent: bauiv1.Mesh
        monkey_face_level: bauiv1.Mesh
        monkey_face_level_bottom: bauiv1.Mesh
        nature_background: bauiv1.Mesh
        nature_background_vrfill: bauiv1.Mesh
        neo_spaz_fore_arm: bauiv1.Mesh
        neo_spaz_hand: bauiv1.Mesh
        neo_spaz_head: bauiv1.Mesh
        neo_spaz_lower_leg: bauiv1.Mesh
        neo_spaz_pelvis: bauiv1.Mesh
        neo_spaz_toes: bauiv1.Mesh
        neo_spaz_torso: bauiv1.Mesh
        neo_spaz_upper_arm: bauiv1.Mesh
        neo_spaz_upper_leg: bauiv1.Mesh
        ninja_fore_arm: bauiv1.Mesh
        ninja_hand: bauiv1.Mesh
        ninja_head: bauiv1.Mesh
        ninja_lower_leg: bauiv1.Mesh
        ninja_pelvis: bauiv1.Mesh
        ninja_toes: bauiv1.Mesh
        ninja_torso: bauiv1.Mesh
        ninja_upper_arm: bauiv1.Mesh
        ninja_upper_leg: bauiv1.Mesh
        old_lady_fore_arm: bauiv1.Mesh
        old_lady_hand: bauiv1.Mesh
        old_lady_head: bauiv1.Mesh
        old_lady_lower_leg: bauiv1.Mesh
        old_lady_pelvis: bauiv1.Mesh
        old_lady_toes: bauiv1.Mesh
        old_lady_torso: bauiv1.Mesh
        old_lady_upper_arm: bauiv1.Mesh
        old_lady_upper_leg: bauiv1.Mesh
        opera_singer_fore_arm: bauiv1.Mesh
        opera_singer_hand: bauiv1.Mesh
        opera_singer_head: bauiv1.Mesh
        opera_singer_lower_leg: bauiv1.Mesh
        opera_singer_pelvis: bauiv1.Mesh
        opera_singer_toes: bauiv1.Mesh
        opera_singer_torso: bauiv1.Mesh
        opera_singer_upper_arm: bauiv1.Mesh
        opera_singer_upper_leg: bauiv1.Mesh
        penguin_fore_arm: bauiv1.Mesh
        penguin_hand: bauiv1.Mesh
        penguin_head: bauiv1.Mesh
        penguin_lower_leg: bauiv1.Mesh
        penguin_pelvis: bauiv1.Mesh
        penguin_toes: bauiv1.Mesh
        penguin_torso: bauiv1.Mesh
        penguin_upper_arm: bauiv1.Mesh
        penguin_upper_leg: bauiv1.Mesh
        pixie_fore_arm: bauiv1.Mesh
        pixie_hand: bauiv1.Mesh
        pixie_head: bauiv1.Mesh
        pixie_lower_leg: bauiv1.Mesh
        pixie_pelvis: bauiv1.Mesh
        pixie_toes: bauiv1.Mesh
        pixie_torso: bauiv1.Mesh
        pixie_upper_arm: bauiv1.Mesh
        pixie_upper_leg: bauiv1.Mesh
        plastic_eyes_transparent: bauiv1.Mesh
        player_lineup1_transparent: bauiv1.Mesh
        player_lineup2_transparent: bauiv1.Mesh
        player_lineup3_transparent: bauiv1.Mesh
        player_lineup4_transparent: bauiv1.Mesh
        powerup: bauiv1.Mesh
        powerup_simple: bauiv1.Mesh
        puck: bauiv1.Mesh
        rampage_bg: bauiv1.Mesh
        rampage_bg2: bauiv1.Mesh
        rampage_level: bauiv1.Mesh
        rampage_level_bottom: bauiv1.Mesh
        rampage_vrfill: bauiv1.Mesh
        robot_fore_arm: bauiv1.Mesh
        robot_hand: bauiv1.Mesh
        robot_head: bauiv1.Mesh
        robot_lower_leg: bauiv1.Mesh
        robot_pelvis: bauiv1.Mesh
        robot_toes: bauiv1.Mesh
        robot_torso: bauiv1.Mesh
        robot_upper_arm: bauiv1.Mesh
        robot_upper_leg: bauiv1.Mesh
        roundabout_level: bauiv1.Mesh
        roundabout_level_bottom: bauiv1.Mesh
        running_shoes: bauiv1.Mesh
        santa_fore_arm: bauiv1.Mesh
        santa_hand: bauiv1.Mesh
        santa_head: bauiv1.Mesh
        santa_lower_leg: bauiv1.Mesh
        santa_toes: bauiv1.Mesh
        santa_torso: bauiv1.Mesh
        santa_upper_arm: bauiv1.Mesh
        santa_upper_leg: bauiv1.Mesh
        scroll_widget_short: bauiv1.Mesh
        step_right_up_level: bauiv1.Mesh
        step_right_up_level_bottom: bauiv1.Mesh
        step_right_up_vrfill_mound: bauiv1.Mesh
        superhero_fore_arm: bauiv1.Mesh
        superhero_hand: bauiv1.Mesh
        superhero_head: bauiv1.Mesh
        superhero_lower_leg: bauiv1.Mesh
        superhero_pelvis: bauiv1.Mesh
        superhero_toes: bauiv1.Mesh
        superhero_torso: bauiv1.Mesh
        superhero_upper_arm: bauiv1.Mesh
        superhero_upper_leg: bauiv1.Mesh
        the_pad_bg: bauiv1.Mesh
        the_pad_bgsmall: bauiv1.Mesh
        the_pad_level: bauiv1.Mesh
        the_pad_level_bottom: bauiv1.Mesh
        the_pad_vrfill_bottom: bauiv1.Mesh
        the_pad_vrfill_mound: bauiv1.Mesh
        the_pad_vrfill_top: bauiv1.Mesh
        tip_top_bg: bauiv1.Mesh
        tip_top_level: bauiv1.Mesh
        tip_top_level_bottom: bauiv1.Mesh
        tnt: bauiv1.Mesh
        toolbar_backing: bauiv1.Mesh
        toolbar_backing_bottom: bauiv1.Mesh
        toolbar_backing_bottom2: bauiv1.Mesh
        toolbar_backing_opaque: bauiv1.Mesh
        toolbar_backing_top: bauiv1.Mesh
        toolbar_backing_top2: bauiv1.Mesh
        toolbar_backing_transparent: bauiv1.Mesh
        tower_dlevel: bauiv1.Mesh
        tower_dlevel_bottom: bauiv1.Mesh
        trees: bauiv1.Mesh
        warrior_fore_arm: bauiv1.Mesh
        warrior_hand: bauiv1.Mesh
        warrior_head: bauiv1.Mesh
        warrior_lower_leg: bauiv1.Mesh
        warrior_pelvis: bauiv1.Mesh
        warrior_toes: bauiv1.Mesh
        warrior_torso: bauiv1.Mesh
        warrior_upper_arm: bauiv1.Mesh
        warrior_upper_leg: bauiv1.Mesh
        window_bgblotch: bauiv1.Mesh
        witch_fore_arm: bauiv1.Mesh
        witch_hand: bauiv1.Mesh
        witch_head: bauiv1.Mesh
        witch_lower_leg: bauiv1.Mesh
        witch_pelvis: bauiv1.Mesh
        witch_toes: bauiv1.Mesh
        witch_torso: bauiv1.Mesh
        witch_upper_arm: bauiv1.Mesh
        witch_upper_leg: bauiv1.Mesh
        wizard_fore_arm: bauiv1.Mesh
        wizard_hand: bauiv1.Mesh
        wizard_head: bauiv1.Mesh
        wizard_lower_leg: bauiv1.Mesh
        wizard_pelvis: bauiv1.Mesh
        wizard_toes: bauiv1.Mesh
        wizard_torso: bauiv1.Mesh
        wizard_upper_arm: bauiv1.Mesh
        wizard_upper_leg: bauiv1.Mesh
        wrestler_fore_arm: bauiv1.Mesh
        wrestler_hand: bauiv1.Mesh
        wrestler_head: bauiv1.Mesh
        wrestler_lower_leg: bauiv1.Mesh
        wrestler_pelvis: bauiv1.Mesh
        wrestler_toes: bauiv1.Mesh
        wrestler_torso: bauiv1.Mesh
        wrestler_upper_arm: bauiv1.Mesh
        wrestler_upper_leg: bauiv1.Mesh
        zig_zag_level: bauiv1.Mesh
        zig_zag_level_bottom: bauiv1.Mesh
        zoe_fore_arm: bauiv1.Mesh
        zoe_hand: bauiv1.Mesh
        zoe_head: bauiv1.Mesh
        zoe_lower_leg: bauiv1.Mesh
        zoe_pelvis: bauiv1.Mesh
        zoe_toes: bauiv1.Mesh
        zoe_torso: bauiv1.Mesh
        zoe_upper_arm: bauiv1.Mesh
        zoe_upper_leg: bauiv1.Mesh

    class TexturesGroup:
        """Asset-group type; see source for the full list."""

        achievement_boxer: bauiv1.Texture
        achievement_cross_hair: bauiv1.Texture
        achievement_dual_wielding: bauiv1.Texture
        achievement_empty: bauiv1.Texture
        achievement_flawless_victory: bauiv1.Texture
        achievement_football_shutout: bauiv1.Texture
        achievement_football_victory: bauiv1.Texture
        achievement_free_loader: bauiv1.Texture
        achievement_got_the_moves: bauiv1.Texture
        achievement_in_control: bauiv1.Texture
        achievement_medal_large: bauiv1.Texture
        achievement_medal_medium: bauiv1.Texture
        achievement_medal_small: bauiv1.Texture
        achievement_mine: bauiv1.Texture
        achievement_off_you_go: bauiv1.Texture
        achievement_onslaught: bauiv1.Texture
        achievement_outline: bauiv1.Texture
        achievement_runaround: bauiv1.Texture
        achievement_sharing_is_caring: bauiv1.Texture
        achievement_stayin_alive: bauiv1.Texture
        achievement_super_punch: bauiv1.Texture
        achievement_team_player: bauiv1.Texture
        achievement_tnt: bauiv1.Texture
        achievement_wall: bauiv1.Texture
        achievements_icon: bauiv1.Texture
        action_hero_color: bauiv1.Texture
        action_hero_color_mask: bauiv1.Texture
        action_hero_icon: bauiv1.Texture
        action_hero_icon_color_mask: bauiv1.Texture
        advanced_icon: bauiv1.Texture
        agent_color: bauiv1.Texture
        agent_color_mask: bauiv1.Texture
        agent_icon: bauiv1.Texture
        agent_icon_color_mask: bauiv1.Texture
        ali_color: bauiv1.Texture
        ali_color_mask: bauiv1.Texture
        ali_icon: bauiv1.Texture
        ali_icon_color_mask: bauiv1.Texture
        ali_splash: bauiv1.Texture
        alien_color: bauiv1.Texture
        alien_color_mask: bauiv1.Texture
        alien_icon: bauiv1.Texture
        alien_icon_color_mask: bauiv1.Texture
        always_land_bgcolor: bauiv1.Texture
        always_land_level_color: bauiv1.Texture
        always_land_preview: bauiv1.Texture
        analog_stick: bauiv1.Texture
        assassin_color: bauiv1.Texture
        assassin_color_mask: bauiv1.Texture
        assassin_icon: bauiv1.Texture
        assassin_icon_color_mask: bauiv1.Texture
        audio_icon: bauiv1.Texture
        bar: bauiv1.Texture
        bear_color: bauiv1.Texture
        bear_color_mask: bauiv1.Texture
        bear_icon: bauiv1.Texture
        bear_icon_color_mask: bauiv1.Texture
        bg: bauiv1.Texture
        big_g: bauiv1.Texture
        big_gpreview: bauiv1.Texture
        bomb_color: bauiv1.Texture
        bomb_color_ice: bauiv1.Texture
        bomb_sticky_color: bauiv1.Texture
        bones_color: bauiv1.Texture
        bones_color_mask: bauiv1.Texture
        bones_icon: bauiv1.Texture
        bones_icon_color_mask: bauiv1.Texture
        bridgit_level_color: bauiv1.Texture
        bridgit_preview: bauiv1.Texture
        bunny_color: bauiv1.Texture
        bunny_color_mask: bauiv1.Texture
        bunny_icon: bauiv1.Texture
        bunny_icon_color_mask: bauiv1.Texture
        button_bomb: bauiv1.Texture
        button_jump: bauiv1.Texture
        button_pick_up: bauiv1.Texture
        button_punch: bauiv1.Texture
        ch_title_char1: bauiv1.Texture
        ch_title_char2: bauiv1.Texture
        ch_title_char3: bauiv1.Texture
        ch_title_char4: bauiv1.Texture
        ch_title_char5: bauiv1.Texture
        chest_icon: bauiv1.Texture
        chest_icon_empty: bauiv1.Texture
        chest_icon_multi: bauiv1.Texture
        chest_icon_tint: bauiv1.Texture
        chest_open_icon: bauiv1.Texture
        chest_open_icon_tint: bauiv1.Texture
        circle_zig_zag: bauiv1.Texture
        clay_stroke: bauiv1.Texture
        coin: bauiv1.Texture
        controller_icon: bauiv1.Texture
        courtyard_level_color: bauiv1.Texture
        courtyard_preview: bauiv1.Texture
        cowboy_color: bauiv1.Texture
        cowboy_color_mask: bauiv1.Texture
        cowboy_icon: bauiv1.Texture
        cowboy_icon_color_mask: bauiv1.Texture
        crag_castle_level_color: bauiv1.Texture
        crag_castle_preview: bauiv1.Texture
        cross_out: bauiv1.Texture
        cross_out_mask: bauiv1.Texture
        cute_spaz: bauiv1.Texture
        cyborg_color: bauiv1.Texture
        cyborg_color_mask: bauiv1.Texture
        cyborg_icon: bauiv1.Texture
        cyborg_icon_color_mask: bauiv1.Texture
        discord_icon: bauiv1.Texture
        discord_logo: bauiv1.Texture
        discord_server: bauiv1.Texture
        doom_shroom_bgcolor: bauiv1.Texture
        doom_shroom_level_color: bauiv1.Texture
        doom_shroom_preview: bauiv1.Texture
        down_button: bauiv1.Texture
        egg1: bauiv1.Texture
        egg2: bauiv1.Texture
        egg3: bauiv1.Texture
        egg4: bauiv1.Texture
        egg_tex1: bauiv1.Texture
        egg_tex2: bauiv1.Texture
        egg_tex3: bauiv1.Texture
        empty: bauiv1.Texture
        file: bauiv1.Texture
        flag_color: bauiv1.Texture
        folder: bauiv1.Texture
        football_stadium: bauiv1.Texture
        football_stadium_preview: bauiv1.Texture
        frame_inset: bauiv1.Texture
        frosty_color: bauiv1.Texture
        frosty_color_mask: bauiv1.Texture
        frosty_icon: bauiv1.Texture
        frosty_icon_color_mask: bauiv1.Texture
        game_center_icon: bauiv1.Texture
        github_logo: bauiv1.Texture
        gladiator_color: bauiv1.Texture
        gladiator_color_mask: bauiv1.Texture
        gladiator_icon: bauiv1.Texture
        gladiator_icon_color_mask: bauiv1.Texture
        gold_pass: bauiv1.Texture
        google_play_achievements_icon: bauiv1.Texture
        google_play_games_icon: bauiv1.Texture
        google_play_leaderboards_icon: bauiv1.Texture
        google_plus_icon: bauiv1.Texture
        google_plus_sign_in_button: bauiv1.Texture
        graphics_icon: bauiv1.Texture
        heart: bauiv1.Texture
        hockey_stadium: bauiv1.Texture
        hockey_stadium_preview: bauiv1.Texture
        icon_onslaught: bauiv1.Texture
        icon_runaround: bauiv1.Texture
        impact_bomb_color: bauiv1.Texture
        impact_bomb_color_lit: bauiv1.Texture
        inventory_icon: bauiv1.Texture
        jack_color: bauiv1.Texture
        jack_color_mask: bauiv1.Texture
        jack_icon: bauiv1.Texture
        jack_icon_color_mask: bauiv1.Texture
        jumpsuit_color: bauiv1.Texture
        jumpsuit_color_mask: bauiv1.Texture
        jumpsuit_icon: bauiv1.Texture
        jumpsuit_icon_color_mask: bauiv1.Texture
        kronk: bauiv1.Texture
        kronk_color_mask: bauiv1.Texture
        kronk_icon: bauiv1.Texture
        kronk_icon_color_mask: bauiv1.Texture
        lake_frigid: bauiv1.Texture
        lake_frigid_preview: bauiv1.Texture
        lake_frigid_reflections: bauiv1.Texture
        land_mine: bauiv1.Texture
        land_mine_lit: bauiv1.Texture
        leaderboards_icon: bauiv1.Texture
        left_button: bauiv1.Texture
        level_icon: bauiv1.Texture
        lock: bauiv1.Texture
        log_icon: bauiv1.Texture
        logo: bauiv1.Texture
        logo_easter: bauiv1.Texture
        map_preview_mask: bauiv1.Texture
        medal_bronze: bauiv1.Texture
        medal_complete: bauiv1.Texture
        medal_gold: bauiv1.Texture
        medal_silver: bauiv1.Texture
        mel_color: bauiv1.Texture
        mel_color_mask: bauiv1.Texture
        mel_icon: bauiv1.Texture
        mel_icon_color_mask: bauiv1.Texture
        menu_bg: bauiv1.Texture
        menu_icon: bauiv1.Texture
        merch: bauiv1.Texture
        meter: bauiv1.Texture
        monkey_face_level_color: bauiv1.Texture
        monkey_face_preview: bauiv1.Texture
        multiplayer_examples: bauiv1.Texture
        nature_background_color: bauiv1.Texture
        neo_spaz_color: bauiv1.Texture
        neo_spaz_color_mask: bauiv1.Texture
        neo_spaz_icon: bauiv1.Texture
        neo_spaz_icon_color_mask: bauiv1.Texture
        next_level_icon: bauiv1.Texture
        ninja_color: bauiv1.Texture
        ninja_color_mask: bauiv1.Texture
        ninja_icon: bauiv1.Texture
        ninja_icon_color_mask: bauiv1.Texture
        null: bauiv1.Texture
        old_lady_color: bauiv1.Texture
        old_lady_color_mask: bauiv1.Texture
        old_lady_icon: bauiv1.Texture
        old_lady_icon_color_mask: bauiv1.Texture
        opera_singer_color: bauiv1.Texture
        opera_singer_color_mask: bauiv1.Texture
        opera_singer_icon: bauiv1.Texture
        opera_singer_icon_color_mask: bauiv1.Texture
        ouya_icon: bauiv1.Texture
        ouya_obutton: bauiv1.Texture
        ouya_ubutton: bauiv1.Texture
        ouya_ybutton: bauiv1.Texture
        penguin_color: bauiv1.Texture
        penguin_color_mask: bauiv1.Texture
        penguin_icon: bauiv1.Texture
        penguin_icon_color_mask: bauiv1.Texture
        pixie_color: bauiv1.Texture
        pixie_color_mask: bauiv1.Texture
        pixie_icon: bauiv1.Texture
        pixie_icon_color_mask: bauiv1.Texture
        player_lineup: bauiv1.Texture
        plus_button: bauiv1.Texture
        powerup_bomb: bauiv1.Texture
        powerup_curse: bauiv1.Texture
        powerup_health: bauiv1.Texture
        powerup_ice_bombs: bauiv1.Texture
        powerup_impact_bombs: bauiv1.Texture
        powerup_land_mines: bauiv1.Texture
        powerup_punch: bauiv1.Texture
        powerup_shield: bauiv1.Texture
        powerup_speed: bauiv1.Texture
        powerup_sticky_bombs: bauiv1.Texture
        puck_color: bauiv1.Texture
        quote_bubble: bauiv1.Texture
        rampage_bgcolor: bauiv1.Texture
        rampage_bgcolor2: bauiv1.Texture
        rampage_level_color: bauiv1.Texture
        rampage_preview: bauiv1.Texture
        replay_icon: bauiv1.Texture
        right_button: bauiv1.Texture
        robot_color: bauiv1.Texture
        robot_color_mask: bauiv1.Texture
        robot_icon: bauiv1.Texture
        robot_icon_color_mask: bauiv1.Texture
        roundabout_level_color: bauiv1.Texture
        roundabout_preview: bauiv1.Texture
        santa_color: bauiv1.Texture
        santa_color_mask: bauiv1.Texture
        santa_icon: bauiv1.Texture
        santa_icon_color_mask: bauiv1.Texture
        settings_icon: bauiv1.Texture
        slash: bauiv1.Texture
        star: bauiv1.Texture
        step_right_up_level_color: bauiv1.Texture
        step_right_up_preview: bauiv1.Texture
        store_character: bauiv1.Texture
        store_character_easter: bauiv1.Texture
        store_character_xmas: bauiv1.Texture
        store_icon: bauiv1.Texture
        superhero_color: bauiv1.Texture
        superhero_color_mask: bauiv1.Texture
        superhero_icon: bauiv1.Texture
        superhero_icon_color_mask: bauiv1.Texture
        the_pad_level_color: bauiv1.Texture
        the_pad_preview: bauiv1.Texture
        ticket_roll: bauiv1.Texture
        ticket_roll_big: bauiv1.Texture
        ticket_rolls: bauiv1.Texture
        tickets: bauiv1.Texture
        tickets_more: bauiv1.Texture
        tickets_purple: bauiv1.Texture
        tip_top_bgcolor: bauiv1.Texture
        tip_top_level_color: bauiv1.Texture
        tip_top_preview: bauiv1.Texture
        tnt: bauiv1.Texture
        tokens1: bauiv1.Texture
        tokens2: bauiv1.Texture
        tokens3: bauiv1.Texture
        tokens4: bauiv1.Texture
        tower_dlevel_color: bauiv1.Texture
        tower_dpreview: bauiv1.Texture
        trees_color: bauiv1.Texture
        trophy: bauiv1.Texture
        tv: bauiv1.Texture
        up_button: bauiv1.Texture
        vr_fill_mound: bauiv1.Texture
        warrior_color: bauiv1.Texture
        warrior_color_mask: bauiv1.Texture
        warrior_icon: bauiv1.Texture
        warrior_icon_color_mask: bauiv1.Texture
        window_bottom_cap: bauiv1.Texture
        witch_color: bauiv1.Texture
        witch_color_mask: bauiv1.Texture
        witch_icon: bauiv1.Texture
        witch_icon_color_mask: bauiv1.Texture
        wizard_color: bauiv1.Texture
        wizard_color_mask: bauiv1.Texture
        wizard_icon: bauiv1.Texture
        wizard_icon_color_mask: bauiv1.Texture
        wrestler_color: bauiv1.Texture
        wrestler_color_mask: bauiv1.Texture
        wrestler_icon: bauiv1.Texture
        wrestler_icon_color_mask: bauiv1.Texture
        zig_zag_level_color: bauiv1.Texture
        zigzag_preview: bauiv1.Texture
        zoe_color: bauiv1.Texture
        zoe_color_mask: bauiv1.Texture
        zoe_icon: bauiv1.Texture
        zoe_icon_color_mask: bauiv1.Texture

    #: The ``audio`` group - 412 assets (``achievement``, ``action_hero1``,
    #: ``action_hero2``, ``action_hero3``, ``action_hero4``, and 407 more). Full
    #: list in source.
    audio: AudioGroup

    #: The ``meshes`` group - 360 assets (``achievement_outline``,
    #: ``action_hero_fore_arm``, ``action_hero_hand``, ``action_hero_head``,
    #: ``action_hero_lower_leg``, and 355 more). Full list in source.
    meshes: MeshesGroup

    #: The ``textures`` group - 313 assets (``achievement_boxer``,
    #: ``achievement_cross_hair``, ``achievement_dual_wielding``,
    #: ``achievement_empty``, ``achievement_flawless_victory``, and 308 more).
    #: Full list in source.
    textures: TexturesGroup

_TREE = {
    'audio': {
        'achievement': 's',
        'action_hero1': 's',
        'action_hero2': 's',
        'action_hero3': 's',
        'action_hero4': 's',
        'action_hero_death': 's',
        'action_hero_fall': 's',
        'action_hero_hit1': 's',
        'action_hero_hit2': 's',
        'activate_beep': 's',
        'agent1': 's',
        'agent2': 's',
        'agent3': 's',
        'agent4': 's',
        'agent_death': 's',
        'agent_fall': 's',
        'agent_hit1': 's',
        'agent_hit2': 's',
        'alarm': 's',
        'ali1': 's',
        'ali2': 's',
        'ali3': 's',
        'ali4': 's',
        'ali_death': 's',
        'ali_fall': 's',
        'ali_hit1': 's',
        'ali_hit2': 's',
        'alien1': 's',
        'alien2': 's',
        'alien3': 's',
        'alien4': 's',
        'alien_death': 's',
        'alien_fall': 's',
        'alien_hit1': 's',
        'alien_hit2': 's',
        'announce_eight': 's',
        'announce_five': 's',
        'announce_four': 's',
        'announce_nine': 's',
        'announce_one': 's',
        'announce_seven': 's',
        'announce_six': 's',
        'announce_ten': 's',
        'announce_three': 's',
        'announce_two': 's',
        'assassin1': 's',
        'assassin2': 's',
        'assassin3': 's',
        'assassin4': 's',
        'assassin_death': 's',
        'assassin_fall': 's',
        'assassin_hit1': 's',
        'assassin_hit2': 's',
        'aww': 's',
        'bear1': 's',
        'bear2': 's',
        'bear3': 's',
        'bear4': 's',
        'bear_death': 's',
        'bear_fall': 's',
        'bear_hit1': 's',
        'bear_hit2': 's',
        'bell_high': 's',
        'bell_low': 's',
        'bell_med': 's',
        'big_impact': 's',
        'big_impact2': 's',
        'block': 's',
        'bomb_drop01': 's',
        'bomb_drop02': 's',
        'bomb_roll01': 's',
        'bones1': 's',
        'bones2': 's',
        'bones3': 's',
        'bones_death': 's',
        'bones_fall': 's',
        'boo': 's',
        'box_drop': 's',
        'boxing_bell': 's',
        'bunny1': 's',
        'bunny2': 's',
        'bunny3': 's',
        'bunny4': 's',
        'bunny_death': 's',
        'bunny_fall': 's',
        'bunny_hit1': 's',
        'bunny_hit2': 's',
        'bunny_jump': 's',
        'cash_register2': 's',
        'char_select_music': 's',
        'cheer': 's',
        'cork_pop2': 's',
        'cowboy1': 's',
        'cowboy2': 's',
        'cowboy3': 's',
        'cowboy4': 's',
        'cowboy_death': 's',
        'cowboy_fall': 's',
        'cowboy_hit1': 's',
        'cowboy_hit2': 's',
        'crowd_chant': 's',
        'cyborg1': 's',
        'cyborg2': 's',
        'cyborg3': 's',
        'cyborg4': 's',
        'cyborg_death': 's',
        'cyborg_fall': 's',
        'cyborg_hit1': 's',
        'cyborg_hit2': 's',
        'cymbal': 's',
        'debris_fall': 's',
        'deek2': 's',
        'ding_small': 's',
        'ding_small_high': 's',
        'dripity': 's',
        'drum_roll': 's',
        'drum_roll_short': 's',
        'explosion01': 's',
        'explosion02': 's',
        'explosion03': 's',
        'explosion04': 's',
        'explosion05': 's',
        'fanfare': 's',
        'flag_catcher_music': 's',
        'flying_music': 's',
        'foghorn': 's',
        'foot_impact01': 's',
        'foot_impact02': 's',
        'foot_impact03': 's',
        'forward_march_music': 's',
        'freeze': 's',
        'frosty01': 's',
        'frosty02': 's',
        'frosty03': 's',
        'frosty04': 's',
        'frosty05': 's',
        'frosty_death': 's',
        'frosty_fall': 's',
        'frosty_hit01': 's',
        'frosty_hit02': 's',
        'frosty_hit03': 's',
        'fuse01': 's',
        'gasp': 's',
        'gladiator1': 's',
        'gladiator2': 's',
        'gladiator3': 's',
        'gladiator4': 's',
        'gladiator_death': 's',
        'gladiator_fall': 's',
        'gladiator_hit1': 's',
        'gladiator_hit2': 's',
        'gong': 's',
        'grand_romp_music': 's',
        'gravel_skid': 's',
        'health_powerup': 's',
        'hiss': 's',
        'impact_hard': 's',
        'impact_hard2': 's',
        'impact_hard3': 's',
        'impact_medium': 's',
        'impact_medium2': 's',
        'jack01': 's',
        'jack02': 's',
        'jack03': 's',
        'jack04': 's',
        'jack05': 's',
        'jack06': 's',
        'jack_death01': 's',
        'jack_fall01': 's',
        'jack_hit01': 's',
        'jack_hit02': 's',
        'jack_hit03': 's',
        'jack_hit04': 's',
        'jack_hit05': 's',
        'jack_hit06': 's',
        'jack_hit07': 's',
        'jumpsuit1': 's',
        'jumpsuit2': 's',
        'jumpsuit3': 's',
        'jumpsuit4': 's',
        'jumpsuit_death': 's',
        'jumpsuit_fall': 's',
        'jumpsuit_hit1': 's',
        'jumpsuit_hit2': 's',
        'kronk1': 's',
        'kronk10': 's',
        'kronk2': 's',
        'kronk3': 's',
        'kronk4': 's',
        'kronk5': 's',
        'kronk6': 's',
        'kronk7': 's',
        'kronk8': 's',
        'kronk9': 's',
        'kronk_death': 's',
        'kronk_fall': 's',
        'laser': 's',
        'laser_reverse': 's',
        'mel01': 's',
        'mel02': 's',
        'mel03': 's',
        'mel04': 's',
        'mel05': 's',
        'mel06': 's',
        'mel07': 's',
        'mel08': 's',
        'mel09': 's',
        'mel10': 's',
        'mel_death01': 's',
        'mel_fall01': 's',
        'menu_music': 's',
        'metal_hit': 's',
        'metal_skid': 's',
        'nice': 's',
        'ninja_attack1': 's',
        'ninja_attack2': 's',
        'ninja_attack3': 's',
        'ninja_attack4': 's',
        'ninja_attack5': 's',
        'ninja_attack6': 's',
        'ninja_attack7': 's',
        'ninja_death1': 's',
        'ninja_fall1': 's',
        'ninja_hit1': 's',
        'ninja_hit2': 's',
        'ninja_hit3': 's',
        'ninja_hit4': 's',
        'ninja_hit5': 's',
        'ninja_hit6': 's',
        'ninja_hit7': 's',
        'ninja_hit8': 's',
        'old_lady1': 's',
        'old_lady2': 's',
        'old_lady3': 's',
        'old_lady4': 's',
        'old_lady_death': 's',
        'old_lady_fall': 's',
        'old_lady_hit1': 's',
        'old_lady_hit2': 's',
        'ooh': 's',
        'opera_singer1': 's',
        'opera_singer2': 's',
        'opera_singer3': 's',
        'opera_singer4': 's',
        'opera_singer_death': 's',
        'opera_singer_fall': 's',
        'opera_singer_hit1': 's',
        'opera_singer_hit2': 's',
        'orchestra_hit': 's',
        'orchestra_hit2': 's',
        'orchestra_hit3': 's',
        'orchestra_hit4': 's',
        'orchestra_hit_big1': 's',
        'orchestra_hit_big2': 's',
        'penguin1': 's',
        'penguin2': 's',
        'penguin3': 's',
        'penguin4': 's',
        'penguin_death': 's',
        'penguin_fall': 's',
        'penguin_hit1': 's',
        'penguin_hit2': 's',
        'pixie1': 's',
        'pixie2': 's',
        'pixie3': 's',
        'pixie4': 's',
        'pixie_death': 's',
        'pixie_fall': 's',
        'pixie_hit1': 's',
        'pixie_hit2': 's',
        'player_death': 's',
        'player_left': 's',
        'pop01': 's',
        'powerup01': 's',
        'punch_strong01': 's',
        'punch_strong02': 's',
        'punch_swish': 's',
        'punch_weak01': 's',
        'race_beep1': 's',
        'race_beep2': 's',
        'ref_whistle': 's',
        'rev_up': 's',
        'robot1': 's',
        'robot2': 's',
        'robot3': 's',
        'robot4': 's',
        'robot_death': 's',
        'robot_fall': 's',
        'robot_hit1': 's',
        'robot_hit2': 's',
        'run_away_music': 's',
        'santa01': 's',
        'santa02': 's',
        'santa03': 's',
        'santa04': 's',
        'santa05': 's',
        'santa_death': 's',
        'santa_fall': 's',
        'santa_hit01': 's',
        'santa_hit02': 's',
        'santa_hit03': 's',
        'santa_hit04': 's',
        'scamper01': 's',
        'scary_music': 's',
        'score': 's',
        'score_hit01': 's',
        'score_hit02': 's',
        'scores_epic_music': 's',
        'shatter': 's',
        'shield_down': 's',
        'shield_hit': 's',
        'shield_up': 's',
        'skid01': 's',
        'slow_epic_music': 's',
        'spawn': 's',
        'spaz_attack01': 's',
        'spaz_attack02': 's',
        'spaz_attack03': 's',
        'spaz_attack04': 's',
        'spaz_death01': 's',
        'spaz_eff': 's',
        'spaz_fall01': 's',
        'spaz_impact01': 's',
        'spaz_impact02': 's',
        'spaz_impact03': 's',
        'spaz_impact04': 's',
        'spaz_jump01': 's',
        'spaz_jump02': 's',
        'spaz_jump03': 's',
        'spaz_jump04': 's',
        'spaz_ow': 's',
        'spaz_pickup01': 's',
        'spaz_scream01': 's',
        'splatter': 's',
        'sports_music': 's',
        'sticky_impact': 's',
        'super_punch': 's',
        'superhero1': 's',
        'superhero2': 's',
        'superhero3': 's',
        'superhero4': 's',
        'superhero_death': 's',
        'superhero_fall': 's',
        'superhero_hit1': 's',
        'superhero_hit2': 's',
        'survival_music': 's',
        'swip': 's',
        'swip2': 's',
        'techno_hit01': 's',
        'tick': 's',
        'ticking': 's',
        'to_the_death_music': 's',
        'trash_rummage': 's',
        'victory_music': 's',
        'warn_beep': 's',
        'warn_beeps': 's',
        'warrior1': 's',
        'warrior2': 's',
        'warrior3': 's',
        'warrior4': 's',
        'warrior_death': 's',
        'warrior_fall': 's',
        'warrior_hit1': 's',
        'warrior_hit2': 's',
        'when_johnny_comes_marching_home_music': 's',
        'witch1': 's',
        'witch2': 's',
        'witch3': 's',
        'witch4': 's',
        'witch_death': 's',
        'witch_fall': 's',
        'witch_hit1': 's',
        'witch_hit2': 's',
        'wizard1': 's',
        'wizard2': 's',
        'wizard3': 's',
        'wizard4': 's',
        'wizard_death': 's',
        'wizard_fall': 's',
        'wizard_hit1': 's',
        'wizard_hit2': 's',
        'woo': 's',
        'woo2': 's',
        'woo3': 's',
        'wood_debris_fall': 's',
        'wow': 's',
        'wrestler1': 's',
        'wrestler2': 's',
        'wrestler3': 's',
        'wrestler4': 's',
        'wrestler_death': 's',
        'wrestler_fall': 's',
        'wrestler_hit1': 's',
        'wrestler_hit2': 's',
        'yeah': 's',
        'zoe_attack01': 's',
        'zoe_attack02': 's',
        'zoe_attack03': 's',
        'zoe_attack04': 's',
        'zoe_death01': 's',
        'zoe_eff': 's',
        'zoe_fall01': 's',
        'zoe_impact01': 's',
        'zoe_impact02': 's',
        'zoe_impact03': 's',
        'zoe_impact04': 's',
        'zoe_jump01': 's',
        'zoe_jump02': 's',
        'zoe_jump03': 's',
        'zoe_ow': 's',
        'zoe_pickup01': 's',
        'zoe_scream01': 's',
    },
    'meshes': {
        'achievement_outline': 'm',
        'action_hero_fore_arm': 'm',
        'action_hero_hand': 'm',
        'action_hero_head': 'm',
        'action_hero_lower_leg': 'm',
        'action_hero_pelvis': 'm',
        'action_hero_toes': 'm',
        'action_hero_torso': 'm',
        'action_hero_upper_arm': 'm',
        'action_hero_upper_leg': 'm',
        'agent_fore_arm': 'm',
        'agent_hand': 'm',
        'agent_head': 'm',
        'agent_lower_leg': 'm',
        'agent_pelvis': 'm',
        'agent_toes': 'm',
        'agent_torso': 'm',
        'agent_upper_arm': 'm',
        'agent_upper_leg': 'm',
        'ali_fore_arm': 'm',
        'ali_hand': 'm',
        'ali_head': 'm',
        'ali_lower_leg': 'm',
        'ali_pelvis': 'm',
        'ali_toes': 'm',
        'ali_torso': 'm',
        'ali_upper_arm': 'm',
        'ali_upper_leg': 'm',
        'alien_fore_arm': 'm',
        'alien_hand': 'm',
        'alien_head': 'm',
        'alien_lower_leg': 'm',
        'alien_pelvis': 'm',
        'alien_toes': 'm',
        'alien_torso': 'm',
        'alien_upper_arm': 'm',
        'alien_upper_leg': 'm',
        'always_land_bg': 'm',
        'always_land_level': 'm',
        'always_land_level_bottom': 'm',
        'always_land_vrfill_mound': 'm',
        'angry_computer_transparent': 'm',
        'assassin_fore_arm': 'm',
        'assassin_hand': 'm',
        'assassin_head': 'm',
        'assassin_lower_leg': 'm',
        'assassin_pelvis': 'm',
        'assassin_toes': 'm',
        'assassin_torso': 'm',
        'assassin_upper_arm': 'm',
        'assassin_upper_leg': 'm',
        'bear_fore_arm': 'm',
        'bear_hand': 'm',
        'bear_head': 'm',
        'bear_lower_leg': 'm',
        'bear_pelvis': 'm',
        'bear_toes': 'm',
        'bear_torso': 'm',
        'bear_upper_arm': 'm',
        'bear_upper_leg': 'm',
        'big_g': 'm',
        'big_gbottom': 'm',
        'bomb': 'm',
        'bomb_sticky': 'm',
        'bones_fore_arm': 'm',
        'bones_hand': 'm',
        'bones_head': 'm',
        'bones_lower_leg': 'm',
        'bones_pelvis': 'm',
        'bones_toes': 'm',
        'bones_torso': 'm',
        'bones_upper_arm': 'm',
        'bones_upper_leg': 'm',
        'bridgit_level_bottom': 'm',
        'bridgit_level_top': 'm',
        'bunny_fore_arm': 'm',
        'bunny_hand': 'm',
        'bunny_head': 'm',
        'bunny_lower_leg': 'm',
        'bunny_pelvis': 'm',
        'bunny_toes': 'm',
        'bunny_torso': 'm',
        'bunny_upper_arm': 'm',
        'bunny_upper_leg': 'm',
        'button_null': 'm',
        'courtyard_level': 'm',
        'courtyard_level_bottom': 'm',
        'cowboy_fore_arm': 'm',
        'cowboy_hand': 'm',
        'cowboy_head': 'm',
        'cowboy_lower_leg': 'm',
        'cowboy_pelvis': 'm',
        'cowboy_toes': 'm',
        'cowboy_torso': 'm',
        'cowboy_upper_arm': 'm',
        'cowboy_upper_leg': 'm',
        'crag_castle_level': 'm',
        'crag_castle_level_bottom': 'm',
        'crag_castle_vrfill_mound': 'm',
        'currency_meter': 'm',
        'currency_plus_button': 'm',
        'cyborg_fore_arm': 'm',
        'cyborg_hand': 'm',
        'cyborg_head': 'm',
        'cyborg_lower_leg': 'm',
        'cyborg_pelvis': 'm',
        'cyborg_toes': 'm',
        'cyborg_torso': 'm',
        'cyborg_upper_arm': 'm',
        'cyborg_upper_leg': 'm',
        'doom_shroom_bg': 'm',
        'doom_shroom_level': 'm',
        'doom_shroom_stem': 'm',
        'doom_shroom_vrfill': 'm',
        'egg': 'm',
        'football_stadium': 'm',
        'football_stadium_vrfill': 'm',
        'frame_inset': 'm',
        'frosty_fore_arm': 'm',
        'frosty_hand': 'm',
        'frosty_head': 'm',
        'frosty_lower_leg': 'm',
        'frosty_pelvis': 'm',
        'frosty_toes': 'm',
        'frosty_torso': 'm',
        'frosty_upper_arm': 'm',
        'frosty_upper_leg': 'm',
        'gladiator_fore_arm': 'm',
        'gladiator_hand': 'm',
        'gladiator_head': 'm',
        'gladiator_lower_leg': 'm',
        'gladiator_pelvis': 'm',
        'gladiator_toes': 'm',
        'gladiator_torso': 'm',
        'gladiator_upper_arm': 'm',
        'gladiator_upper_leg': 'm',
        'heart_opaque': 'm',
        'heart_transparent': 'm',
        'hockey_stadium_inner': 'm',
        'hockey_stadium_outer': 'm',
        'hockey_stadium_stands': 'm',
        'image2x1_vertical': 'm',
        'impact_bomb': 'm',
        'jack_fore_arm': 'm',
        'jack_hand': 'm',
        'jack_head': 'm',
        'jack_lower_leg': 'm',
        'jack_toes': 'm',
        'jack_torso': 'm',
        'jack_upper_arm': 'm',
        'jack_upper_leg': 'm',
        'jumpsuit_fore_arm': 'm',
        'jumpsuit_hand': 'm',
        'jumpsuit_head': 'm',
        'jumpsuit_lower_leg': 'm',
        'jumpsuit_pelvis': 'm',
        'jumpsuit_toes': 'm',
        'jumpsuit_torso': 'm',
        'jumpsuit_upper_arm': 'm',
        'jumpsuit_upper_leg': 'm',
        'kronk_fore_arm': 'm',
        'kronk_hand': 'm',
        'kronk_head': 'm',
        'kronk_lower_leg': 'm',
        'kronk_pelvis': 'm',
        'kronk_toes': 'm',
        'kronk_torso': 'm',
        'kronk_upper_arm': 'm',
        'kronk_upper_leg': 'm',
        'lake_frigid': 'm',
        'lake_frigid_reflections': 'm',
        'lake_frigid_top': 'm',
        'lake_frigid_vrfill': 'm',
        'land_mine': 'm',
        'level_select_button_opaque': 'm',
        'level_select_button_transparent': 'm',
        'logo': 'm',
        'logo_transparent': 'm',
        'mel_fore_arm': 'm',
        'mel_hand': 'm',
        'mel_head': 'm',
        'mel_lower_leg': 'm',
        'mel_toes': 'm',
        'mel_torso': 'm',
        'mel_upper_arm': 'm',
        'mel_upper_leg': 'm',
        'meter_transparent': 'm',
        'monkey_face_level': 'm',
        'monkey_face_level_bottom': 'm',
        'nature_background': 'm',
        'nature_background_vrfill': 'm',
        'neo_spaz_fore_arm': 'm',
        'neo_spaz_hand': 'm',
        'neo_spaz_head': 'm',
        'neo_spaz_lower_leg': 'm',
        'neo_spaz_pelvis': 'm',
        'neo_spaz_toes': 'm',
        'neo_spaz_torso': 'm',
        'neo_spaz_upper_arm': 'm',
        'neo_spaz_upper_leg': 'm',
        'ninja_fore_arm': 'm',
        'ninja_hand': 'm',
        'ninja_head': 'm',
        'ninja_lower_leg': 'm',
        'ninja_pelvis': 'm',
        'ninja_toes': 'm',
        'ninja_torso': 'm',
        'ninja_upper_arm': 'm',
        'ninja_upper_leg': 'm',
        'old_lady_fore_arm': 'm',
        'old_lady_hand': 'm',
        'old_lady_head': 'm',
        'old_lady_lower_leg': 'm',
        'old_lady_pelvis': 'm',
        'old_lady_toes': 'm',
        'old_lady_torso': 'm',
        'old_lady_upper_arm': 'm',
        'old_lady_upper_leg': 'm',
        'opera_singer_fore_arm': 'm',
        'opera_singer_hand': 'm',
        'opera_singer_head': 'm',
        'opera_singer_lower_leg': 'm',
        'opera_singer_pelvis': 'm',
        'opera_singer_toes': 'm',
        'opera_singer_torso': 'm',
        'opera_singer_upper_arm': 'm',
        'opera_singer_upper_leg': 'm',
        'penguin_fore_arm': 'm',
        'penguin_hand': 'm',
        'penguin_head': 'm',
        'penguin_lower_leg': 'm',
        'penguin_pelvis': 'm',
        'penguin_toes': 'm',
        'penguin_torso': 'm',
        'penguin_upper_arm': 'm',
        'penguin_upper_leg': 'm',
        'pixie_fore_arm': 'm',
        'pixie_hand': 'm',
        'pixie_head': 'm',
        'pixie_lower_leg': 'm',
        'pixie_pelvis': 'm',
        'pixie_toes': 'm',
        'pixie_torso': 'm',
        'pixie_upper_arm': 'm',
        'pixie_upper_leg': 'm',
        'plastic_eyes_transparent': 'm',
        'player_lineup1_transparent': 'm',
        'player_lineup2_transparent': 'm',
        'player_lineup3_transparent': 'm',
        'player_lineup4_transparent': 'm',
        'powerup': 'm',
        'powerup_simple': 'm',
        'puck': 'm',
        'rampage_bg': 'm',
        'rampage_bg2': 'm',
        'rampage_level': 'm',
        'rampage_level_bottom': 'm',
        'rampage_vrfill': 'm',
        'robot_fore_arm': 'm',
        'robot_hand': 'm',
        'robot_head': 'm',
        'robot_lower_leg': 'm',
        'robot_pelvis': 'm',
        'robot_toes': 'm',
        'robot_torso': 'm',
        'robot_upper_arm': 'm',
        'robot_upper_leg': 'm',
        'roundabout_level': 'm',
        'roundabout_level_bottom': 'm',
        'running_shoes': 'm',
        'santa_fore_arm': 'm',
        'santa_hand': 'm',
        'santa_head': 'm',
        'santa_lower_leg': 'm',
        'santa_toes': 'm',
        'santa_torso': 'm',
        'santa_upper_arm': 'm',
        'santa_upper_leg': 'm',
        'scroll_widget_short': 'm',
        'step_right_up_level': 'm',
        'step_right_up_level_bottom': 'm',
        'step_right_up_vrfill_mound': 'm',
        'superhero_fore_arm': 'm',
        'superhero_hand': 'm',
        'superhero_head': 'm',
        'superhero_lower_leg': 'm',
        'superhero_pelvis': 'm',
        'superhero_toes': 'm',
        'superhero_torso': 'm',
        'superhero_upper_arm': 'm',
        'superhero_upper_leg': 'm',
        'the_pad_bg': 'm',
        'the_pad_bgsmall': 'm',
        'the_pad_level': 'm',
        'the_pad_level_bottom': 'm',
        'the_pad_vrfill_bottom': 'm',
        'the_pad_vrfill_mound': 'm',
        'the_pad_vrfill_top': 'm',
        'tip_top_bg': 'm',
        'tip_top_level': 'm',
        'tip_top_level_bottom': 'm',
        'tnt': 'm',
        'toolbar_backing': 'm',
        'toolbar_backing_bottom': 'm',
        'toolbar_backing_bottom2': 'm',
        'toolbar_backing_opaque': 'm',
        'toolbar_backing_top': 'm',
        'toolbar_backing_top2': 'm',
        'toolbar_backing_transparent': 'm',
        'tower_dlevel': 'm',
        'tower_dlevel_bottom': 'm',
        'trees': 'm',
        'warrior_fore_arm': 'm',
        'warrior_hand': 'm',
        'warrior_head': 'm',
        'warrior_lower_leg': 'm',
        'warrior_pelvis': 'm',
        'warrior_toes': 'm',
        'warrior_torso': 'm',
        'warrior_upper_arm': 'm',
        'warrior_upper_leg': 'm',
        'window_bgblotch': 'm',
        'witch_fore_arm': 'm',
        'witch_hand': 'm',
        'witch_head': 'm',
        'witch_lower_leg': 'm',
        'witch_pelvis': 'm',
        'witch_toes': 'm',
        'witch_torso': 'm',
        'witch_upper_arm': 'm',
        'witch_upper_leg': 'm',
        'wizard_fore_arm': 'm',
        'wizard_hand': 'm',
        'wizard_head': 'm',
        'wizard_lower_leg': 'm',
        'wizard_pelvis': 'm',
        'wizard_toes': 'm',
        'wizard_torso': 'm',
        'wizard_upper_arm': 'm',
        'wizard_upper_leg': 'm',
        'wrestler_fore_arm': 'm',
        'wrestler_hand': 'm',
        'wrestler_head': 'm',
        'wrestler_lower_leg': 'm',
        'wrestler_pelvis': 'm',
        'wrestler_toes': 'm',
        'wrestler_torso': 'm',
        'wrestler_upper_arm': 'm',
        'wrestler_upper_leg': 'm',
        'zig_zag_level': 'm',
        'zig_zag_level_bottom': 'm',
        'zoe_fore_arm': 'm',
        'zoe_hand': 'm',
        'zoe_head': 'm',
        'zoe_lower_leg': 'm',
        'zoe_pelvis': 'm',
        'zoe_toes': 'm',
        'zoe_torso': 'm',
        'zoe_upper_arm': 'm',
        'zoe_upper_leg': 'm',
    },
    'textures': {
        'achievement_boxer': 't',
        'achievement_cross_hair': 't',
        'achievement_dual_wielding': 't',
        'achievement_empty': 't',
        'achievement_flawless_victory': 't',
        'achievement_football_shutout': 't',
        'achievement_football_victory': 't',
        'achievement_free_loader': 't',
        'achievement_got_the_moves': 't',
        'achievement_in_control': 't',
        'achievement_medal_large': 't',
        'achievement_medal_medium': 't',
        'achievement_medal_small': 't',
        'achievement_mine': 't',
        'achievement_off_you_go': 't',
        'achievement_onslaught': 't',
        'achievement_outline': 't',
        'achievement_runaround': 't',
        'achievement_sharing_is_caring': 't',
        'achievement_stayin_alive': 't',
        'achievement_super_punch': 't',
        'achievement_team_player': 't',
        'achievement_tnt': 't',
        'achievement_wall': 't',
        'achievements_icon': 't',
        'action_hero_color': 't',
        'action_hero_color_mask': 't',
        'action_hero_icon': 't',
        'action_hero_icon_color_mask': 't',
        'advanced_icon': 't',
        'agent_color': 't',
        'agent_color_mask': 't',
        'agent_icon': 't',
        'agent_icon_color_mask': 't',
        'ali_color': 't',
        'ali_color_mask': 't',
        'ali_icon': 't',
        'ali_icon_color_mask': 't',
        'ali_splash': 't',
        'alien_color': 't',
        'alien_color_mask': 't',
        'alien_icon': 't',
        'alien_icon_color_mask': 't',
        'always_land_bgcolor': 't',
        'always_land_level_color': 't',
        'always_land_preview': 't',
        'analog_stick': 't',
        'assassin_color': 't',
        'assassin_color_mask': 't',
        'assassin_icon': 't',
        'assassin_icon_color_mask': 't',
        'audio_icon': 't',
        'bar': 't',
        'bear_color': 't',
        'bear_color_mask': 't',
        'bear_icon': 't',
        'bear_icon_color_mask': 't',
        'bg': 't',
        'big_g': 't',
        'big_gpreview': 't',
        'bomb_color': 't',
        'bomb_color_ice': 't',
        'bomb_sticky_color': 't',
        'bones_color': 't',
        'bones_color_mask': 't',
        'bones_icon': 't',
        'bones_icon_color_mask': 't',
        'bridgit_level_color': 't',
        'bridgit_preview': 't',
        'bunny_color': 't',
        'bunny_color_mask': 't',
        'bunny_icon': 't',
        'bunny_icon_color_mask': 't',
        'button_bomb': 't',
        'button_jump': 't',
        'button_pick_up': 't',
        'button_punch': 't',
        'ch_title_char1': 't',
        'ch_title_char2': 't',
        'ch_title_char3': 't',
        'ch_title_char4': 't',
        'ch_title_char5': 't',
        'chest_icon': 't',
        'chest_icon_empty': 't',
        'chest_icon_multi': 't',
        'chest_icon_tint': 't',
        'chest_open_icon': 't',
        'chest_open_icon_tint': 't',
        'circle_zig_zag': 't',
        'clay_stroke': 't',
        'coin': 't',
        'controller_icon': 't',
        'courtyard_level_color': 't',
        'courtyard_preview': 't',
        'cowboy_color': 't',
        'cowboy_color_mask': 't',
        'cowboy_icon': 't',
        'cowboy_icon_color_mask': 't',
        'crag_castle_level_color': 't',
        'crag_castle_preview': 't',
        'cross_out': 't',
        'cross_out_mask': 't',
        'cute_spaz': 't',
        'cyborg_color': 't',
        'cyborg_color_mask': 't',
        'cyborg_icon': 't',
        'cyborg_icon_color_mask': 't',
        'discord_icon': 't',
        'discord_logo': 't',
        'discord_server': 't',
        'doom_shroom_bgcolor': 't',
        'doom_shroom_level_color': 't',
        'doom_shroom_preview': 't',
        'down_button': 't',
        'egg1': 't',
        'egg2': 't',
        'egg3': 't',
        'egg4': 't',
        'egg_tex1': 't',
        'egg_tex2': 't',
        'egg_tex3': 't',
        'empty': 't',
        'file': 't',
        'flag_color': 't',
        'folder': 't',
        'football_stadium': 't',
        'football_stadium_preview': 't',
        'frame_inset': 't',
        'frosty_color': 't',
        'frosty_color_mask': 't',
        'frosty_icon': 't',
        'frosty_icon_color_mask': 't',
        'game_center_icon': 't',
        'github_logo': 't',
        'gladiator_color': 't',
        'gladiator_color_mask': 't',
        'gladiator_icon': 't',
        'gladiator_icon_color_mask': 't',
        'gold_pass': 't',
        'google_play_achievements_icon': 't',
        'google_play_games_icon': 't',
        'google_play_leaderboards_icon': 't',
        'google_plus_icon': 't',
        'google_plus_sign_in_button': 't',
        'graphics_icon': 't',
        'heart': 't',
        'hockey_stadium': 't',
        'hockey_stadium_preview': 't',
        'icon_onslaught': 't',
        'icon_runaround': 't',
        'impact_bomb_color': 't',
        'impact_bomb_color_lit': 't',
        'inventory_icon': 't',
        'jack_color': 't',
        'jack_color_mask': 't',
        'jack_icon': 't',
        'jack_icon_color_mask': 't',
        'jumpsuit_color': 't',
        'jumpsuit_color_mask': 't',
        'jumpsuit_icon': 't',
        'jumpsuit_icon_color_mask': 't',
        'kronk': 't',
        'kronk_color_mask': 't',
        'kronk_icon': 't',
        'kronk_icon_color_mask': 't',
        'lake_frigid': 't',
        'lake_frigid_preview': 't',
        'lake_frigid_reflections': 't',
        'land_mine': 't',
        'land_mine_lit': 't',
        'leaderboards_icon': 't',
        'left_button': 't',
        'level_icon': 't',
        'lock': 't',
        'log_icon': 't',
        'logo': 't',
        'logo_easter': 't',
        'map_preview_mask': 't',
        'medal_bronze': 't',
        'medal_complete': 't',
        'medal_gold': 't',
        'medal_silver': 't',
        'mel_color': 't',
        'mel_color_mask': 't',
        'mel_icon': 't',
        'mel_icon_color_mask': 't',
        'menu_bg': 't',
        'menu_icon': 't',
        'merch': 't',
        'meter': 't',
        'monkey_face_level_color': 't',
        'monkey_face_preview': 't',
        'multiplayer_examples': 't',
        'nature_background_color': 't',
        'neo_spaz_color': 't',
        'neo_spaz_color_mask': 't',
        'neo_spaz_icon': 't',
        'neo_spaz_icon_color_mask': 't',
        'next_level_icon': 't',
        'ninja_color': 't',
        'ninja_color_mask': 't',
        'ninja_icon': 't',
        'ninja_icon_color_mask': 't',
        'null': 't',
        'old_lady_color': 't',
        'old_lady_color_mask': 't',
        'old_lady_icon': 't',
        'old_lady_icon_color_mask': 't',
        'opera_singer_color': 't',
        'opera_singer_color_mask': 't',
        'opera_singer_icon': 't',
        'opera_singer_icon_color_mask': 't',
        'ouya_icon': 't',
        'ouya_obutton': 't',
        'ouya_ubutton': 't',
        'ouya_ybutton': 't',
        'penguin_color': 't',
        'penguin_color_mask': 't',
        'penguin_icon': 't',
        'penguin_icon_color_mask': 't',
        'pixie_color': 't',
        'pixie_color_mask': 't',
        'pixie_icon': 't',
        'pixie_icon_color_mask': 't',
        'player_lineup': 't',
        'plus_button': 't',
        'powerup_bomb': 't',
        'powerup_curse': 't',
        'powerup_health': 't',
        'powerup_ice_bombs': 't',
        'powerup_impact_bombs': 't',
        'powerup_land_mines': 't',
        'powerup_punch': 't',
        'powerup_shield': 't',
        'powerup_speed': 't',
        'powerup_sticky_bombs': 't',
        'puck_color': 't',
        'quote_bubble': 't',
        'rampage_bgcolor': 't',
        'rampage_bgcolor2': 't',
        'rampage_level_color': 't',
        'rampage_preview': 't',
        'replay_icon': 't',
        'right_button': 't',
        'robot_color': 't',
        'robot_color_mask': 't',
        'robot_icon': 't',
        'robot_icon_color_mask': 't',
        'roundabout_level_color': 't',
        'roundabout_preview': 't',
        'santa_color': 't',
        'santa_color_mask': 't',
        'santa_icon': 't',
        'santa_icon_color_mask': 't',
        'settings_icon': 't',
        'slash': 't',
        'star': 't',
        'step_right_up_level_color': 't',
        'step_right_up_preview': 't',
        'store_character': 't',
        'store_character_easter': 't',
        'store_character_xmas': 't',
        'store_icon': 't',
        'superhero_color': 't',
        'superhero_color_mask': 't',
        'superhero_icon': 't',
        'superhero_icon_color_mask': 't',
        'the_pad_level_color': 't',
        'the_pad_preview': 't',
        'ticket_roll': 't',
        'ticket_roll_big': 't',
        'ticket_rolls': 't',
        'tickets': 't',
        'tickets_more': 't',
        'tickets_purple': 't',
        'tip_top_bgcolor': 't',
        'tip_top_level_color': 't',
        'tip_top_preview': 't',
        'tnt': 't',
        'tokens1': 't',
        'tokens2': 't',
        'tokens3': 't',
        'tokens4': 't',
        'tower_dlevel_color': 't',
        'tower_dpreview': 't',
        'trees_color': 't',
        'trophy': 't',
        'tv': 't',
        'up_button': 't',
        'vr_fill_mound': 't',
        'warrior_color': 't',
        'warrior_color_mask': 't',
        'warrior_icon': 't',
        'warrior_icon_color_mask': 't',
        'window_bottom_cap': 't',
        'witch_color': 't',
        'witch_color_mask': 't',
        'witch_icon': 't',
        'witch_icon_color_mask': 't',
        'wizard_color': 't',
        'wizard_color_mask': 't',
        'wizard_icon': 't',
        'wizard_icon_color_mask': 't',
        'wrestler_color': 't',
        'wrestler_color_mask': 't',
        'wrestler_icon': 't',
        'wrestler_icon_color_mask': 't',
        'zig_zag_level_color': 't',
        'zigzag_preview': 't',
        'zoe_color': 't',
        'zoe_color_mask': 't',
        'zoe_icon': 't',
        'zoe_icon_color_mask': 't',
    },
}


if not TYPE_CHECKING:
    audio = AssetDir(__asset_package__, _TREE['audio'], 'audio')
    meshes = AssetDir(__asset_package__, _TREE['meshes'], 'meshes')
    textures = AssetDir(__asset_package__, _TREE['textures'], 'textures')
