# Released under the MIT License. See LICENSE for details.
#
# Auto-generated; do not edit by hand.
"""Asset-package wrapper for ``a-0.bastdassets.260716`` (bauiv1).

All assets for classic bombsquad.
"""

# ba_meta require api 9
# ba_meta require asset-package a-0.bastdassets.260716

# pylint: disable=useless-suppression
# pylint: disable=too-many-lines
# pylint: disable=too-few-public-methods, disallowed-name

__asset_package__ = 'a-0.bastdassets.260716'

from typing import TYPE_CHECKING

from bauiv1._assetref import AssetRefDir

from bacommon.langstr import LangStrDir

if TYPE_CHECKING:
    from bauiv1._assetref import MeshRef, SoundRef, TextureRef
    from bacommon.langstr import LangStr

    class AudioGroup:
        """
        All standard game sounds (everything non-bootstrap).

        See source for the full asset list.
        """

        achievement: SoundRef
        action_hero1: SoundRef
        action_hero2: SoundRef
        action_hero3: SoundRef
        action_hero4: SoundRef
        action_hero_death: SoundRef
        action_hero_fall: SoundRef
        action_hero_hit1: SoundRef
        action_hero_hit2: SoundRef
        activate_beep: SoundRef
        agent1: SoundRef
        agent2: SoundRef
        agent3: SoundRef
        agent4: SoundRef
        agent_death: SoundRef
        agent_fall: SoundRef
        agent_hit1: SoundRef
        agent_hit2: SoundRef
        alarm: SoundRef
        ali1: SoundRef
        ali2: SoundRef
        ali3: SoundRef
        ali4: SoundRef
        ali_death: SoundRef
        ali_fall: SoundRef
        ali_hit1: SoundRef
        ali_hit2: SoundRef
        alien1: SoundRef
        alien2: SoundRef
        alien3: SoundRef
        alien4: SoundRef
        alien_death: SoundRef
        alien_fall: SoundRef
        alien_hit1: SoundRef
        alien_hit2: SoundRef
        announce_eight: SoundRef
        announce_five: SoundRef
        announce_four: SoundRef
        announce_nine: SoundRef
        announce_one: SoundRef
        announce_seven: SoundRef
        announce_six: SoundRef
        announce_ten: SoundRef
        announce_three: SoundRef
        announce_two: SoundRef
        assassin1: SoundRef
        assassin2: SoundRef
        assassin3: SoundRef
        assassin4: SoundRef
        assassin_death: SoundRef
        assassin_fall: SoundRef
        assassin_hit1: SoundRef
        assassin_hit2: SoundRef
        aww: SoundRef
        bear1: SoundRef
        bear2: SoundRef
        bear3: SoundRef
        bear4: SoundRef
        bear_death: SoundRef
        bear_fall: SoundRef
        bear_hit1: SoundRef
        bear_hit2: SoundRef
        bell_high: SoundRef
        bell_low: SoundRef
        bell_med: SoundRef
        big_impact: SoundRef
        big_impact2: SoundRef
        block: SoundRef
        bomb_drop01: SoundRef
        bomb_drop02: SoundRef
        bomb_roll01: SoundRef
        bones1: SoundRef
        bones2: SoundRef
        bones3: SoundRef
        bones_death: SoundRef
        bones_fall: SoundRef
        boo: SoundRef
        box_drop: SoundRef
        boxing_bell: SoundRef
        bunny1: SoundRef
        bunny2: SoundRef
        bunny3: SoundRef
        bunny4: SoundRef
        bunny_death: SoundRef
        bunny_fall: SoundRef
        bunny_hit1: SoundRef
        bunny_hit2: SoundRef
        bunny_jump: SoundRef
        cash_register2: SoundRef
        char_select_music: SoundRef
        cheer: SoundRef
        cork_pop2: SoundRef
        cowboy1: SoundRef
        cowboy2: SoundRef
        cowboy3: SoundRef
        cowboy4: SoundRef
        cowboy_death: SoundRef
        cowboy_fall: SoundRef
        cowboy_hit1: SoundRef
        cowboy_hit2: SoundRef
        crowd_chant: SoundRef
        cyborg1: SoundRef
        cyborg2: SoundRef
        cyborg3: SoundRef
        cyborg4: SoundRef
        cyborg_death: SoundRef
        cyborg_fall: SoundRef
        cyborg_hit1: SoundRef
        cyborg_hit2: SoundRef
        cymbal: SoundRef
        debris_fall: SoundRef
        deek2: SoundRef
        ding_small: SoundRef
        ding_small_high: SoundRef
        dripity: SoundRef
        drum_roll: SoundRef
        drum_roll_short: SoundRef
        explosion01: SoundRef
        explosion02: SoundRef
        explosion03: SoundRef
        explosion04: SoundRef
        explosion05: SoundRef
        fanfare: SoundRef
        flag_catcher_music: SoundRef
        flying_music: SoundRef
        foghorn: SoundRef
        foot_impact01: SoundRef
        foot_impact02: SoundRef
        foot_impact03: SoundRef
        forward_march_music: SoundRef
        freeze: SoundRef
        frosty01: SoundRef
        frosty02: SoundRef
        frosty03: SoundRef
        frosty04: SoundRef
        frosty05: SoundRef
        frosty_death: SoundRef
        frosty_fall: SoundRef
        frosty_hit01: SoundRef
        frosty_hit02: SoundRef
        frosty_hit03: SoundRef
        fuse01: SoundRef
        gasp: SoundRef
        gladiator1: SoundRef
        gladiator2: SoundRef
        gladiator3: SoundRef
        gladiator4: SoundRef
        gladiator_death: SoundRef
        gladiator_fall: SoundRef
        gladiator_hit1: SoundRef
        gladiator_hit2: SoundRef
        gong: SoundRef
        grand_romp_music: SoundRef
        gravel_skid: SoundRef
        health_powerup: SoundRef
        hiss: SoundRef
        impact_hard: SoundRef
        impact_hard2: SoundRef
        impact_hard3: SoundRef
        impact_medium: SoundRef
        impact_medium2: SoundRef
        jack01: SoundRef
        jack02: SoundRef
        jack03: SoundRef
        jack04: SoundRef
        jack05: SoundRef
        jack06: SoundRef
        jack_death01: SoundRef
        jack_fall01: SoundRef
        jack_hit01: SoundRef
        jack_hit02: SoundRef
        jack_hit03: SoundRef
        jack_hit04: SoundRef
        jack_hit05: SoundRef
        jack_hit06: SoundRef
        jack_hit07: SoundRef
        jumpsuit1: SoundRef
        jumpsuit2: SoundRef
        jumpsuit3: SoundRef
        jumpsuit4: SoundRef
        jumpsuit_death: SoundRef
        jumpsuit_fall: SoundRef
        jumpsuit_hit1: SoundRef
        jumpsuit_hit2: SoundRef
        kronk1: SoundRef
        kronk10: SoundRef
        kronk2: SoundRef
        kronk3: SoundRef
        kronk4: SoundRef
        kronk5: SoundRef
        kronk6: SoundRef
        kronk7: SoundRef
        kronk8: SoundRef
        kronk9: SoundRef
        kronk_death: SoundRef
        kronk_fall: SoundRef
        laser: SoundRef
        laser_reverse: SoundRef
        mel01: SoundRef
        mel02: SoundRef
        mel03: SoundRef
        mel04: SoundRef
        mel05: SoundRef
        mel06: SoundRef
        mel07: SoundRef
        mel08: SoundRef
        mel09: SoundRef
        mel10: SoundRef
        mel_death01: SoundRef
        mel_fall01: SoundRef
        menu_music: SoundRef
        metal_hit: SoundRef
        metal_skid: SoundRef
        nice: SoundRef
        ninja_attack1: SoundRef
        ninja_attack2: SoundRef
        ninja_attack3: SoundRef
        ninja_attack4: SoundRef
        ninja_attack5: SoundRef
        ninja_attack6: SoundRef
        ninja_attack7: SoundRef
        ninja_death1: SoundRef
        ninja_fall1: SoundRef
        ninja_hit1: SoundRef
        ninja_hit2: SoundRef
        ninja_hit3: SoundRef
        ninja_hit4: SoundRef
        ninja_hit5: SoundRef
        ninja_hit6: SoundRef
        ninja_hit7: SoundRef
        ninja_hit8: SoundRef
        old_lady1: SoundRef
        old_lady2: SoundRef
        old_lady3: SoundRef
        old_lady4: SoundRef
        old_lady_death: SoundRef
        old_lady_fall: SoundRef
        old_lady_hit1: SoundRef
        old_lady_hit2: SoundRef
        ooh: SoundRef
        opera_singer1: SoundRef
        opera_singer2: SoundRef
        opera_singer3: SoundRef
        opera_singer4: SoundRef
        opera_singer_death: SoundRef
        opera_singer_fall: SoundRef
        opera_singer_hit1: SoundRef
        opera_singer_hit2: SoundRef
        orchestra_hit: SoundRef
        orchestra_hit2: SoundRef
        orchestra_hit3: SoundRef
        orchestra_hit4: SoundRef
        orchestra_hit_big1: SoundRef
        orchestra_hit_big2: SoundRef
        penguin1: SoundRef
        penguin2: SoundRef
        penguin3: SoundRef
        penguin4: SoundRef
        penguin_death: SoundRef
        penguin_fall: SoundRef
        penguin_hit1: SoundRef
        penguin_hit2: SoundRef
        pixie1: SoundRef
        pixie2: SoundRef
        pixie3: SoundRef
        pixie4: SoundRef
        pixie_death: SoundRef
        pixie_fall: SoundRef
        pixie_hit1: SoundRef
        pixie_hit2: SoundRef
        player_death: SoundRef
        player_left: SoundRef
        pop01: SoundRef
        powerup01: SoundRef
        punch_strong01: SoundRef
        punch_strong02: SoundRef
        punch_swish: SoundRef
        punch_weak01: SoundRef
        race_beep1: SoundRef
        race_beep2: SoundRef
        ref_whistle: SoundRef
        rev_up: SoundRef
        robot1: SoundRef
        robot2: SoundRef
        robot3: SoundRef
        robot4: SoundRef
        robot_death: SoundRef
        robot_fall: SoundRef
        robot_hit1: SoundRef
        robot_hit2: SoundRef
        run_away_music: SoundRef
        santa01: SoundRef
        santa02: SoundRef
        santa03: SoundRef
        santa04: SoundRef
        santa05: SoundRef
        santa_death: SoundRef
        santa_fall: SoundRef
        santa_hit01: SoundRef
        santa_hit02: SoundRef
        santa_hit03: SoundRef
        santa_hit04: SoundRef
        scamper01: SoundRef
        scary_music: SoundRef
        score: SoundRef
        score_hit01: SoundRef
        score_hit02: SoundRef
        scores_epic_music: SoundRef
        shatter: SoundRef
        shield_down: SoundRef
        shield_hit: SoundRef
        shield_up: SoundRef
        skid01: SoundRef
        slow_epic_music: SoundRef
        spawn: SoundRef
        spaz_attack01: SoundRef
        spaz_attack02: SoundRef
        spaz_attack03: SoundRef
        spaz_attack04: SoundRef
        spaz_death01: SoundRef
        spaz_eff: SoundRef
        spaz_fall01: SoundRef
        spaz_impact01: SoundRef
        spaz_impact02: SoundRef
        spaz_impact03: SoundRef
        spaz_impact04: SoundRef
        spaz_jump01: SoundRef
        spaz_jump02: SoundRef
        spaz_jump03: SoundRef
        spaz_jump04: SoundRef
        spaz_ow: SoundRef
        spaz_pickup01: SoundRef
        spaz_scream01: SoundRef
        splatter: SoundRef
        sports_music: SoundRef
        sticky_impact: SoundRef
        super_punch: SoundRef
        superhero1: SoundRef
        superhero2: SoundRef
        superhero3: SoundRef
        superhero4: SoundRef
        superhero_death: SoundRef
        superhero_fall: SoundRef
        superhero_hit1: SoundRef
        superhero_hit2: SoundRef
        survival_music: SoundRef
        swip: SoundRef
        swip2: SoundRef
        techno_hit01: SoundRef
        tick: SoundRef
        ticking: SoundRef
        to_the_death_music: SoundRef
        trash_rummage: SoundRef
        victory_music: SoundRef
        warn_beep: SoundRef
        warn_beeps: SoundRef
        warrior1: SoundRef
        warrior2: SoundRef
        warrior3: SoundRef
        warrior4: SoundRef
        warrior_death: SoundRef
        warrior_fall: SoundRef
        warrior_hit1: SoundRef
        warrior_hit2: SoundRef
        when_johnny_comes_marching_home_music: SoundRef
        witch1: SoundRef
        witch2: SoundRef
        witch3: SoundRef
        witch4: SoundRef
        witch_death: SoundRef
        witch_fall: SoundRef
        witch_hit1: SoundRef
        witch_hit2: SoundRef
        wizard1: SoundRef
        wizard2: SoundRef
        wizard3: SoundRef
        wizard4: SoundRef
        wizard_death: SoundRef
        wizard_fall: SoundRef
        wizard_hit1: SoundRef
        wizard_hit2: SoundRef
        woo: SoundRef
        woo2: SoundRef
        woo3: SoundRef
        wood_debris_fall: SoundRef
        wow: SoundRef
        wrestler1: SoundRef
        wrestler2: SoundRef
        wrestler3: SoundRef
        wrestler4: SoundRef
        wrestler_death: SoundRef
        wrestler_fall: SoundRef
        wrestler_hit1: SoundRef
        wrestler_hit2: SoundRef
        yeah: SoundRef
        zoe_attack01: SoundRef
        zoe_attack02: SoundRef
        zoe_attack03: SoundRef
        zoe_attack04: SoundRef
        zoe_death01: SoundRef
        zoe_eff: SoundRef
        zoe_fall01: SoundRef
        zoe_impact01: SoundRef
        zoe_impact02: SoundRef
        zoe_impact03: SoundRef
        zoe_impact04: SoundRef
        zoe_jump01: SoundRef
        zoe_jump02: SoundRef
        zoe_jump03: SoundRef
        zoe_ow: SoundRef
        zoe_pickup01: SoundRef
        zoe_scream01: SoundRef

    class MeshesGroup:
        """
        All standard game meshes (everything non-bootstrap).

        See source for the full asset list.
        """

        achievement_outline: MeshRef
        action_hero_fore_arm: MeshRef
        action_hero_hand: MeshRef
        action_hero_head: MeshRef
        action_hero_lower_leg: MeshRef
        action_hero_pelvis: MeshRef
        action_hero_toes: MeshRef
        action_hero_torso: MeshRef
        action_hero_upper_arm: MeshRef
        action_hero_upper_leg: MeshRef
        agent_fore_arm: MeshRef
        agent_hand: MeshRef
        agent_head: MeshRef
        agent_lower_leg: MeshRef
        agent_pelvis: MeshRef
        agent_toes: MeshRef
        agent_torso: MeshRef
        agent_upper_arm: MeshRef
        agent_upper_leg: MeshRef
        ali_fore_arm: MeshRef
        ali_hand: MeshRef
        ali_head: MeshRef
        ali_lower_leg: MeshRef
        ali_pelvis: MeshRef
        ali_toes: MeshRef
        ali_torso: MeshRef
        ali_upper_arm: MeshRef
        ali_upper_leg: MeshRef
        alien_fore_arm: MeshRef
        alien_hand: MeshRef
        alien_head: MeshRef
        alien_lower_leg: MeshRef
        alien_pelvis: MeshRef
        alien_toes: MeshRef
        alien_torso: MeshRef
        alien_upper_arm: MeshRef
        alien_upper_leg: MeshRef
        always_land_bg: MeshRef
        always_land_level: MeshRef
        always_land_level_bottom: MeshRef
        always_land_vrfill_mound: MeshRef
        angry_computer_transparent: MeshRef
        assassin_fore_arm: MeshRef
        assassin_hand: MeshRef
        assassin_head: MeshRef
        assassin_lower_leg: MeshRef
        assassin_pelvis: MeshRef
        assassin_toes: MeshRef
        assassin_torso: MeshRef
        assassin_upper_arm: MeshRef
        assassin_upper_leg: MeshRef
        bear_fore_arm: MeshRef
        bear_hand: MeshRef
        bear_head: MeshRef
        bear_lower_leg: MeshRef
        bear_pelvis: MeshRef
        bear_toes: MeshRef
        bear_torso: MeshRef
        bear_upper_arm: MeshRef
        bear_upper_leg: MeshRef
        big_g: MeshRef
        big_gbottom: MeshRef
        bomb: MeshRef
        bomb_sticky: MeshRef
        bones_fore_arm: MeshRef
        bones_hand: MeshRef
        bones_head: MeshRef
        bones_lower_leg: MeshRef
        bones_pelvis: MeshRef
        bones_toes: MeshRef
        bones_torso: MeshRef
        bones_upper_arm: MeshRef
        bones_upper_leg: MeshRef
        bridgit_level_bottom: MeshRef
        bridgit_level_top: MeshRef
        bunny_fore_arm: MeshRef
        bunny_hand: MeshRef
        bunny_head: MeshRef
        bunny_lower_leg: MeshRef
        bunny_pelvis: MeshRef
        bunny_toes: MeshRef
        bunny_torso: MeshRef
        bunny_upper_arm: MeshRef
        bunny_upper_leg: MeshRef
        button_null: MeshRef
        courtyard_level: MeshRef
        courtyard_level_bottom: MeshRef
        cowboy_fore_arm: MeshRef
        cowboy_hand: MeshRef
        cowboy_head: MeshRef
        cowboy_lower_leg: MeshRef
        cowboy_pelvis: MeshRef
        cowboy_toes: MeshRef
        cowboy_torso: MeshRef
        cowboy_upper_arm: MeshRef
        cowboy_upper_leg: MeshRef
        crag_castle_level: MeshRef
        crag_castle_level_bottom: MeshRef
        crag_castle_vrfill_mound: MeshRef
        currency_meter: MeshRef
        currency_plus_button: MeshRef
        cyborg_fore_arm: MeshRef
        cyborg_hand: MeshRef
        cyborg_head: MeshRef
        cyborg_lower_leg: MeshRef
        cyborg_pelvis: MeshRef
        cyborg_toes: MeshRef
        cyborg_torso: MeshRef
        cyborg_upper_arm: MeshRef
        cyborg_upper_leg: MeshRef
        doom_shroom_bg: MeshRef
        doom_shroom_level: MeshRef
        doom_shroom_stem: MeshRef
        doom_shroom_vrfill: MeshRef
        egg: MeshRef
        football_stadium: MeshRef
        football_stadium_vrfill: MeshRef
        frame_inset: MeshRef
        frosty_fore_arm: MeshRef
        frosty_hand: MeshRef
        frosty_head: MeshRef
        frosty_lower_leg: MeshRef
        frosty_pelvis: MeshRef
        frosty_toes: MeshRef
        frosty_torso: MeshRef
        frosty_upper_arm: MeshRef
        frosty_upper_leg: MeshRef
        gladiator_fore_arm: MeshRef
        gladiator_hand: MeshRef
        gladiator_head: MeshRef
        gladiator_lower_leg: MeshRef
        gladiator_pelvis: MeshRef
        gladiator_toes: MeshRef
        gladiator_torso: MeshRef
        gladiator_upper_arm: MeshRef
        gladiator_upper_leg: MeshRef
        heart_opaque: MeshRef
        heart_transparent: MeshRef
        hockey_stadium_inner: MeshRef
        hockey_stadium_outer: MeshRef
        hockey_stadium_stands: MeshRef
        image2x1_vertical: MeshRef
        impact_bomb: MeshRef
        jack_fore_arm: MeshRef
        jack_hand: MeshRef
        jack_head: MeshRef
        jack_lower_leg: MeshRef
        jack_toes: MeshRef
        jack_torso: MeshRef
        jack_upper_arm: MeshRef
        jack_upper_leg: MeshRef
        jumpsuit_fore_arm: MeshRef
        jumpsuit_hand: MeshRef
        jumpsuit_head: MeshRef
        jumpsuit_lower_leg: MeshRef
        jumpsuit_pelvis: MeshRef
        jumpsuit_toes: MeshRef
        jumpsuit_torso: MeshRef
        jumpsuit_upper_arm: MeshRef
        jumpsuit_upper_leg: MeshRef
        kronk_fore_arm: MeshRef
        kronk_hand: MeshRef
        kronk_head: MeshRef
        kronk_lower_leg: MeshRef
        kronk_pelvis: MeshRef
        kronk_toes: MeshRef
        kronk_torso: MeshRef
        kronk_upper_arm: MeshRef
        kronk_upper_leg: MeshRef
        lake_frigid: MeshRef
        lake_frigid_reflections: MeshRef
        lake_frigid_top: MeshRef
        lake_frigid_vrfill: MeshRef
        land_mine: MeshRef
        level_select_button_opaque: MeshRef
        level_select_button_transparent: MeshRef
        logo: MeshRef
        logo_transparent: MeshRef
        mel_fore_arm: MeshRef
        mel_hand: MeshRef
        mel_head: MeshRef
        mel_lower_leg: MeshRef
        mel_toes: MeshRef
        mel_torso: MeshRef
        mel_upper_arm: MeshRef
        mel_upper_leg: MeshRef
        meter_transparent: MeshRef
        monkey_face_level: MeshRef
        monkey_face_level_bottom: MeshRef
        nature_background: MeshRef
        nature_background_vrfill: MeshRef
        neo_spaz_fore_arm: MeshRef
        neo_spaz_hand: MeshRef
        neo_spaz_head: MeshRef
        neo_spaz_lower_leg: MeshRef
        neo_spaz_pelvis: MeshRef
        neo_spaz_toes: MeshRef
        neo_spaz_torso: MeshRef
        neo_spaz_upper_arm: MeshRef
        neo_spaz_upper_leg: MeshRef
        ninja_fore_arm: MeshRef
        ninja_hand: MeshRef
        ninja_head: MeshRef
        ninja_lower_leg: MeshRef
        ninja_pelvis: MeshRef
        ninja_toes: MeshRef
        ninja_torso: MeshRef
        ninja_upper_arm: MeshRef
        ninja_upper_leg: MeshRef
        old_lady_fore_arm: MeshRef
        old_lady_hand: MeshRef
        old_lady_head: MeshRef
        old_lady_lower_leg: MeshRef
        old_lady_pelvis: MeshRef
        old_lady_toes: MeshRef
        old_lady_torso: MeshRef
        old_lady_upper_arm: MeshRef
        old_lady_upper_leg: MeshRef
        opera_singer_fore_arm: MeshRef
        opera_singer_hand: MeshRef
        opera_singer_head: MeshRef
        opera_singer_lower_leg: MeshRef
        opera_singer_pelvis: MeshRef
        opera_singer_toes: MeshRef
        opera_singer_torso: MeshRef
        opera_singer_upper_arm: MeshRef
        opera_singer_upper_leg: MeshRef
        penguin_fore_arm: MeshRef
        penguin_hand: MeshRef
        penguin_head: MeshRef
        penguin_lower_leg: MeshRef
        penguin_pelvis: MeshRef
        penguin_toes: MeshRef
        penguin_torso: MeshRef
        penguin_upper_arm: MeshRef
        penguin_upper_leg: MeshRef
        pixie_fore_arm: MeshRef
        pixie_hand: MeshRef
        pixie_head: MeshRef
        pixie_lower_leg: MeshRef
        pixie_pelvis: MeshRef
        pixie_toes: MeshRef
        pixie_torso: MeshRef
        pixie_upper_arm: MeshRef
        pixie_upper_leg: MeshRef
        plastic_eyes_transparent: MeshRef
        player_lineup1_transparent: MeshRef
        player_lineup2_transparent: MeshRef
        player_lineup3_transparent: MeshRef
        player_lineup4_transparent: MeshRef
        powerup: MeshRef
        powerup_simple: MeshRef
        puck: MeshRef
        rampage_bg: MeshRef
        rampage_bg2: MeshRef
        rampage_level: MeshRef
        rampage_level_bottom: MeshRef
        rampage_vrfill: MeshRef
        robot_fore_arm: MeshRef
        robot_hand: MeshRef
        robot_head: MeshRef
        robot_lower_leg: MeshRef
        robot_pelvis: MeshRef
        robot_toes: MeshRef
        robot_torso: MeshRef
        robot_upper_arm: MeshRef
        robot_upper_leg: MeshRef
        roundabout_level: MeshRef
        roundabout_level_bottom: MeshRef
        running_shoes: MeshRef
        santa_fore_arm: MeshRef
        santa_hand: MeshRef
        santa_head: MeshRef
        santa_lower_leg: MeshRef
        santa_toes: MeshRef
        santa_torso: MeshRef
        santa_upper_arm: MeshRef
        santa_upper_leg: MeshRef
        scroll_widget_short: MeshRef
        step_right_up_level: MeshRef
        step_right_up_level_bottom: MeshRef
        step_right_up_vrfill_mound: MeshRef
        superhero_fore_arm: MeshRef
        superhero_hand: MeshRef
        superhero_head: MeshRef
        superhero_lower_leg: MeshRef
        superhero_pelvis: MeshRef
        superhero_toes: MeshRef
        superhero_torso: MeshRef
        superhero_upper_arm: MeshRef
        superhero_upper_leg: MeshRef
        the_pad_bg: MeshRef
        the_pad_bgsmall: MeshRef
        the_pad_level: MeshRef
        the_pad_level_bottom: MeshRef
        the_pad_vrfill_bottom: MeshRef
        the_pad_vrfill_mound: MeshRef
        the_pad_vrfill_top: MeshRef
        tip_top_bg: MeshRef
        tip_top_level: MeshRef
        tip_top_level_bottom: MeshRef
        tnt: MeshRef
        toolbar_backing: MeshRef
        toolbar_backing_bottom: MeshRef
        toolbar_backing_bottom2: MeshRef
        toolbar_backing_opaque: MeshRef
        toolbar_backing_top: MeshRef
        toolbar_backing_top2: MeshRef
        toolbar_backing_transparent: MeshRef
        tower_dlevel: MeshRef
        tower_dlevel_bottom: MeshRef
        trees: MeshRef
        warrior_fore_arm: MeshRef
        warrior_hand: MeshRef
        warrior_head: MeshRef
        warrior_lower_leg: MeshRef
        warrior_pelvis: MeshRef
        warrior_toes: MeshRef
        warrior_torso: MeshRef
        warrior_upper_arm: MeshRef
        warrior_upper_leg: MeshRef
        window_bgblotch: MeshRef
        witch_fore_arm: MeshRef
        witch_hand: MeshRef
        witch_head: MeshRef
        witch_lower_leg: MeshRef
        witch_pelvis: MeshRef
        witch_toes: MeshRef
        witch_torso: MeshRef
        witch_upper_arm: MeshRef
        witch_upper_leg: MeshRef
        wizard_fore_arm: MeshRef
        wizard_hand: MeshRef
        wizard_head: MeshRef
        wizard_lower_leg: MeshRef
        wizard_pelvis: MeshRef
        wizard_toes: MeshRef
        wizard_torso: MeshRef
        wizard_upper_arm: MeshRef
        wizard_upper_leg: MeshRef
        wrestler_fore_arm: MeshRef
        wrestler_hand: MeshRef
        wrestler_head: MeshRef
        wrestler_lower_leg: MeshRef
        wrestler_pelvis: MeshRef
        wrestler_toes: MeshRef
        wrestler_torso: MeshRef
        wrestler_upper_arm: MeshRef
        wrestler_upper_leg: MeshRef
        zig_zag_level: MeshRef
        zig_zag_level_bottom: MeshRef
        zoe_fore_arm: MeshRef
        zoe_hand: MeshRef
        zoe_head: MeshRef
        zoe_lower_leg: MeshRef
        zoe_pelvis: MeshRef
        zoe_toes: MeshRef
        zoe_torso: MeshRef
        zoe_upper_arm: MeshRef
        zoe_upper_leg: MeshRef

    class StringsEconomyGroup:
        """
        Screen-messages about currency: grants and related notices.

        See source for the full asset list.
        """

        def you_got_tokens(self, *, tokens: int) -> LangStr:
            """
            Confirmation effect sent to game clients when tokens are credited
            (store purchases, promo codes, and other grant flows).

            English: (one) "You got # token!" / (other) "You got # tokens!"
            """

    class StringsGroup:
        """
        All standard game strings (everything non-bootstrap).

        See source for the full asset list.
        """

        economy: StringsEconomyGroup

    class TexturesGroup:
        """
        All standard game textures (everything non-bootstrap).

        See source for the full asset list.
        """

        achievement_boxer: TextureRef
        achievement_cross_hair: TextureRef
        achievement_dual_wielding: TextureRef
        achievement_empty: TextureRef
        achievement_flawless_victory: TextureRef
        achievement_football_shutout: TextureRef
        achievement_football_victory: TextureRef
        achievement_free_loader: TextureRef
        achievement_got_the_moves: TextureRef
        achievement_in_control: TextureRef
        achievement_medal_large: TextureRef
        achievement_medal_medium: TextureRef
        achievement_medal_small: TextureRef
        achievement_mine: TextureRef
        achievement_off_you_go: TextureRef
        achievement_onslaught: TextureRef
        achievement_outline: TextureRef
        achievement_runaround: TextureRef
        achievement_sharing_is_caring: TextureRef
        achievement_stayin_alive: TextureRef
        achievement_super_punch: TextureRef
        achievement_team_player: TextureRef
        achievement_tnt: TextureRef
        achievement_wall: TextureRef
        achievements_icon: TextureRef
        action_hero_color: TextureRef
        action_hero_color_mask: TextureRef
        action_hero_icon: TextureRef
        action_hero_icon_color_mask: TextureRef
        advanced_icon: TextureRef
        agent_color: TextureRef
        agent_color_mask: TextureRef
        agent_icon: TextureRef
        agent_icon_color_mask: TextureRef
        ali_color: TextureRef
        ali_color_mask: TextureRef
        ali_icon: TextureRef
        ali_icon_color_mask: TextureRef
        ali_splash: TextureRef
        alien_color: TextureRef
        alien_color_mask: TextureRef
        alien_icon: TextureRef
        alien_icon_color_mask: TextureRef
        always_land_bgcolor: TextureRef
        always_land_level_color: TextureRef
        always_land_preview: TextureRef
        analog_stick: TextureRef
        assassin_color: TextureRef
        assassin_color_mask: TextureRef
        assassin_icon: TextureRef
        assassin_icon_color_mask: TextureRef
        audio_icon: TextureRef
        bar: TextureRef
        bear_color: TextureRef
        bear_color_mask: TextureRef
        bear_icon: TextureRef
        bear_icon_color_mask: TextureRef
        bg: TextureRef
        big_g: TextureRef
        big_gpreview: TextureRef
        bomb_color: TextureRef
        bomb_color_ice: TextureRef
        bomb_sticky_color: TextureRef
        bones_color: TextureRef
        bones_color_mask: TextureRef
        bones_icon: TextureRef
        bones_icon_color_mask: TextureRef
        bridgit_level_color: TextureRef
        bridgit_preview: TextureRef
        bunny_color: TextureRef
        bunny_color_mask: TextureRef
        bunny_icon: TextureRef
        bunny_icon_color_mask: TextureRef
        button_bomb: TextureRef
        button_jump: TextureRef
        button_pick_up: TextureRef
        button_punch: TextureRef
        ch_title_char1: TextureRef
        ch_title_char2: TextureRef
        ch_title_char3: TextureRef
        ch_title_char4: TextureRef
        ch_title_char5: TextureRef
        chest_icon: TextureRef
        chest_icon_empty: TextureRef
        chest_icon_multi: TextureRef
        chest_icon_tint: TextureRef
        chest_open_icon: TextureRef
        chest_open_icon_tint: TextureRef
        circle_zig_zag: TextureRef
        clay_stroke: TextureRef
        coin: TextureRef
        controller_icon: TextureRef
        courtyard_level_color: TextureRef
        courtyard_preview: TextureRef
        cowboy_color: TextureRef
        cowboy_color_mask: TextureRef
        cowboy_icon: TextureRef
        cowboy_icon_color_mask: TextureRef
        crag_castle_level_color: TextureRef
        crag_castle_preview: TextureRef
        cross_out: TextureRef
        cross_out_mask: TextureRef
        cute_spaz: TextureRef
        cyborg_color: TextureRef
        cyborg_color_mask: TextureRef
        cyborg_icon: TextureRef
        cyborg_icon_color_mask: TextureRef
        discord_icon: TextureRef
        discord_logo: TextureRef
        discord_server: TextureRef
        doom_shroom_bgcolor: TextureRef
        doom_shroom_level_color: TextureRef
        doom_shroom_preview: TextureRef
        down_button: TextureRef
        egg1: TextureRef
        egg2: TextureRef
        egg3: TextureRef
        egg4: TextureRef
        egg_tex1: TextureRef
        egg_tex2: TextureRef
        egg_tex3: TextureRef
        empty: TextureRef
        file: TextureRef
        flag_color: TextureRef
        folder: TextureRef
        football_stadium: TextureRef
        football_stadium_preview: TextureRef
        frame_inset: TextureRef
        frosty_color: TextureRef
        frosty_color_mask: TextureRef
        frosty_icon: TextureRef
        frosty_icon_color_mask: TextureRef
        game_center_icon: TextureRef
        github_logo: TextureRef
        gladiator_color: TextureRef
        gladiator_color_mask: TextureRef
        gladiator_icon: TextureRef
        gladiator_icon_color_mask: TextureRef
        gold_pass: TextureRef
        google_play_achievements_icon: TextureRef
        google_play_games_icon: TextureRef
        google_play_leaderboards_icon: TextureRef
        google_plus_icon: TextureRef
        google_plus_sign_in_button: TextureRef
        graphics_icon: TextureRef
        heart: TextureRef
        hockey_stadium: TextureRef
        hockey_stadium_preview: TextureRef
        icon_onslaught: TextureRef
        icon_runaround: TextureRef
        impact_bomb_color: TextureRef
        impact_bomb_color_lit: TextureRef
        inventory_icon: TextureRef
        jack_color: TextureRef
        jack_color_mask: TextureRef
        jack_icon: TextureRef
        jack_icon_color_mask: TextureRef
        jumpsuit_color: TextureRef
        jumpsuit_color_mask: TextureRef
        jumpsuit_icon: TextureRef
        jumpsuit_icon_color_mask: TextureRef
        kronk: TextureRef
        kronk_color_mask: TextureRef
        kronk_icon: TextureRef
        kronk_icon_color_mask: TextureRef
        lake_frigid: TextureRef
        lake_frigid_preview: TextureRef
        lake_frigid_reflections: TextureRef
        land_mine: TextureRef
        land_mine_lit: TextureRef
        leaderboards_icon: TextureRef
        left_button: TextureRef
        level_icon: TextureRef
        lock: TextureRef
        log_icon: TextureRef
        logo: TextureRef
        logo_easter: TextureRef
        map_preview_mask: TextureRef
        medal_bronze: TextureRef
        medal_complete: TextureRef
        medal_gold: TextureRef
        medal_silver: TextureRef
        mel_color: TextureRef
        mel_color_mask: TextureRef
        mel_icon: TextureRef
        mel_icon_color_mask: TextureRef
        menu_bg: TextureRef
        menu_icon: TextureRef
        merch: TextureRef
        meter: TextureRef
        monkey_face_level_color: TextureRef
        monkey_face_preview: TextureRef
        multiplayer_examples: TextureRef
        nature_background_color: TextureRef
        neo_spaz_color: TextureRef
        neo_spaz_color_mask: TextureRef
        neo_spaz_icon: TextureRef
        neo_spaz_icon_color_mask: TextureRef
        next_level_icon: TextureRef
        ninja_color: TextureRef
        ninja_color_mask: TextureRef
        ninja_icon: TextureRef
        ninja_icon_color_mask: TextureRef
        null: TextureRef
        old_lady_color: TextureRef
        old_lady_color_mask: TextureRef
        old_lady_icon: TextureRef
        old_lady_icon_color_mask: TextureRef
        opera_singer_color: TextureRef
        opera_singer_color_mask: TextureRef
        opera_singer_icon: TextureRef
        opera_singer_icon_color_mask: TextureRef
        ouya_icon: TextureRef
        ouya_obutton: TextureRef
        ouya_ubutton: TextureRef
        ouya_ybutton: TextureRef
        penguin_color: TextureRef
        penguin_color_mask: TextureRef
        penguin_icon: TextureRef
        penguin_icon_color_mask: TextureRef
        pixie_color: TextureRef
        pixie_color_mask: TextureRef
        pixie_icon: TextureRef
        pixie_icon_color_mask: TextureRef
        player_lineup: TextureRef
        plus_button: TextureRef
        powerup_bomb: TextureRef
        powerup_curse: TextureRef
        powerup_health: TextureRef
        powerup_ice_bombs: TextureRef
        powerup_impact_bombs: TextureRef
        powerup_land_mines: TextureRef
        powerup_punch: TextureRef
        powerup_shield: TextureRef
        powerup_speed: TextureRef
        powerup_sticky_bombs: TextureRef
        puck_color: TextureRef
        quote_bubble: TextureRef
        rampage_bgcolor: TextureRef
        rampage_bgcolor2: TextureRef
        rampage_level_color: TextureRef
        rampage_preview: TextureRef
        replay_icon: TextureRef
        right_button: TextureRef
        robot_color: TextureRef
        robot_color_mask: TextureRef
        robot_icon: TextureRef
        robot_icon_color_mask: TextureRef
        roundabout_level_color: TextureRef
        roundabout_preview: TextureRef
        santa_color: TextureRef
        santa_color_mask: TextureRef
        santa_icon: TextureRef
        santa_icon_color_mask: TextureRef
        settings_icon: TextureRef
        slash: TextureRef
        star: TextureRef
        step_right_up_level_color: TextureRef
        step_right_up_preview: TextureRef
        store_character: TextureRef
        store_character_easter: TextureRef
        store_character_xmas: TextureRef
        store_icon: TextureRef
        superhero_color: TextureRef
        superhero_color_mask: TextureRef
        superhero_icon: TextureRef
        superhero_icon_color_mask: TextureRef
        the_pad_level_color: TextureRef
        the_pad_preview: TextureRef
        ticket_roll: TextureRef
        ticket_roll_big: TextureRef
        ticket_rolls: TextureRef
        tickets: TextureRef
        tickets_more: TextureRef
        tickets_purple: TextureRef
        tip_top_bgcolor: TextureRef
        tip_top_level_color: TextureRef
        tip_top_preview: TextureRef
        tnt: TextureRef
        tokens1: TextureRef
        tokens2: TextureRef
        tokens3: TextureRef
        tokens4: TextureRef
        tower_dlevel_color: TextureRef
        tower_dpreview: TextureRef
        trees_color: TextureRef
        trophy: TextureRef
        tv: TextureRef
        up_button: TextureRef
        vr_fill_mound: TextureRef
        warrior_color: TextureRef
        warrior_color_mask: TextureRef
        warrior_icon: TextureRef
        warrior_icon_color_mask: TextureRef
        window_bottom_cap: TextureRef
        witch_color: TextureRef
        witch_color_mask: TextureRef
        witch_icon: TextureRef
        witch_icon_color_mask: TextureRef
        wizard_color: TextureRef
        wizard_color_mask: TextureRef
        wizard_icon: TextureRef
        wizard_icon_color_mask: TextureRef
        wrestler_color: TextureRef
        wrestler_color_mask: TextureRef
        wrestler_icon: TextureRef
        wrestler_icon_color_mask: TextureRef
        zig_zag_level_color: TextureRef
        zigzag_preview: TextureRef
        zoe_color: TextureRef
        zoe_color_mask: TextureRef
        zoe_icon: TextureRef
        zoe_icon_color_mask: TextureRef

    #: The ``audio`` group - 412 assets (``achievement``, ``action_hero1``,
    #: ``action_hero2``, ``action_hero3``, ``action_hero4``, and 407 more). Full
    #: list in source.
    audio: AudioGroup

    #: The ``meshes`` group - 360 assets (``achievement_outline``,
    #: ``action_hero_fore_arm``, ``action_hero_hand``, ``action_hero_head``,
    #: ``action_hero_lower_leg``, and 355 more). Full list in source.
    meshes: MeshesGroup

    #: The ``strings`` group - 1 string (``economy``). Full list in source.
    strings: StringsGroup

    #: The ``textures`` group - 313 assets (``achievement_boxer``,
    #: ``achievement_cross_hair``, ``achievement_dual_wielding``,
    #: ``achievement_empty``, ``achievement_flawless_victory``, and 308 more).
    #: Full list in source.
    textures: TexturesGroup

_TREE = {
    'audio': {
        'achievement': 's',
        'action_hero1': 's',
        'action_hero2': 's',
        'action_hero3': 's',
        'action_hero4': 's',
        'action_hero_death': 's',
        'action_hero_fall': 's',
        'action_hero_hit1': 's',
        'action_hero_hit2': 's',
        'activate_beep': 's',
        'agent1': 's',
        'agent2': 's',
        'agent3': 's',
        'agent4': 's',
        'agent_death': 's',
        'agent_fall': 's',
        'agent_hit1': 's',
        'agent_hit2': 's',
        'alarm': 's',
        'ali1': 's',
        'ali2': 's',
        'ali3': 's',
        'ali4': 's',
        'ali_death': 's',
        'ali_fall': 's',
        'ali_hit1': 's',
        'ali_hit2': 's',
        'alien1': 's',
        'alien2': 's',
        'alien3': 's',
        'alien4': 's',
        'alien_death': 's',
        'alien_fall': 's',
        'alien_hit1': 's',
        'alien_hit2': 's',
        'announce_eight': 's',
        'announce_five': 's',
        'announce_four': 's',
        'announce_nine': 's',
        'announce_one': 's',
        'announce_seven': 's',
        'announce_six': 's',
        'announce_ten': 's',
        'announce_three': 's',
        'announce_two': 's',
        'assassin1': 's',
        'assassin2': 's',
        'assassin3': 's',
        'assassin4': 's',
        'assassin_death': 's',
        'assassin_fall': 's',
        'assassin_hit1': 's',
        'assassin_hit2': 's',
        'aww': 's',
        'bear1': 's',
        'bear2': 's',
        'bear3': 's',
        'bear4': 's',
        'bear_death': 's',
        'bear_fall': 's',
        'bear_hit1': 's',
        'bear_hit2': 's',
        'bell_high': 's',
        'bell_low': 's',
        'bell_med': 's',
        'big_impact': 's',
        'big_impact2': 's',
        'block': 's',
        'bomb_drop01': 's',
        'bomb_drop02': 's',
        'bomb_roll01': 's',
        'bones1': 's',
        'bones2': 's',
        'bones3': 's',
        'bones_death': 's',
        'bones_fall': 's',
        'boo': 's',
        'box_drop': 's',
        'boxing_bell': 's',
        'bunny1': 's',
        'bunny2': 's',
        'bunny3': 's',
        'bunny4': 's',
        'bunny_death': 's',
        'bunny_fall': 's',
        'bunny_hit1': 's',
        'bunny_hit2': 's',
        'bunny_jump': 's',
        'cash_register2': 's',
        'char_select_music': 's',
        'cheer': 's',
        'cork_pop2': 's',
        'cowboy1': 's',
        'cowboy2': 's',
        'cowboy3': 's',
        'cowboy4': 's',
        'cowboy_death': 's',
        'cowboy_fall': 's',
        'cowboy_hit1': 's',
        'cowboy_hit2': 's',
        'crowd_chant': 's',
        'cyborg1': 's',
        'cyborg2': 's',
        'cyborg3': 's',
        'cyborg4': 's',
        'cyborg_death': 's',
        'cyborg_fall': 's',
        'cyborg_hit1': 's',
        'cyborg_hit2': 's',
        'cymbal': 's',
        'debris_fall': 's',
        'deek2': 's',
        'ding_small': 's',
        'ding_small_high': 's',
        'dripity': 's',
        'drum_roll': 's',
        'drum_roll_short': 's',
        'explosion01': 's',
        'explosion02': 's',
        'explosion03': 's',
        'explosion04': 's',
        'explosion05': 's',
        'fanfare': 's',
        'flag_catcher_music': 's',
        'flying_music': 's',
        'foghorn': 's',
        'foot_impact01': 's',
        'foot_impact02': 's',
        'foot_impact03': 's',
        'forward_march_music': 's',
        'freeze': 's',
        'frosty01': 's',
        'frosty02': 's',
        'frosty03': 's',
        'frosty04': 's',
        'frosty05': 's',
        'frosty_death': 's',
        'frosty_fall': 's',
        'frosty_hit01': 's',
        'frosty_hit02': 's',
        'frosty_hit03': 's',
        'fuse01': 's',
        'gasp': 's',
        'gladiator1': 's',
        'gladiator2': 's',
        'gladiator3': 's',
        'gladiator4': 's',
        'gladiator_death': 's',
        'gladiator_fall': 's',
        'gladiator_hit1': 's',
        'gladiator_hit2': 's',
        'gong': 's',
        'grand_romp_music': 's',
        'gravel_skid': 's',
        'health_powerup': 's',
        'hiss': 's',
        'impact_hard': 's',
        'impact_hard2': 's',
        'impact_hard3': 's',
        'impact_medium': 's',
        'impact_medium2': 's',
        'jack01': 's',
        'jack02': 's',
        'jack03': 's',
        'jack04': 's',
        'jack05': 's',
        'jack06': 's',
        'jack_death01': 's',
        'jack_fall01': 's',
        'jack_hit01': 's',
        'jack_hit02': 's',
        'jack_hit03': 's',
        'jack_hit04': 's',
        'jack_hit05': 's',
        'jack_hit06': 's',
        'jack_hit07': 's',
        'jumpsuit1': 's',
        'jumpsuit2': 's',
        'jumpsuit3': 's',
        'jumpsuit4': 's',
        'jumpsuit_death': 's',
        'jumpsuit_fall': 's',
        'jumpsuit_hit1': 's',
        'jumpsuit_hit2': 's',
        'kronk1': 's',
        'kronk10': 's',
        'kronk2': 's',
        'kronk3': 's',
        'kronk4': 's',
        'kronk5': 's',
        'kronk6': 's',
        'kronk7': 's',
        'kronk8': 's',
        'kronk9': 's',
        'kronk_death': 's',
        'kronk_fall': 's',
        'laser': 's',
        'laser_reverse': 's',
        'mel01': 's',
        'mel02': 's',
        'mel03': 's',
        'mel04': 's',
        'mel05': 's',
        'mel06': 's',
        'mel07': 's',
        'mel08': 's',
        'mel09': 's',
        'mel10': 's',
        'mel_death01': 's',
        'mel_fall01': 's',
        'menu_music': 's',
        'metal_hit': 's',
        'metal_skid': 's',
        'nice': 's',
        'ninja_attack1': 's',
        'ninja_attack2': 's',
        'ninja_attack3': 's',
        'ninja_attack4': 's',
        'ninja_attack5': 's',
        'ninja_attack6': 's',
        'ninja_attack7': 's',
        'ninja_death1': 's',
        'ninja_fall1': 's',
        'ninja_hit1': 's',
        'ninja_hit2': 's',
        'ninja_hit3': 's',
        'ninja_hit4': 's',
        'ninja_hit5': 's',
        'ninja_hit6': 's',
        'ninja_hit7': 's',
        'ninja_hit8': 's',
        'old_lady1': 's',
        'old_lady2': 's',
        'old_lady3': 's',
        'old_lady4': 's',
        'old_lady_death': 's',
        'old_lady_fall': 's',
        'old_lady_hit1': 's',
        'old_lady_hit2': 's',
        'ooh': 's',
        'opera_singer1': 's',
        'opera_singer2': 's',
        'opera_singer3': 's',
        'opera_singer4': 's',
        'opera_singer_death': 's',
        'opera_singer_fall': 's',
        'opera_singer_hit1': 's',
        'opera_singer_hit2': 's',
        'orchestra_hit': 's',
        'orchestra_hit2': 's',
        'orchestra_hit3': 's',
        'orchestra_hit4': 's',
        'orchestra_hit_big1': 's',
        'orchestra_hit_big2': 's',
        'penguin1': 's',
        'penguin2': 's',
        'penguin3': 's',
        'penguin4': 's',
        'penguin_death': 's',
        'penguin_fall': 's',
        'penguin_hit1': 's',
        'penguin_hit2': 's',
        'pixie1': 's',
        'pixie2': 's',
        'pixie3': 's',
        'pixie4': 's',
        'pixie_death': 's',
        'pixie_fall': 's',
        'pixie_hit1': 's',
        'pixie_hit2': 's',
        'player_death': 's',
        'player_left': 's',
        'pop01': 's',
        'powerup01': 's',
        'punch_strong01': 's',
        'punch_strong02': 's',
        'punch_swish': 's',
        'punch_weak01': 's',
        'race_beep1': 's',
        'race_beep2': 's',
        'ref_whistle': 's',
        'rev_up': 's',
        'robot1': 's',
        'robot2': 's',
        'robot3': 's',
        'robot4': 's',
        'robot_death': 's',
        'robot_fall': 's',
        'robot_hit1': 's',
        'robot_hit2': 's',
        'run_away_music': 's',
        'santa01': 's',
        'santa02': 's',
        'santa03': 's',
        'santa04': 's',
        'santa05': 's',
        'santa_death': 's',
        'santa_fall': 's',
        'santa_hit01': 's',
        'santa_hit02': 's',
        'santa_hit03': 's',
        'santa_hit04': 's',
        'scamper01': 's',
        'scary_music': 's',
        'score': 's',
        'score_hit01': 's',
        'score_hit02': 's',
        'scores_epic_music': 's',
        'shatter': 's',
        'shield_down': 's',
        'shield_hit': 's',
        'shield_up': 's',
        'skid01': 's',
        'slow_epic_music': 's',
        'spawn': 's',
        'spaz_attack01': 's',
        'spaz_attack02': 's',
        'spaz_attack03': 's',
        'spaz_attack04': 's',
        'spaz_death01': 's',
        'spaz_eff': 's',
        'spaz_fall01': 's',
        'spaz_impact01': 's',
        'spaz_impact02': 's',
        'spaz_impact03': 's',
        'spaz_impact04': 's',
        'spaz_jump01': 's',
        'spaz_jump02': 's',
        'spaz_jump03': 's',
        'spaz_jump04': 's',
        'spaz_ow': 's',
        'spaz_pickup01': 's',
        'spaz_scream01': 's',
        'splatter': 's',
        'sports_music': 's',
        'sticky_impact': 's',
        'super_punch': 's',
        'superhero1': 's',
        'superhero2': 's',
        'superhero3': 's',
        'superhero4': 's',
        'superhero_death': 's',
        'superhero_fall': 's',
        'superhero_hit1': 's',
        'superhero_hit2': 's',
        'survival_music': 's',
        'swip': 's',
        'swip2': 's',
        'techno_hit01': 's',
        'tick': 's',
        'ticking': 's',
        'to_the_death_music': 's',
        'trash_rummage': 's',
        'victory_music': 's',
        'warn_beep': 's',
        'warn_beeps': 's',
        'warrior1': 's',
        'warrior2': 's',
        'warrior3': 's',
        'warrior4': 's',
        'warrior_death': 's',
        'warrior_fall': 's',
        'warrior_hit1': 's',
        'warrior_hit2': 's',
        'when_johnny_comes_marching_home_music': 's',
        'witch1': 's',
        'witch2': 's',
        'witch3': 's',
        'witch4': 's',
        'witch_death': 's',
        'witch_fall': 's',
        'witch_hit1': 's',
        'witch_hit2': 's',
        'wizard1': 's',
        'wizard2': 's',
        'wizard3': 's',
        'wizard4': 's',
        'wizard_death': 's',
        'wizard_fall': 's',
        'wizard_hit1': 's',
        'wizard_hit2': 's',
        'woo': 's',
        'woo2': 's',
        'woo3': 's',
        'wood_debris_fall': 's',
        'wow': 's',
        'wrestler1': 's',
        'wrestler2': 's',
        'wrestler3': 's',
        'wrestler4': 's',
        'wrestler_death': 's',
        'wrestler_fall': 's',
        'wrestler_hit1': 's',
        'wrestler_hit2': 's',
        'yeah': 's',
        'zoe_attack01': 's',
        'zoe_attack02': 's',
        'zoe_attack03': 's',
        'zoe_attack04': 's',
        'zoe_death01': 's',
        'zoe_eff': 's',
        'zoe_fall01': 's',
        'zoe_impact01': 's',
        'zoe_impact02': 's',
        'zoe_impact03': 's',
        'zoe_impact04': 's',
        'zoe_jump01': 's',
        'zoe_jump02': 's',
        'zoe_jump03': 's',
        'zoe_ow': 's',
        'zoe_pickup01': 's',
        'zoe_scream01': 's',
    },
    'meshes': {
        'achievement_outline': 'm',
        'action_hero_fore_arm': 'm',
        'action_hero_hand': 'm',
        'action_hero_head': 'm',
        'action_hero_lower_leg': 'm',
        'action_hero_pelvis': 'm',
        'action_hero_toes': 'm',
        'action_hero_torso': 'm',
        'action_hero_upper_arm': 'm',
        'action_hero_upper_leg': 'm',
        'agent_fore_arm': 'm',
        'agent_hand': 'm',
        'agent_head': 'm',
        'agent_lower_leg': 'm',
        'agent_pelvis': 'm',
        'agent_toes': 'm',
        'agent_torso': 'm',
        'agent_upper_arm': 'm',
        'agent_upper_leg': 'm',
        'ali_fore_arm': 'm',
        'ali_hand': 'm',
        'ali_head': 'm',
        'ali_lower_leg': 'm',
        'ali_pelvis': 'm',
        'ali_toes': 'm',
        'ali_torso': 'm',
        'ali_upper_arm': 'm',
        'ali_upper_leg': 'm',
        'alien_fore_arm': 'm',
        'alien_hand': 'm',
        'alien_head': 'm',
        'alien_lower_leg': 'm',
        'alien_pelvis': 'm',
        'alien_toes': 'm',
        'alien_torso': 'm',
        'alien_upper_arm': 'm',
        'alien_upper_leg': 'm',
        'always_land_bg': 'm',
        'always_land_level': 'm',
        'always_land_level_bottom': 'm',
        'always_land_vrfill_mound': 'm',
        'angry_computer_transparent': 'm',
        'assassin_fore_arm': 'm',
        'assassin_hand': 'm',
        'assassin_head': 'm',
        'assassin_lower_leg': 'm',
        'assassin_pelvis': 'm',
        'assassin_toes': 'm',
        'assassin_torso': 'm',
        'assassin_upper_arm': 'm',
        'assassin_upper_leg': 'm',
        'bear_fore_arm': 'm',
        'bear_hand': 'm',
        'bear_head': 'm',
        'bear_lower_leg': 'm',
        'bear_pelvis': 'm',
        'bear_toes': 'm',
        'bear_torso': 'm',
        'bear_upper_arm': 'm',
        'bear_upper_leg': 'm',
        'big_g': 'm',
        'big_gbottom': 'm',
        'bomb': 'm',
        'bomb_sticky': 'm',
        'bones_fore_arm': 'm',
        'bones_hand': 'm',
        'bones_head': 'm',
        'bones_lower_leg': 'm',
        'bones_pelvis': 'm',
        'bones_toes': 'm',
        'bones_torso': 'm',
        'bones_upper_arm': 'm',
        'bones_upper_leg': 'm',
        'bridgit_level_bottom': 'm',
        'bridgit_level_top': 'm',
        'bunny_fore_arm': 'm',
        'bunny_hand': 'm',
        'bunny_head': 'm',
        'bunny_lower_leg': 'm',
        'bunny_pelvis': 'm',
        'bunny_toes': 'm',
        'bunny_torso': 'm',
        'bunny_upper_arm': 'm',
        'bunny_upper_leg': 'm',
        'button_null': 'm',
        'courtyard_level': 'm',
        'courtyard_level_bottom': 'm',
        'cowboy_fore_arm': 'm',
        'cowboy_hand': 'm',
        'cowboy_head': 'm',
        'cowboy_lower_leg': 'm',
        'cowboy_pelvis': 'm',
        'cowboy_toes': 'm',
        'cowboy_torso': 'm',
        'cowboy_upper_arm': 'm',
        'cowboy_upper_leg': 'm',
        'crag_castle_level': 'm',
        'crag_castle_level_bottom': 'm',
        'crag_castle_vrfill_mound': 'm',
        'currency_meter': 'm',
        'currency_plus_button': 'm',
        'cyborg_fore_arm': 'm',
        'cyborg_hand': 'm',
        'cyborg_head': 'm',
        'cyborg_lower_leg': 'm',
        'cyborg_pelvis': 'm',
        'cyborg_toes': 'm',
        'cyborg_torso': 'm',
        'cyborg_upper_arm': 'm',
        'cyborg_upper_leg': 'm',
        'doom_shroom_bg': 'm',
        'doom_shroom_level': 'm',
        'doom_shroom_stem': 'm',
        'doom_shroom_vrfill': 'm',
        'egg': 'm',
        'football_stadium': 'm',
        'football_stadium_vrfill': 'm',
        'frame_inset': 'm',
        'frosty_fore_arm': 'm',
        'frosty_hand': 'm',
        'frosty_head': 'm',
        'frosty_lower_leg': 'm',
        'frosty_pelvis': 'm',
        'frosty_toes': 'm',
        'frosty_torso': 'm',
        'frosty_upper_arm': 'm',
        'frosty_upper_leg': 'm',
        'gladiator_fore_arm': 'm',
        'gladiator_hand': 'm',
        'gladiator_head': 'm',
        'gladiator_lower_leg': 'm',
        'gladiator_pelvis': 'm',
        'gladiator_toes': 'm',
        'gladiator_torso': 'm',
        'gladiator_upper_arm': 'm',
        'gladiator_upper_leg': 'm',
        'heart_opaque': 'm',
        'heart_transparent': 'm',
        'hockey_stadium_inner': 'm',
        'hockey_stadium_outer': 'm',
        'hockey_stadium_stands': 'm',
        'image2x1_vertical': 'm',
        'impact_bomb': 'm',
        'jack_fore_arm': 'm',
        'jack_hand': 'm',
        'jack_head': 'm',
        'jack_lower_leg': 'm',
        'jack_toes': 'm',
        'jack_torso': 'm',
        'jack_upper_arm': 'm',
        'jack_upper_leg': 'm',
        'jumpsuit_fore_arm': 'm',
        'jumpsuit_hand': 'm',
        'jumpsuit_head': 'm',
        'jumpsuit_lower_leg': 'm',
        'jumpsuit_pelvis': 'm',
        'jumpsuit_toes': 'm',
        'jumpsuit_torso': 'm',
        'jumpsuit_upper_arm': 'm',
        'jumpsuit_upper_leg': 'm',
        'kronk_fore_arm': 'm',
        'kronk_hand': 'm',
        'kronk_head': 'm',
        'kronk_lower_leg': 'm',
        'kronk_pelvis': 'm',
        'kronk_toes': 'm',
        'kronk_torso': 'm',
        'kronk_upper_arm': 'm',
        'kronk_upper_leg': 'm',
        'lake_frigid': 'm',
        'lake_frigid_reflections': 'm',
        'lake_frigid_top': 'm',
        'lake_frigid_vrfill': 'm',
        'land_mine': 'm',
        'level_select_button_opaque': 'm',
        'level_select_button_transparent': 'm',
        'logo': 'm',
        'logo_transparent': 'm',
        'mel_fore_arm': 'm',
        'mel_hand': 'm',
        'mel_head': 'm',
        'mel_lower_leg': 'm',
        'mel_toes': 'm',
        'mel_torso': 'm',
        'mel_upper_arm': 'm',
        'mel_upper_leg': 'm',
        'meter_transparent': 'm',
        'monkey_face_level': 'm',
        'monkey_face_level_bottom': 'm',
        'nature_background': 'm',
        'nature_background_vrfill': 'm',
        'neo_spaz_fore_arm': 'm',
        'neo_spaz_hand': 'm',
        'neo_spaz_head': 'm',
        'neo_spaz_lower_leg': 'm',
        'neo_spaz_pelvis': 'm',
        'neo_spaz_toes': 'm',
        'neo_spaz_torso': 'm',
        'neo_spaz_upper_arm': 'm',
        'neo_spaz_upper_leg': 'm',
        'ninja_fore_arm': 'm',
        'ninja_hand': 'm',
        'ninja_head': 'm',
        'ninja_lower_leg': 'm',
        'ninja_pelvis': 'm',
        'ninja_toes': 'm',
        'ninja_torso': 'm',
        'ninja_upper_arm': 'm',
        'ninja_upper_leg': 'm',
        'old_lady_fore_arm': 'm',
        'old_lady_hand': 'm',
        'old_lady_head': 'm',
        'old_lady_lower_leg': 'm',
        'old_lady_pelvis': 'm',
        'old_lady_toes': 'm',
        'old_lady_torso': 'm',
        'old_lady_upper_arm': 'm',
        'old_lady_upper_leg': 'm',
        'opera_singer_fore_arm': 'm',
        'opera_singer_hand': 'm',
        'opera_singer_head': 'm',
        'opera_singer_lower_leg': 'm',
        'opera_singer_pelvis': 'm',
        'opera_singer_toes': 'm',
        'opera_singer_torso': 'm',
        'opera_singer_upper_arm': 'm',
        'opera_singer_upper_leg': 'm',
        'penguin_fore_arm': 'm',
        'penguin_hand': 'm',
        'penguin_head': 'm',
        'penguin_lower_leg': 'm',
        'penguin_pelvis': 'm',
        'penguin_toes': 'm',
        'penguin_torso': 'm',
        'penguin_upper_arm': 'm',
        'penguin_upper_leg': 'm',
        'pixie_fore_arm': 'm',
        'pixie_hand': 'm',
        'pixie_head': 'm',
        'pixie_lower_leg': 'm',
        'pixie_pelvis': 'm',
        'pixie_toes': 'm',
        'pixie_torso': 'm',
        'pixie_upper_arm': 'm',
        'pixie_upper_leg': 'm',
        'plastic_eyes_transparent': 'm',
        'player_lineup1_transparent': 'm',
        'player_lineup2_transparent': 'm',
        'player_lineup3_transparent': 'm',
        'player_lineup4_transparent': 'm',
        'powerup': 'm',
        'powerup_simple': 'm',
        'puck': 'm',
        'rampage_bg': 'm',
        'rampage_bg2': 'm',
        'rampage_level': 'm',
        'rampage_level_bottom': 'm',
        'rampage_vrfill': 'm',
        'robot_fore_arm': 'm',
        'robot_hand': 'm',
        'robot_head': 'm',
        'robot_lower_leg': 'm',
        'robot_pelvis': 'm',
        'robot_toes': 'm',
        'robot_torso': 'm',
        'robot_upper_arm': 'm',
        'robot_upper_leg': 'm',
        'roundabout_level': 'm',
        'roundabout_level_bottom': 'm',
        'running_shoes': 'm',
        'santa_fore_arm': 'm',
        'santa_hand': 'm',
        'santa_head': 'm',
        'santa_lower_leg': 'm',
        'santa_toes': 'm',
        'santa_torso': 'm',
        'santa_upper_arm': 'm',
        'santa_upper_leg': 'm',
        'scroll_widget_short': 'm',
        'step_right_up_level': 'm',
        'step_right_up_level_bottom': 'm',
        'step_right_up_vrfill_mound': 'm',
        'superhero_fore_arm': 'm',
        'superhero_hand': 'm',
        'superhero_head': 'm',
        'superhero_lower_leg': 'm',
        'superhero_pelvis': 'm',
        'superhero_toes': 'm',
        'superhero_torso': 'm',
        'superhero_upper_arm': 'm',
        'superhero_upper_leg': 'm',
        'the_pad_bg': 'm',
        'the_pad_bgsmall': 'm',
        'the_pad_level': 'm',
        'the_pad_level_bottom': 'm',
        'the_pad_vrfill_bottom': 'm',
        'the_pad_vrfill_mound': 'm',
        'the_pad_vrfill_top': 'm',
        'tip_top_bg': 'm',
        'tip_top_level': 'm',
        'tip_top_level_bottom': 'm',
        'tnt': 'm',
        'toolbar_backing': 'm',
        'toolbar_backing_bottom': 'm',
        'toolbar_backing_bottom2': 'm',
        'toolbar_backing_opaque': 'm',
        'toolbar_backing_top': 'm',
        'toolbar_backing_top2': 'm',
        'toolbar_backing_transparent': 'm',
        'tower_dlevel': 'm',
        'tower_dlevel_bottom': 'm',
        'trees': 'm',
        'warrior_fore_arm': 'm',
        'warrior_hand': 'm',
        'warrior_head': 'm',
        'warrior_lower_leg': 'm',
        'warrior_pelvis': 'm',
        'warrior_toes': 'm',
        'warrior_torso': 'm',
        'warrior_upper_arm': 'm',
        'warrior_upper_leg': 'm',
        'window_bgblotch': 'm',
        'witch_fore_arm': 'm',
        'witch_hand': 'm',
        'witch_head': 'm',
        'witch_lower_leg': 'm',
        'witch_pelvis': 'm',
        'witch_toes': 'm',
        'witch_torso': 'm',
        'witch_upper_arm': 'm',
        'witch_upper_leg': 'm',
        'wizard_fore_arm': 'm',
        'wizard_hand': 'm',
        'wizard_head': 'm',
        'wizard_lower_leg': 'm',
        'wizard_pelvis': 'm',
        'wizard_toes': 'm',
        'wizard_torso': 'm',
        'wizard_upper_arm': 'm',
        'wizard_upper_leg': 'm',
        'wrestler_fore_arm': 'm',
        'wrestler_hand': 'm',
        'wrestler_head': 'm',
        'wrestler_lower_leg': 'm',
        'wrestler_pelvis': 'm',
        'wrestler_toes': 'm',
        'wrestler_torso': 'm',
        'wrestler_upper_arm': 'm',
        'wrestler_upper_leg': 'm',
        'zig_zag_level': 'm',
        'zig_zag_level_bottom': 'm',
        'zoe_fore_arm': 'm',
        'zoe_hand': 'm',
        'zoe_head': 'm',
        'zoe_lower_leg': 'm',
        'zoe_pelvis': 'm',
        'zoe_toes': 'm',
        'zoe_torso': 'm',
        'zoe_upper_arm': 'm',
        'zoe_upper_leg': 'm',
    },
    'strings': {'economy': {'you_got_tokens': ('tokens',)}},
    'textures': {
        'achievement_boxer': 't',
        'achievement_cross_hair': 't',
        'achievement_dual_wielding': 't',
        'achievement_empty': 't',
        'achievement_flawless_victory': 't',
        'achievement_football_shutout': 't',
        'achievement_football_victory': 't',
        'achievement_free_loader': 't',
        'achievement_got_the_moves': 't',
        'achievement_in_control': 't',
        'achievement_medal_large': 't',
        'achievement_medal_medium': 't',
        'achievement_medal_small': 't',
        'achievement_mine': 't',
        'achievement_off_you_go': 't',
        'achievement_onslaught': 't',
        'achievement_outline': 't',
        'achievement_runaround': 't',
        'achievement_sharing_is_caring': 't',
        'achievement_stayin_alive': 't',
        'achievement_super_punch': 't',
        'achievement_team_player': 't',
        'achievement_tnt': 't',
        'achievement_wall': 't',
        'achievements_icon': 't',
        'action_hero_color': 't',
        'action_hero_color_mask': 't',
        'action_hero_icon': 't',
        'action_hero_icon_color_mask': 't',
        'advanced_icon': 't',
        'agent_color': 't',
        'agent_color_mask': 't',
        'agent_icon': 't',
        'agent_icon_color_mask': 't',
        'ali_color': 't',
        'ali_color_mask': 't',
        'ali_icon': 't',
        'ali_icon_color_mask': 't',
        'ali_splash': 't',
        'alien_color': 't',
        'alien_color_mask': 't',
        'alien_icon': 't',
        'alien_icon_color_mask': 't',
        'always_land_bgcolor': 't',
        'always_land_level_color': 't',
        'always_land_preview': 't',
        'analog_stick': 't',
        'assassin_color': 't',
        'assassin_color_mask': 't',
        'assassin_icon': 't',
        'assassin_icon_color_mask': 't',
        'audio_icon': 't',
        'bar': 't',
        'bear_color': 't',
        'bear_color_mask': 't',
        'bear_icon': 't',
        'bear_icon_color_mask': 't',
        'bg': 't',
        'big_g': 't',
        'big_gpreview': 't',
        'bomb_color': 't',
        'bomb_color_ice': 't',
        'bomb_sticky_color': 't',
        'bones_color': 't',
        'bones_color_mask': 't',
        'bones_icon': 't',
        'bones_icon_color_mask': 't',
        'bridgit_level_color': 't',
        'bridgit_preview': 't',
        'bunny_color': 't',
        'bunny_color_mask': 't',
        'bunny_icon': 't',
        'bunny_icon_color_mask': 't',
        'button_bomb': 't',
        'button_jump': 't',
        'button_pick_up': 't',
        'button_punch': 't',
        'ch_title_char1': 't',
        'ch_title_char2': 't',
        'ch_title_char3': 't',
        'ch_title_char4': 't',
        'ch_title_char5': 't',
        'chest_icon': 't',
        'chest_icon_empty': 't',
        'chest_icon_multi': 't',
        'chest_icon_tint': 't',
        'chest_open_icon': 't',
        'chest_open_icon_tint': 't',
        'circle_zig_zag': 't',
        'clay_stroke': 't',
        'coin': 't',
        'controller_icon': 't',
        'courtyard_level_color': 't',
        'courtyard_preview': 't',
        'cowboy_color': 't',
        'cowboy_color_mask': 't',
        'cowboy_icon': 't',
        'cowboy_icon_color_mask': 't',
        'crag_castle_level_color': 't',
        'crag_castle_preview': 't',
        'cross_out': 't',
        'cross_out_mask': 't',
        'cute_spaz': 't',
        'cyborg_color': 't',
        'cyborg_color_mask': 't',
        'cyborg_icon': 't',
        'cyborg_icon_color_mask': 't',
        'discord_icon': 't',
        'discord_logo': 't',
        'discord_server': 't',
        'doom_shroom_bgcolor': 't',
        'doom_shroom_level_color': 't',
        'doom_shroom_preview': 't',
        'down_button': 't',
        'egg1': 't',
        'egg2': 't',
        'egg3': 't',
        'egg4': 't',
        'egg_tex1': 't',
        'egg_tex2': 't',
        'egg_tex3': 't',
        'empty': 't',
        'file': 't',
        'flag_color': 't',
        'folder': 't',
        'football_stadium': 't',
        'football_stadium_preview': 't',
        'frame_inset': 't',
        'frosty_color': 't',
        'frosty_color_mask': 't',
        'frosty_icon': 't',
        'frosty_icon_color_mask': 't',
        'game_center_icon': 't',
        'github_logo': 't',
        'gladiator_color': 't',
        'gladiator_color_mask': 't',
        'gladiator_icon': 't',
        'gladiator_icon_color_mask': 't',
        'gold_pass': 't',
        'google_play_achievements_icon': 't',
        'google_play_games_icon': 't',
        'google_play_leaderboards_icon': 't',
        'google_plus_icon': 't',
        'google_plus_sign_in_button': 't',
        'graphics_icon': 't',
        'heart': 't',
        'hockey_stadium': 't',
        'hockey_stadium_preview': 't',
        'icon_onslaught': 't',
        'icon_runaround': 't',
        'impact_bomb_color': 't',
        'impact_bomb_color_lit': 't',
        'inventory_icon': 't',
        'jack_color': 't',
        'jack_color_mask': 't',
        'jack_icon': 't',
        'jack_icon_color_mask': 't',
        'jumpsuit_color': 't',
        'jumpsuit_color_mask': 't',
        'jumpsuit_icon': 't',
        'jumpsuit_icon_color_mask': 't',
        'kronk': 't',
        'kronk_color_mask': 't',
        'kronk_icon': 't',
        'kronk_icon_color_mask': 't',
        'lake_frigid': 't',
        'lake_frigid_preview': 't',
        'lake_frigid_reflections': 't',
        'land_mine': 't',
        'land_mine_lit': 't',
        'leaderboards_icon': 't',
        'left_button': 't',
        'level_icon': 't',
        'lock': 't',
        'log_icon': 't',
        'logo': 't',
        'logo_easter': 't',
        'map_preview_mask': 't',
        'medal_bronze': 't',
        'medal_complete': 't',
        'medal_gold': 't',
        'medal_silver': 't',
        'mel_color': 't',
        'mel_color_mask': 't',
        'mel_icon': 't',
        'mel_icon_color_mask': 't',
        'menu_bg': 't',
        'menu_icon': 't',
        'merch': 't',
        'meter': 't',
        'monkey_face_level_color': 't',
        'monkey_face_preview': 't',
        'multiplayer_examples': 't',
        'nature_background_color': 't',
        'neo_spaz_color': 't',
        'neo_spaz_color_mask': 't',
        'neo_spaz_icon': 't',
        'neo_spaz_icon_color_mask': 't',
        'next_level_icon': 't',
        'ninja_color': 't',
        'ninja_color_mask': 't',
        'ninja_icon': 't',
        'ninja_icon_color_mask': 't',
        'null': 't',
        'old_lady_color': 't',
        'old_lady_color_mask': 't',
        'old_lady_icon': 't',
        'old_lady_icon_color_mask': 't',
        'opera_singer_color': 't',
        'opera_singer_color_mask': 't',
        'opera_singer_icon': 't',
        'opera_singer_icon_color_mask': 't',
        'ouya_icon': 't',
        'ouya_obutton': 't',
        'ouya_ubutton': 't',
        'ouya_ybutton': 't',
        'penguin_color': 't',
        'penguin_color_mask': 't',
        'penguin_icon': 't',
        'penguin_icon_color_mask': 't',
        'pixie_color': 't',
        'pixie_color_mask': 't',
        'pixie_icon': 't',
        'pixie_icon_color_mask': 't',
        'player_lineup': 't',
        'plus_button': 't',
        'powerup_bomb': 't',
        'powerup_curse': 't',
        'powerup_health': 't',
        'powerup_ice_bombs': 't',
        'powerup_impact_bombs': 't',
        'powerup_land_mines': 't',
        'powerup_punch': 't',
        'powerup_shield': 't',
        'powerup_speed': 't',
        'powerup_sticky_bombs': 't',
        'puck_color': 't',
        'quote_bubble': 't',
        'rampage_bgcolor': 't',
        'rampage_bgcolor2': 't',
        'rampage_level_color': 't',
        'rampage_preview': 't',
        'replay_icon': 't',
        'right_button': 't',
        'robot_color': 't',
        'robot_color_mask': 't',
        'robot_icon': 't',
        'robot_icon_color_mask': 't',
        'roundabout_level_color': 't',
        'roundabout_preview': 't',
        'santa_color': 't',
        'santa_color_mask': 't',
        'santa_icon': 't',
        'santa_icon_color_mask': 't',
        'settings_icon': 't',
        'slash': 't',
        'star': 't',
        'step_right_up_level_color': 't',
        'step_right_up_preview': 't',
        'store_character': 't',
        'store_character_easter': 't',
        'store_character_xmas': 't',
        'store_icon': 't',
        'superhero_color': 't',
        'superhero_color_mask': 't',
        'superhero_icon': 't',
        'superhero_icon_color_mask': 't',
        'the_pad_level_color': 't',
        'the_pad_preview': 't',
        'ticket_roll': 't',
        'ticket_roll_big': 't',
        'ticket_rolls': 't',
        'tickets': 't',
        'tickets_more': 't',
        'tickets_purple': 't',
        'tip_top_bgcolor': 't',
        'tip_top_level_color': 't',
        'tip_top_preview': 't',
        'tnt': 't',
        'tokens1': 't',
        'tokens2': 't',
        'tokens3': 't',
        'tokens4': 't',
        'tower_dlevel_color': 't',
        'tower_dpreview': 't',
        'trees_color': 't',
        'trophy': 't',
        'tv': 't',
        'up_button': 't',
        'vr_fill_mound': 't',
        'warrior_color': 't',
        'warrior_color_mask': 't',
        'warrior_icon': 't',
        'warrior_icon_color_mask': 't',
        'window_bottom_cap': 't',
        'witch_color': 't',
        'witch_color_mask': 't',
        'witch_icon': 't',
        'witch_icon_color_mask': 't',
        'wizard_color': 't',
        'wizard_color_mask': 't',
        'wizard_icon': 't',
        'wizard_icon_color_mask': 't',
        'wrestler_color': 't',
        'wrestler_color_mask': 't',
        'wrestler_icon': 't',
        'wrestler_icon_color_mask': 't',
        'zig_zag_level_color': 't',
        'zigzag_preview': 't',
        'zoe_color': 't',
        'zoe_color_mask': 't',
        'zoe_icon': 't',
        'zoe_icon_color_mask': 't',
    },
}


if not TYPE_CHECKING:
    audio = AssetRefDir(__asset_package__, _TREE['audio'], 'audio')
    meshes = AssetRefDir(__asset_package__, _TREE['meshes'], 'meshes')
    strings = LangStrDir(__asset_package__, _TREE['strings'], 'strings')
    textures = AssetRefDir(__asset_package__, _TREE['textures'], 'textures')
