name: TEST2

on:
  push:

jobs:
    make_docker_image_arm64:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: setup dependencies
          run: |
            brew install rsync clang-format 
            brew install --cask docker
            brew install docker-buildx      
            mkdir -p ~/.docker       
            if [ ! -f ~/.docker/config.json ]; then
              echo '{"cliPluginsExtraDirs":["/opt/homebrew/lib/docker/cli-plugins"]}' > ~/.docker/config.json
            else
              cat ~/.docker/config.json | jq '.cliPluginsExtraDirs |= .+ ["/opt/homebrew/lib/docker/cli-plugins"]' > ~/.docker/config_tmp.json
              mv ~/.docker/config_tmp.json ~/.docker/config.json
            fi
            export PATH="/opt/homebrew/bin:$PATH"
            docker buildx install
        - name: Setup project environment
          run: make env
        - name: Make the build
          run: make docker-build-arm64 && make docker-save
        - name: Upload the build
          uses: actions/upload-artifact@v4
          with:
            name: docker_server(release)
            path: build/docker/bombsquad_server_docker.tar
