// Released under the MIT License. See LICENSE for details.

#ifndef BALLISTICA_CORE_PYTHON_PYEMBED_H_
#define BALLISTICA_CORE_PYTHON_PYEMBED_H_

#include <cstddef>
#include <cstdint>

typedef struct _object PyObject;

namespace ballistica::core {

/// Execute a pyembed bytecode blob generated by
/// ``tools/batoolsinternal/meta.py:gen_pyembed`` (wrapped in .inc files
/// under each featureset's ``mgen/pyembed/`` dir). If ``encrypted``,
/// the buffer is XOR-deobfuscated into a local copy before
/// unmarshaling; the key matches the Python-side ``_PYEMBED_XOR_KEY``.
/// ``ctx`` is used as both globals and locals for ``PyEval_EvalCode``.
/// GIL must be held by the caller. On unmarshal or exec failure,
/// prints the exception and ``FatalError``s.
void PyembedExec(const uint8_t* bytes, size_t n, const char* filename,
                 PyObject* ctx, bool encrypted);

}  // namespace ballistica::core

#endif  // BALLISTICA_CORE_PYTHON_PYEMBED_H_
